/**
 * Onshape REST API
 * The Onshape REST API consumed by all clients.
 *
 * The version of the OpenAPI document: 1.113
 * Contact: api-support@onshape.zendesk.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 4.3.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "BTAppElementUpdateParams.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {




BTAppElementUpdateParams::BTAppElementUpdateParams()
{
    m_ChangesIsSet = false;
    m_Description = utility::conversions::to_string_t("");
    m_DescriptionIsSet = false;
    m_ParentChangeId = utility::conversions::to_string_t("");
    m_ParentChangeIdIsSet = false;
    m_ReturnError = false;
    m_ReturnErrorIsSet = false;
    m_TransactionId = utility::conversions::to_string_t("");
    m_TransactionIdIsSet = false;
}

BTAppElementUpdateParams::~BTAppElementUpdateParams()
{
}

void BTAppElementUpdateParams::validate()
{
    // TODO: implement validation
}

web::json::value BTAppElementUpdateParams::toJson() const
{

    web::json::value val = web::json::value::object();
    
    if(m_ChangesIsSet)
    {
        val[utility::conversions::to_string_t("changes")] = ModelBase::toJson(m_Changes);
    }
    if(m_DescriptionIsSet)
    {
        val[utility::conversions::to_string_t("description")] = ModelBase::toJson(m_Description);
    }
    if(m_ParentChangeIdIsSet)
    {
        val[utility::conversions::to_string_t("parentChangeId")] = ModelBase::toJson(m_ParentChangeId);
    }
    if(m_ReturnErrorIsSet)
    {
        val[utility::conversions::to_string_t("returnError")] = ModelBase::toJson(m_ReturnError);
    }
    if(m_TransactionIdIsSet)
    {
        val[utility::conversions::to_string_t("transactionId")] = ModelBase::toJson(m_TransactionId);
    }

    return val;
}

bool BTAppElementUpdateParams::fromJson(const web::json::value& val)
{
    bool ok = true;
    
    if(val.has_field(utility::conversions::to_string_t("changes")))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t("changes"));
        if(!fieldValue.is_null())
        {
            std::vector<std::shared_ptr<BTAppElementChangeParams>> refVal_changes;
            ok &= ModelBase::fromJson(fieldValue, refVal_changes);
            setChanges(refVal_changes);
        }
    }
    if(val.has_field(utility::conversions::to_string_t("description")))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t("description"));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_description;
            ok &= ModelBase::fromJson(fieldValue, refVal_description);
            setDescription(refVal_description);
        }
    }
    if(val.has_field(utility::conversions::to_string_t("parentChangeId")))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t("parentChangeId"));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_parentChangeId;
            ok &= ModelBase::fromJson(fieldValue, refVal_parentChangeId);
            setParentChangeId(refVal_parentChangeId);
        }
    }
    if(val.has_field(utility::conversions::to_string_t("returnError")))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t("returnError"));
        if(!fieldValue.is_null())
        {
            bool refVal_returnError;
            ok &= ModelBase::fromJson(fieldValue, refVal_returnError);
            setReturnError(refVal_returnError);
        }
    }
    if(val.has_field(utility::conversions::to_string_t("transactionId")))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t("transactionId"));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_transactionId;
            ok &= ModelBase::fromJson(fieldValue, refVal_transactionId);
            setTransactionId(refVal_transactionId);
        }
    }
    return ok;
}

void BTAppElementUpdateParams::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t("."))
    {
        namePrefix += utility::conversions::to_string_t(".");
    }
    if(m_ChangesIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t("changes"), m_Changes));
    }
    if(m_DescriptionIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t("description"), m_Description));
    }
    if(m_ParentChangeIdIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t("parentChangeId"), m_ParentChangeId));
    }
    if(m_ReturnErrorIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t("returnError"), m_ReturnError));
    }
    if(m_TransactionIdIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t("transactionId"), m_TransactionId));
    }
}

bool BTAppElementUpdateParams::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t("."))
    {
        namePrefix += utility::conversions::to_string_t(".");
    }

    if(multipart->hasContent(utility::conversions::to_string_t("changes")))
    {
        std::vector<std::shared_ptr<BTAppElementChangeParams>> refVal_changes;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t("changes")), refVal_changes );
        setChanges(refVal_changes);
    }
    if(multipart->hasContent(utility::conversions::to_string_t("description")))
    {
        utility::string_t refVal_description;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t("description")), refVal_description );
        setDescription(refVal_description);
    }
    if(multipart->hasContent(utility::conversions::to_string_t("parentChangeId")))
    {
        utility::string_t refVal_parentChangeId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t("parentChangeId")), refVal_parentChangeId );
        setParentChangeId(refVal_parentChangeId);
    }
    if(multipart->hasContent(utility::conversions::to_string_t("returnError")))
    {
        bool refVal_returnError;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t("returnError")), refVal_returnError );
        setReturnError(refVal_returnError);
    }
    if(multipart->hasContent(utility::conversions::to_string_t("transactionId")))
    {
        utility::string_t refVal_transactionId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t("transactionId")), refVal_transactionId );
        setTransactionId(refVal_transactionId);
    }
    return ok;
}

std::vector<std::shared_ptr<BTAppElementChangeParams>>& BTAppElementUpdateParams::getChanges()
{
    return m_Changes;
}

void BTAppElementUpdateParams::setChanges(const std::vector<std::shared_ptr<BTAppElementChangeParams>>& value)
{
    m_Changes = value;
    m_ChangesIsSet = true;
}

bool BTAppElementUpdateParams::changesIsSet() const
{
    return m_ChangesIsSet;
}

void BTAppElementUpdateParams::unsetChanges()
{
    m_ChangesIsSet = false;
}
utility::string_t BTAppElementUpdateParams::getDescription() const
{
    return m_Description;
}

void BTAppElementUpdateParams::setDescription(const utility::string_t& value)
{
    m_Description = value;
    m_DescriptionIsSet = true;
}

bool BTAppElementUpdateParams::descriptionIsSet() const
{
    return m_DescriptionIsSet;
}

void BTAppElementUpdateParams::unsetDescription()
{
    m_DescriptionIsSet = false;
}
utility::string_t BTAppElementUpdateParams::getParentChangeId() const
{
    return m_ParentChangeId;
}

void BTAppElementUpdateParams::setParentChangeId(const utility::string_t& value)
{
    m_ParentChangeId = value;
    m_ParentChangeIdIsSet = true;
}

bool BTAppElementUpdateParams::parentChangeIdIsSet() const
{
    return m_ParentChangeIdIsSet;
}

void BTAppElementUpdateParams::unsetParentChangeId()
{
    m_ParentChangeIdIsSet = false;
}
bool BTAppElementUpdateParams::isReturnError() const
{
    return m_ReturnError;
}

void BTAppElementUpdateParams::setReturnError(bool value)
{
    m_ReturnError = value;
    m_ReturnErrorIsSet = true;
}

bool BTAppElementUpdateParams::returnErrorIsSet() const
{
    return m_ReturnErrorIsSet;
}

void BTAppElementUpdateParams::unsetReturnError()
{
    m_ReturnErrorIsSet = false;
}
utility::string_t BTAppElementUpdateParams::getTransactionId() const
{
    return m_TransactionId;
}

void BTAppElementUpdateParams::setTransactionId(const utility::string_t& value)
{
    m_TransactionId = value;
    m_TransactionIdIsSet = true;
}

bool BTAppElementUpdateParams::transactionIdIsSet() const
{
    return m_TransactionIdIsSet;
}

void BTAppElementUpdateParams::unsetTransactionId()
{
    m_TransactionIdIsSet = false;
}
}
}
}
}


