/**
 * Onshape REST API
 * The Onshape REST API consumed by all clients.
 *
 * The version of the OpenAPI document: 1.113
 * Contact: api-support@onshape.zendesk.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 4.3.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "BTEntityTypeFilter_124_allOf.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {




BTEntityTypeFilter_124_allOf::BTEntityTypeFilter_124_allOf()
{
    m_EntityType = utility::conversions::to_string_t("");
    m_EntityTypeIsSet = false;
    m_BtType = utility::conversions::to_string_t("");
    m_BtTypeIsSet = false;
}

BTEntityTypeFilter_124_allOf::~BTEntityTypeFilter_124_allOf()
{
}

void BTEntityTypeFilter_124_allOf::validate()
{
    // TODO: implement validation
}

web::json::value BTEntityTypeFilter_124_allOf::toJson() const
{

    web::json::value val = web::json::value::object();
    
    if(m_EntityTypeIsSet)
    {
        val[utility::conversions::to_string_t("entityType")] = ModelBase::toJson(m_EntityType);
    }
    if(m_BtTypeIsSet)
    {
        val[utility::conversions::to_string_t("btType")] = ModelBase::toJson(m_BtType);
    }

    return val;
}

bool BTEntityTypeFilter_124_allOf::fromJson(const web::json::value& val)
{
    bool ok = true;
    
    if(val.has_field(utility::conversions::to_string_t("entityType")))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t("entityType"));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_entityType;
            ok &= ModelBase::fromJson(fieldValue, refVal_entityType);
            setEntityType(refVal_entityType);
        }
    }
    if(val.has_field(utility::conversions::to_string_t("btType")))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t("btType"));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_btType;
            ok &= ModelBase::fromJson(fieldValue, refVal_btType);
            setBtType(refVal_btType);
        }
    }
    return ok;
}

void BTEntityTypeFilter_124_allOf::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t("."))
    {
        namePrefix += utility::conversions::to_string_t(".");
    }
    if(m_EntityTypeIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t("entityType"), m_EntityType));
    }
    if(m_BtTypeIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t("btType"), m_BtType));
    }
}

bool BTEntityTypeFilter_124_allOf::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t("."))
    {
        namePrefix += utility::conversions::to_string_t(".");
    }

    if(multipart->hasContent(utility::conversions::to_string_t("entityType")))
    {
        utility::string_t refVal_entityType;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t("entityType")), refVal_entityType );
        setEntityType(refVal_entityType);
    }
    if(multipart->hasContent(utility::conversions::to_string_t("btType")))
    {
        utility::string_t refVal_btType;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t("btType")), refVal_btType );
        setBtType(refVal_btType);
    }
    return ok;
}

utility::string_t BTEntityTypeFilter_124_allOf::getEntityType() const
{
    return m_EntityType;
}

void BTEntityTypeFilter_124_allOf::setEntityType(const utility::string_t& value)
{
    m_EntityType = value;
    m_EntityTypeIsSet = true;
}

bool BTEntityTypeFilter_124_allOf::entityTypeIsSet() const
{
    return m_EntityTypeIsSet;
}

void BTEntityTypeFilter_124_allOf::unsetEntityType()
{
    m_EntityTypeIsSet = false;
}
utility::string_t BTEntityTypeFilter_124_allOf::getBtType() const
{
    return m_BtType;
}

void BTEntityTypeFilter_124_allOf::setBtType(const utility::string_t& value)
{
    m_BtType = value;
    m_BtTypeIsSet = true;
}

bool BTEntityTypeFilter_124_allOf::btTypeIsSet() const
{
    return m_BtTypeIsSet;
}

void BTEntityTypeFilter_124_allOf::unsetBtType()
{
    m_BtTypeIsSet = false;
}
}
}
}
}


