/**
 * Onshape REST API
 * The Onshape REST API consumed by all clients.
 *
 * The version of the OpenAPI document: 1.113
 * Contact: api-support@onshape.zendesk.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 4.3.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "BTExportTessellatedEdgesBody_890_allOf.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {




BTExportTessellatedEdgesBody_890_allOf::BTExportTessellatedEdgesBody_890_allOf()
{
    m_EdgesIsSet = false;
    m_BtType = utility::conversions::to_string_t("");
    m_BtTypeIsSet = false;
}

BTExportTessellatedEdgesBody_890_allOf::~BTExportTessellatedEdgesBody_890_allOf()
{
}

void BTExportTessellatedEdgesBody_890_allOf::validate()
{
    // TODO: implement validation
}

web::json::value BTExportTessellatedEdgesBody_890_allOf::toJson() const
{

    web::json::value val = web::json::value::object();
    
    if(m_EdgesIsSet)
    {
        val[utility::conversions::to_string_t("edges")] = ModelBase::toJson(m_Edges);
    }
    if(m_BtTypeIsSet)
    {
        val[utility::conversions::to_string_t("btType")] = ModelBase::toJson(m_BtType);
    }

    return val;
}

bool BTExportTessellatedEdgesBody_890_allOf::fromJson(const web::json::value& val)
{
    bool ok = true;
    
    if(val.has_field(utility::conversions::to_string_t("edges")))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t("edges"));
        if(!fieldValue.is_null())
        {
            std::vector<std::shared_ptr<BTExportTessellatedEdgesEdge_1364>> refVal_edges;
            ok &= ModelBase::fromJson(fieldValue, refVal_edges);
            setEdges(refVal_edges);
        }
    }
    if(val.has_field(utility::conversions::to_string_t("btType")))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t("btType"));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_btType;
            ok &= ModelBase::fromJson(fieldValue, refVal_btType);
            setBtType(refVal_btType);
        }
    }
    return ok;
}

void BTExportTessellatedEdgesBody_890_allOf::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t("."))
    {
        namePrefix += utility::conversions::to_string_t(".");
    }
    if(m_EdgesIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t("edges"), m_Edges));
    }
    if(m_BtTypeIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t("btType"), m_BtType));
    }
}

bool BTExportTessellatedEdgesBody_890_allOf::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t("."))
    {
        namePrefix += utility::conversions::to_string_t(".");
    }

    if(multipart->hasContent(utility::conversions::to_string_t("edges")))
    {
        std::vector<std::shared_ptr<BTExportTessellatedEdgesEdge_1364>> refVal_edges;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t("edges")), refVal_edges );
        setEdges(refVal_edges);
    }
    if(multipart->hasContent(utility::conversions::to_string_t("btType")))
    {
        utility::string_t refVal_btType;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t("btType")), refVal_btType );
        setBtType(refVal_btType);
    }
    return ok;
}

std::vector<std::shared_ptr<BTExportTessellatedEdgesEdge_1364>>& BTExportTessellatedEdgesBody_890_allOf::getEdges()
{
    return m_Edges;
}

void BTExportTessellatedEdgesBody_890_allOf::setEdges(const std::vector<std::shared_ptr<BTExportTessellatedEdgesEdge_1364>>& value)
{
    m_Edges = value;
    m_EdgesIsSet = true;
}

bool BTExportTessellatedEdgesBody_890_allOf::edgesIsSet() const
{
    return m_EdgesIsSet;
}

void BTExportTessellatedEdgesBody_890_allOf::unsetEdges()
{
    m_EdgesIsSet = false;
}
utility::string_t BTExportTessellatedEdgesBody_890_allOf::getBtType() const
{
    return m_BtType;
}

void BTExportTessellatedEdgesBody_890_allOf::setBtType(const utility::string_t& value)
{
    m_BtType = value;
    m_BtTypeIsSet = true;
}

bool BTExportTessellatedEdgesBody_890_allOf::btTypeIsSet() const
{
    return m_BtTypeIsSet;
}

void BTExportTessellatedEdgesBody_890_allOf::unsetBtType()
{
    m_BtTypeIsSet = false;
}
}
}
}
}


