/**
 * Onshape REST API
 * The Onshape REST API consumed by all clients.
 *
 * The version of the OpenAPI document: 1.113
 * Contact: api-support@onshape.zendesk.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 4.3.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * BTLineDescription_1559.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_BTLineDescription_1559_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_BTLineDescription_1559_H_


#include "BTLineDescription_1559_allOf.h"
#include "BTCurveDescription_1583.h"
#include <cpprest/details/basic_types.h>
#include "BTVector3d_389.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {


/// <summary>
/// 
/// </summary>
class  BTLineDescription_1559
    : public BTCurveDescription_1583
{
public:
    BTLineDescription_1559();
    virtual ~BTLineDescription_1559();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// BTLineDescription_1559 members

    /// <summary>
    /// 
    /// </summary>
    std::shared_ptr<BTVector3d_389> getDirection() const;
    bool directionIsSet() const;
    void unsetDirection();

    void setDirection(const std::shared_ptr<BTVector3d_389>& value);

    /// <summary>
    /// 
    /// </summary>
    std::shared_ptr<BTVector3d_389> getOrigin() const;
    bool originIsSet() const;
    void unsetOrigin();

    void setOrigin(const std::shared_ptr<BTVector3d_389>& value);


protected:
    std::shared_ptr<BTVector3d_389> m_Direction;
    bool m_DirectionIsSet;
    std::shared_ptr<BTVector3d_389> m_Origin;
    bool m_OriginIsSet;
};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_BTLineDescription_1559_H_ */
