/**
 * Onshape REST API
 * The Onshape REST API consumed by all clients.
 *
 * The version of the OpenAPI document: 1.113
 * Contact: api-support@onshape.zendesk.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 4.3.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * BTMParameterDerived_864_allOf.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_BTMParameterDerived_864_allOf_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_BTMParameterDerived_864_allOf_H_


#include "../ModelBase.h"

#include "BTMImport_136.h"
#include "BTPModuleId_235.h"
#include <cpprest/details/basic_types.h>
#include <vector>

namespace org {
namespace openapitools {
namespace client {
namespace model {


/// <summary>
/// 
/// </summary>
class  BTMParameterDerived_864_allOf
    : public ModelBase
{
public:
    BTMParameterDerived_864_allOf();
    virtual ~BTMParameterDerived_864_allOf();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// BTMParameterDerived_864_allOf members

    /// <summary>
    /// 
    /// </summary>
    std::shared_ptr<BTPModuleId_235> getModuleId() const;
    bool moduleIdIsSet() const;
    void unsetModuleId();

    void setModuleId(const std::shared_ptr<BTPModuleId_235>& value);

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getRNamespace() const;
    bool rNamespaceIsSet() const;
    void unsetr_namespace();

    void setRNamespace(const utility::string_t& value);

    /// <summary>
    /// 
    /// </summary>
    std::vector<std::shared_ptr<BTMImport_136>>& getImports();
    bool importsIsSet() const;
    void unsetImports();

    void setImports(const std::vector<std::shared_ptr<BTMImport_136>>& value);

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getBtType() const;
    bool btTypeIsSet() const;
    void unsetBtType();

    void setBtType(const utility::string_t& value);


protected:
    std::shared_ptr<BTPModuleId_235> m_ModuleId;
    bool m_ModuleIdIsSet;
    utility::string_t m_r_namespace;
    bool m_r_namespaceIsSet;
    std::vector<std::shared_ptr<BTMImport_136>> m_Imports;
    bool m_ImportsIsSet;
    utility::string_t m_BtType;
    bool m_BtTypeIsSet;
};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_BTMParameterDerived_864_allOf_H_ */
