/**
 * Onshape REST API
 * The Onshape REST API consumed by all clients.
 *
 * The version of the OpenAPI document: 1.113
 * Contact: api-support@onshape.zendesk.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 4.3.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * BTMSketchCurve_4.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_BTMSketchCurve_4_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_BTMSketchCurve_4_H_


#include "BTMParameter_1.h"
#include "BTMSketchCurve_4_allOf.h"
#include <cpprest/details/basic_types.h>
#include "BTMSketchGeomEntity_5.h"
#include <vector>
#include "BTCurveGeometry_114.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {


/// <summary>
/// 
/// </summary>
class  BTMSketchCurve_4
    : public BTMSketchGeomEntity_5
{
public:
    BTMSketchCurve_4();
    virtual ~BTMSketchCurve_4();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// BTMSketchCurve_4 members

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getCenterId() const;
    bool centerIdIsSet() const;
    void unsetCenterId();

    void setCenterId(const utility::string_t& value);

    /// <summary>
    /// 
    /// </summary>
    std::vector<utility::string_t>& getInternalIds();
    bool internalIdsIsSet() const;
    void unsetInternalIds();

    void setInternalIds(const std::vector<utility::string_t>& value);

    /// <summary>
    /// 
    /// </summary>
    std::shared_ptr<BTCurveGeometry_114> getGeometry() const;
    bool geometryIsSet() const;
    void unsetGeometry();

    void setGeometry(const std::shared_ptr<BTCurveGeometry_114>& value);


protected:
    utility::string_t m_CenterId;
    bool m_CenterIdIsSet;
    std::vector<utility::string_t> m_InternalIds;
    bool m_InternalIdsIsSet;
    std::shared_ptr<BTCurveGeometry_114> m_Geometry;
    bool m_GeometryIsSet;
};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_BTMSketchCurve_4_H_ */
