/**
 * Onshape REST API
 * The Onshape REST API consumed by all clients.
 *
 * The version of the OpenAPI document: 1.113
 * Contact: api-support@onshape.zendesk.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 4.3.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * BTPLValueBoxDereference_251.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_BTPLValueBoxDereference_251_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_BTPLValueBoxDereference_251_H_


#include "BTPExpression_9.h"
#include "BTPLValue_249.h"
#include "BTPLValueBoxDereference_251_allOf.h"
#include <cpprest/details/basic_types.h>
#include "BTPSpace_10.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {


/// <summary>
/// 
/// </summary>
class  BTPLValueBoxDereference_251
    : public BTPLValue_249
{
public:
    BTPLValueBoxDereference_251();
    virtual ~BTPLValueBoxDereference_251();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// BTPLValueBoxDereference_251 members

    /// <summary>
    /// 
    /// </summary>
    std::shared_ptr<BTPExpression_9> getBox() const;
    bool boxIsSet() const;
    void unsetBox();

    void setBox(const std::shared_ptr<BTPExpression_9>& value);

    /// <summary>
    /// 
    /// </summary>
    std::shared_ptr<BTPSpace_10> getSpaceInside() const;
    bool spaceInsideIsSet() const;
    void unsetSpaceInside();

    void setSpaceInside(const std::shared_ptr<BTPSpace_10>& value);


protected:
    std::shared_ptr<BTPExpression_9> m_Box;
    bool m_BoxIsSet;
    std::shared_ptr<BTPSpace_10> m_SpaceInside;
    bool m_SpaceInsideIsSet;
};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_BTPLValueBoxDereference_251_H_ */
