/**
 * Onshape REST API
 * The Onshape REST API consumed by all clients.
 *
 * The version of the OpenAPI document: 1.113
 * Contact: api-support@onshape.zendesk.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 4.3.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * BTSetFeatureRollbackCall_1899_allOf.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_BTSetFeatureRollbackCall_1899_allOf_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_BTSetFeatureRollbackCall_1899_allOf_H_


#include "../ModelBase.h"

#include <cpprest/details/basic_types.h>

namespace org {
namespace openapitools {
namespace client {
namespace model {


/// <summary>
/// 
/// </summary>
class  BTSetFeatureRollbackCall_1899_allOf
    : public ModelBase
{
public:
    BTSetFeatureRollbackCall_1899_allOf();
    virtual ~BTSetFeatureRollbackCall_1899_allOf();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// BTSetFeatureRollbackCall_1899_allOf members

    /// <summary>
    /// 
    /// </summary>
    int32_t getRollbackIndex() const;
    bool rollbackIndexIsSet() const;
    void unsetRollbackIndex();

    void setRollbackIndex(int32_t value);

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getBtType() const;
    bool btTypeIsSet() const;
    void unsetBtType();

    void setBtType(const utility::string_t& value);


protected:
    int32_t m_RollbackIndex;
    bool m_RollbackIndexIsSet;
    utility::string_t m_BtType;
    bool m_BtTypeIsSet;
};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_BTSetFeatureRollbackCall_1899_allOf_H_ */
