/**
 * Onshape REST API
 * The Onshape REST API consumed by all clients.
 *
 * The version of the OpenAPI document: 1.113
 * Contact: api-support@onshape.zendesk.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 4.3.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "BTTableColumnInfo_1222.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {




BTTableColumnInfo_1222::BTTableColumnInfo_1222()
{
    m_BtType = utility::conversions::to_string_t("");
    m_BtTypeIsSet = false;
    m_Id = utility::conversions::to_string_t("");
    m_IdIsSet = false;
    m_NodeId = utility::conversions::to_string_t("");
    m_NodeIdIsSet = false;
    m_SpecificationIsSet = false;
}

BTTableColumnInfo_1222::~BTTableColumnInfo_1222()
{
}

void BTTableColumnInfo_1222::validate()
{
    // TODO: implement validation
}

web::json::value BTTableColumnInfo_1222::toJson() const
{

    web::json::value val = web::json::value::object();
    
    if(m_BtTypeIsSet)
    {
        val[utility::conversions::to_string_t("btType")] = ModelBase::toJson(m_BtType);
    }
    if(m_IdIsSet)
    {
        val[utility::conversions::to_string_t("id")] = ModelBase::toJson(m_Id);
    }
    if(m_NodeIdIsSet)
    {
        val[utility::conversions::to_string_t("nodeId")] = ModelBase::toJson(m_NodeId);
    }
    if(m_SpecificationIsSet)
    {
        val[utility::conversions::to_string_t("specification")] = ModelBase::toJson(m_Specification);
    }

    return val;
}

bool BTTableColumnInfo_1222::fromJson(const web::json::value& val)
{
    bool ok = true;
    
    if(val.has_field(utility::conversions::to_string_t("btType")))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t("btType"));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_btType;
            ok &= ModelBase::fromJson(fieldValue, refVal_btType);
            setBtType(refVal_btType);
        }
    }
    if(val.has_field(utility::conversions::to_string_t("id")))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t("id"));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_id;
            ok &= ModelBase::fromJson(fieldValue, refVal_id);
            setId(refVal_id);
        }
    }
    if(val.has_field(utility::conversions::to_string_t("nodeId")))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t("nodeId"));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_nodeId;
            ok &= ModelBase::fromJson(fieldValue, refVal_nodeId);
            setNodeId(refVal_nodeId);
        }
    }
    if(val.has_field(utility::conversions::to_string_t("specification")))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t("specification"));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<BTTableColumnSpec_1967> refVal_specification;
            ok &= ModelBase::fromJson(fieldValue, refVal_specification);
            setSpecification(refVal_specification);
        }
    }
    return ok;
}

void BTTableColumnInfo_1222::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t("."))
    {
        namePrefix += utility::conversions::to_string_t(".");
    }
    if(m_BtTypeIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t("btType"), m_BtType));
    }
    if(m_IdIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t("id"), m_Id));
    }
    if(m_NodeIdIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t("nodeId"), m_NodeId));
    }
    if(m_SpecificationIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t("specification"), m_Specification));
    }
}

bool BTTableColumnInfo_1222::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t("."))
    {
        namePrefix += utility::conversions::to_string_t(".");
    }

    if(multipart->hasContent(utility::conversions::to_string_t("btType")))
    {
        utility::string_t refVal_btType;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t("btType")), refVal_btType );
        setBtType(refVal_btType);
    }
    if(multipart->hasContent(utility::conversions::to_string_t("id")))
    {
        utility::string_t refVal_id;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t("id")), refVal_id );
        setId(refVal_id);
    }
    if(multipart->hasContent(utility::conversions::to_string_t("nodeId")))
    {
        utility::string_t refVal_nodeId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t("nodeId")), refVal_nodeId );
        setNodeId(refVal_nodeId);
    }
    if(multipart->hasContent(utility::conversions::to_string_t("specification")))
    {
        std::shared_ptr<BTTableColumnSpec_1967> refVal_specification;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t("specification")), refVal_specification );
        setSpecification(refVal_specification);
    }
    return ok;
}

utility::string_t BTTableColumnInfo_1222::getBtType() const
{
    return m_BtType;
}

void BTTableColumnInfo_1222::setBtType(const utility::string_t& value)
{
    m_BtType = value;
    m_BtTypeIsSet = true;
}

bool BTTableColumnInfo_1222::btTypeIsSet() const
{
    return m_BtTypeIsSet;
}

void BTTableColumnInfo_1222::unsetBtType()
{
    m_BtTypeIsSet = false;
}
utility::string_t BTTableColumnInfo_1222::getId() const
{
    return m_Id;
}

void BTTableColumnInfo_1222::setId(const utility::string_t& value)
{
    m_Id = value;
    m_IdIsSet = true;
}

bool BTTableColumnInfo_1222::idIsSet() const
{
    return m_IdIsSet;
}

void BTTableColumnInfo_1222::unsetId()
{
    m_IdIsSet = false;
}
utility::string_t BTTableColumnInfo_1222::getNodeId() const
{
    return m_NodeId;
}

void BTTableColumnInfo_1222::setNodeId(const utility::string_t& value)
{
    m_NodeId = value;
    m_NodeIdIsSet = true;
}

bool BTTableColumnInfo_1222::nodeIdIsSet() const
{
    return m_NodeIdIsSet;
}

void BTTableColumnInfo_1222::unsetNodeId()
{
    m_NodeIdIsSet = false;
}
std::shared_ptr<BTTableColumnSpec_1967> BTTableColumnInfo_1222::getSpecification() const
{
    return m_Specification;
}

void BTTableColumnInfo_1222::setSpecification(const std::shared_ptr<BTTableColumnSpec_1967>& value)
{
    m_Specification = value;
    m_SpecificationIsSet = true;
}

bool BTTableColumnInfo_1222::specificationIsSet() const
{
    return m_SpecificationIsSet;
}

void BTTableColumnInfo_1222::unsetSpecification()
{
    m_SpecificationIsSet = false;
}
}
}
}
}


