{
  "openapi": "3.0.1",
  "info": {
    "title": "Onshape REST API",
    "description": "The Onshape REST API consumed by all clients.",
    "termsOfService": "http://swagger.io/terms/",
    "contact": {
      "email": "api-support@onshape.zendesk.com"
    },
    "license": {
      "name": "Apache 2.0",
      "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
    },
    "version": "1.133.27428.63074130d61b",
    "x-logo": {
      "backgroundColor": "#ffffff",
      "altText": "Onshape",
      "href": "https://www.onshape.com/",
      "url": "https://demo-c.dev.onshape.com/images/logo-onshape-gray-green.svg"
    },
    "x-filter-info": {
      "includeDeprecated": false,
      "restUserRole": "PUBLIC",
      "includedTags": [],
      "excludedTags": [],
      "documentationStatusesAllowedAndDesired": [
        "PRODUCTION"
      ],
      "desiredDocumentStatuses": []
    }
  },
  "servers": [
    {
      "url": "https://cad.onshape.com/api",
      "description": "Production"
    }
  ],
  "tags": [
    {
      "name": "Applications",
      "description": "Manage application settings."
    },
    {
      "name": "Accounts",
      "description": "Modify and access account information."
    },
    {
      "name": "AppElements",
      "description": "Modify, change, and get AppElements."
    },
    {
      "name": "Assemblies",
      "description": "Access and manipulate assembly elements."
    },
    {
      "name": "Billing",
      "description": "Access billing plans for clients."
    },
    {
      "name": "BlobElements",
      "description": "Save and access Blob Elements."
    },
    {
      "name": "Comments",
      "description": "CRUD for comments."
    },
    {
      "name": "Companies",
      "description": "Access company information."
    },
    {
      "name": "Document",
      "description": "Manage documents."
    },
    {
      "name": "Drawings",
      "description": "Access drawing translations."
    },
    {
      "name": "Elements",
      "description": "Access and manipulate Elements."
    },
    {
      "name": "FeatureStudios",
      "description": "Access and write to Feature Studio Elements."
    },
    {
      "name": "Folders",
      "description": "Access Folders."
    },
    {
      "name": "Metadata",
      "description": "Manipulate and access metadata."
    },
    {
      "name": "OpenAPI",
      "description": "Endpoints for getting the OpenAPI specification for the Onshape API."
    },
    {
      "name": "Parts",
      "description": "Get details about specific parts."
    },
    {
      "name": "PartStudios",
      "description": "Modify, change, and get PartStudios."
    },
    {
      "name": "ReleaseManagement",
      "description": "Manage Release Management workflows."
    },
    {
      "name": "Revisions",
      "description": "Access revisions."
    },
    {
      "name": "Teams",
      "description": "Access team details."
    },
    {
      "name": "Thumbnails",
      "description": "Get Thumbnails."
    },
    {
      "name": "Translations",
      "description": "Create and manage translations."
    },
    {
      "name": "Users",
      "description": "Get details about users."
    },
    {
      "name": "Versions",
      "description": "Example of API version management."
    },
    {
      "name": "Webhooks",
      "description": "Create and manage webhooks."
    },
    {
      "name": "Workflow",
      "description": "Access Release Management workflows."
    }
  ],
  "paths": {
    "/api/applications/clients/{cid}/settings/users/{uid}": {
      "get": {
        "tags": [
          "Applications"
        ],
        "summary": "Get User Application Settings",
        "operationId": "getUserAppSettings",
        "deprecated": false,
        "x-BTVisibility": "PRODUCTION"
      },
      "post": {
        "tags": [
          "Applications"
        ],
        "summary": "Update Application Settings",
        "operationId": "updateAppSettings",
        "deprecated": false,
        "x-BTVisibility": "PRODUCTION"
      },
      "delete": {
        "tags": [
          "Applications"
        ],
        "summary": "Delete Application Settings",
        "operationId": "deleteAppSettings",
        "deprecated": false,
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/applications/clients/{cid}/settings/companies/{cpid}": {
      "get": {
        "tags": [
          "Applications"
        ],
        "operationId": "getCompanyAppSettings",
        "deprecated": false,
        "x-BTVisibility": "PRODUCTION"
      },
      "post": {
        "tags": [
          "Applications"
        ],
        "operationId": "updateAppCompanySettings",
        "deprecated": false,
        "x-BTVisibility": "PRODUCTION"
      },
      "delete": {
        "tags": [
          "Applications"
        ],
        "operationId": "deleteCompanyAppSettings",
        "deprecated": false,
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/accounts/{aid}/purchases/{pid}": {
      "delete": {
        "tags": [
          "Accounts"
        ],
        "summary": "Cancel Recurring Subscription",
        "operationId": "cancelPurchaseNew",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Purchase"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/accounts/purchases/{pid}/consume": {
      "post": {
        "tags": [
          "Accounts"
        ],
        "summary": "Mark Purchase Consumed For User",
        "operationId": "consumePurchase",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Purchase"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/accounts/plans/{planId}/purchases": {
      "get": {
        "tags": [
          "Accounts"
        ],
        "summary": "Get Plan Purchases",
        "operationId": "getPlanPurchases",
        "deprecated": false,
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/accounts/purchases": {
      "get": {
        "tags": [
          "Accounts"
        ],
        "summary": "Get User's Appstore Purchases.",
        "operationId": "getPurchases",
        "deprecated": false,
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/aliases": {
      "get": {
        "operationId": "getAliasesInCompany",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      },
      "post": {
        "operationId": "createAlias",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Write"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/aliases/{aid}": {
      "get": {
        "operationId": "getAlias",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      },
      "post": {
        "operationId": "updateAlias",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Write"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      },
      "delete": {
        "operationId": "deleteAlias",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Write"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/aliases/{aid}/members": {
      "get": {
        "operationId": "getAliasMembers",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/appelements/d/{did}/w/{wid}/e/{eid}/copyassociativedata": {
      "post": {
        "operationId": "copyAssociativeData",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Write"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/appelements/d/{did}/{wvm}/{wvmid}/e/{eid}/associativedata": {
      "get": {
        "operationId": "getAssociativeData",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      },
      "post": {
        "operationId": "postAssociativeData",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read",
              "OAuth2Write"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      },
      "delete": {
        "operationId": "deleteAssociativeData",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Write"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/appelements/d/{did}/w/{wid}/e/{eid}/transactions/{tid}": {
      "delete": {
        "tags": [
          "AppElements"
        ],
        "summary": "Abort Transaction",
        "operationId": "abortTransaction",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Write"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/appelements/d/{did}/w/{wid}/transactions": {
      "post": {
        "tags": [
          "AppElements"
        ],
        "summary": "Commit Transactions",
        "operationId": "commitTransactions",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Write"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/appelements/d/{did}/{wvm}/{wvmid}/e/{eid}/compare": {
      "get": {
        "tags": [
          "AppElements"
        ],
        "summary": "Compare Json",
        "operationId": "compareAppElementJson",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/appelements/d/{did}/w/{wid}": {
      "post": {
        "tags": [
          "AppElements"
        ],
        "summary": "Create App Element",
        "operationId": "createElement",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Write"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/appelements/d/{did}/{wvm}/{wvmid}/e/{eid}/references": {
      "post": {
        "tags": [
          "AppElements"
        ],
        "summary": "Create Reference",
        "operationId": "createReference",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Write",
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/appelements/d/{did}/{wvm}/{wvmid}/e/{eid}/content/subelements/{sid}": {
      "delete": {
        "tags": [
          "AppElements"
        ],
        "summary": "Delete a Subelement",
        "operationId": "deleteAppElementContent",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Write"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/appelements/d/{did}/w/{wid}/e/{eid}/blob/{bid}": {
      "get": {
        "tags": [
          "AppElements"
        ],
        "operationId": "downloadBlobSubelementWorkspace",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      },
      "post": {
        "tags": [
          "AppElements"
        ],
        "summary": "Upload Blob Subelement",
        "operationId": "uploadBlobSubelement",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Write"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      },
      "delete": {
        "tags": [
          "AppElements"
        ],
        "summary": "Delete Blob Subelement",
        "operationId": "deleteBlobSubelement",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Write"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/appelements/d/{did}/{wvm}/{wvmid}/e/{eid}/references/{rid}": {
      "get": {
        "tags": [
          "AppElements"
        ],
        "summary": "Resolve Reference",
        "operationId": "resolveReference",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      },
      "post": {
        "tags": [
          "AppElements"
        ],
        "summary": "Update Reference",
        "operationId": "updateReference",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Write",
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      },
      "delete": {
        "tags": [
          "AppElements"
        ],
        "summary": "Delete Reference",
        "operationId": "deleteReference",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Write"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/appelements/d/{did}/{vm}/{vmid}/e/{eid}/blob/{bid}": {
      "get": {
        "tags": [
          "AppElements"
        ],
        "summary": "Download Blob Subelement",
        "operationId": "downloadBlobSubelement",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/appelements/d/{did}/{wvm}/{wvmid}/e/{eid}/content/history": {
      "get": {
        "tags": [
          "AppElements"
        ],
        "summary": "Get History",
        "operationId": "getAppElementHistory",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/appelements/d/{did}/{wvm}/{wvmid}/e/{eid}/blob": {
      "get": {
        "tags": [
          "AppElements"
        ],
        "summary": "Get Blob Subelement IDs",
        "operationId": "getBlobSubelementIds",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/appelements/d/{did}/w/{wid}/e/{eid}/transactions": {
      "get": {
        "tags": [
          "AppElements"
        ],
        "summary": "List App Element Transactions",
        "operationId": "getElementTransactions",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      },
      "post": {
        "tags": [
          "AppElements"
        ],
        "summary": "Start App Element Transaction",
        "operationId": "startTransaction",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Write"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/appelements/d/{did}/{wvm}/{wvmid}/e/{eid}/content/json": {
      "get": {
        "tags": [
          "AppElements"
        ],
        "summary": "Get Json",
        "operationId": "getJson",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/appelements/d/{did}/{wvm}/{wvmid}/e/{eid}/content/jsonpaths": {
      "post": {
        "tags": [
          "AppElements"
        ],
        "summary": "Get Json Paths",
        "operationId": "getJsonPaths",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/appelements/d/{did}/{wvm}/{wvmid}/e/{eid}/content": {
      "get": {
        "tags": [
          "AppElements"
        ],
        "summary": "Get Subelement Content",
        "operationId": "getSubElementContent",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      },
      "post": {
        "tags": [
          "AppElements"
        ],
        "summary": "Update App Element",
        "operationId": "updateAppElement",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read",
              "OAuth2Write"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/appelements/d/{did}/{wvm}/{wvmid}/e/{eid}/content/ids": {
      "get": {
        "tags": [
          "AppElements"
        ],
        "summary": "Get Subelement IDs",
        "operationId": "getSubelementIds",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/appelements/d/{did}/{wvm}/{wvmid}/e/{eid}/resolvereferences": {
      "get": {
        "tags": [
          "AppElements"
        ],
        "summary": "Resolve references.",
        "operationId": "resolveReferences",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/assemblies/d/{did}/{wvm}/{wvmid}/e/{eid}/features": {
      "get": {
        "tags": [
          "Assemblies"
        ],
        "summary": "Get Feature List",
        "operationId": "getFeatures",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      },
      "post": {
        "tags": [
          "Assemblies"
        ],
        "operationId": "addFeature",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Write"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/assemblies/d/{did}/w/{wid}": {
      "post": {
        "tags": [
          "Assemblies"
        ],
        "summary": "Create Assembly",
        "operationId": "createAssembly",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Write"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/assemblies/d/{did}/w/{wid}/e/{eid}/instances": {
      "post": {
        "tags": [
          "Assemblies"
        ],
        "summary": "Create assembly instance",
        "operationId": "createInstance",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read",
              "OAuth2Write"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/assemblies/d/{did}/w/{wid}/e/{eid}/features/featureid/{fid}": {
      "post": {
        "tags": [
          "Assemblies"
        ],
        "operationId": "updateFeature",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Write"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      },
      "delete": {
        "tags": [
          "Assemblies"
        ],
        "summary": "Delete Feature",
        "operationId": "deleteFeature",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Write"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/assemblies/d/{did}/w/{wid}/e/{eid}/instance/nodeid/{nid}": {
      "delete": {
        "tags": [
          "Assemblies"
        ],
        "summary": "Delete assembly instance.",
        "operationId": "deleteInstance",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Write"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/assemblies/d/{did}/{wvm}/{wvmid}/e/{eid}/boundingboxes": {
      "get": {
        "tags": [
          "Assemblies"
        ],
        "summary": "Bounding Boxes.",
        "operationId": "getAssemblyBoundingBoxes",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/assemblies/d/{did}/{wvm}/{wvmid}/e/{eid}": {
      "get": {
        "tags": [
          "Assemblies"
        ],
        "summary": "Assembly Definition.",
        "operationId": "getAssemblyDefinition",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/assemblies/d/{did}/{wvm}/{wvmid}/e/{eid}/shadedviews": {
      "get": {
        "tags": [
          "Assemblies"
        ],
        "operationId": "getAssemblyShadedViews",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/assemblies/d/{did}/{wvm}/{wvmid}/e/{eid}/bom": {
      "get": {
        "tags": [
          "Assemblies"
        ],
        "summary": "Get Bill of Materials",
        "operationId": "getBillOfMaterials",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/assemblies/d/{did}/{wvm}/{wvmid}/e/{eid}/featurespecs": {
      "get": {
        "tags": [
          "Assemblies"
        ],
        "operationId": "getFeatureSpecs",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/assemblies/d/{did}/e/{eid}/namedViews": {
      "get": {
        "tags": [
          "Assemblies"
        ],
        "operationId": "getNamedViews",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/assemblies/d/{did}/w/{wid}/e/{eid}/bomelement": {
      "post": {
        "tags": [
          "Assemblies"
        ],
        "summary": "Get or Create Bill of Materials Element",
        "operationId": "getOrCreateBillOfMaterialsElement",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/assemblies/d/{did}/w/{wid}/e/{eid}/transformedinstances": {
      "post": {
        "tags": [
          "Assemblies"
        ],
        "summary": "Create and transform assembly instances",
        "operationId": "insertTransformedInstances",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read",
              "OAuth2Write"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/assemblies/d/{did}/w/{wid}/e/{eid}/occurrencetransforms": {
      "post": {
        "tags": [
          "Assemblies"
        ],
        "summary": "Transform assembly occurrences.",
        "operationId": "transformOccurrences",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read",
              "OAuth2Write"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/assemblies/d/{did}/{wv}/{wvid}/e/{eid}/translations": {
      "post": {
        "tags": [
          "Assemblies"
        ],
        "summary": "Create Assembly translation.",
        "operationId": "translateFormat",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/billing/plans/client/{cid}": {
      "get": {
        "tags": [
          "Billing"
        ],
        "summary": "Get billing plans for client.",
        "operationId": "getClientPlans",
        "deprecated": false,
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/blobelements/d/{did}/{wv}/{wvid}/e/{eid}/translations": {
      "post": {
        "tags": [
          "BlobElements"
        ],
        "summary": "Create Translation.",
        "operationId": "createBlobTranslation",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/blobelements/d/{did}/w/{wid}/e/{eid}": {
      "get": {
        "tags": [
          "BlobElements"
        ],
        "operationId": "downloadFileWorkspace",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      },
      "post": {
        "tags": [
          "BlobElements"
        ],
        "summary": "Update Blob Element.",
        "operationId": "uploadFileUpdateElement",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Write"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/blobelements/d/{did}/w/{wid}/e/{eid}/units": {
      "post": {
        "tags": [
          "BlobElements"
        ],
        "summary": "Update Mesh Units.",
        "operationId": "updateUnits",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Write"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/blobelements/d/{did}/w/{wid}": {
      "post": {
        "tags": [
          "BlobElements"
        ],
        "summary": "Upload file to new element.",
        "operationId": "uploadFileCreateElement",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Write"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/comments/{cid}/attachment": {
      "post": {
        "tags": [
          "Comments"
        ],
        "operationId": "addAttachment",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Write"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      },
      "delete": {
        "tags": [
          "Comments"
        ],
        "operationId": "deleteAttachments",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Delete"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/comments": {
      "get": {
        "tags": [
          "Comments"
        ],
        "operationId": "getComments",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      },
      "post": {
        "tags": [
          "Comments"
        ],
        "operationId": "createComment",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/comments/{cid}": {
      "get": {
        "tags": [
          "Comments"
        ],
        "operationId": "getComment",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      },
      "post": {
        "tags": [
          "Comments"
        ],
        "operationId": "updateComment",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Write"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      },
      "delete": {
        "tags": [
          "Comments"
        ],
        "operationId": "deleteComment",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Delete"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/comments/{cid}/attachment/{fdid}.{ext}": {
      "get": {
        "tags": [
          "Comments"
        ],
        "operationId": "getAttachment",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/comments/{cid}/reopen": {
      "post": {
        "tags": [
          "Comments"
        ],
        "operationId": "reopen",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Write"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/comments/{cid}/resolve": {
      "post": {
        "tags": [
          "Comments"
        ],
        "operationId": "resolve",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Write"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/companies": {
      "get": {
        "tags": [
          "Companies"
        ],
        "summary": "Get User companies.",
        "operationId": "findCompany",
        "deprecated": false,
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/companies/{cid}": {
      "get": {
        "tags": [
          "Companies"
        ],
        "summary": "Get company.",
        "operationId": "getCompany",
        "deprecated": false,
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/companies/{cid}/documentsbyname": {
      "get": {
        "tags": [
          "Companies"
        ],
        "operationId": "getDocumentsByName",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/documents/{did}/workspaces/{wid}/copy": {
      "post": {
        "tags": [
          "Document"
        ],
        "summary": "Copy Workspace",
        "operationId": "copyWorkspace",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Write"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/documents": {
      "get": {
        "tags": [
          "Document"
        ],
        "summary": "Get Documents",
        "operationId": "getDocuments",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      },
      "post": {
        "tags": [
          "Document"
        ],
        "summary": "Create document.",
        "operationId": "createDocument",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Write"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/documents/d/{did}/versions": {
      "get": {
        "tags": [
          "Document"
        ],
        "summary": "Get Versions",
        "operationId": "getDocumentVersions",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      },
      "post": {
        "tags": [
          "Document"
        ],
        "summary": "Create Version.",
        "operationId": "createVersion",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Write"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/documents/d/{did}/workspaces": {
      "get": {
        "tags": [
          "Document"
        ],
        "summary": "Get Workspaces",
        "operationId": "getDocumentWorkspaces",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      },
      "post": {
        "tags": [
          "Document"
        ],
        "summary": "Create Workspace",
        "operationId": "createWorkspace",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Write"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/documents/{did}": {
      "get": {
        "tags": [
          "Document"
        ],
        "summary": "Get Document",
        "operationId": "getDocument",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      },
      "post": {
        "tags": [
          "Document"
        ],
        "summary": "Update Document Attributes.",
        "operationId": "updateDocumentAttributes",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Write"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      },
      "delete": {
        "tags": [
          "Document"
        ],
        "summary": "Delete Document",
        "operationId": "deleteDocument",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Delete"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/documents/d/{did}/workspaces/{wid}": {
      "delete": {
        "tags": [
          "Document"
        ],
        "summary": "Delete Workspace",
        "operationId": "deleteWorkspace",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Delete"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/documents/d/{did}/externaldata/{fid}": {
      "get": {
        "tags": [
          "Document"
        ],
        "summary": "Download External Data",
        "operationId": "downloadExternalData",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/documents/d/{did}/{wv}/{wvid}/e/{eid}/export": {
      "post": {
        "tags": [
          "Document"
        ],
        "operationId": "export2Json",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/documents/d/{did}/{wv}/{wvid}/currentmicroversion": {
      "get": {
        "tags": [
          "Document"
        ],
        "summary": "Get Current Document Microversion",
        "operationId": "getCurrentMicroversion",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/documents/{did}/acl": {
      "get": {
        "tags": [
          "Document"
        ],
        "summary": "Get Access Control List",
        "operationId": "getDocumentAcl",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/documents/d/{did}/{wm}/{wmid}/documenthistory": {
      "get": {
        "tags": [
          "Document"
        ],
        "operationId": "getDocumentHistory",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/documents/{did}/permissionset": {
      "get": {
        "tags": [
          "Document"
        ],
        "summary": "Get Document Permissions",
        "operationId": "getDocumentPermissionSet",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/documents/d/{did}/{wvm}/{wvmid}/elements": {
      "get": {
        "tags": [
          "Document"
        ],
        "summary": "Get a list of elements in the workspace, version, or microversion of the document.",
        "operationId": "getElementsInDocument",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/documents/d/{did}/{wv}/{wvid}/insertables": {
      "get": {
        "tags": [
          "Document"
        ],
        "operationId": "getInsertables",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/documents/d/{did}/versions/{vid}": {
      "get": {
        "tags": [
          "Document"
        ],
        "summary": "Get Version",
        "operationId": "getVersion",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/documents/{did}/workspaces/{wid}/merge": {
      "post": {
        "tags": [
          "Document"
        ],
        "summary": "Merge into workspace",
        "operationId": "mergeIntoWorkspace",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Write"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/documents/d/{did}/w/{wid}/moveelement": {
      "post": {
        "tags": [
          "Document"
        ],
        "summary": "Move Elements",
        "operationId": "moveElementsToDocument",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Write"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/documents/{did}/w/{wid}/restore/{vm}/{vmid}": {
      "post": {
        "tags": [
          "Document"
        ],
        "summary": "Restore version or microversion to workspace.",
        "operationId": "restoreFromHistory",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Write"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/documents/search": {
      "post": {
        "tags": [
          "Document"
        ],
        "operationId": "search",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/documents/{did}/share": {
      "post": {
        "tags": [
          "Document"
        ],
        "summary": "Share Document",
        "operationId": "shareDocument",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read",
              "OAuth2Share"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/documents/d/{did}/w/{wid}/syncAppElements": {
      "post": {
        "tags": [
          "Document"
        ],
        "operationId": "syncApplicationElements",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Write"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/documents/{did}/share/{eid}": {
      "delete": {
        "tags": [
          "Document"
        ],
        "summary": "Unshare Document",
        "operationId": "unShareDocument",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read",
              "OAuth2Share"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/documents/d/{did}/w/{wid}/e/{eid}/latestdocumentreferences": {
      "post": {
        "tags": [
          "Document"
        ],
        "summary": "Update External References to Latest",
        "operationId": "updateExternalReferencesToLatestDocuments",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Write"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/drawings/create": {
      "post": {
        "tags": [
          "Drawings"
        ],
        "operationId": "createDrawingAppElement",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Write"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/drawings/d/{did}/{wv}/{wvid}/e/{eid}/translations": {
      "post": {
        "tags": [
          "Drawings"
        ],
        "summary": "Create Drawing translation",
        "operationId": "createDrawingTranslation",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/drawings/d/{did}/w/{wid}/e/{eid}/translationformats": {
      "get": {
        "tags": [
          "Drawings"
        ],
        "operationId": "getDrawingTranslatorFormats",
        "deprecated": false,
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/elements/copyelement/{did}/workspace/{wid}": {
      "post": {
        "tags": [
          "Elements"
        ],
        "summary": "Copy Element",
        "operationId": "copyElementFromSourceDocument",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Write"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/elements/d/{did}/{wvm}/{wvmid}/e/{eid}/configurationencodings/{cid}": {
      "get": {
        "tags": [
          "Elements"
        ],
        "summary": "Decode Configuration String",
        "operationId": "decodeConfiguration",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/elements/d/{did}/w/{wid}/e/{eid}": {
      "delete": {
        "tags": [
          "Elements"
        ],
        "summary": "Delete Element",
        "operationId": "deleteElement",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Delete"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/elements/d/{did}/e/{eid}/configurationencodings": {
      "post": {
        "tags": [
          "Elements"
        ],
        "summary": "Encode Configuration",
        "operationId": "encodeConfigurationMap",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/elements/d/{did}/{wvm}/{wvmid}/e/{eid}/configuration": {
      "get": {
        "tags": [
          "Elements"
        ],
        "summary": "Get Configuration",
        "operationId": "getConfiguration",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      },
      "post": {
        "tags": [
          "Elements"
        ],
        "summary": "Update Configuration",
        "operationId": "updateConfiguration",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Write"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/elements/translatorFormats/{did}/{wv}/{wvid}/{eid}": {
      "get": {
        "tags": [
          "Elements"
        ],
        "summary": "Get Element Translator Formats",
        "operationId": "getElementTranslatorFormatsByVersionOrWorkspace",
        "deprecated": false,
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/elements/d/{did}/w/{wid}/e/{eid}/updatereferences": {
      "post": {
        "tags": [
          "Elements"
        ],
        "summary": "Update or replace node references",
        "operationId": "updateReferences",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read",
              "OAuth2Write"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/exportrules/options/{otype}/{oid}": {
      "get": {
        "operationId": "getValidRuleOptions",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/featurestudios/d/{did}/w/{wid}": {
      "post": {
        "tags": [
          "FeatureStudios"
        ],
        "summary": "Create Feature Studio",
        "operationId": "createFeatureStudio",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Write"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/featurestudios/d/{did}/{wvm}/{wvmid}/e/{eid}": {
      "get": {
        "tags": [
          "FeatureStudios"
        ],
        "summary": "Get Feature Studio Contents.",
        "operationId": "getFeatureStudioContents",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      },
      "post": {
        "tags": [
          "FeatureStudios"
        ],
        "summary": "Update Feature Studio contents",
        "operationId": "updateFeatureStudioContents",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Write"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/featurestudios/d/{did}/{wvm}/{wvmid}/e/{eid}/featurespecs": {
      "get": {
        "tags": [
          "FeatureStudios"
        ],
        "summary": "Get Feature Studio Specs",
        "operationId": "getFeatureStudioSpecs",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/folders/{fid}/acl": {
      "get": {
        "tags": [
          "Folders"
        ],
        "summary": "Get Access Control List",
        "operationId": "getFolderAcl",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/folders/{fid}/share": {
      "post": {
        "tags": [
          "Folders"
        ],
        "summary": "Share Folder",
        "operationId": "share",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read",
              "OAuth2Share"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/folders/{fid}/share/{eid}": {
      "delete": {
        "tags": [
          "Folders"
        ],
        "summary": "Unshare Folder",
        "operationId": "unShare",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read",
              "OAuth2Share"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/insertables/d/{did}/latest": {
      "get": {
        "summary": "Insertables for a document",
        "operationId": "getLatestInDocument",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/metadata/standardcontent/d/{did}/v/{vid}/e/{eid}/{otype}/{oid}/p/{pid}": {
      "get": {
        "tags": [
          "Metadata"
        ],
        "operationId": "getVEOPStandardContentMetadata",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      },
      "post": {
        "tags": [
          "Metadata"
        ],
        "operationId": "updateVEOPStandardContentPartMetadata",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Write"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/metadata/d/{did}/{wvm}/{wvmid}/e/{eid}": {
      "get": {
        "tags": [
          "Metadata"
        ],
        "operationId": "getWMVEMetadata",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      },
      "post": {
        "tags": [
          "Metadata"
        ],
        "operationId": "updateWVEMetadata",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Write"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/metadata/d/{did}/{wvm}/{wvmid}/e/{eid}/p/{pid}": {
      "get": {
        "tags": [
          "Metadata"
        ],
        "operationId": "getWMVEPMetadata",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      },
      "post": {
        "tags": [
          "Metadata"
        ],
        "operationId": "updateWVEPMetadata",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Write"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/metadata/d/{did}/{wvm}/{wvmid}/e/{eid}/p": {
      "get": {
        "tags": [
          "Metadata"
        ],
        "operationId": "getWMVEPsMetadata",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/metadata/d/{did}/{wvm}/{wvmid}/e": {
      "get": {
        "tags": [
          "Metadata"
        ],
        "operationId": "getWMVEsMetadata",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/metadata/d/{did}/{wv}/{wvid}": {
      "get": {
        "tags": [
          "Metadata"
        ],
        "operationId": "getWVMetadata",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      },
      "post": {
        "tags": [
          "Metadata"
        ],
        "operationId": "updateWVMetadata",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Write"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/metadatacategory/categoryproperties": {
      "get": {
        "operationId": "getCategoryProperties",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/openapi": {
      "get": {
        "tags": [
          "OpenAPI"
        ],
        "summary": "OpenAPI spec documentation for the Onshape REST API.",
        "operationId": "getOpenApi",
        "deprecated": false,
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/openapi/tags": {
      "get": {
        "tags": [
          "OpenAPI"
        ],
        "summary": "OpenAPI spec documentation for the Onshape REST API.",
        "operationId": "getTags",
        "deprecated": false,
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/parts/d/{did}/{wvm}/{wvmid}/e/{eid}/partid/{partid}/parasolid": {
      "get": {
        "tags": [
          "Parts"
        ],
        "summary": "Export Part to Parasolid.",
        "operationId": "exportPS",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/parts/d/{did}/{wvm}/{wvmid}/e/{eid}/partid/{partid}/stl": {
      "get": {
        "tags": [
          "Parts"
        ],
        "operationId": "exportStl",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/parts/d/{did}/{wvm}/{wvmid}/e/{eid}/partid/{partid}/sheetmetal/bendtable": {
      "get": {
        "tags": [
          "Parts"
        ],
        "summary": "Get Sheet Metal Bend Table.",
        "operationId": "getBendTable",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/parts/d/{did}/{wvm}/{wvmid}/e/{eid}/partid/{partid}/bodydetails": {
      "get": {
        "tags": [
          "Parts"
        ],
        "operationId": "getBodyDetails",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/parts/d/{did}/{wvm}/{wvmid}/e/{eid}/partid/{partid}/boundingboxes": {
      "get": {
        "tags": [
          "Parts"
        ],
        "operationId": "getBoundingBoxes",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/parts/d/{did}/{wvm}/{wvmid}/e/{eid}/partid/{partid}/tessellatededges": {
      "get": {
        "tags": [
          "Parts"
        ],
        "summary": "Tessellated Edges",
        "operationId": "getEdges",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/parts/d/{did}/{wvm}/{wvmid}/e/{eid}/partid/{partid}/massproperties": {
      "get": {
        "tags": [
          "Parts"
        ],
        "operationId": "getMassProperties",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/parts/d/{did}/{wvm}/{wvmid}/e/{eid}/partid/{partid}/metadata": {
      "get": {
        "tags": [
          "Parts"
        ],
        "operationId": "getPartMetadata",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      },
      "post": {
        "tags": [
          "Parts"
        ],
        "operationId": "updatePartMetadata",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read",
              "OAuth2Write"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/parts/d/{did}/{wvm}/{wvmid}/e/{eid}/partid/{partid}/shadedviews": {
      "get": {
        "tags": [
          "Parts"
        ],
        "operationId": "getPartShadedViews",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/parts/d/{did}/{wvm}/{wvmid}": {
      "get": {
        "tags": [
          "Parts"
        ],
        "summary": "Get list of parts",
        "operationId": "getPartsWMV",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/parts/d/{did}/{wvm}/{wvmid}/e/{eid}": {
      "get": {
        "tags": [
          "Parts"
        ],
        "summary": "Get parts from an element.",
        "operationId": "getPartsWMVE",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/parts/standardcontent/d/{did}/v/{vid}/e/{eid}/{otype}/{oid}/partid/{partid}/metadata": {
      "get": {
        "tags": [
          "Parts"
        ],
        "operationId": "getStandardContentPartMetadata",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      },
      "post": {
        "tags": [
          "Parts"
        ],
        "operationId": "updateStandardContentPartMetadata",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read",
              "OAuth2Write"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/partnumber/nextnumbers": {
      "post": {
        "operationId": "nextNumbers",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/partstudios/d/{did}/{wvm}/{wvmid}/e/{eid}/features": {
      "get": {
        "tags": [
          "PartStudios"
        ],
        "summary": "Get Feature List",
        "operationId": "getPartStudioFeatures",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      },
      "post": {
        "tags": [
          "PartStudios"
        ],
        "summary": "Add Feature",
        "operationId": "addPartStudioFeature",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Write"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/partstudios/d/{did}/{wvm}/{wvmid}/e/{eid}/compare": {
      "get": {
        "tags": [
          "PartStudios"
        ],
        "summary": "Compare Part Studios",
        "operationId": "comparePartStudios",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/partstudios/d/{did}/w/{wid}": {
      "post": {
        "tags": [
          "PartStudios"
        ],
        "summary": "Create Part Studio",
        "operationId": "createPartStudio",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Write"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/partstudios/d/{did}/{wv}/{wvid}/e/{eid}/translations": {
      "post": {
        "tags": [
          "PartStudios"
        ],
        "summary": "Create Part Studio translation",
        "operationId": "createPartStudioTranslation",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/partstudios/d/{did}/w/{wid}/e/{eid}/features/featureid/{fid}": {
      "post": {
        "tags": [
          "PartStudios"
        ],
        "summary": "Update Feature",
        "operationId": "updatePartStudioFeature",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Write"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      },
      "delete": {
        "tags": [
          "PartStudios"
        ],
        "summary": "Delete Feature",
        "operationId": "deletePartStudioFeature",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Write"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/partstudios/d/{did}/{wvm}/{wvmid}/e/{eid}/featurescript": {
      "post": {
        "tags": [
          "PartStudios"
        ],
        "operationId": "evalFeatureScript",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/partstudios/d/{did}/{wvm}/{wvmid}/e/{eid}/parasolid": {
      "get": {
        "tags": [
          "PartStudios"
        ],
        "summary": "Export Part Studio to Parasolid",
        "operationId": "exportParasolid",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/partstudios/d/{did}/{wvm}/{wvmid}/e/{eid}/stl": {
      "get": {
        "tags": [
          "PartStudios"
        ],
        "summary": "Export Part Studio to STL",
        "operationId": "exportPartStudioStl",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/partstudios/d/{did}/{wvm}/{wvmid}/e/{eid}/featurescriptrepresentation": {
      "get": {
        "tags": [
          "PartStudios"
        ],
        "operationId": "getFeatureScriptRepresentation",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/partstudios/d/{did}/{wvm}/{wvmid}/e/{eid}/bodydetails": {
      "get": {
        "tags": [
          "PartStudios"
        ],
        "summary": "Array of body information",
        "operationId": "getPartStudioBodyDetails",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/partstudios/d/{did}/{wvm}/{wvmid}/e/{eid}/boundingboxes": {
      "get": {
        "tags": [
          "PartStudios"
        ],
        "summary": "Mass properties of parts or a PartStudio.",
        "operationId": "getPartStudioBoundingBoxes",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/partstudios/d/{did}/{wvm}/{wvmid}/e/{eid}/tessellatededges": {
      "get": {
        "tags": [
          "PartStudios"
        ],
        "operationId": "getPartStudioEdges",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/partstudios/d/{did}/{wvm}/{wvmid}/e/{eid}/featurespecs": {
      "get": {
        "tags": [
          "PartStudios"
        ],
        "summary": "Get Feature Specs",
        "operationId": "getPartStudioFeatureSpecs",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/partstudios/d/{did}/{wvm}/{wvmid}/e/{eid}/massproperties": {
      "get": {
        "tags": [
          "PartStudios"
        ],
        "summary": "Mass properties of parts or a PartStudio.",
        "operationId": "getPartStudioMassProperties",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/partstudios/d/{did}/e/{eid}/namedViews": {
      "get": {
        "tags": [
          "PartStudios"
        ],
        "summary": "Get Named Views",
        "operationId": "getPartStudioNamedViews",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/partstudios/d/{did}/{wvm}/{wvmid}/e/{eid}/shadedviews": {
      "get": {
        "tags": [
          "PartStudios"
        ],
        "summary": "Get Shaded Views",
        "operationId": "getPartStudioShadedViews",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/partstudios/d/{did}/{wvm}/{wvmid}/e/{eid}/idtranslations": {
      "post": {
        "tags": [
          "PartStudios"
        ],
        "summary": "Id Translations",
        "operationId": "translateIds",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/partstudios/d/{did}/w/{wid}/e/{eid}/features/updates": {
      "post": {
        "tags": [
          "PartStudios"
        ],
        "summary": "Update Features",
        "operationId": "updateFeatures",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Write"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/partstudios/d/{did}/w/{wid}/e/{eid}/features/rollback": {
      "post": {
        "tags": [
          "PartStudios"
        ],
        "summary": "Update Feature Rollback",
        "operationId": "updateRollback",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Write"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/releasepackages/obsoletion/{wfid}": {
      "post": {
        "tags": [
          "ReleaseManagement"
        ],
        "operationId": "createObsoletionPackage",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Write"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/releasepackages/release/{wfid}": {
      "post": {
        "tags": [
          "ReleaseManagement"
        ],
        "operationId": "createReleasePackage",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Write"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/releasepackages/{rpid}": {
      "get": {
        "tags": [
          "ReleaseManagement"
        ],
        "operationId": "getReleasePackage",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      },
      "post": {
        "tags": [
          "ReleaseManagement"
        ],
        "operationId": "updateReleasePackage",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Write"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/releasepackages/companyreleaseworkflow": {
      "get": {
        "tags": [
          "ReleaseManagement"
        ],
        "operationId": "getCompanyReleaseWorkflow",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/revisions/companies/{cid}/partnumber/{pnum}/elementType/{et}": {
      "delete": {
        "tags": [
          "Revisions"
        ],
        "operationId": "deleteRevisionHistory",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Delete"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/revisions/companies/{cid}": {
      "get": {
        "tags": [
          "Revisions"
        ],
        "operationId": "enumerateRevisions",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/revisions/{cd}/{cdid}/p/{pnum}/latest": {
      "get": {
        "tags": [
          "Revisions"
        ],
        "operationId": "getLatestInDocumentOrCompany",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/revisions/companies/{cid}/d/{did}/{wv}/{wvid}/e/{eid}": {
      "get": {
        "tags": [
          "Revisions"
        ],
        "operationId": "getRevisionHistoryInCompanyByElementId",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/revisions/companies/{cid}/d/{did}/{wv}/{wvid}/e/{eid}/p/{pid}": {
      "get": {
        "tags": [
          "Revisions"
        ],
        "operationId": "getRevisionHistoryInCompanyByPartId",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/revisions/companies/{cid}/partnumber/{pnum}": {
      "get": {
        "tags": [
          "Revisions"
        ],
        "operationId": "getRevisionHistoryInCompanyByPartNumber",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/partstudios/d/{did}/{wvm}/{wvmid}/e/{eid}/sketches/{sid}/boundingboxes": {
      "get": {
        "operationId": "getSketchBoundingBoxes",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/partstudios/d/{did}/{wvm}/{wvmid}/e/{eid}/sketches": {
      "get": {
        "operationId": "getSketchInfo",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/partstudios/d/{did}/{wvm}/{wvmid}/e/{eid}/sketches/{sid}/tessellatedentities": {
      "get": {
        "operationId": "getTessellatedEntities",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/teams": {
      "get": {
        "tags": [
          "Teams"
        ],
        "operationId": "find",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/teams/{tid}": {
      "get": {
        "tags": [
          "Teams"
        ],
        "operationId": "getTeam",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/thumbnails/d/{did}/{wv}/{wvid}/e/{eid}": {
      "get": {
        "tags": [
          "Thumbnails"
        ],
        "operationId": "getElementThumbnail",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      },
      "post": {
        "tags": [
          "Thumbnails"
        ],
        "operationId": "setApplicationElementThumbnail",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Write"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      },
      "delete": {
        "tags": [
          "Thumbnails"
        ],
        "operationId": "deleteApplicationThumbnails",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Write"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/thumbnails/d/{did}/w/{wid}": {
      "get": {
        "tags": [
          "Thumbnails"
        ],
        "operationId": "getDocumentThumbnail",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/thumbnails/d/{did}/w/{wid}/s/{sz}": {
      "get": {
        "tags": [
          "Thumbnails"
        ],
        "operationId": "getDocumentThumbnailWithSize",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/thumbnails/d/{did}/w/{wid}/e/{eid}/ac/{cid}/s/{sz}": {
      "get": {
        "tags": [
          "Thumbnails"
        ],
        "operationId": "getElementThumbnailWithApiConfiguration",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/thumbnails/d/{did}/w/{wid}/e/{eid}/s/{sz}": {
      "get": {
        "tags": [
          "Thumbnails"
        ],
        "operationId": "getElementThumbnailWithSize",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/thumbnails/d/{did}": {
      "get": {
        "tags": [
          "Thumbnails"
        ],
        "operationId": "getThumbnailForDocument",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/thumbnails/d/{did}/v/{vid}": {
      "get": {
        "tags": [
          "Thumbnails"
        ],
        "operationId": "getThumbnailForDocumentAndVersion",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/thumbnails/document/{did}/version/{vid}": {
      "get": {
        "tags": [
          "Thumbnails"
        ],
        "operationId": "getThumbnailForDocumentAndVersionOld",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/thumbnails/document/{did}": {
      "get": {
        "tags": [
          "Thumbnails"
        ],
        "operationId": "getThumbnailForDocumentOld",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/translations/d/{did}/w/{wid}": {
      "post": {
        "tags": [
          "Translations"
        ],
        "summary": "Create translation from upload.",
        "operationId": "createTranslation",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/translations/{tid}": {
      "get": {
        "tags": [
          "Translations"
        ],
        "operationId": "getTranslation",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      },
      "delete": {
        "tags": [
          "Translations"
        ],
        "operationId": "deleteTranslation",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Write"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/translations/translationformats": {
      "get": {
        "tags": [
          "Translations"
        ],
        "operationId": "getAllTranslatorFormats",
        "deprecated": false,
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/translations/d/{did}": {
      "get": {
        "tags": [
          "Translations"
        ],
        "operationId": "getDocumentTranslations",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/users/session": {
      "post": {
        "tags": [
          "Users"
        ],
        "operationId": "session",
        "deprecated": false,
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/users/{uid}/settings": {
      "get": {
        "tags": [
          "Users"
        ],
        "operationId": "getUserSettings",
        "deprecated": false,
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/users/settings": {
      "get": {
        "tags": [
          "Users"
        ],
        "operationId": "getUserSettingsCurrentLoggedInUser",
        "deprecated": false,
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/users/sessioninfo": {
      "get": {
        "tags": [
          "Users"
        ],
        "operationId": "sessionInfo",
        "deprecated": false,
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/versions/test": {
      "get": {
        "tags": [
          "Versions"
        ],
        "operationId": "testVersionsGet",
        "deprecated": false,
        "x-BTVisibility": "PRODUCTION"
      },
      "post": {
        "tags": [
          "Versions"
        ],
        "operationId": "testVersionsPost",
        "deprecated": false,
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/webhooks": {
      "get": {
        "tags": [
          "Webhooks"
        ],
        "operationId": "getWebhooks",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      },
      "post": {
        "tags": [
          "Webhooks"
        ],
        "operationId": "createWebhook",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/webhooks/{webhookid}": {
      "get": {
        "tags": [
          "Webhooks"
        ],
        "operationId": "getWebhook",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      },
      "post": {
        "tags": [
          "Webhooks"
        ],
        "operationId": "updateWebhook",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      },
      "delete": {
        "tags": [
          "Webhooks"
        ],
        "operationId": "unregisterWebhook",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/webhooks/{webhookid}/ping": {
      "post": {
        "tags": [
          "Webhooks"
        ],
        "operationId": "pingWebhook",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/workflow/active": {
      "get": {
        "tags": [
          "Workflow"
        ],
        "operationId": "getActiveWorkflows",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/workflowabletestobject/testobject/{wfid}": {
      "post": {
        "operationId": "createWorkflowableTestObject",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Write"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/workflowabletestobject/{oid}": {
      "get": {
        "operationId": "getWorkflowableTestObject",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      },
      "post": {
        "operationId": "updateWorkflowableTestObject",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Write"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/workflowabletestobject/{oid}/{transition}": {
      "post": {
        "operationId": "transitionWorkflowableTestObject",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Write"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    }
  },
  "components": {
    "schemas": {
      "BTCompanySummaryInfo": {
        "type": "object",
        "properties": {
          "secondaryDomainPrefixes": {
            "uniqueItems": true,
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "noPublicDocuments": {
            "type": "boolean"
          },
          "enterpriseBaseUrl": {
            "type": "string"
          },
          "type": {
            "type": "integer",
            "format": "int32"
          },
          "state": {
            "type": "integer",
            "format": "int32"
          },
          "description": {
            "type": "string"
          },
          "admin": {
            "type": "boolean"
          },
          "domainPrefix": {
            "type": "string"
          },
          "ownerId": {
            "type": "string"
          },
          "image": {
            "type": "string"
          },
          "id": {
            "type": "string"
          },
          "href": {
            "type": "string",
            "format": "uri"
          },
          "viewRef": {
            "type": "string",
            "format": "uri"
          },
          "name": {
            "type": "string"
          }
        }
      },
      "BTUserSummaryInfo": {
        "type": "object",
        "properties": {
          "isGuest": {
            "type": "boolean"
          },
          "lastLoginTime": {
            "type": "string",
            "format": "date-time"
          },
          "isLight": {
            "type": "boolean"
          },
          "source": {
            "type": "integer",
            "format": "int32"
          },
          "company": {
            "$ref": "#/components/schemas/BTCompanySummaryInfo"
          },
          "globalPermissions": {
            "$ref": "#/components/schemas/GlobalPermissionInfo"
          },
          "firstName": {
            "type": "string"
          },
          "lastName": {
            "type": "string"
          },
          "email": {
            "type": "string"
          },
          "state": {
            "type": "integer",
            "format": "int32"
          },
          "image": {
            "type": "string"
          },
          "id": {
            "type": "string"
          },
          "href": {
            "type": "string",
            "format": "uri"
          },
          "viewRef": {
            "type": "string",
            "format": "uri"
          },
          "name": {
            "type": "string"
          }
        }
      },
      "GlobalPermissionInfo": {
        "type": "object",
        "properties": {
          "allowPublicDocumentsAccess_": {
            "type": "boolean"
          },
          "adminEnterprise": {
            "type": "boolean"
          },
          "manageRbac": {
            "type": "boolean"
          },
          "manageUsers": {
            "type": "boolean"
          },
          "manageGuestUsers": {
            "type": "boolean"
          },
          "deletePermanently": {
            "type": "boolean"
          },
          "accessReports": {
            "type": "boolean"
          },
          "createProject": {
            "type": "boolean"
          },
          "approveReleases": {
            "type": "boolean"
          },
          "createReleases": {
            "type": "boolean"
          },
          "shareForAnonymousAccess": {
            "type": "boolean"
          },
          "allowAppStoreAccess": {
            "type": "boolean"
          },
          "createDocumentsInRoot": {
            "type": "boolean"
          },
          "allowPublicDocumentsAccess": {
            "type": "boolean",
            "writeOnly": true
          },
          "createChangeRequests": {
            "type": "boolean"
          },
          "viewChangeRequests": {
            "type": "boolean"
          },
          "createChangeOrders": {
            "type": "boolean"
          },
          "viewChangeOrders": {
            "type": "boolean"
          }
        }
      },
      "BTSettingInfo": {
        "type": "object",
        "properties": {
          "key": {
            "type": "string"
          },
          "value": {
            "type": "object"
          }
        }
      },
      "BTUserAppSettingsInfo": {
        "type": "object",
        "properties": {
          "settings": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/BTSettingInfo"
            }
          }
        }
      },
      "BTSettingParam": {
        "type": "object",
        "properties": {
          "value": {
            "type": "object"
          },
          "key": {
            "type": "string"
          }
        }
      },
      "BTUserAppSettingsParams": {
        "type": "object",
        "properties": {
          "settings": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/BTSettingParam"
            }
          }
        }
      },
      "BodyPart": {
        "type": "object",
        "properties": {
          "contentDisposition": {
            "$ref": "#/components/schemas/ContentDisposition"
          },
          "entity": {
            "type": "object"
          },
          "mediaType": {
            "type": "object",
            "properties": {
              "type": {
                "type": "string"
              },
              "subtype": {
                "type": "string"
              },
              "wildcardType": {
                "type": "boolean"
              },
              "wildcardSubtype": {
                "type": "boolean"
              }
            }
          },
          "messageBodyWorkers": {
            "$ref": "#/components/schemas/MessageBodyWorkers"
          },
          "parent": {
            "$ref": "#/components/schemas/MultiPart"
          },
          "providers": {
            "type": "object"
          },
          "parameterizedHeaders": {
            "type": "object",
            "additionalProperties": {
              "type": "array",
              "items": {
                "$ref": "#/components/schemas/ParameterizedHeader"
              }
            }
          }
        }
      },
      "ContentDisposition": {
        "type": "object",
        "properties": {
          "type": {
            "type": "string"
          },
          "fileName": {
            "type": "string"
          },
          "creationDate": {
            "type": "string",
            "format": "date-time"
          },
          "modificationDate": {
            "type": "string",
            "format": "date-time"
          },
          "readDate": {
            "type": "string",
            "format": "date-time"
          },
          "size": {
            "type": "integer",
            "format": "int64"
          }
        }
      },
      "FormDataBodyPart": {
        "type": "object",
        "properties": {
          "contentDisposition": {
            "$ref": "#/components/schemas/ContentDisposition"
          },
          "entity": {
            "type": "object"
          },
          "mediaType": {
            "type": "object",
            "properties": {
              "type": {
                "type": "string"
              },
              "subtype": {
                "type": "string"
              },
              "wildcardType": {
                "type": "boolean"
              },
              "wildcardSubtype": {
                "type": "boolean"
              }
            }
          },
          "messageBodyWorkers": {
            "$ref": "#/components/schemas/MessageBodyWorkers"
          },
          "parent": {
            "$ref": "#/components/schemas/MultiPart"
          },
          "providers": {
            "type": "object"
          },
          "formDataContentDisposition": {
            "$ref": "#/components/schemas/FormDataContentDisposition"
          },
          "simple": {
            "type": "boolean"
          },
          "name": {
            "type": "string"
          },
          "value": {
            "type": "string"
          },
          "parameterizedHeaders": {
            "type": "object",
            "additionalProperties": {
              "type": "array",
              "items": {
                "$ref": "#/components/schemas/ParameterizedHeader"
              }
            }
          }
        }
      },
      "FormDataContentDisposition": {
        "type": "object",
        "properties": {
          "type": {
            "type": "string"
          },
          "fileName": {
            "type": "string"
          },
          "creationDate": {
            "type": "string",
            "format": "date-time"
          },
          "modificationDate": {
            "type": "string",
            "format": "date-time"
          },
          "readDate": {
            "type": "string",
            "format": "date-time"
          },
          "size": {
            "type": "integer",
            "format": "int64"
          },
          "name": {
            "type": "string"
          }
        }
      },
      "FormDataMultiPart": {
        "type": "object",
        "properties": {
          "contentDisposition": {
            "$ref": "#/components/schemas/ContentDisposition"
          },
          "entity": {
            "type": "object"
          },
          "mediaType": {
            "type": "object",
            "properties": {
              "type": {
                "type": "string"
              },
              "subtype": {
                "type": "string"
              },
              "wildcardType": {
                "type": "boolean"
              },
              "wildcardSubtype": {
                "type": "boolean"
              }
            }
          },
          "messageBodyWorkers": {
            "$ref": "#/components/schemas/MessageBodyWorkers"
          },
          "parent": {
            "$ref": "#/components/schemas/MultiPart"
          },
          "providers": {
            "type": "object"
          },
          "bodyParts": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/BodyPart"
            }
          },
          "fields": {
            "type": "object",
            "additionalProperties": {
              "type": "array",
              "items": {
                "$ref": "#/components/schemas/FormDataBodyPart"
              }
            }
          },
          "parameterizedHeaders": {
            "type": "object",
            "additionalProperties": {
              "type": "array",
              "items": {
                "$ref": "#/components/schemas/ParameterizedHeader"
              }
            }
          }
        }
      },
      "MessageBodyWorkers": {
        "type": "object"
      },
      "MultiPart": {
        "type": "object",
        "properties": {
          "contentDisposition": {
            "$ref": "#/components/schemas/ContentDisposition"
          },
          "entity": {
            "type": "object"
          },
          "mediaType": {
            "type": "object",
            "properties": {
              "type": {
                "type": "string"
              },
              "subtype": {
                "type": "string"
              },
              "wildcardType": {
                "type": "boolean"
              },
              "wildcardSubtype": {
                "type": "boolean"
              }
            }
          },
          "messageBodyWorkers": {
            "$ref": "#/components/schemas/MessageBodyWorkers"
          },
          "parent": {
            "$ref": "#/components/schemas/MultiPart"
          },
          "providers": {
            "type": "object"
          },
          "bodyParts": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/BodyPart"
            }
          },
          "parameterizedHeaders": {
            "type": "object",
            "additionalProperties": {
              "type": "array",
              "items": {
                "$ref": "#/components/schemas/ParameterizedHeader"
              }
            }
          }
        }
      },
      "ParameterizedHeader": {
        "type": "object",
        "properties": {
          "value": {
            "type": "string"
          }
        }
      },
      "BTAddressInfo": {
        "type": "object",
        "properties": {
          "country": {
            "type": "string"
          },
          "state": {
            "type": "string"
          },
          "id": {
            "type": "string"
          },
          "zip": {
            "type": "string"
          },
          "address": {
            "type": "string"
          },
          "city": {
            "type": "string"
          },
          "stateCode": {
            "type": "string"
          },
          "countryCode": {
            "type": "string"
          }
        }
      },
      "BTCardInfo": {
        "type": "object",
        "properties": {
          "billingAddress": {
            "$ref": "#/components/schemas/BTAddressInfo"
          },
          "last4": {
            "type": "string"
          },
          "expMonth": {
            "type": "integer",
            "format": "int32"
          },
          "expYear": {
            "type": "integer",
            "format": "int32"
          },
          "type": {
            "type": "string"
          }
        }
      },
      "Address": {
        "type": "object",
        "properties": {
          "city": {
            "type": "string"
          },
          "country": {
            "type": "string"
          },
          "line1": {
            "type": "string"
          },
          "line2": {
            "type": "string"
          },
          "postalCode": {
            "type": "string"
          },
          "state": {
            "type": "string"
          }
        }
      },
      "BTAPIApplicationSummaryInfo": {
        "type": "object",
        "properties": {
          "state": {
            "type": "integer",
            "format": "int32"
          },
          "description": {
            "type": "string"
          },
          "id": {
            "type": "string"
          },
          "clientId": {
            "type": "string"
          },
          "href": {
            "type": "string",
            "format": "uri"
          },
          "viewRef": {
            "type": "string",
            "format": "uri"
          },
          "name": {
            "type": "string"
          }
        }
      },
      "BTBillingPlanInfo": {
        "type": "object",
        "properties": {
          "discountInfo": {
            "$ref": "#/components/schemas/BTDiscountInfo"
          },
          "group": {
            "type": "string"
          },
          "clientId": {
            "type": "string"
          },
          "trialPeriodDays": {
            "type": "integer",
            "format": "int32"
          },
          "onshapePlan": {
            "type": "boolean"
          },
          "deprecated": {
            "type": "boolean"
          },
          "hidden": {
            "type": "boolean"
          },
          "description": {
            "type": "string"
          },
          "applicationId": {
            "type": "string"
          },
          "companyPlan": {
            "type": "boolean"
          },
          "planType": {
            "type": "integer",
            "format": "int32"
          },
          "amountCents": {
            "type": "integer",
            "format": "int32"
          },
          "interval": {
            "type": "string"
          },
          "consumableQuantity": {
            "type": "integer",
            "format": "int32"
          },
          "id": {
            "type": "string"
          },
          "href": {
            "type": "string",
            "format": "uri"
          },
          "viewRef": {
            "type": "string",
            "format": "uri"
          },
          "name": {
            "type": "string"
          }
        }
      },
      "BTDiscountInfo": {
        "type": "object",
        "properties": {
          "trialEndDate": {
            "type": "string"
          },
          "amountOff": {
            "type": "integer",
            "format": "int32"
          },
          "couponType": {
            "type": "integer",
            "format": "int32"
          },
          "accountBalance": {
            "type": "integer",
            "format": "int32"
          },
          "couponValidMonths": {
            "type": "integer",
            "format": "int32"
          },
          "percentOff": {
            "type": "integer",
            "format": "int32"
          },
          "usedAt": {
            "type": "string",
            "format": "date-time"
          },
          "createdAt": {
            "type": "string",
            "format": "date-time"
          },
          "planId": {
            "type": "string"
          },
          "createdBy": {
            "$ref": "#/components/schemas/BTUserSummaryInfo"
          },
          "ownerId": {
            "type": "string"
          },
          "expiresAt": {
            "type": "string",
            "format": "date-time"
          },
          "id": {
            "type": "string"
          },
          "href": {
            "type": "string",
            "format": "uri"
          },
          "viewRef": {
            "type": "string",
            "format": "uri"
          },
          "name": {
            "type": "string"
          }
        }
      },
      "BTPlanSubscriberInfo": {
        "type": "object",
        "properties": {
          "state": {
            "type": "integer",
            "format": "int32"
          },
          "firstName": {
            "type": "string"
          },
          "lastName": {
            "type": "string"
          },
          "email": {
            "type": "string"
          },
          "image": {
            "type": "string"
          },
          "id": {
            "type": "string"
          },
          "href": {
            "type": "string",
            "format": "uri"
          },
          "viewRef": {
            "type": "string",
            "format": "uri"
          },
          "name": {
            "type": "string"
          }
        }
      },
      "BTPurchaseInfo": {
        "type": "object",
        "properties": {
          "card": {
            "$ref": "#/components/schemas/BTCardInfo"
          },
          "lastModifiedBy": {
            "type": "string"
          },
          "trialEnd": {
            "type": "string",
            "format": "date-time"
          },
          "actualAmountPaidCents": {
            "type": "integer",
            "format": "int64"
          },
          "subscriptionId": {
            "type": "string"
          },
          "lightSeats": {
            "type": "integer",
            "format": "int64"
          },
          "planName": {
            "type": "string"
          },
          "taxAmountCents": {
            "type": "integer",
            "format": "int64"
          },
          "couponPercentOff": {
            "type": "integer",
            "format": "int32"
          },
          "resellerName": {
            "type": "string"
          },
          "trialInitiatedBy": {
            "type": "string"
          },
          "purchaseDate": {
            "type": "string",
            "format": "date-time"
          },
          "subscribers": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/BTPlanSubscriberInfo"
            }
          },
          "pendingCancelation": {
            "type": "boolean"
          },
          "nextCharge": {
            "$ref": "#/components/schemas/NextCharge"
          },
          "proratedCharges": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/ProratedCharges"
            }
          },
          "proratedTotal": {
            "type": "integer",
            "format": "int64"
          },
          "couponAmountOff": {
            "type": "integer",
            "format": "int64"
          },
          "durationMonths": {
            "type": "integer",
            "format": "int32"
          },
          "subscriptionFields": {
            "$ref": "#/components/schemas/Subscription"
          },
          "seats": {
            "type": "integer",
            "format": "int64"
          },
          "subscriptionType": {
            "type": "integer",
            "format": "int32"
          },
          "subscriptionBeginAt": {
            "type": "string",
            "format": "date-time"
          },
          "subscriptionEndAt": {
            "type": "string",
            "format": "date-time"
          },
          "canceledAt": {
            "type": "string",
            "format": "date-time"
          },
          "duration": {
            "type": "integer",
            "format": "int32"
          },
          "lastModified": {
            "type": "string",
            "format": "date-time"
          },
          "currency": {
            "type": "string"
          },
          "state": {
            "type": "integer",
            "format": "int32"
          },
          "group": {
            "type": "string"
          },
          "accountId": {
            "type": "string"
          },
          "planId": {
            "type": "string"
          },
          "plan": {
            "$ref": "#/components/schemas/BTBillingPlanInfo"
          },
          "planType": {
            "type": "integer",
            "format": "int32"
          },
          "paymentType": {
            "type": "integer",
            "format": "int32"
          },
          "application": {
            "$ref": "#/components/schemas/BTAPIApplicationSummaryInfo"
          },
          "clientId": {
            "type": "string"
          },
          "amountCents": {
            "type": "integer",
            "format": "int64"
          },
          "createdBy": {
            "type": "string"
          },
          "id": {
            "type": "string"
          },
          "href": {
            "type": "string",
            "format": "uri"
          },
          "viewRef": {
            "type": "string",
            "format": "uri"
          },
          "name": {
            "type": "string"
          }
        }
      },
      "BTUserBasicSummaryInfo": {
        "type": "object",
        "properties": {
          "state": {
            "type": "integer",
            "format": "int32"
          },
          "image": {
            "type": "string"
          },
          "id": {
            "type": "string"
          },
          "href": {
            "type": "string",
            "format": "uri"
          },
          "viewRef": {
            "type": "string",
            "format": "uri"
          },
          "name": {
            "type": "string"
          }
        },
        "discriminator": {
          "propertyName": "jsonType",
          "mapping": {
            "user-summary": "#/components/schemas/BTUserSummaryInfo"
          }
        }
      },
      "Card": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string"
          },
          "object": {
            "type": "string"
          },
          "account": {
            "type": "string"
          },
          "customer": {
            "type": "string"
          },
          "metadata": {
            "type": "object",
            "additionalProperties": {
              "type": "string"
            }
          },
          "addressCity": {
            "type": "string"
          },
          "addressCountry": {
            "type": "string"
          },
          "addressLine1": {
            "type": "string"
          },
          "addressLine1Check": {
            "type": "string"
          },
          "addressLine2": {
            "type": "string"
          },
          "addressState": {
            "type": "string"
          },
          "addressZip": {
            "type": "string"
          },
          "addressZipCheck": {
            "type": "string"
          },
          "availablePayoutMethods": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "brand": {
            "type": "string"
          },
          "country": {
            "type": "string"
          },
          "currency": {
            "type": "string"
          },
          "cvcCheck": {
            "type": "string"
          },
          "defaultForCurrency": {
            "type": "boolean"
          },
          "dynamicLast4": {
            "type": "string"
          },
          "expMonth": {
            "type": "integer",
            "format": "int32"
          },
          "expYear": {
            "type": "integer",
            "format": "int32"
          },
          "fingerprint": {
            "type": "string"
          },
          "funding": {
            "type": "string"
          },
          "last4": {
            "type": "string"
          },
          "name": {
            "type": "string"
          },
          "recipient": {
            "type": "string"
          },
          "status": {
            "type": "string"
          },
          "threeDSecure": {
            "$ref": "#/components/schemas/ThreeDSecure"
          },
          "tokenizationMethod": {
            "type": "string"
          },
          "description": {
            "type": "string"
          },
          "iin": {
            "type": "string"
          },
          "issuer": {
            "type": "string"
          },
          "type": {
            "type": "string"
          },
          "instanceURL": {
            "type": "string"
          }
        }
      },
      "Coupon": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string"
          },
          "object": {
            "type": "string"
          },
          "amountOff": {
            "type": "integer",
            "format": "int64"
          },
          "created": {
            "type": "integer",
            "format": "int64"
          },
          "currency": {
            "type": "string"
          },
          "duration": {
            "type": "string"
          },
          "durationInMonths": {
            "type": "integer",
            "format": "int32"
          },
          "livemode": {
            "type": "boolean"
          },
          "maxRedemptions": {
            "type": "integer",
            "format": "int64"
          },
          "metadata": {
            "type": "object",
            "additionalProperties": {
              "type": "string"
            }
          },
          "percentOff": {
            "type": "integer",
            "format": "int32"
          },
          "redeemBy": {
            "type": "integer",
            "format": "int64"
          },
          "timesRedeemed": {
            "type": "integer",
            "format": "int32"
          },
          "valid": {
            "type": "boolean"
          }
        }
      },
      "Customer": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string"
          },
          "object": {
            "type": "string"
          },
          "accountBalance": {
            "type": "integer",
            "format": "int64"
          },
          "businessVatId": {
            "type": "string"
          },
          "created": {
            "type": "integer",
            "format": "int64"
          },
          "currency": {
            "type": "string"
          },
          "defaultSource": {
            "type": "string"
          },
          "deleted": {
            "type": "boolean"
          },
          "delinquent": {
            "type": "boolean"
          },
          "description": {
            "type": "string"
          },
          "discount": {
            "$ref": "#/components/schemas/Discount"
          },
          "email": {
            "type": "string"
          },
          "livemode": {
            "type": "boolean"
          },
          "metadata": {
            "type": "object",
            "additionalProperties": {
              "type": "string"
            }
          },
          "shipping": {
            "$ref": "#/components/schemas/ShippingDetails"
          },
          "sources": {
            "$ref": "#/components/schemas/ExternalAccountCollection"
          },
          "subscriptions": {
            "$ref": "#/components/schemas/CustomerSubscriptionCollection"
          },
          "cards": {
            "$ref": "#/components/schemas/CustomerCardCollection"
          },
          "defaultCard": {
            "type": "string"
          },
          "nextRecurringCharge": {
            "$ref": "#/components/schemas/NextRecurringCharge"
          },
          "subscription": {
            "$ref": "#/components/schemas/Subscription"
          },
          "trialEnd": {
            "type": "integer",
            "format": "int64"
          },
          "defaultSourceObject": {
            "$ref": "#/components/schemas/ExternalAccount"
          }
        }
      },
      "CustomerCardCollection": {
        "type": "object",
        "properties": {
          "data": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/Card"
            }
          },
          "totalCount": {
            "type": "integer",
            "format": "int32"
          },
          "hasMore": {
            "type": "boolean"
          },
          "requestOptions": {
            "$ref": "#/components/schemas/RequestOptions"
          },
          "requestParams": {
            "type": "object",
            "additionalProperties": {
              "type": "object"
            }
          },
          "url": {
            "type": "string"
          },
          "count": {
            "type": "integer",
            "format": "int32"
          }
        }
      },
      "CustomerSubscriptionCollection": {
        "type": "object",
        "properties": {
          "data": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/Subscription"
            }
          },
          "totalCount": {
            "type": "integer",
            "format": "int32"
          },
          "hasMore": {
            "type": "boolean"
          },
          "requestOptions": {
            "$ref": "#/components/schemas/RequestOptions"
          },
          "requestParams": {
            "type": "object",
            "additionalProperties": {
              "type": "object"
            }
          },
          "url": {
            "type": "string"
          },
          "count": {
            "type": "integer",
            "format": "int32"
          }
        }
      },
      "Discount": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string"
          },
          "object": {
            "type": "string"
          },
          "coupon": {
            "$ref": "#/components/schemas/Coupon"
          },
          "customer": {
            "type": "string"
          },
          "end": {
            "type": "integer",
            "format": "int64"
          },
          "start": {
            "type": "integer",
            "format": "int64"
          },
          "subscription": {
            "type": "string"
          }
        }
      },
      "ExternalAccount": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string"
          },
          "object": {
            "type": "string"
          },
          "account": {
            "type": "string"
          },
          "customer": {
            "type": "string"
          },
          "metadata": {
            "type": "object",
            "additionalProperties": {
              "type": "string"
            }
          },
          "instanceURL": {
            "type": "string"
          }
        }
      },
      "ExternalAccountCollection": {
        "type": "object",
        "properties": {
          "data": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/ExternalAccount"
            }
          },
          "totalCount": {
            "type": "integer",
            "format": "int32"
          },
          "hasMore": {
            "type": "boolean"
          },
          "requestOptions": {
            "$ref": "#/components/schemas/RequestOptions"
          },
          "requestParams": {
            "type": "object",
            "additionalProperties": {
              "type": "object"
            }
          },
          "url": {
            "type": "string"
          },
          "count": {
            "type": "integer",
            "format": "int32"
          }
        }
      },
      "NextCharge": {
        "type": "object",
        "properties": {
          "amount": {
            "type": "integer",
            "format": "int64"
          },
          "currentPeriodEnd": {
            "type": "string",
            "format": "date-time"
          },
          "total": {
            "type": "integer",
            "format": "int64"
          },
          "interval": {
            "type": "string"
          }
        }
      },
      "NextRecurringCharge": {
        "type": "object",
        "properties": {
          "amount": {
            "type": "integer",
            "format": "int64"
          },
          "date": {
            "type": "string"
          }
        }
      },
      "Plan": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string"
          },
          "object": {
            "type": "string"
          },
          "amount": {
            "type": "integer",
            "format": "int64"
          },
          "created": {
            "type": "integer",
            "format": "int64"
          },
          "currency": {
            "type": "string"
          },
          "interval": {
            "type": "string"
          },
          "intervalCount": {
            "type": "integer",
            "format": "int32"
          },
          "livemode": {
            "type": "boolean"
          },
          "metadata": {
            "type": "object",
            "additionalProperties": {
              "type": "string"
            }
          },
          "name": {
            "type": "string"
          },
          "statementDescriptor": {
            "type": "string"
          },
          "trialPeriodDays": {
            "type": "integer",
            "format": "int32"
          },
          "statementDescription": {
            "type": "string"
          }
        }
      },
      "ProratedCharges": {
        "type": "object",
        "properties": {
          "amount": {
            "type": "integer",
            "format": "int64"
          },
          "date": {
            "type": "string",
            "format": "date-time"
          },
          "description": {
            "type": "string"
          }
        }
      },
      "RequestOptions": {
        "type": "object",
        "properties": {
          "apiKey": {
            "type": "string"
          },
          "stripeVersion": {
            "type": "string"
          },
          "idempotencyKey": {
            "type": "string"
          },
          "stripeAccount": {
            "type": "string"
          },
          "connectTimeout": {
            "type": "integer",
            "format": "int32"
          },
          "readTimeout": {
            "type": "integer",
            "format": "int32"
          }
        }
      },
      "ShippingDetails": {
        "type": "object",
        "properties": {
          "address": {
            "$ref": "#/components/schemas/Address"
          },
          "name": {
            "type": "string"
          },
          "phone": {
            "type": "string"
          }
        }
      },
      "Subscription": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string"
          },
          "object": {
            "type": "string"
          },
          "applicationFeePercent": {
            "type": "number",
            "format": "double"
          },
          "billing": {
            "type": "string"
          },
          "cancelAtPeriodEnd": {
            "type": "boolean"
          },
          "canceledAt": {
            "type": "integer",
            "format": "int64"
          },
          "created": {
            "type": "integer",
            "format": "int64"
          },
          "currentPeriodEnd": {
            "type": "integer",
            "format": "int64"
          },
          "currentPeriodStart": {
            "type": "integer",
            "format": "int64"
          },
          "customer": {
            "type": "string"
          },
          "daysUntilDue": {
            "type": "integer",
            "format": "int32"
          },
          "discount": {
            "$ref": "#/components/schemas/Discount"
          },
          "endedAt": {
            "type": "integer",
            "format": "int64"
          },
          "metadata": {
            "type": "object",
            "additionalProperties": {
              "type": "string"
            }
          },
          "plan": {
            "$ref": "#/components/schemas/Plan"
          },
          "quantity": {
            "type": "integer",
            "format": "int32"
          },
          "start": {
            "type": "integer",
            "format": "int64"
          },
          "status": {
            "type": "string"
          },
          "taxPercent": {
            "type": "number",
            "format": "double"
          },
          "trialEnd": {
            "type": "integer",
            "format": "int64"
          },
          "trialStart": {
            "type": "integer",
            "format": "int64"
          },
          "customerObject": {
            "$ref": "#/components/schemas/Customer"
          },
          "subscriptionItems": {
            "$ref": "#/components/schemas/SubscriptionItemCollection"
          }
        }
      },
      "SubscriptionItem": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string"
          },
          "object": {
            "type": "string"
          },
          "created": {
            "type": "integer",
            "format": "int64"
          },
          "plan": {
            "$ref": "#/components/schemas/Plan"
          },
          "quantity": {
            "type": "integer",
            "format": "int32"
          }
        }
      },
      "SubscriptionItemCollection": {
        "type": "object",
        "properties": {
          "data": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/SubscriptionItem"
            }
          },
          "totalCount": {
            "type": "integer",
            "format": "int32"
          },
          "hasMore": {
            "type": "boolean"
          },
          "requestOptions": {
            "$ref": "#/components/schemas/RequestOptions"
          },
          "requestParams": {
            "type": "object",
            "additionalProperties": {
              "type": "object"
            }
          },
          "url": {
            "type": "string"
          },
          "count": {
            "type": "integer",
            "format": "int32"
          }
        }
      },
      "ThreeDSecure": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string"
          },
          "object": {
            "type": "string"
          },
          "amount": {
            "type": "integer",
            "format": "int64"
          },
          "authenticated": {
            "type": "boolean"
          },
          "card": {
            "$ref": "#/components/schemas/Card"
          },
          "created": {
            "type": "integer",
            "format": "int64"
          },
          "currency": {
            "type": "string"
          },
          "livemode": {
            "type": "boolean"
          },
          "redirectURL": {
            "type": "string"
          },
          "status": {
            "type": "string"
          }
        }
      },
      "BTPurchaseUserParams": {
        "type": "object",
        "properties": {
          "userId": {
            "type": "string"
          },
          "consumedQuantity": {
            "type": "integer",
            "format": "int32"
          },
          "purchaseId": {
            "type": "string"
          }
        }
      },
      "BTBaseInfo": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string"
          },
          "href": {
            "type": "string",
            "format": "uri"
          },
          "viewRef": {
            "type": "string",
            "format": "uri"
          },
          "name": {
            "type": "string"
          }
        }
      },
      "BTCompanyInfo": {
        "type": "object",
        "properties": {
          "purchase": {
            "$ref": "#/components/schemas/BTPurchaseInfo"
          },
          "address": {
            "$ref": "#/components/schemas/BTAddressInfo"
          },
          "secondaryDomainPrefixes": {
            "uniqueItems": true,
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "noPublicDocuments": {
            "type": "boolean"
          },
          "enterpriseBaseUrl": {
            "type": "string"
          },
          "type": {
            "type": "integer",
            "format": "int32"
          },
          "state": {
            "type": "integer",
            "format": "int32"
          },
          "description": {
            "type": "string"
          },
          "admin": {
            "type": "boolean"
          },
          "domainPrefix": {
            "type": "string"
          },
          "ownerId": {
            "type": "string"
          },
          "image": {
            "type": "string"
          },
          "id": {
            "type": "string"
          },
          "href": {
            "type": "string",
            "format": "uri"
          },
          "viewRef": {
            "type": "string",
            "format": "uri"
          },
          "name": {
            "type": "string"
          }
        }
      },
      "BTListResponseBTPurchaseInfo": {
        "type": "object",
        "properties": {
          "previous": {
            "type": "string",
            "format": "uri"
          },
          "next": {
            "type": "string",
            "format": "uri"
          },
          "href": {
            "type": "string",
            "format": "uri"
          },
          "items": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/BTPurchaseInfo"
            }
          }
        }
      },
      "BTDocumentElementInfo": {
        "type": "object",
        "properties": {
          "lengthUnits": {
            "type": "string"
          },
          "angleUnits": {
            "type": "string"
          },
          "massUnits": {
            "type": "string"
          },
          "elementType": {
            "type": "string",
            "enum": [
              "PARTSTUDIO",
              "ASSEMBLY",
              "DRAWING",
              "FEATURESTUDIO",
              "BLOB",
              "APPLICATION",
              "TABLE",
              "BILLOFMATERIALS",
              "UNKNOWN"
            ]
          },
          "type": {
            "type": "string"
          },
          "filename": {
            "type": "string"
          },
          "id": {
            "type": "string"
          },
          "dataType": {
            "type": "string"
          },
          "thumbnails": {
            "type": "string",
            "format": "uri"
          },
          "microversionId": {
            "type": "string"
          },
          "thumbnailInfo": {
            "$ref": "#/components/schemas/BTThumbnailInfo"
          },
          "foreignDataId": {
            "type": "string"
          },
          "unupdatable": {
            "type": "boolean"
          },
          "specifiedUnit": {
            "type": "string"
          },
          "name": {
            "type": "string"
          }
        }
      },
      "BTThumbnailInfo": {
        "type": "object",
        "properties": {
          "sizes": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/BTThumbnailSizeInfo"
            }
          },
          "secondarySizes": {
            "type": "array",
            "items": {
              "type": "array",
              "items": {
                "$ref": "#/components/schemas/BTThumbnailSizeInfo"
              }
            }
          },
          "id": {
            "type": "string"
          },
          "href": {
            "type": "string",
            "format": "uri"
          }
        }
      },
      "BTThumbnailSizeInfo": {
        "type": "object",
        "properties": {
          "viewOrientation": {
            "type": "string"
          },
          "sheetName": {
            "type": "string"
          },
          "mediaType": {
            "type": "string"
          },
          "size": {
            "type": "string"
          },
          "uniqueId": {
            "type": "string"
          },
          "href": {
            "type": "string",
            "format": "uri"
          },
          "renderMode": {
            "type": "string"
          }
        }
      },
      "BTVersionInfo": {
        "type": "object",
        "properties": {
          "purpose": {
            "type": "integer",
            "format": "int32"
          },
          "overrideDate": {
            "type": "string",
            "format": "date-time"
          },
          "microversion": {
            "type": "string"
          },
          "type": {
            "type": "string"
          },
          "description": {
            "type": "string"
          },
          "creator": {
            "$ref": "#/components/schemas/BTUserBasicSummaryInfo"
          },
          "modifiedAt": {
            "type": "string",
            "format": "date-time"
          },
          "documentId": {
            "type": "string"
          },
          "createdAt": {
            "type": "string",
            "format": "date-time"
          },
          "lastModifier": {
            "$ref": "#/components/schemas/BTUserBasicSummaryInfo"
          },
          "thumbnail": {
            "$ref": "#/components/schemas/BTThumbnailInfo"
          },
          "parent": {
            "type": "string"
          },
          "id": {
            "type": "string"
          },
          "href": {
            "type": "string",
            "format": "uri"
          },
          "viewRef": {
            "type": "string",
            "format": "uri"
          },
          "name": {
            "type": "string"
          }
        }
      },
      "BTWorkspaceInfo": {
        "type": "object",
        "properties": {
          "canDelete": {
            "type": "boolean"
          },
          "isReadOnly": {
            "type": "boolean"
          },
          "overrideDate": {
            "type": "string",
            "format": "date-time"
          },
          "microversion": {
            "type": "string"
          },
          "type": {
            "type": "string"
          },
          "description": {
            "type": "string"
          },
          "creator": {
            "$ref": "#/components/schemas/BTUserBasicSummaryInfo"
          },
          "modifiedAt": {
            "type": "string",
            "format": "date-time"
          },
          "documentId": {
            "type": "string"
          },
          "createdAt": {
            "type": "string",
            "format": "date-time"
          },
          "lastModifier": {
            "$ref": "#/components/schemas/BTUserBasicSummaryInfo"
          },
          "thumbnail": {
            "$ref": "#/components/schemas/BTThumbnailInfo"
          },
          "parents": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/BTVersionInfo"
            }
          },
          "parent": {
            "type": "string"
          },
          "id": {
            "type": "string"
          },
          "href": {
            "type": "string",
            "format": "uri"
          },
          "viewRef": {
            "type": "string",
            "format": "uri"
          },
          "name": {
            "type": "string"
          }
        }
      },
      "BTAliasEntryInfo": {
        "type": "object",
        "properties": {
          "identity": {
            "$ref": "#/components/schemas/BTIdentityInfo"
          },
          "createdAt": {
            "type": "string",
            "format": "date-time"
          },
          "id": {
            "type": "string"
          },
          "href": {
            "type": "string",
            "format": "uri"
          },
          "viewRef": {
            "type": "string",
            "format": "uri"
          },
          "name": {
            "type": "string"
          }
        }
      },
      "BTAliasInfo": {
        "type": "object",
        "properties": {
          "identities": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/BTIdentityInfo"
            }
          },
          "description": {
            "type": "string"
          },
          "companyId": {
            "type": "string"
          },
          "createdAt": {
            "type": "string",
            "format": "date-time"
          },
          "entries": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/BTAliasEntryInfo"
            }
          },
          "id": {
            "type": "string"
          },
          "href": {
            "type": "string",
            "format": "uri"
          },
          "viewRef": {
            "type": "string",
            "format": "uri"
          },
          "name": {
            "type": "string"
          }
        }
      },
      "BTIdentityInfo": {
        "type": "object",
        "properties": {
          "team": {
            "$ref": "#/components/schemas/BTTeamSummaryInfo"
          },
          "identityType": {
            "type": "integer",
            "format": "int32"
          },
          "user": {
            "$ref": "#/components/schemas/BTUserSummaryInfo"
          },
          "id": {
            "type": "string"
          },
          "href": {
            "type": "string",
            "format": "uri"
          },
          "viewRef": {
            "type": "string",
            "format": "uri"
          }
        }
      },
      "BTOwnerInfo": {
        "type": "object",
        "properties": {
          "acceptOwnershipTransfer": {
            "type": "boolean"
          },
          "isEnterpriseOwnedResource": {
            "type": "boolean"
          },
          "type": {
            "type": "integer",
            "format": "int32"
          },
          "image": {
            "type": "string"
          },
          "id": {
            "type": "string"
          },
          "href": {
            "type": "string",
            "format": "uri"
          },
          "viewRef": {
            "type": "string",
            "format": "uri"
          },
          "name": {
            "type": "string"
          }
        }
      },
      "BTTeamInfo": {
        "type": "object",
        "allOf": [
          {
            "$ref": "#/components/schemas/BTTeamSummaryInfo"
          },
          {
            "type": "object",
            "properties": {
              "member": {
                "type": "boolean"
              },
              "size": {
                "type": "integer",
                "format": "int32"
              },
              "admin": {
                "type": "boolean"
              }
            }
          }
        ]
      },
      "BTTeamSummaryInfo": {
        "type": "object",
        "properties": {
          "predefinedTeam": {
            "type": "integer",
            "format": "int32"
          },
          "active": {
            "type": "boolean"
          },
          "resourceType": {
            "type": "string"
          },
          "treeHref": {
            "type": "string"
          },
          "isMutable": {
            "type": "boolean"
          },
          "isContainer": {
            "type": "boolean"
          },
          "canMove": {
            "type": "boolean"
          },
          "owner": {
            "$ref": "#/components/schemas/BTOwnerInfo"
          },
          "description": {
            "type": "string"
          },
          "modifiedAt": {
            "type": "string",
            "format": "date-time"
          },
          "createdAt": {
            "type": "string",
            "format": "date-time"
          },
          "createdBy": {
            "$ref": "#/components/schemas/BTUserBasicSummaryInfo"
          },
          "modifiedBy": {
            "$ref": "#/components/schemas/BTUserBasicSummaryInfo"
          },
          "projectId": {
            "type": "string"
          },
          "isEnterpriseOwned": {
            "type": "boolean"
          },
          "id": {
            "type": "string"
          },
          "href": {
            "type": "string",
            "format": "uri"
          },
          "viewRef": {
            "type": "string",
            "format": "uri"
          },
          "name": {
            "type": "string"
          }
        },
        "discriminator": {
          "propertyName": "jsonType",
          "mapping": {
            "team": "#/components/schemas/BTTeamInfo"
          }
        }
      },
      "BTAliasEntryParams": {
        "type": "object",
        "properties": {
          "userId": {
            "type": "string"
          },
          "email": {
            "type": "string"
          },
          "teamId": {
            "type": "string"
          }
        }
      },
      "BTAliasParams": {
        "type": "object",
        "properties": {
          "description": {
            "type": "string"
          },
          "additions": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/BTAliasEntryParams"
            }
          },
          "removals": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/BTAliasEntryParams"
            }
          },
          "name": {
            "type": "string"
          },
          "entries": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/BTAliasEntryParams"
            }
          }
        }
      },
      "BTListResponseBTAliasEntryInfo": {
        "type": "object",
        "properties": {
          "previous": {
            "type": "string",
            "format": "uri"
          },
          "next": {
            "type": "string",
            "format": "uri"
          },
          "href": {
            "type": "string",
            "format": "uri"
          },
          "items": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/BTAliasEntryInfo"
            }
          }
        }
      },
      "BTListResponseBTAliasInfo": {
        "type": "object",
        "properties": {
          "previous": {
            "type": "string",
            "format": "uri"
          },
          "next": {
            "type": "string",
            "format": "uri"
          },
          "href": {
            "type": "string",
            "format": "uri"
          },
          "items": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/BTAliasInfo"
            }
          }
        }
      },
      "BTAppAssociativeDataArrayInfo": {
        "type": "object",
        "properties": {
          "items": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/BTAssociativeDataInfo"
            }
          },
          "parentChangeId": {
            "type": "string"
          },
          "changeId": {
            "type": "string"
          },
          "errorDescription": {
            "type": "string"
          },
          "errorCode": {
            "type": "integer",
            "format": "int32"
          },
          "errorValue": {
            "type": "string",
            "writeOnly": true,
            "enum": [
              "OK",
              "TRANSACTION_CONFLICT",
              "NOT_FOUND",
              "INCONSISTENT_CHANGES"
            ]
          }
        }
      },
      "BTAssociativeDataInfo": {
        "type": "object",
        "properties": {
          "occurrenceId": {
            "type": "string"
          },
          "associativeDataId": {
            "type": "string"
          },
          "data": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/BTNameValuePair"
            }
          },
          "type": {
            "type": "string",
            "enum": [
              "ONSHAPE_DRAWING_VIEW",
              "MODEL_TOPOLOGY",
              "MODEL_DEFINITION_FEATURE",
              "MODEL_DEFINITION_ENTITY",
              "UNKNOWN"
            ]
          },
          "microversionId": {
            "type": "string"
          },
          "versionId": {
            "type": "string"
          },
          "documentId": {
            "type": "string"
          },
          "elementId": {
            "type": "string"
          },
          "documentMicroversion": {
            "type": "string"
          },
          "idTag": {
            "type": "string"
          },
          "error": {
            "type": "string"
          }
        }
      },
      "BTNameValuePair": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "value": {
            "type": "string"
          }
        }
      },
      "BTAppElementParamsArrayBTCopyViewAssociativeDataParams": {
        "type": "object",
        "properties": {
          "description": {
            "type": "string"
          },
          "parentChangeId": {
            "type": "string"
          },
          "items": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/BTCopyViewAssociativeDataParams"
            }
          },
          "transactionId": {
            "type": "string"
          }
        }
      },
      "BTCopyViewAssociativeDataParams": {
        "type": "object",
        "properties": {
          "sourceViewId": {
            "type": "string"
          },
          "destinationViewId": {
            "type": "string"
          }
        }
      },
      "BTAppElementBasicInfo": {
        "type": "object",
        "properties": {
          "parentChangeId": {
            "type": "string"
          },
          "changeId": {
            "type": "string"
          },
          "errorDescription": {
            "type": "string"
          },
          "errorCode": {
            "type": "integer",
            "format": "int32"
          },
          "errorValue": {
            "type": "string",
            "writeOnly": true,
            "enum": [
              "OK",
              "TRANSACTION_CONFLICT",
              "NOT_FOUND",
              "INCONSISTENT_CHANGES"
            ]
          }
        }
      },
      "BTBoundingBox-1052": {
        "type": "object",
        "properties": {
          "valid": {
            "type": "boolean"
          },
          "minCorner": {
            "$ref": "#/components/schemas/BTVector3d-389"
          },
          "maxCorner": {
            "$ref": "#/components/schemas/BTVector3d-389"
          }
        }
      },
      "BTVector3d-389": {
        "type": "object",
        "properties": {
          "z": {
            "type": "number",
            "format": "double"
          },
          "x": {
            "type": "number",
            "format": "double"
          },
          "y": {
            "type": "number",
            "format": "double"
          },
          "btType": {
            "type": "string"
          }
        }
      },
      "BTAppElementModifyInfo": {
        "type": "object",
        "properties": {
          "elementId": {
            "type": "string"
          },
          "elementIds": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "propertyEditsMerged": {
            "type": "boolean"
          },
          "parentChangeId": {
            "type": "string"
          },
          "changeId": {
            "type": "string"
          },
          "transactionId": {
            "type": "string"
          },
          "errorDescription": {
            "type": "string"
          },
          "errorCode": {
            "type": "integer",
            "format": "int32"
          },
          "errorValue": {
            "type": "string",
            "writeOnly": true,
            "enum": [
              "OK",
              "TRANSACTION_CONFLICT",
              "NOT_FOUND",
              "INCONSISTENT_CHANGES"
            ]
          }
        }
      },
      "BTAppElementCommitTransactionParams": {
        "type": "object",
        "properties": {
          "description": {
            "type": "string"
          },
          "transactionIds": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "allowMerge": {
            "type": "boolean"
          },
          "returnError": {
            "type": "boolean"
          }
        }
      },
      "BTDiffJsonResponse-2725": {
        "type": "object",
        "properties": {
          "sourceChangeId": {
            "type": "string"
          },
          "targetChangeId": {
            "type": "string"
          },
          "patch": {
            "type": "object",
            "properties": {
              "btType": {
                "type": "string"
              }
            }
          },
          "change": {
            "$ref": "#/components/schemas/BTJEdit-3734"
          }
        }
      },
      "BTJEdit-3734": {
        "type": "object",
        "properties": {
          "btType": {
            "type": "string"
          }
        },
        "discriminator": {
          "propertyName": "btType",
          "mapping": {
            "BTJEditChange-2636": "#/components/schemas/BTJEditChange-2636",
            "BTJEditDelete-1992": "#/components/schemas/BTJEditDelete-1992",
            "BTJEditInsert-2523": "#/components/schemas/BTJEditInsert-2523",
            "BTJEditList-2707": "#/components/schemas/BTJEditList-2707",
            "BTJEditMove-3245": "#/components/schemas/BTJEditMove-3245"
          }
        }
      },
      "BTJEditChange-2636": {
        "required": [
          "value"
        ],
        "type": "object",
        "allOf": [
          {
            "$ref": "#/components/schemas/BTJEdit-3734"
          },
          {
            "type": "object",
            "properties": {
              "value": {
                "type": "object",
                "properties": {
                  "btType": {
                    "type": "string"
                  }
                }
              },
              "path": {
                "$ref": "#/components/schemas/BTJPath-3073"
              },
              "btType": {
                "type": "string"
              }
            }
          }
        ]
      },
      "BTJEditDelete-1992": {
        "type": "object",
        "allOf": [
          {
            "$ref": "#/components/schemas/BTJEdit-3734"
          },
          {
            "type": "object",
            "properties": {
              "path": {
                "$ref": "#/components/schemas/BTJPath-3073"
              },
              "btType": {
                "type": "string"
              }
            }
          }
        ]
      },
      "BTJEditInsert-2523": {
        "type": "object",
        "allOf": [
          {
            "$ref": "#/components/schemas/BTJEdit-3734"
          },
          {
            "type": "object",
            "properties": {
              "path": {
                "$ref": "#/components/schemas/BTJPath-3073"
              },
              "value": {
                "type": "object",
                "properties": {
                  "btType": {
                    "type": "string"
                  }
                }
              },
              "btType": {
                "type": "string"
              }
            }
          }
        ]
      },
      "BTJEditList-2707": {
        "type": "object",
        "allOf": [
          {
            "$ref": "#/components/schemas/BTJEdit-3734"
          },
          {
            "type": "object",
            "properties": {
              "edits": {
                "type": "array",
                "items": {
                  "$ref": "#/components/schemas/BTJEdit-3734"
                }
              },
              "btType": {
                "type": "string"
              }
            }
          }
        ]
      },
      "BTJEditMove-3245": {
        "type": "object",
        "allOf": [
          {
            "$ref": "#/components/schemas/BTJEdit-3734"
          },
          {
            "type": "object",
            "properties": {
              "destinationPath": {
                "$ref": "#/components/schemas/BTJPath-3073"
              },
              "sourcePath": {
                "$ref": "#/components/schemas/BTJPath-3073"
              },
              "btType": {
                "type": "string"
              }
            }
          }
        ]
      },
      "BTJPath-3073": {
        "required": [
          "startNode"
        ],
        "type": "object",
        "properties": {
          "startNode": {
            "type": "string"
          },
          "path": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/BTJPathElement-2297"
            }
          },
          "btType": {
            "type": "string"
          }
        }
      },
      "BTJPathElement-2297": {
        "type": "object",
        "properties": {
          "btType": {
            "type": "string"
          }
        },
        "discriminator": {
          "propertyName": "btType",
          "mapping": {
            "BTJPathIndex-1871": "#/components/schemas/BTJPathIndex-1871",
            "BTJPathKey-3221": "#/components/schemas/BTJPathKey-3221"
          }
        }
      },
      "BTJPathIndex-1871": {
        "type": "object",
        "allOf": [
          {
            "$ref": "#/components/schemas/BTJPathElement-2297"
          },
          {
            "type": "object",
            "properties": {
              "index": {
                "type": "integer",
                "format": "int32"
              },
              "btType": {
                "type": "string"
              }
            }
          }
        ]
      },
      "BTJPathKey-3221": {
        "type": "object",
        "allOf": [
          {
            "$ref": "#/components/schemas/BTJPathElement-2297"
          },
          {
            "type": "object",
            "properties": {
              "key": {
                "type": "string"
              },
              "btType": {
                "type": "string"
              }
            }
          }
        ]
      },
      "BTAppElementChangeParams": {
        "type": "object",
        "properties": {
          "delta": {
            "type": "string"
          },
          "subelementId": {
            "type": "string"
          },
          "baseContent": {
            "type": "string"
          }
        }
      },
      "BTAppElementParams": {
        "type": "object",
        "properties": {
          "description": {
            "type": "string"
          },
          "subelements": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/BTAppElementChangeParams"
            }
          },
          "formatId": {
            "type": "string"
          },
          "jsonTree": {
            "$ref": "#/components/schemas/JsonNode"
          },
          "name": {
            "type": "string"
          },
          "location": {
            "$ref": "#/components/schemas/BTElementLocationParams"
          }
        }
      },
      "BTElementLocationParams": {
        "type": "object",
        "properties": {
          "position": {
            "type": "integer",
            "format": "int32"
          },
          "elementId": {
            "type": "string"
          },
          "groupId": {
            "type": "string"
          }
        }
      },
      "JsonNode": {
        "type": "object"
      },
      "BTAppElementReferenceInfo": {
        "type": "object",
        "properties": {
          "referenceId": {
            "type": "string"
          },
          "parentChangeId": {
            "type": "string"
          },
          "changeId": {
            "type": "string"
          },
          "transactionId": {
            "type": "string"
          },
          "errorDescription": {
            "type": "string"
          },
          "errorCode": {
            "type": "integer",
            "format": "int32"
          },
          "errorValue": {
            "type": "string",
            "writeOnly": true,
            "enum": [
              "OK",
              "TRANSACTION_CONFLICT",
              "NOT_FOUND",
              "INCONSISTENT_CHANGES"
            ]
          }
        }
      },
      "BTAppElementReferenceParams": {
        "type": "object",
        "properties": {
          "updateSketchInfo": {
            "type": "boolean"
          },
          "revision": {
            "type": "string"
          },
          "partNumber": {
            "type": "string"
          },
          "parentChangeId": {
            "type": "string"
          },
          "transactionId": {
            "type": "string"
          },
          "idTag": {
            "type": "string"
          },
          "targetDocumentId": {
            "type": "string"
          },
          "targetElementId": {
            "type": "string"
          },
          "targetConfiguration": {
            "type": "string"
          },
          "sketchIds": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "parentViewId": {
            "type": "string"
          },
          "targetVersionId": {
            "type": "string"
          },
          "pureSketch": {
            "type": "boolean"
          },
          "isSketchOnly": {
            "type": "boolean"
          },
          "referenceType": {
            "type": "integer",
            "format": "int32"
          },
          "isLocked": {
            "type": "boolean"
          },
          "returnError": {
            "type": "boolean"
          },
          "hasDocumentMicroversions": {
            "type": "boolean"
          },
          "targetMicroversionId": {
            "type": "string"
          },
          "idTagMicroversionId": {
            "type": "string"
          },
          "trackNewVersions": {
            "type": "boolean"
          }
        }
      },
      "BTAppElementHistoryEntryInfo": {
        "type": "object",
        "properties": {
          "description": {
            "type": "string"
          },
          "createdAt": {
            "type": "string",
            "format": "date-time"
          },
          "changeId": {
            "type": "string"
          }
        }
      },
      "BTAppElementHistoryInfo": {
        "type": "object",
        "properties": {
          "changes": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/BTAppElementHistoryEntryInfo"
            }
          },
          "errorDescription": {
            "type": "string"
          },
          "errorCode": {
            "type": "integer",
            "format": "int32"
          },
          "errorValue": {
            "type": "string",
            "writeOnly": true,
            "enum": [
              "OK",
              "TRANSACTION_CONFLICT",
              "NOT_FOUND",
              "INCONSISTENT_CHANGES"
            ]
          }
        }
      },
      "BTAppElementIdsInfo": {
        "type": "object",
        "properties": {
          "subelementIds": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "changeId": {
            "type": "string"
          },
          "errorDescription": {
            "type": "string"
          },
          "errorCode": {
            "type": "integer",
            "format": "int32"
          },
          "errorValue": {
            "type": "string",
            "writeOnly": true,
            "enum": [
              "OK",
              "TRANSACTION_CONFLICT",
              "NOT_FOUND",
              "INCONSISTENT_CHANGES"
            ]
          }
        }
      },
      "BTAppElementTransactionsInfo": {
        "type": "object",
        "properties": {
          "elementTransactions": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/BTElementTransaction"
            }
          },
          "errorDescription": {
            "type": "string"
          },
          "errorCode": {
            "type": "integer",
            "format": "int32"
          },
          "errorValue": {
            "type": "string",
            "writeOnly": true,
            "enum": [
              "OK",
              "TRANSACTION_CONFLICT",
              "NOT_FOUND",
              "INCONSISTENT_CHANGES"
            ]
          }
        }
      },
      "BTElementTransaction": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string"
          },
          "documentId": {
            "type": "string"
          },
          "elementId": {
            "type": "string"
          },
          "workspaceId": {
            "type": "string"
          },
          "description": {
            "type": "string"
          },
          "new": {
            "type": "boolean"
          },
          "microbranchId": {
            "type": "string"
          }
        }
      },
      "BTGetJsonResponse-2137": {
        "type": "object",
        "properties": {
          "tree": {
            "type": "object",
            "properties": {
              "btType": {
                "type": "string"
              }
            },
            "additionalProperties": {
              "type": "object",
              "properties": {
                "btType": {
                  "type": "string"
                }
              }
            }
          },
          "changeId": {
            "type": "string"
          }
        }
      },
      "BTGetJsonPathsResponse-1544": {
        "type": "object",
        "properties": {
          "results": {
            "type": "array",
            "items": {
              "type": "array",
              "items": {
                "$ref": "#/components/schemas/BTJsonMatch-2290"
              }
            }
          },
          "changeId": {
            "type": "string"
          }
        }
      },
      "BTJsonMatch-2290": {
        "type": "object",
        "properties": {
          "definiteJsonPath": {
            "type": "string"
          },
          "node": {
            "type": "object",
            "properties": {
              "btType": {
                "type": "string"
              }
            }
          }
        }
      },
      "BTGetJsonPaths-1697": {
        "type": "object",
        "properties": {
          "paths": {
            "type": "array",
            "items": {
              "type": "string"
            }
          }
        }
      },
      "BTAppElementContentDeltaInfo": {
        "type": "object",
        "properties": {
          "delta": {
            "type": "string"
          }
        }
      },
      "BTAppElementContentEntryInfo": {
        "type": "object",
        "properties": {
          "deltas": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/BTAppElementContentDeltaInfo"
            }
          },
          "subelementId": {
            "type": "string"
          },
          "baseContent": {
            "type": "string"
          }
        }
      },
      "BTAppElementContentInfo": {
        "type": "object",
        "properties": {
          "data": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/BTAppElementContentEntryInfo"
            }
          },
          "changeId": {
            "type": "string"
          },
          "errorDescription": {
            "type": "string"
          },
          "errorCode": {
            "type": "integer",
            "format": "int32"
          },
          "errorValue": {
            "type": "string",
            "writeOnly": true,
            "enum": [
              "OK",
              "TRANSACTION_CONFLICT",
              "NOT_FOUND",
              "INCONSISTENT_CHANGES"
            ]
          }
        }
      },
      "BTAppElementReferenceResolveInfo": {
        "type": "object",
        "properties": {
          "targetElementMicroversionId": {
            "type": "string"
          },
          "resolvedElementMicroversionId": {
            "type": "string"
          },
          "revision": {
            "type": "string"
          },
          "partNumber": {
            "type": "string"
          },
          "changeId": {
            "type": "string"
          },
          "idTag": {
            "type": "string"
          },
          "targetDocumentId": {
            "type": "string"
          },
          "targetElementId": {
            "type": "string"
          },
          "targetConfiguration": {
            "type": "string"
          },
          "targetVersionId": {
            "type": "string"
          },
          "sketchIds": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "resolvedDocumentMicroversionId": {
            "type": "string"
          },
          "isSurface": {
            "type": "boolean"
          },
          "isSketchOnly": {
            "type": "boolean"
          },
          "isFlattenedPart": {
            "type": "boolean"
          },
          "referenceType": {
            "type": "integer",
            "format": "int32"
          },
          "isLocked": {
            "type": "boolean"
          },
          "idTagIsValid": {
            "type": "boolean"
          },
          "referenceId": {
            "type": "string"
          },
          "targetDocumentMicroversionId": {
            "type": "string"
          },
          "isConfigurable": {
            "type": "boolean"
          },
          "trackNewVersions": {
            "type": "boolean"
          },
          "errorDescription": {
            "type": "string"
          },
          "errorCode": {
            "type": "integer",
            "format": "int32"
          },
          "errorValue": {
            "type": "string",
            "writeOnly": true,
            "enum": [
              "OK",
              "TRANSACTION_CONFLICT",
              "NOT_FOUND",
              "INCONSISTENT_CHANGES"
            ]
          }
        }
      },
      "BTAppElementReferencesResolveInfo": {
        "type": "object",
        "properties": {
          "resolvedReferences": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/BTAppElementReferenceResolveInfo"
            }
          },
          "unresolvedReferenceIds": {
            "type": "array",
            "items": {
              "type": "string"
            }
          }
        }
      },
      "BTAppElementStartTransactionParams": {
        "type": "object",
        "properties": {
          "description": {
            "type": "string"
          },
          "parentChangeId": {
            "type": "string"
          },
          "returnError": {
            "type": "boolean"
          }
        }
      },
      "BTAppElementUpdateParams": {
        "type": "object",
        "properties": {
          "description": {
            "type": "string"
          },
          "parentChangeId": {
            "type": "string"
          },
          "transactionId": {
            "type": "string"
          },
          "changes": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/BTAppElementChangeParams"
            }
          },
          "jsonTreeEdit": {
            "$ref": "#/components/schemas/BTJEdit-3734"
          },
          "propertyUpdates": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/BTMetadataPropertyUpdateParams"
            }
          },
          "returnError": {
            "type": "boolean"
          }
        }
      },
      "BTMetadataPropertyUpdateParams": {
        "type": "object",
        "properties": {
          "propertyId": {
            "type": "string"
          },
          "value": {
            "type": "object"
          }
        }
      },
      "BTAssemblySimulation-2246": {
        "type": "object",
        "allOf": [
          {
            "$ref": "#/components/schemas/BTMAssemblyFeature-887"
          },
          {
            "type": "object",
            "properties": {
              "type": {
                "type": "string",
                "enum": [
                  "LINEAR_STATIC",
                  "MODAL",
                  "UNKNOWN"
                ]
              },
              "btType": {
                "type": "string"
              }
            }
          }
        ]
      },
      "BTBSMatrix-386": {
        "type": "object",
        "properties": {
          "isNormalized": {
            "type": "boolean"
          },
          "translation": {
            "$ref": "#/components/schemas/BTVector3d-389"
          },
          "m00": {
            "type": "number",
            "format": "double"
          },
          "m01": {
            "type": "number",
            "format": "double"
          },
          "m02": {
            "type": "number",
            "format": "double"
          },
          "m03": {
            "type": "number",
            "format": "double"
          },
          "m10": {
            "type": "number",
            "format": "double"
          },
          "m11": {
            "type": "number",
            "format": "double"
          },
          "m12": {
            "type": "number",
            "format": "double"
          },
          "m13": {
            "type": "number",
            "format": "double"
          },
          "m23": {
            "type": "number",
            "format": "double"
          },
          "m20": {
            "type": "number",
            "format": "double"
          },
          "m21": {
            "type": "number",
            "format": "double"
          },
          "m22": {
            "type": "number",
            "format": "double"
          },
          "btType": {
            "type": "string"
          }
        }
      },
      "BTCurveGeometry-114": {
        "type": "object",
        "properties": {
          "btType": {
            "type": "string"
          }
        },
        "discriminator": {
          "propertyName": "btType",
          "mapping": {
            "BTCurveGeometryCircle-115": "#/components/schemas/BTCurveGeometryCircle-115",
            "BTCurveGeometryConic-2284": "#/components/schemas/BTCurveGeometryConic-2284",
            "BTCurveGeometryInterpolatedSpline-116": "#/components/schemas/BTCurveGeometryInterpolatedSpline-116",
            "BTCurveGeometryLine-117": "#/components/schemas/BTCurveGeometryLine-117",
            "BTCurveGeometrySpline-118": "#/components/schemas/BTCurveGeometrySpline-118"
          }
        }
      },
      "BTCurveGeometryCircle-115": {
        "type": "object",
        "discriminator": {
          "propertyName": "btType",
          "mapping": {
            "BTCurveGeometryEllipse-1189": "#/components/schemas/BTCurveGeometryEllipse-1189"
          }
        },
        "allOf": [
          {
            "$ref": "#/components/schemas/BTCurveGeometry-114"
          },
          {
            "type": "object",
            "properties": {
              "radius": {
                "type": "number",
                "format": "double"
              },
              "xcenter": {
                "type": "number",
                "format": "double"
              },
              "ycenter": {
                "type": "number",
                "format": "double"
              },
              "xdir": {
                "type": "number",
                "format": "double"
              },
              "ydir": {
                "type": "number",
                "format": "double"
              },
              "clockwise": {
                "type": "boolean"
              },
              "btType": {
                "type": "string"
              }
            }
          }
        ]
      },
      "BTCurveGeometryConic-2284": {
        "type": "object",
        "allOf": [
          {
            "$ref": "#/components/schemas/BTCurveGeometry-114"
          },
          {
            "type": "object",
            "properties": {
              "rho": {
                "type": "number",
                "format": "double"
              },
              "points": {
                "type": "array",
                "items": {
                  "type": "number",
                  "format": "double"
                }
              },
              "btType": {
                "type": "string"
              }
            }
          }
        ]
      },
      "BTCurveGeometryEllipse-1189": {
        "type": "object",
        "allOf": [
          {
            "$ref": "#/components/schemas/BTCurveGeometryCircle-115"
          },
          {
            "type": "object",
            "properties": {
              "minorRadius": {
                "type": "number",
                "format": "double"
              },
              "btType": {
                "type": "string"
              }
            }
          }
        ]
      },
      "BTCurveGeometryInterpolatedSpline-116": {
        "type": "object",
        "allOf": [
          {
            "$ref": "#/components/schemas/BTCurveGeometry-114"
          },
          {
            "type": "object",
            "properties": {
              "startHandleY": {
                "type": "number",
                "format": "double"
              },
              "endHandleX": {
                "type": "number",
                "format": "double"
              },
              "endHandleY": {
                "type": "number",
                "format": "double"
              },
              "isPeriodic": {
                "type": "boolean"
              },
              "interpolationPoints": {
                "type": "array",
                "items": {
                  "type": "number",
                  "format": "double"
                }
              },
              "startDerivativeX": {
                "type": "number",
                "format": "double"
              },
              "startDerivativeY": {
                "type": "number",
                "format": "double"
              },
              "endDerivativeX": {
                "type": "number",
                "format": "double"
              },
              "endDerivativeY": {
                "type": "number",
                "format": "double"
              },
              "startHandleX": {
                "type": "number",
                "format": "double"
              },
              "btType": {
                "type": "string"
              }
            }
          }
        ]
      },
      "BTCurveGeometryLine-117": {
        "type": "object",
        "allOf": [
          {
            "$ref": "#/components/schemas/BTCurveGeometry-114"
          },
          {
            "type": "object",
            "properties": {
              "pntX": {
                "type": "number",
                "format": "double"
              },
              "pntY": {
                "type": "number",
                "format": "double"
              },
              "dirX": {
                "type": "number",
                "format": "double"
              },
              "dirY": {
                "type": "number",
                "format": "double"
              },
              "btType": {
                "type": "string"
              }
            }
          }
        ]
      },
      "BTCurveGeometrySpline-118": {
        "type": "object",
        "allOf": [
          {
            "$ref": "#/components/schemas/BTCurveGeometry-114"
          },
          {
            "type": "object",
            "properties": {
              "degree": {
                "type": "integer",
                "format": "int32"
              },
              "isRational": {
                "type": "boolean"
              },
              "controlPointCount": {
                "type": "integer",
                "format": "int32"
              },
              "controlPoints": {
                "type": "array",
                "items": {
                  "type": "number",
                  "format": "double"
                }
              },
              "knots": {
                "type": "array",
                "items": {
                  "type": "number",
                  "format": "double"
                }
              },
              "isPeriodic": {
                "type": "boolean"
              },
              "btType": {
                "type": "string"
              }
            }
          }
        ]
      },
      "BTDocumentWithVersionAndElementId": {
        "type": "object",
        "properties": {
          "documentId": {
            "type": "string"
          },
          "documentVersionId": {
            "type": "string"
          },
          "elementId": {
            "type": "string"
          },
          "partNumber": {
            "type": "string"
          },
          "revision": {
            "type": "string"
          },
          "uniqueVersionId": {
            "type": "string"
          },
          "validRevisionReference": {
            "type": "boolean"
          }
        }
      },
      "BTDocumentWithVersionId": {
        "type": "object",
        "properties": {
          "documentId": {
            "type": "string"
          },
          "documentVersionId": {
            "type": "string"
          }
        }
      },
      "BTElementReference-725": {
        "type": "object",
        "properties": {
          "externalDocumentWithVersion": {
            "$ref": "#/components/schemas/BTDocumentWithVersionId"
          },
          "microversionIdAndConfiguration": {
            "$ref": "#/components/schemas/BTMicroversionIdAndConfiguration-2338"
          },
          "externalDocumentWithVersionAndElementId": {
            "$ref": "#/components/schemas/BTDocumentWithVersionAndElementId"
          },
          "externalReference": {
            "type": "boolean"
          },
          "configured": {
            "type": "boolean"
          },
          "elementId": {
            "type": "string"
          },
          "fullElementId": {
            "$ref": "#/components/schemas/BTFullElementId-756"
          },
          "nodeId": {
            "type": "string"
          },
          "btType": {
            "type": "string"
          }
        },
        "discriminator": {
          "propertyName": "btType",
          "mapping": {
            "BTExternalReference-1936": "#/components/schemas/BTExternalReference-1936"
          }
        }
      },
      "BTExplosion-2754": {
        "type": "object",
        "allOf": [
          {
            "$ref": "#/components/schemas/BTMAssemblyFeature-887"
          },
          {
            "type": "object",
            "properties": {
              "explodeSteps": {
                "type": "array",
                "items": {
                  "$ref": "#/components/schemas/BTExplosionStepFeature-3008"
                }
              },
              "startingPositionId": {
                "$ref": "#/components/schemas/BTMicroversionIdAndConfiguration-2338"
              },
              "btType": {
                "type": "string"
              }
            }
          }
        ]
      },
      "BTExplosionStepFeature-3008": {
        "type": "object",
        "allOf": [
          {
            "$ref": "#/components/schemas/BTMAssemblyFeature-887"
          },
          {
            "type": "object",
            "properties": {
              "btType": {
                "type": "string"
              }
            }
          }
        ]
      },
      "BTExternalReference-1936": {
        "type": "object",
        "allOf": [
          {
            "$ref": "#/components/schemas/BTElementReference-725"
          },
          {
            "type": "object",
            "properties": {
              "documentVersionId": {
                "type": "string"
              },
              "btType": {
                "type": "string"
              }
            }
          }
        ]
      },
      "BTFSValue-1888": {
        "required": [
          "btType"
        ],
        "type": "object",
        "properties": {
          "typeTag": {
            "type": "string"
          },
          "btType": {
            "type": "string"
          }
        },
        "discriminator": {
          "propertyName": "btType",
          "mapping": {
            "BTFSValueArray-1499": "#/components/schemas/BTFSValueArray-1499",
            "BTFSValueBoolean-1195": "#/components/schemas/BTFSValueBoolean-1195",
            "BTFSValueMap-2062": "#/components/schemas/BTFSValueMap-2062",
            "BTFSValueNumber-772": "#/components/schemas/BTFSValueNumber-772",
            "BTFSValueOther-1124": "#/components/schemas/BTFSValueOther-1124",
            "BTFSValueString-1422": "#/components/schemas/BTFSValueString-1422",
            "BTFSValueTooBig-1247": "#/components/schemas/BTFSValueTooBig-1247",
            "BTFSValueUndefined-2003": "#/components/schemas/BTFSValueUndefined-2003",
            "BTFSValueWithUnits-1817": "#/components/schemas/BTFSValueWithUnits-1817"
          }
        }
      },
      "BTFSValueArray-1499": {
        "type": "object",
        "allOf": [
          {
            "$ref": "#/components/schemas/BTFSValue-1888"
          },
          {
            "type": "object",
            "properties": {
              "value": {
                "type": "array",
                "items": {
                  "$ref": "#/components/schemas/BTFSValue-1888"
                }
              },
              "btType": {
                "type": "string"
              }
            }
          }
        ]
      },
      "BTFSValueBoolean-1195": {
        "type": "object",
        "allOf": [
          {
            "$ref": "#/components/schemas/BTFSValue-1888"
          },
          {
            "type": "object",
            "properties": {
              "value": {
                "type": "boolean"
              },
              "btType": {
                "type": "string"
              }
            }
          }
        ]
      },
      "BTFSValueMap-2062": {
        "type": "object",
        "properties": {
          "value": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/BTFSValueMapEntry-2077"
            }
          },
          "typeTag": {
            "type": "string"
          }
        }
      },
      "BTFSValueMapEntry-2077": {
        "type": "object",
        "properties": {
          "key": {
            "$ref": "#/components/schemas/BTFSValue-1888"
          },
          "value": {
            "$ref": "#/components/schemas/BTFSValue-1888"
          }
        }
      },
      "BTFSValueNumber-772": {
        "type": "object",
        "allOf": [
          {
            "$ref": "#/components/schemas/BTFSValue-1888"
          },
          {
            "type": "object",
            "properties": {
              "value": {
                "type": "number",
                "format": "double"
              },
              "btType": {
                "type": "string"
              }
            }
          }
        ]
      },
      "BTFSValueOther-1124": {
        "type": "object",
        "allOf": [
          {
            "$ref": "#/components/schemas/BTFSValue-1888"
          },
          {
            "type": "object",
            "properties": {
              "type": {
                "type": "string",
                "enum": [
                  "UNDEFINED",
                  "BOOLEAN",
                  "NUMBER",
                  "STRING",
                  "ARRAY",
                  "MAP",
                  "BOX",
                  "BUILTIN",
                  "FUNCTION",
                  "UNKNOWN"
                ]
              },
              "btType": {
                "type": "string"
              }
            }
          }
        ]
      },
      "BTFSValueString-1422": {
        "type": "object",
        "allOf": [
          {
            "$ref": "#/components/schemas/BTFSValue-1888"
          },
          {
            "type": "object",
            "properties": {
              "value": {
                "type": "string"
              },
              "btType": {
                "type": "string"
              }
            }
          }
        ]
      },
      "BTFSValueTooBig-1247": {
        "type": "object",
        "allOf": [
          {
            "$ref": "#/components/schemas/BTFSValue-1888"
          },
          {
            "type": "object",
            "properties": {
              "btType": {
                "type": "string"
              }
            }
          }
        ]
      },
      "BTFSValueUndefined-2003": {
        "type": "object",
        "allOf": [
          {
            "$ref": "#/components/schemas/BTFSValue-1888"
          },
          {
            "type": "object",
            "properties": {
              "btType": {
                "type": "string"
              }
            }
          }
        ]
      },
      "BTFSValueWithUnits-1817": {
        "type": "object",
        "allOf": [
          {
            "$ref": "#/components/schemas/BTFSValue-1888"
          },
          {
            "type": "object",
            "properties": {
              "unitToPower": {
                "type": "object",
                "additionalProperties": {
                  "type": "integer",
                  "format": "int32"
                }
              },
              "value": {
                "type": "number",
                "format": "double"
              },
              "btType": {
                "type": "string"
              }
            }
          }
        ]
      },
      "BTFeatureDefinitionResponse-1617": {
        "type": "object",
        "properties": {
          "featureState": {
            "$ref": "#/components/schemas/BTFeatureState-1688"
          },
          "feature": {
            "$ref": "#/components/schemas/BTMFeature-134"
          },
          "serializationVersion": {
            "type": "string"
          },
          "rejectMicroversionSkew": {
            "type": "boolean"
          },
          "microversionSkew": {
            "type": "boolean"
          },
          "libraryVersion": {
            "type": "integer",
            "format": "int32"
          },
          "sourceMicroversion": {
            "type": "string"
          }
        }
      },
      "BTFeatureState-1688": {
        "type": "object",
        "properties": {
          "featureStatus": {
            "type": "string",
            "enum": [
              "OK",
              "INFO",
              "WARNING",
              "ERROR",
              "UNKNOWN"
            ]
          }
        }
      },
      "BTForeignDataResponse-1070": {
        "type": "object",
        "properties": {
          "dataId": {
            "type": "string"
          },
          "useLocalStorage": {
            "type": "boolean"
          },
          "cacheChunkList": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "region": {
            "type": "string"
          },
          "format": {
            "type": "string",
            "enum": [
              "X_T",
              "XMM",
              "STL",
              "ONSHAPE",
              "ZIP",
              "X_T_XMM_ZIP",
              "OBJ_MTL_ZIP",
              "UNKNOWN"
            ]
          },
          "size": {
            "type": "integer",
            "format": "int32"
          },
          "bucketPath": {
            "type": "string"
          },
          "bucketName": {
            "type": "string"
          },
          "name": {
            "type": "string"
          },
          "btType": {
            "type": "string"
          }
        }
      },
      "BTFullElementId-756": {
        "type": "object",
        "properties": {
          "configured": {
            "type": "boolean"
          },
          "elementId": {
            "type": "string"
          },
          "target": {
            "$ref": "#/components/schemas/BTMicroversionIdAndConfiguration-2338"
          },
          "microversionIdAndConfiguration": {
            "$ref": "#/components/schemas/BTMicroversionIdAndConfiguration-2338"
          },
          "microversionId": {
            "$ref": "#/components/schemas/BTMicroversionId-366"
          },
          "btType": {
            "type": "string"
          }
        },
        "discriminator": {
          "propertyName": "btType",
          "mapping": {
            "BTFullElementIdWithDocument-1729": "#/components/schemas/BTFullElementIdWithDocument-1729"
          }
        }
      },
      "BTFullElementIdAndPartId-643": {
        "type": "object",
        "allOf": [
          {
            "$ref": "#/components/schemas/BTFullElementIdWithDocument-1729"
          },
          {
            "type": "object",
            "properties": {
              "partId": {
                "type": "string"
              },
              "btType": {
                "type": "string"
              }
            }
          }
        ]
      },
      "BTFullElementIdWithDocument-1729": {
        "type": "object",
        "properties": {
          "documentId": {
            "type": "string"
          },
          "configured": {
            "type": "boolean"
          },
          "elementId": {
            "type": "string"
          },
          "target": {
            "$ref": "#/components/schemas/BTMicroversionIdAndConfiguration-2338"
          },
          "microversionIdAndConfiguration": {
            "$ref": "#/components/schemas/BTMicroversionIdAndConfiguration-2338"
          },
          "microversionId": {
            "$ref": "#/components/schemas/BTMicroversionId-366"
          },
          "btType": {
            "type": "string"
          }
        },
        "discriminator": {
          "propertyName": "btType",
          "mapping": {
            "BTFullElementIdAndPartId-643": "#/components/schemas/BTFullElementIdAndPartId-643"
          }
        }
      },
      "BTGraphicsAppearance-1152": {
        "type": "object",
        "properties": {
          "rgbaColor": {
            "type": "array",
            "items": {
              "type": "string",
              "format": "byte"
            }
          },
          "usableAppearance": {
            "type": "boolean"
          },
          "nonTrivial": {
            "type": "boolean"
          },
          "reset": {
            "type": "boolean"
          },
          "color": {
            "type": "array",
            "items": {
              "type": "string",
              "format": "byte"
            }
          },
          "opacity": {
            "type": "integer",
            "format": "int32"
          },
          "btType": {
            "type": "string"
          }
        }
      },
      "BTMArrayParameterItem-1843": {
        "type": "object",
        "properties": {
          "importMicroversion": {
            "type": "string",
            "writeOnly": true
          },
          "nodeId": {
            "type": "string"
          },
          "btType": {
            "type": "string"
          }
        }
      },
      "BTMAssemblyFeature-887": {
        "type": "object",
        "discriminator": {
          "propertyName": "btType",
          "mapping": {
            "BTAssemblySimulation-2246": "#/components/schemas/BTAssemblySimulation-2246",
            "BTExplosion-2754": "#/components/schemas/BTExplosion-2754",
            "BTExplosionStepFeature-3008": "#/components/schemas/BTExplosionStepFeature-3008",
            "BTMAssemblyFeature1-2218": "#/components/schemas/BTMAssemblyFeature1-2218",
            "BTMAssemblyFeature2-1022": "#/components/schemas/BTMAssemblyFeature2-1022",
            "BTMAssemblyFeatureFolder-2543": "#/components/schemas/BTMAssemblyFeatureFolder-2543",
            "BTMAssemblyPatternFeature-2241": "#/components/schemas/BTMAssemblyPatternFeature-2241",
            "BTMAssemblyReplicateFeature-1351": "#/components/schemas/BTMAssemblyReplicateFeature-1351",
            "BTMGeometryMate-1260": "#/components/schemas/BTMGeometryMate-1260",
            "BTMLoad-3538": "#/components/schemas/BTMLoad-3538",
            "BTMMate-64": "#/components/schemas/BTMMate-64",
            "BTMMateConnector-66": "#/components/schemas/BTMMateConnector-66",
            "BTMMateGroup-65": "#/components/schemas/BTMMateGroup-65",
            "BTMMateRelation-1412": "#/components/schemas/BTMMateRelation-1412",
            "BTMNonGeometricItem-1864": "#/components/schemas/BTMNonGeometricItem-1864"
          }
        },
        "allOf": [
          {
            "$ref": "#/components/schemas/BTMFeature-134"
          },
          {
            "type": "object",
            "properties": {
              "occurrenceQueriesFromAllConfigurations": {
                "type": "array",
                "items": {
                  "$ref": "#/components/schemas/BTMIndividualQueryWithOccurrenceBase-904"
                }
              },
              "featureListFieldIndex": {
                "type": "integer",
                "format": "int32"
              },
              "featureFolder": {
                "type": "boolean"
              },
              "auxiliaryTreeFeature": {
                "type": "boolean"
              },
              "version": {
                "type": "integer",
                "format": "int32"
              },
              "btType": {
                "type": "string"
              }
            }
          }
        ]
      },
      "BTMAssemblyFeature1-2218": {
        "type": "object",
        "allOf": [
          {
            "$ref": "#/components/schemas/BTMAssemblyFeature-887"
          },
          {
            "type": "object",
            "properties": {
              "btType": {
                "type": "string"
              }
            }
          }
        ]
      },
      "BTMAssemblyFeature2-1022": {
        "type": "object",
        "allOf": [
          {
            "$ref": "#/components/schemas/BTMAssemblyFeature-887"
          },
          {
            "type": "object",
            "properties": {
              "btType": {
                "type": "string"
              }
            }
          }
        ]
      },
      "BTMAssemblyFeatureFolder-2543": {
        "type": "object",
        "allOf": [
          {
            "$ref": "#/components/schemas/BTMAssemblyFeature-887"
          },
          {
            "type": "object",
            "properties": {
              "folderEnd": {
                "type": "boolean"
              },
              "folderStart": {
                "type": "boolean"
              },
              "startNodeId": {
                "type": "string"
              },
              "startNodeIdRaw": {
                "$ref": "#/components/schemas/BTObjectId"
              },
              "btType": {
                "type": "string"
              }
            }
          }
        ]
      },
      "BTMAssemblyPatternFeature-2241": {
        "type": "object",
        "allOf": [
          {
            "$ref": "#/components/schemas/BTMAssemblyFeature-887"
          },
          {
            "type": "object",
            "properties": {
              "patternType": {
                "type": "string",
                "enum": [
                  "LINEAR",
                  "CIRCULAR",
                  "UNKNOWN"
                ]
              },
              "btType": {
                "type": "string"
              }
            }
          }
        ]
      },
      "BTMAssemblyReplicateFeature-1351": {
        "type": "object",
        "allOf": [
          {
            "$ref": "#/components/schemas/BTMAssemblyFeature-887"
          },
          {
            "type": "object",
            "properties": {
              "btType": {
                "type": "string"
              }
            }
          }
        ]
      },
      "BTMConfiguredValue-1341": {
        "type": "object",
        "properties": {
          "configurationValueString": {
            "type": "string"
          },
          "value": {
            "$ref": "#/components/schemas/BTMParameter-1"
          },
          "importMicroversion": {
            "type": "string",
            "writeOnly": true
          },
          "nodeId": {
            "type": "string"
          },
          "btType": {
            "type": "string"
          }
        },
        "discriminator": {
          "propertyName": "btType",
          "mapping": {
            "BTMConfiguredValueByBoolean-1501": "#/components/schemas/BTMConfiguredValueByBoolean-1501",
            "BTMConfiguredValueByEnum-1923": "#/components/schemas/BTMConfiguredValueByEnum-1923"
          }
        }
      },
      "BTMConfiguredValueByBoolean-1501": {
        "type": "object",
        "allOf": [
          {
            "$ref": "#/components/schemas/BTMConfiguredValue-1341"
          },
          {
            "type": "object",
            "properties": {
              "booleanValue": {
                "type": "boolean"
              },
              "btType": {
                "type": "string"
              }
            }
          }
        ]
      },
      "BTMConfiguredValueByEnum-1923": {
        "type": "object",
        "allOf": [
          {
            "$ref": "#/components/schemas/BTMConfiguredValue-1341"
          },
          {
            "type": "object",
            "properties": {
              "namespace": {
                "type": "string"
              },
              "enumName": {
                "type": "string"
              },
              "enumValue": {
                "type": "string"
              },
              "btType": {
                "type": "string"
              }
            }
          }
        ]
      },
      "BTMDatabaseParameter-2229": {
        "type": "object",
        "allOf": [
          {
            "$ref": "#/components/schemas/BTMParameter-1"
          },
          {
            "type": "object",
            "properties": {
              "databaseId": {
                "type": "string"
              },
              "btType": {
                "type": "string"
              }
            }
          }
        ]
      },
      "BTMFeature-134": {
        "type": "object",
        "properties": {
          "namespace": {
            "type": "string"
          },
          "nodeId": {
            "type": "string"
          },
          "importMicroversion": {
            "type": "string",
            "writeOnly": true
          },
          "name": {
            "type": "string"
          },
          "suppressed": {
            "type": "boolean"
          },
          "suppressionConfigured": {
            "type": "boolean"
          },
          "returnAfterSubfeatures": {
            "type": "boolean"
          },
          "subFeatures": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/BTMFeature-134"
            }
          },
          "featureType": {
            "type": "string"
          },
[...]
