{
  "openapi": "3.0.1",
  "info": {
    "title": "Onshape REST API",
    "description": "The Onshape REST API consumed by all clients.",
    "termsOfService": "http://swagger.io/terms/",
    "contact": {
      "email": "api-support@onshape.zendesk.com"
    },
    "license": {
      "name": "Apache 2.0",
      "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
    },
    "version": "1.111",
    "x-logo": {
      "backgroundColor": "#ffffff",
      "altText": "Onshape",
      "href": "https://www.onshape.com/",
      "url": "http://localhost.dev.onshape.com:8080/images/onshape_logo_medium.png"
    }
  },
  "servers": [
    {
      "url": "https://cad.onshape.com",
      "description": "Production"
    }
  ],
  "tags": [
    {
      "name": "Applications",
      "description": "Manage application settings."
    },
    {
      "name": "Accounts",
      "description": "Modify and access account information."
    },
    {
      "name": "App Elements",
      "description": "Save and manage application state."
    },
    {
      "name": "Assemblies",
      "description": "Access and manipulate assembly elements."
    },
    {
      "name": "Billing",
      "description": "Access billing plans for clients."
    },
    {
      "name": "BlobElements",
      "description": "Save and access Blob Elements."
    },
    {
      "name": "Companies",
      "description": "Access company information."
    },
    {
      "name": "Documents",
      "description": "Manage documents."
    },
    {
      "name": "Drawings",
      "description": "Access drawing translations."
    },
    {
      "name": "Elements",
      "description": "Access and manipulate Elements."
    },
    {
      "name": "FeatureStudios",
      "description": "Access and write to Feature Studio Elements."
    },
    {
      "name": "Folders",
      "description": "Access Folders."
    },
    {
      "name": "Metadata",
      "description": "Manipulate and access metadata."
    },
    {
      "name": "OpenAPI",
      "description": "Endpoints for getting the OpenAPI specification for the Onshape API."
    },
    {
      "name": "Parts",
      "description": "Get details about specific parts."
    },
    {
      "name": "PartStudios",
      "description": "Modify, change, and get PartStudios."
    },
    {
      "name": "ReleaseManagement",
      "description": "Manage Release Management workflows."
    },
    {
      "name": "Revisions",
      "description": "Access revisions."
    },
    {
      "name": "Teams",
      "description": "Access team details."
    },
    {
      "name": "Translations",
      "description": "Create and manage translations."
    },
    {
      "name": "Users",
      "description": "Get details about users."
    },
    {
      "name": "Versions",
      "description": "Example of API version management."
    },
    {
      "name": "Webhooks",
      "description": "Create and manage webhooks."
    },
    {
      "name": "Workflow",
      "description": "Access Release Management workflows."
    }
  ],
  "paths": {
    "/api/accounts/plans/{planId}/purchases": {
      "get": {
        "tags": [
          "Accounts"
        ],
        "summary": "Get Plan Purchases",
        "operationId": "getPlanPurchases",
        "deprecated": false,
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/accounts/purchases": {
      "get": {
        "tags": [
          "Accounts"
        ],
        "summary": "Get User's Appstore Purchases.",
        "operationId": "getPurchases",
        "deprecated": false,
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/accounts/purchases/{pid}/consume": {
      "post": {
        "tags": [
          "Accounts"
        ],
        "summary": "Mark Purchase Consumed For User",
        "operationId": "consumePurchase",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Purchase"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/accounts/{aid}/purchases/{pid}": {
      "delete": {
        "tags": [
          "Accounts"
        ],
        "summary": "Cancel Recurring Subscription",
        "operationId": "cancelPurchaseNew",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Purchase"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/appelements/d/{did}/w/{wid}": {
      "post": {
        "tags": [
          "App Elements"
        ],
        "summary": "Create Element.",
        "operationId": "createElement",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Write"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/appelements/d/{did}/w/{wid}/e/{eid}/transactions": {
      "post": {
        "tags": [
          "App Elements"
        ],
        "summary": "Start Transaction",
        "operationId": "startTransaction",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Write"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/appelements/d/{did}/w/{wid}/e/{eid}/transactions/{tid}": {
      "post": {
        "tags": [
          "App Elements"
        ],
        "summary": "Commit Transaction",
        "operationId": "commitTransaction",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Write"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/appelements/d/{did}/{wvm}/{wvmid}/e/{eid}/associativedata": {
      "get": {
        "operationId": "getAssociativeData",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      },
      "post": {
        "operationId": "postAssociativeData",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read",
              "OAuth2Write"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      },
      "delete": {
        "operationId": "deleteAssociativeData",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Write"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/appelements/d/{did}/{wvm}/{wvmid}/e/{eid}/content": {
      "get": {
        "tags": [
          "App Elements"
        ],
        "summary": "Get Content",
        "operationId": "getSubElementContent",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      },
      "post": {
        "tags": [
          "App Elements"
        ],
        "summary": "Update Element",
        "operationId": "updateAppElement",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read",
              "OAuth2Write"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/appelements/d/{did}/{wvm}/{wvmid}/e/{eid}/content/history": {
      "get": {
        "tags": [
          "App Elements"
        ],
        "summary": "Get History",
        "operationId": "getAppElementHistory",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/appelements/d/{did}/{wvm}/{wvmid}/e/{eid}/content/ids": {
      "get": {
        "tags": [
          "App Elements"
        ],
        "summary": "Get Sub-element IDs",
        "operationId": "getSubelementIds",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/appelements/d/{did}/{wvm}/{wvmid}/e/{eid}/content/subelements/{sid}": {
      "delete": {
        "tags": [
          "App Elements"
        ],
        "summary": "Delete a Sub-element",
        "operationId": "deleteAppElementContent",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Write"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/appelements/d/{did}/{wvm}/{wvmid}/e/{eid}/references": {
      "post": {
        "tags": [
          "App Elements"
        ],
        "summary": "Create Reference",
        "operationId": "createReference",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Write",
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/appelements/d/{did}/{wvm}/{wvmid}/e/{eid}/references/{rid}": {
      "get": {
        "tags": [
          "App Elements"
        ],
        "summary": "Resolve Reference",
        "operationId": "resolveReference",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      },
      "post": {
        "tags": [
          "App Elements"
        ],
        "summary": "Update Reference",
        "operationId": "updateReference",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Write",
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      },
      "delete": {
        "tags": [
          "App Elements"
        ],
        "summary": "Delete Reference",
        "operationId": "deleteReference",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Write"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/appelements/d/{did}/{wvm}/{wvmid}/e/{eid}/resolvereferences": {
      "get": {
        "tags": [
          "App Elements"
        ],
        "summary": "Resolve references.",
        "operationId": "resolveReferences",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/applications/clients/{cid}/settings/users/{uid}": {
      "get": {
        "tags": [
          "Applications"
        ],
        "summary": "Get User Application Settings",
        "operationId": "getUserAppSettings",
        "deprecated": false,
        "x-BTVisibility": "PRODUCTION"
      },
      "post": {
        "tags": [
          "Applications"
        ],
        "summary": "Update Application Settings",
        "operationId": "updateAppSettings",
        "deprecated": false,
        "x-BTVisibility": "PRODUCTION"
      },
      "delete": {
        "tags": [
          "Applications"
        ],
        "summary": "Delete Application Settings",
        "operationId": "deleteAppSettings",
        "deprecated": false,
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/assemblies/d/{did}/e/{eid}/namedViews": {
      "get": {
        "tags": [
          "Assemblies"
        ],
        "operationId": "getNamedViews",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/assemblies/d/{did}/w/{wid}": {
      "post": {
        "tags": [
          "Assemblies"
        ],
        "summary": "Create Assembly",
        "operationId": "createAssembly",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Write"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/assemblies/d/{did}/w/{wid}/e/{eid}/bomelement": {
      "post": {
        "tags": [
          "Assemblies"
        ],
        "summary": "Get or Create Bill of Materials Element",
        "operationId": "getOrCreateBillOfMaterialsElement",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/assemblies/d/{did}/w/{wid}/e/{eid}/features/featureid/{fid}": {
      "post": {
        "tags": [
          "Assemblies"
        ],
        "operationId": "updateFeature",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Write"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      },
      "delete": {
        "tags": [
          "Assemblies"
        ],
        "summary": "Delete Feature",
        "operationId": "deleteFeature",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Write"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/assemblies/d/{did}/w/{wid}/e/{eid}/instance/nodeid/{nid}": {
      "delete": {
        "tags": [
          "Assemblies"
        ],
        "summary": "Delete assembly instance.",
        "operationId": "deleteInstance",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Write"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/assemblies/d/{did}/w/{wid}/e/{eid}/instances": {
      "post": {
        "tags": [
          "Assemblies"
        ],
        "summary": "Create assembly instance",
        "operationId": "createInstance",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read",
              "OAuth2Write"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/assemblies/d/{did}/w/{wid}/e/{eid}/occurrencetransforms": {
      "post": {
        "tags": [
          "Assemblies"
        ],
        "summary": "Transform assembly occurrences.",
        "operationId": "transformOccurrences",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read",
              "OAuth2Write"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/assemblies/d/{did}/w/{wid}/e/{eid}/transformedinstances": {
      "post": {
        "tags": [
          "Assemblies"
        ],
        "summary": "Create and transform assembly instances",
        "operationId": "insertTransformedInstances",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read",
              "OAuth2Write"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/assemblies/d/{did}/w/{wid}/e/{eid}/translationformats": {
      "get": {
        "tags": [
          "Assemblies"
        ],
        "summary": "Get Translation Formats",
        "operationId": "getTranslatorFormats",
        "deprecated": false,
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/assemblies/d/{did}/{wvm}/{wvmid}/e/{eid}": {
      "get": {
        "tags": [
          "Assemblies"
        ],
        "summary": "Assembly Definition.",
        "operationId": "getAssemblyDefinition",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/assemblies/d/{did}/{wvm}/{wvmid}/e/{eid}/bom": {
      "get": {
        "tags": [
          "Assemblies"
        ],
        "summary": "Get Bill of Materials",
        "operationId": "getBillOfMaterials",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/assemblies/d/{did}/{wvm}/{wvmid}/e/{eid}/boundingboxes": {
      "get": {
        "tags": [
          "Assemblies"
        ],
        "summary": "Bounding Boxes.",
        "operationId": "getAssemblyBoundingBoxes",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/assemblies/d/{did}/{wvm}/{wvmid}/e/{eid}/features": {
      "get": {
        "tags": [
          "Assemblies"
        ],
        "summary": "Get Feature List",
        "operationId": "getFeatures",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      },
      "post": {
        "tags": [
          "Assemblies"
        ],
        "operationId": "addFeature",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Write"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/assemblies/d/{did}/{wvm}/{wvmid}/e/{eid}/featurespecs": {
      "get": {
        "tags": [
          "Assemblies"
        ],
        "operationId": "getFeatureSpecs",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/assemblies/d/{did}/{wvm}/{wvmid}/e/{eid}/shadedviews": {
      "get": {
        "tags": [
          "Assemblies"
        ],
        "operationId": "getAssemblyShadedViews",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/assemblies/d/{did}/{wv}/{wvid}/e/{eid}/translations": {
      "post": {
        "tags": [
          "Assemblies"
        ],
        "summary": "Create Assembly translation.",
        "operationId": "translateFormat",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/billing/plans/client/{cid}": {
      "get": {
        "tags": [
          "Billing"
        ],
        "summary": "Get billing plans for client.",
        "operationId": "getClientPlans",
        "deprecated": false,
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/blobelements/d/{did}/w/{wid}": {
      "post": {
        "tags": [
          "BlobElements"
        ],
        "summary": "Upload File to New Blob Element.",
        "operationId": "uploadFileCreateElement",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Write"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/blobelements/d/{did}/w/{wid}/e/{eid}": {
      "get": {
        "tags": [
          "BlobElements"
        ],
        "summary": "Download File From Blob Element.",
        "operationId": "downloadFileWorkspace",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      },
      "post": {
        "tags": [
          "BlobElements"
        ],
        "summary": "Update Blob Element.",
        "operationId": "uploadFileUpdateElement",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Write"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/blobelements/d/{did}/w/{wid}/e/{eid}/units": {
      "post": {
        "tags": [
          "BlobElements"
        ],
        "summary": "Update Mesh Units.",
        "operationId": "updateUnits",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Write"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/blobelements/d/{did}/{wv}/{wvid}/e/{eid}/translations": {
      "post": {
        "tags": [
          "BlobElements"
        ],
        "summary": "Create Translation.",
        "operationId": "createBlobTranslation",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/companies": {
      "get": {
        "tags": [
          "Companies"
        ],
        "summary": "Get User companies.",
        "operationId": "findCompany",
        "deprecated": false,
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/companies/{cid}": {
      "get": {
        "tags": [
          "Companies"
        ],
        "summary": "Get company.",
        "operationId": "getCompany",
        "deprecated": false,
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/documents": {
      "get": {
        "tags": [
          "Documents"
        ],
        "summary": "Get Documents",
        "operationId": "getDocuments",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      },
      "post": {
        "tags": [
          "Documents"
        ],
        "summary": "Create document.",
        "operationId": "createDocument",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Write"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/documents/d/{did}/externaldata/{fid}": {
      "get": {
        "tags": [
          "Documents"
        ],
        "summary": "Download External Data",
        "operationId": "downloadExternalData",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/documents/d/{did}/versions": {
      "get": {
        "tags": [
          "Documents"
        ],
        "summary": "Get Versions",
        "operationId": "getDocumentVersions",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      },
      "post": {
        "tags": [
          "Documents"
        ],
        "summary": "Create Version.",
        "operationId": "createVersion",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Write"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/documents/d/{did}/versions/{vid}": {
      "get": {
        "tags": [
          "Documents"
        ],
        "summary": "Get Version",
        "operationId": "getVersion",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/documents/d/{did}/w/{wid}/e/{eid}/latestdocumentreferences": {
      "post": {
        "tags": [
          "Documents"
        ],
        "summary": "Update External References to Latest",
        "operationId": "updateExternalReferencesToLatestDocuments",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Write"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/documents/d/{did}/w/{wid}/moveelement": {
      "post": {
        "tags": [
          "Documents"
        ],
        "summary": "Move Elements",
        "operationId": "moveElementsToDocument",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Write"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/documents/d/{did}/w/{wid}/syncApplicationElements": {
      "post": {
        "tags": [
          "Documents"
        ],
        "summary": "Sync Application Elements",
        "operationId": "syncApplicationElements",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Write"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/documents/d/{did}/workspaces": {
      "get": {
        "tags": [
          "Documents"
        ],
        "summary": "Get Workspaces",
        "operationId": "getDocumentWorkspaces",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      },
      "post": {
        "tags": [
          "Documents"
        ],
        "summary": "Create Workspace",
        "operationId": "createWorkspace",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Write"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/documents/d/{did}/workspaces/{wid}": {
      "delete": {
        "tags": [
          "Documents"
        ],
        "summary": "Delete Workspace",
        "operationId": "deleteWorkspace",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Delete"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/documents/d/{did}/{wvm}/{wvmid}/elements": {
      "get": {
        "tags": [
          "Documents"
        ],
        "summary": "Get a list of elements in the workspace, version, or microversion of the document.",
        "operationId": "getElementsInDocument",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/documents/d/{did}/{wvm}/{wvmid}/insertables": {
      "get": {
        "tags": [
          "Documents"
        ],
        "summary": "Insertable List for Document Version.",
        "operationId": "getInsertables",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/documents/d/{did}/{wv}/{wvid}/currentmicroversion": {
      "get": {
        "tags": [
          "Documents"
        ],
        "summary": "Get Current Document Microversion",
        "operationId": "getCurrentMicroversion",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/documents/d/{did}/{wv}/{wvid}/e/{eid}/export": {
      "post": {
        "tags": [
          "Documents"
        ],
        "operationId": "export2Json",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/documents/search": {
      "post": {
        "tags": [
          "Documents"
        ],
        "operationId": "search",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/documents/{did}": {
      "get": {
        "tags": [
          "Documents"
        ],
        "summary": "Get Document",
        "operationId": "getDocument",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      },
      "post": {
        "tags": [
          "Documents"
        ],
        "summary": "Update Document Attributes.",
        "operationId": "updateDocumentAttributes",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Write"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      },
      "delete": {
        "tags": [
          "Documents"
        ],
        "summary": "Delete Document",
        "operationId": "deleteDocument",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Delete"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/documents/{did}/acl": {
      "get": {
        "tags": [
          "Documents"
        ],
        "summary": "Get Access Control List",
        "operationId": "getDocumentAcl",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/documents/{did}/permissionset": {
      "get": {
        "tags": [
          "Documents"
        ],
        "summary": "Get Document Permissions",
        "operationId": "getDocumentPermissionSet",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/documents/{did}/share": {
      "post": {
        "tags": [
          "Documents"
        ],
        "summary": "Share Document",
        "operationId": "shareDocument",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read",
              "OAuth2Share"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/documents/{did}/share/{eid}": {
      "delete": {
        "tags": [
          "Documents"
        ],
        "summary": "Unshare Document",
        "operationId": "unShareDocument",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read",
              "OAuth2Share"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/documents/{did}/w/{wid}/restore/{vm}/{vmid}": {
      "post": {
        "tags": [
          "Documents"
        ],
        "summary": "Restore version or microversion to workspace.",
        "operationId": "restoreFromHistory",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Write"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/documents/{did}/workspaces/{wid}/copy": {
      "post": {
        "tags": [
          "Documents"
        ],
        "summary": "Copy Workspace",
        "operationId": "copyWorkspace",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Write"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/documents/{did}/workspaces/{wid}/merge": {
      "post": {
        "tags": [
          "Documents"
        ],
        "summary": "Merge into workspace",
        "operationId": "mergeIntoWorkspace",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Write"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/drawings/d/{did}/w/{wid}/e/{eid}/translationformats": {
      "get": {
        "tags": [
          "Drawings"
        ],
        "operationId": "getDrawingTranslatorFormats",
        "deprecated": false,
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/drawings/d/{did}/{wv}/{wvid}/e/{eid}/translations": {
      "post": {
        "tags": [
          "Drawings"
        ],
        "summary": "Create Drawing translation",
        "operationId": "createDrawingTranslation",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/elements/copyelement/{did}/workspace/{wid}": {
      "post": {
        "tags": [
          "Elements"
        ],
        "summary": "Copy Element",
        "operationId": "copyElementFromSourceDocument",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Write"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/elements/d/{did}/e/{eid}/configurationencodings": {
      "post": {
        "tags": [
          "Elements"
        ],
        "summary": "Encode Configuration",
        "operationId": "encodeConfigurationMap",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/elements/d/{did}/w/{wid}/e/{eid}": {
      "delete": {
        "tags": [
          "Elements"
        ],
        "summary": "Delete Element",
        "operationId": "deleteElement",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Delete"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/elements/d/{did}/w/{wid}/e/{eid}/updatereferences": {
      "post": {
        "tags": [
          "Elements"
        ],
        "summary": "Update or replace node references",
        "operationId": "updateReferences",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read",
              "OAuth2Write"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/elements/d/{did}/{wvm}/{wvmid}/e/{eid}/configuration": {
      "get": {
        "tags": [
          "Elements"
        ],
        "summary": "Get Configuration",
        "operationId": "getConfiguration",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      },
      "post": {
        "tags": [
          "Elements"
        ],
        "summary": "Update Configuration",
        "operationId": "updateConfiguration",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Write"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/elements/d/{did}/{wvm}/{wvmid}/e/{eid}/configurationencodings/{cid}": {
      "get": {
        "tags": [
          "Elements"
        ],
        "summary": "Decode Configuration String",
        "operationId": "decodeConfiguration",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/elements/translatorFormats/{did}/{wv}/{wvid}/{eid}": {
      "get": {
        "tags": [
          "Elements"
        ],
        "summary": "Get Element Translator Formats",
        "operationId": "getElementTranslatorFormatsByVersionOrWorkspace",
        "deprecated": false,
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/featurestudios/d/{did}/w/{wid}": {
      "post": {
        "tags": [
          "FeatureStudios"
        ],
        "summary": "Create Feature Studio",
        "operationId": "createFeatureStudio",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Write"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/featurestudios/d/{did}/{wvm}/{wvmid}/e/{eid}": {
      "get": {
        "tags": [
          "FeatureStudios"
        ],
        "summary": "Get Feature Studio Contents.",
        "operationId": "getFeatureStudioContents",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      },
      "post": {
        "tags": [
          "FeatureStudios"
        ],
        "summary": "Update Feature Studio contents",
        "operationId": "updateFeatureStudioContents",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Write"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/featurestudios/d/{did}/{wvm}/{wvmid}/e/{eid}/featurespecs": {
      "get": {
        "tags": [
          "FeatureStudios"
        ],
        "summary": "Get Feature Studio Specs",
        "operationId": "getFeatureStudioSpecs",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/folders/{fid}/acl": {
      "get": {
        "tags": [
          "Folders"
        ],
        "summary": "Get Access Control List",
        "operationId": "getFolderAcl",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/folders/{fid}/share": {
      "post": {
        "tags": [
          "Folders"
        ],
        "summary": "Share Folder",
        "operationId": "share",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read",
              "OAuth2Share"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/folders/{fid}/share/{eid}": {
      "delete": {
        "tags": [
          "Folders"
        ],
        "summary": "Unshare Folder",
        "operationId": "unShare",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read",
              "OAuth2Share"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/insertables/d/{did}/latest": {
      "get": {
        "summary": "insertables for a document",
        "operationId": "getLatestInDocument",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/metadata/d/{did}/{wvm}/{wvmid}/e": {
      "get": {
        "tags": [
          "Metadata"
        ],
        "operationId": "getWMVEsMetadata",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/metadata/d/{did}/{wvm}/{wvmid}/e/{eid}": {
      "get": {
        "tags": [
          "Metadata"
        ],
        "operationId": "getWMVEMetadata",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      },
      "post": {
        "tags": [
          "Metadata"
        ],
        "operationId": "updateWVEMetadata",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Write"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/metadata/d/{did}/{wvm}/{wvmid}/e/{eid}/p": {
      "get": {
        "tags": [
          "Metadata"
        ],
        "operationId": "getWMVEPsMetadata",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/metadata/d/{did}/{wvm}/{wvmid}/e/{eid}/p/{pid}": {
      "get": {
        "tags": [
          "Metadata"
        ],
        "operationId": "getWMVEPMetadata",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      },
      "post": {
        "tags": [
          "Metadata"
        ],
        "operationId": "updateWVEPMetadata",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Write"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/metadata/d/{did}/{wv}/{wvid}": {
      "get": {
        "tags": [
          "Metadata"
        ],
        "operationId": "getWVMetadata",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      },
      "post": {
        "tags": [
          "Metadata"
        ],
        "operationId": "updateWVMetadata",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Write"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/metadata/standardcontent/d/{did}/v/{vid}/e/{eid}/{otype}/{oid}/p/{pid}": {
      "get": {
        "tags": [
          "Metadata"
        ],
        "operationId": "getVEOPStandardContentMetadata",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      },
      "post": {
        "tags": [
          "Metadata"
        ],
        "operationId": "updateVEOPStandardContentPartMetadata",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Write"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/metadataschema": {
      "get": {
        "operationId": "getMetadataSchema",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/metadataschema/properties": {
      "get": {
        "operationId": "getProperties",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/metadataschema/propertyinfo/{pid}": {
      "get": {
        "operationId": "getPropertyInfo",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/metadataschema/{sid}": {
      "get": {
        "operationId": "getSchema",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/openapi": {
      "get": {
        "tags": [
          "OpenAPI"
        ],
        "summary": "OpenAPI spec documentation for the Onshape REST API.",
        "operationId": "getOpenApi",
        "deprecated": false,
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/parts/d/{did}/{wvm}/{wvmid}": {
      "get": {
        "tags": [
          "Parts"
        ],
        "summary": "Get list of parts",
        "operationId": "getPartsWMV",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/parts/d/{did}/{wvm}/{wvmid}/e/{eid}": {
      "get": {
        "tags": [
          "Parts"
        ],
        "summary": "Get parts from an element.",
        "operationId": "getPartsWMVE",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/parts/d/{did}/{wvm}/{wvmid}/e/{eid}/partid/{partid}/bodydetails": {
      "get": {
        "tags": [
          "Parts"
        ],
        "operationId": "getBodyDetails",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/parts/d/{did}/{wvm}/{wvmid}/e/{eid}/partid/{partid}/boundingboxes": {
      "get": {
        "tags": [
          "Parts"
        ],
        "operationId": "getBoundingBoxes",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/parts/d/{did}/{wvm}/{wvmid}/e/{eid}/partid/{partid}/massproperties": {
      "get": {
        "tags": [
          "Parts"
        ],
        "operationId": "getMassProperties",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/parts/d/{did}/{wvm}/{wvmid}/e/{eid}/partid/{partid}/metadata": {
      "get": {
        "tags": [
          "Parts"
        ],
        "operationId": "getPartMetadata",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      },
      "post": {
        "tags": [
          "Parts"
        ],
        "operationId": "updatePartMetadata",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read",
              "OAuth2Write"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/parts/d/{did}/{wvm}/{wvmid}/e/{eid}/partid/{partid}/parasolid": {
      "get": {
        "tags": [
          "Parts"
        ],
        "summary": "Export Part to Parasolid.",
        "operationId": "exportPS",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/parts/d/{did}/{wvm}/{wvmid}/e/{eid}/partid/{partid}/shadedviews": {
      "get": {
        "tags": [
          "Parts"
        ],
        "operationId": "getShadedViews_1",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/parts/d/{did}/{wvm}/{wvmid}/e/{eid}/partid/{partid}/sheetmetal/bendtable": {
      "get": {
        "tags": [
          "Parts"
        ],
        "summary": "Get Sheet Metal Bend Table.",
        "operationId": "getBendTable",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/parts/d/{did}/{wvm}/{wvmid}/e/{eid}/partid/{partid}/tessellatededges": {
      "get": {
        "tags": [
          "Parts"
        ],
        "summary": "Tessellated Edges",
        "operationId": "getEdges",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/parts/d/{did}/{wvm}/{wvmid}/e/{eid}/partid/{partid}/tessellatedfaces": {
      "get": {
        "tags": [
          "Parts"
        ],
        "summary": "Get Tessellated Faces",
        "operationId": "getFaces_1",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/parts/standardcontent/d/{did}/v/{vid}/e/{eid}/{otype}/{oid}/partid/{partid}/metadata": {
      "get": {
        "tags": [
          "Parts"
        ],
        "operationId": "getStandardContentPartMetadata",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      },
      "post": {
        "tags": [
          "Parts"
        ],
        "operationId": "updateStandardContentPartMetadata",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read",
              "OAuth2Write"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/partstudios/d/{did}/e/{eid}/namedViews": {
      "get": {
        "tags": [
          "PartStudios"
        ],
        "summary": "Get Named Views",
        "operationId": "getPartStudioNamedViews",
        "deprecated": false,
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/partstudios/d/{did}/w/{wid}": {
      "post": {
        "tags": [
          "PartStudios"
        ],
        "summary": "Create Part Studio",
        "operationId": "createPartStudio",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Write"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/partstudios/d/{did}/w/{wid}/e/{eid}/features/featureid/{fid}": {
      "post": {
        "tags": [
          "PartStudios"
        ],
        "summary": "Update Feature",
        "operationId": "updatePartStudioFeature",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Write"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      },
      "delete": {
        "tags": [
          "PartStudios"
        ],
        "summary": "Delete Feature",
        "operationId": "deletePartStudioFeature",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Write"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/partstudios/d/{did}/w/{wid}/e/{eid}/features/rollback": {
      "post": {
        "tags": [
          "PartStudios"
        ],
        "summary": "Update Feature Rollback",
        "operationId": "updateRollback",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Write"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/partstudios/d/{did}/w/{wid}/e/{eid}/features/updates": {
      "post": {
        "tags": [
          "PartStudios"
        ],
        "summary": "Update Features",
        "operationId": "updateFeatures",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Write"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/partstudios/d/{did}/{wvm}/{wvmid}/e/{eid}/bodydetails": {
      "get": {
        "tags": [
          "PartStudios"
        ],
        "summary": "Array of body information",
        "operationId": "getPartStudioBodyDetails",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/partstudios/d/{did}/{wvm}/{wvmid}/e/{eid}/boundingboxes": {
      "get": {
        "tags": [
          "PartStudios"
        ],
        "summary": "Mass properties of parts or a PartStudio.",
        "operationId": "getPartStudioBoundingBoxes",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/partstudios/d/{did}/{wvm}/{wvmid}/e/{eid}/compare": {
      "get": {
        "tags": [
          "PartStudios"
        ],
        "summary": "Compare Part Studios",
        "operationId": "comparePartStudios",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/partstudios/d/{did}/{wvm}/{wvmid}/e/{eid}/configuration": {
      "get": {
        "tags": [
          "PartStudios"
        ],
        "summary": "Get Configuration",
        "operationId": "getPartStudioConfiguration",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      },
      "post": {
        "tags": [
          "PartStudios"
        ],
        "summary": "Update Configuration",
        "operationId": "updatePartStudioConfiguration",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Write"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/partstudios/d/{did}/{wvm}/{wvmid}/e/{eid}/features": {
      "get": {
        "tags": [
          "PartStudios"
        ],
        "summary": "Get Feature List",
        "operationId": "getPartStudioFeatures",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      },
      "post": {
        "tags": [
          "PartStudios"
        ],
        "summary": "Add Feature",
        "operationId": "addPartStudioFeature",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Write"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/partstudios/d/{did}/{wvm}/{wvmid}/e/{eid}/featurescript": {
      "post": {
        "tags": [
          "PartStudios"
        ],
        "summary": "Evaluate FeatureScript",
        "operationId": "evalFeatureScript",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/partstudios/d/{did}/{wvm}/{wvmid}/e/{eid}/featurespecs": {
      "get": {
        "tags": [
          "PartStudios"
        ],
        "summary": "Get Feature Specs",
        "operationId": "getPartStudioFeatureSpecs",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/partstudios/d/{did}/{wvm}/{wvmid}/e/{eid}/idtranslations": {
      "post": {
        "tags": [
          "PartStudios"
        ],
        "summary": "Id Translations",
        "operationId": "translateIds",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/partstudios/d/{did}/{wvm}/{wvmid}/e/{eid}/massproperties": {
      "get": {
        "tags": [
          "PartStudios"
        ],
        "summary": "Mass properties of parts or a PartStudio.",
        "operationId": "getPartStudioMassProperties",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/partstudios/d/{did}/{wvm}/{wvmid}/e/{eid}/parasolid": {
      "get": {
        "tags": [
          "PartStudios"
        ],
        "summary": "Export Part Studio to Parasolid",
        "operationId": "exportPS_1",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/partstudios/d/{did}/{wvm}/{wvmid}/e/{eid}/shadedviews": {
      "get": {
        "tags": [
          "PartStudios"
        ],
        "summary": "Get Shaded Views",
        "operationId": "getPartStudioShadedViews",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/partstudios/d/{did}/{wvm}/{wvmid}/e/{eid}/sketches": {
      "get": {
        "operationId": "getSketchInfo",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/partstudios/d/{did}/{wvm}/{wvmid}/e/{eid}/sketches/{sid}/boundingboxes": {
      "get": {
        "operationId": "getSketchBoundingBoxes",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/partstudios/d/{did}/{wvm}/{wvmid}/e/{eid}/sketches/{sid}/tessellatedentities": {
      "get": {
        "operationId": "getTessellatedEntities",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/partstudios/d/{did}/{wvm}/{wvmid}/e/{eid}/stl": {
      "get": {
        "tags": [
          "PartStudios"
        ],
        "summary": "Export Part Studio to STL",
        "operationId": "exportStl_1",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/partstudios/d/{did}/{wvm}/{wvmid}/e/{eid}/tessellatededges": {
      "get": {
        "tags": [
          "PartStudios"
        ],
        "summary": "Tesselated edges from a PartStudio.",
        "operationId": "getPartStudioTessellatedEdges",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/partstudios/d/{did}/{wvm}/{wvmid}/e/{eid}/tessellatedfaces": {
      "get": {
        "tags": [
          "PartStudios"
        ],
        "summary": "Tesselated faces of the parts in the Part Studio.",
        "operationId": "getPartStudioTessellatedFaces",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/partstudios/d/{did}/{wv}/{wvid}/e/{eid}/translations": {
      "post": {
        "tags": [
          "PartStudios"
        ],
        "summary": "Create Part Studio translation",
        "operationId": "createPartStudioTranslation",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/releasepackages/companyreleaseworkflow": {
      "get": {
        "tags": [
          "ReleaseManagement"
        ],
        "operationId": "getCompanyReleaseWorkflow",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/releasepackages/obsoletion/{wfid}": {
      "post": {
        "tags": [
          "ReleaseManagement"
        ],
        "operationId": "createObsoletionPackage",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Write"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/releasepackages/release/{wfid}": {
      "post": {
        "tags": [
          "ReleaseManagement"
        ],
        "operationId": "createReleasePackage",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Write"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/releasepackages/{rpid}": {
      "get": {
        "tags": [
          "ReleaseManagement"
        ],
        "operationId": "getReleasePackage",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      },
      "post": {
        "tags": [
          "ReleaseManagement"
        ],
        "operationId": "updateReleasePackage",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Write"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/revisions/companies/{cid}": {
      "get": {
        "tags": [
          "Revisions"
        ],
        "operationId": "enumerateRevisions",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/revisions/companies/{cid}/partnumber/{pnum}": {
      "get": {
        "tags": [
          "Revisions"
        ],
        "operationId": "getRevisionHistoryInCompany",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/revisions/{cd}/{cdid}/p/{pnum}/latest": {
      "get": {
        "tags": [
          "Revisions"
        ],
        "operationId": "getLatestInDocumentOrCompany",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/teams": {
      "get": {
        "tags": [
          "Teams"
        ],
        "operationId": "find",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/teams/{tid}": {
      "get": {
        "tags": [
          "Teams"
        ],
        "operationId": "getTeam",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/thumbnails/d/{did}": {
      "get": {
        "operationId": "getThumbnailForDocument",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/thumbnails/d/{did}/v/{vid}": {
      "get": {
        "operationId": "getThumbnailForDocumentAndVersion",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/thumbnails/d/{did}/w/{wid}": {
      "get": {
        "operationId": "getDocumentThumbnail",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/thumbnails/d/{did}/w/{wid}/e/{eid}/ac/{cid}/s/{sz}": {
      "get": {
        "operationId": "getElementThumbnailWithApiConfiguration",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/thumbnails/d/{did}/w/{wid}/e/{eid}/c/{cid}/s/{sz}": {
      "get": {
        "operationId": "getConfiguredElementThumbnailWithSize",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/thumbnails/d/{did}/w/{wid}/e/{eid}/s/{sz}": {
      "get": {
        "operationId": "getElementThumbnailWithSize",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/thumbnails/d/{did}/w/{wid}/s/{sz}": {
      "get": {
        "operationId": "getDocumentThumbnailWithSize",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/thumbnails/d/{did}/{wv}/{wvid}/e/{eid}": {
      "get": {
        "operationId": "getElementThumbnail",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      },
      "post": {
        "operationId": "setApplicationElementThumbnail",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Write"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      },
      "delete": {
        "operationId": "deleteApplicationThumbnails",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Write"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/thumbnails/document/{did}": {
      "get": {
        "operationId": "getThumbnailForDocumentOld",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/thumbnails/document/{did}/version/{vid}": {
      "get": {
        "operationId": "getThumbnailForDocumentAndVersionOld",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/translations/d/{did}": {
      "get": {
        "tags": [
          "Translations"
        ],
        "operationId": "getDocumentTranslations",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/translations/d/{did}/w/{wid}": {
      "post": {
        "tags": [
          "Translations"
        ],
        "operationId": "createTranslation",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/translations/translationformats": {
      "get": {
        "tags": [
          "Translations"
        ],
        "operationId": "getAllTranslatorFormats",
        "deprecated": false,
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/translations/{tid}": {
      "get": {
        "tags": [
          "Translations"
        ],
        "operationId": "getTranslation",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      },
      "delete": {
        "tags": [
          "Translations"
        ],
        "operationId": "deleteTranslation",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Write"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/users/sessioninfo": {
      "get": {
        "tags": [
          "Users"
        ],
        "operationId": "sessionInfo",
        "deprecated": false,
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/users/settings": {
      "get": {
        "tags": [
          "Users"
        ],
        "operationId": "getUserSettingsCurrentLoggedInUser",
        "deprecated": false,
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/users/{uid}/settings": {
      "get": {
        "tags": [
          "Users"
        ],
        "operationId": "getUserSettings",
        "deprecated": false,
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/versions/test": {
      "get": {
        "tags": [
          "Versions"
        ],
        "operationId": "testVersionsGet",
        "deprecated": false,
        "x-BTVisibility": "PRODUCTION"
      },
      "post": {
        "tags": [
          "Versions"
        ],
        "operationId": "testVersionsPost",
        "deprecated": false,
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/webhooks": {
      "get": {
        "tags": [
          "Webhooks"
        ],
        "operationId": "getWebhooks",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      },
      "post": {
        "tags": [
          "Webhooks"
        ],
        "operationId": "createWebhook",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/webhooks/{webhookid}": {
      "get": {
        "tags": [
          "Webhooks"
        ],
        "operationId": "getWebhook",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      },
      "post": {
        "tags": [
          "Webhooks"
        ],
        "operationId": "updateWebhook",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      },
      "delete": {
        "tags": [
          "Webhooks"
        ],
        "operationId": "unregisterWebhook",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/webhooks/{webhookid}/ping": {
      "post": {
        "tags": [
          "Webhooks"
        ],
        "operationId": "pingWebhook",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/workflow/active": {
      "get": {
        "tags": [
          "Workflow"
        ],
        "operationId": "getActiveWorkflows",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/workflowabletestobject/testobject/{wfid}": {
      "post": {
        "operationId": "createWorkflowableTestObject",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Write"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/workflowabletestobject/{oid}": {
      "get": {
        "operationId": "getWorkflowableTestObject",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Read"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      },
      "post": {
        "operationId": "updateWorkflowableTestObject",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Write"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    },
    "/api/workflowabletestobject/{oid}/{transition}": {
      "post": {
        "operationId": "transitionWorkflowableTestObject",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "OAuth2Write"
            ]
          }
        ],
        "x-BTVisibility": "PRODUCTION"
      }
    }
  },
  "components": {
    "schemas": {
      "BTCompanySummaryInfo": {
        "type": "object",
        "properties": {
          "admin": {
            "type": "boolean"
          },
          "description": {
            "type": "string"
          },
          "domainPrefix": {
            "type": "string"
          },
          "enterpriseBaseUrl": {
            "type": "string"
          },
          "href": {
            "type": "string",
            "format": "uri"
          },
          "id": {
            "type": "string"
          },
          "image": {
            "type": "string"
          },
          "name": {
            "type": "string"
          },
          "noPublicDocuments": {
            "type": "boolean"
          },
          "ownerId": {
            "type": "string"
          },
          "secondaryDomainPrefixes": {
            "uniqueItems": true,
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "state": {
            "type": "integer",
            "format": "int32"
          },
          "type": {
            "type": "integer",
            "format": "int32"
          },
          "viewRef": {
            "type": "string",
            "format": "uri"
          }
        }
      },
      "BTUserSummaryInfo": {
        "type": "object",
        "properties": {
          "company": {
            "$ref": "#/components/schemas/BTCompanySummaryInfo"
          },
          "email": {
            "type": "string"
          },
          "firstName": {
            "type": "string"
          },
          "globalPermissions": {
            "$ref": "#/components/schemas/GlobalPermissionInfo"
          },
          "href": {
            "type": "string",
            "format": "uri"
          },
          "id": {
            "type": "string"
          },
          "image": {
            "type": "string"
          },
          "isGuest": {
            "type": "boolean"
          },
          "isLight": {
            "type": "boolean"
          },
          "lastLoginTime": {
            "type": "string",
            "format": "date-time"
          },
          "lastName": {
            "type": "string"
          },
          "name": {
            "type": "string"
          },
          "source": {
            "type": "integer",
            "format": "int32"
          },
          "state": {
            "type": "integer",
            "format": "int32"
          },
          "viewRef": {
            "type": "string",
            "format": "uri"
          }
        }
      },
      "GlobalPermissionInfo": {
        "type": "object",
        "properties": {
          "accessReports": {
            "type": "boolean"
          },
          "adminEnterprise": {
            "type": "boolean"
          },
          "allowAppStoreAccess": {
            "type": "boolean"
          },
          "approveReleases": {
            "type": "boolean"
          },
          "createProject": {
            "type": "boolean"
          },
          "createReleases": {
            "type": "boolean"
          },
          "deletePermanently": {
            "type": "boolean"
          },
          "manageGuestUsers": {
            "type": "boolean"
          },
          "manageRbac": {
            "type": "boolean"
          },
          "manageUsers": {
            "type": "boolean"
          },
          "shareForAnonymousAccess": {
            "type": "boolean"
          }
        }
      },
      "BodyPart": {
        "type": "object",
        "properties": {
          "contentDisposition": {
            "$ref": "#/components/schemas/ContentDisposition"
          },
          "entity": {
            "type": "object"
          },
          "mediaType": {
            "type": "object",
            "properties": {
              "type": {
                "type": "string"
              },
              "subtype": {
                "type": "string"
              },
              "wildcardType": {
                "type": "boolean"
              },
              "wildcardSubtype": {
                "type": "boolean"
              }
            }
          },
          "messageBodyWorkers": {
            "$ref": "#/components/schemas/MessageBodyWorkers"
          },
          "parameterizedHeaders": {
            "type": "object",
            "properties": {
              "empty": {
                "type": "boolean"
              }
            },
            "additionalProperties": {
              "type": "array",
              "items": {
                "$ref": "#/components/schemas/ParameterizedHeader"
              }
            }
          },
          "parent": {
            "$ref": "#/components/schemas/MultiPart"
          },
          "providers": {
            "type": "object"
          }
        }
      },
      "ContentDisposition": {
        "type": "object",
        "properties": {
          "creationDate": {
            "type": "string",
            "format": "date-time"
          },
          "fileName": {
            "type": "string"
          },
          "modificationDate": {
            "type": "string",
            "format": "date-time"
          },
          "readDate": {
            "type": "string",
            "format": "date-time"
          },
          "size": {
            "type": "integer",
            "format": "int64"
          },
          "type": {
            "type": "string"
          }
        }
      },
      "FormDataBodyPart": {
        "type": "object",
        "properties": {
          "contentDisposition": {
            "$ref": "#/components/schemas/ContentDisposition"
          },
          "entity": {
            "type": "object"
          },
          "formDataContentDisposition": {
            "$ref": "#/components/schemas/FormDataContentDisposition"
          },
          "mediaType": {
            "type": "object",
            "properties": {
              "type": {
                "type": "string"
              },
              "subtype": {
                "type": "string"
              },
              "wildcardType": {
                "type": "boolean"
              },
              "wildcardSubtype": {
                "type": "boolean"
              }
            }
          },
          "messageBodyWorkers": {
            "$ref": "#/components/schemas/MessageBodyWorkers"
          },
          "name": {
            "type": "string"
          },
          "parameterizedHeaders": {
            "type": "object",
            "properties": {
              "empty": {
                "type": "boolean"
              }
            },
            "additionalProperties": {
              "type": "array",
              "items": {
                "$ref": "#/components/schemas/ParameterizedHeader"
              }
            }
          },
          "parent": {
            "$ref": "#/components/schemas/MultiPart"
          },
          "providers": {
            "type": "object"
          },
          "simple": {
            "type": "boolean"
          },
          "value": {
            "type": "string"
          }
        }
      },
      "FormDataContentDisposition": {
        "type": "object",
        "properties": {
          "creationDate": {
            "type": "string",
            "format": "date-time"
          },
          "fileName": {
            "type": "string"
          },
          "modificationDate": {
            "type": "string",
            "format": "date-time"
          },
          "name": {
            "type": "string"
          },
          "readDate": {
            "type": "string",
            "format": "date-time"
          },
          "size": {
            "type": "integer",
            "format": "int64"
          },
          "type": {
            "type": "string"
          }
        }
      },
      "MessageBodyWorkers": {
        "type": "object"
      },
      "MultiPart": {
        "type": "object",
        "properties": {
          "bodyParts": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/BodyPart"
            }
          },
          "contentDisposition": {
            "$ref": "#/components/schemas/ContentDisposition"
          },
          "entity": {
            "type": "object"
          },
          "mediaType": {
            "type": "object",
            "properties": {
              "type": {
                "type": "string"
              },
              "subtype": {
                "type": "string"
              },
              "wildcardType": {
                "type": "boolean"
              },
              "wildcardSubtype": {
                "type": "boolean"
              }
            }
          },
          "messageBodyWorkers": {
            "$ref": "#/components/schemas/MessageBodyWorkers"
          },
          "parameterizedHeaders": {
            "type": "object",
            "properties": {
              "empty": {
                "type": "boolean"
              }
            },
            "additionalProperties": {
              "type": "array",
              "items": {
                "$ref": "#/components/schemas/ParameterizedHeader"
              }
            }
          },
          "parent": {
            "$ref": "#/components/schemas/MultiPart"
          },
          "providers": {
            "type": "object"
          }
        }
      },
      "ParameterizedHeader": {
        "type": "object",
        "properties": {
          "value": {
            "type": "string"
          }
        }
      },
      "BTSettingParam": {
        "type": "object",
        "properties": {
          "key": {
            "type": "string"
          },
          "value": {
            "type": "object"
          }
        }
      },
      "BTUserAppSettingsParams": {
        "type": "object",
        "properties": {
          "settings": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/BTSettingParam"
            }
          }
        }
      },
      "BTSettingInfo": {
        "type": "object",
        "properties": {
          "key": {
            "type": "string"
          },
          "value": {
            "type": "object"
          }
        }
      },
      "BTUserAppSettingsInfo": {
        "type": "object",
        "properties": {
          "settings": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/BTSettingInfo"
            }
          }
        }
      },
      "Address": {
        "type": "object",
        "properties": {
          "city": {
            "type": "string"
          },
          "country": {
            "type": "string"
          },
          "line1": {
            "type": "string"
          },
          "line2": {
            "type": "string"
          },
          "postalCode": {
            "type": "string"
          },
          "state": {
            "type": "string"
          }
        }
      },
      "BTAPIApplicationSummaryInfo": {
        "type": "object",
        "properties": {
          "clientId": {
            "type": "string"
          },
          "description": {
            "type": "string"
          },
          "href": {
            "type": "string",
            "format": "uri"
          },
          "id": {
            "type": "string"
          },
          "name": {
            "type": "string"
          },
          "state": {
            "type": "integer",
            "format": "int32"
          },
          "viewRef": {
            "type": "string",
            "format": "uri"
          }
        }
      },
      "BTAddressInfo": {
        "type": "object",
        "properties": {
          "address": {
            "type": "string"
          },
          "city": {
            "type": "string"
          },
          "country": {
            "type": "string"
          },
          "countryCode": {
            "type": "string"
          },
          "id": {
            "type": "string"
          },
          "state": {
            "type": "string"
          },
          "stateCode": {
            "type": "string"
          },
          "zip": {
            "type": "string"
          }
        }
      },
      "BTBillingPlanInfo": {
        "type": "object",
        "properties": {
          "amountCents": {
            "type": "integer",
            "format": "int32"
          },
          "applicationId": {
            "type": "string"
          },
          "clientId": {
            "type": "string"
          },
          "companyPlan": {
            "type": "boolean"
          },
          "consumableQuantity": {
            "type": "integer",
            "format": "int32"
          },
          "deprecated": {
            "type": "boolean"
          },
          "description": {
            "type": "string"
          },
          "discountInfo": {
            "$ref": "#/components/schemas/BTDiscountInfo"
          },
          "group": {
            "type": "string"
          },
          "hidden": {
            "type": "boolean"
          },
          "href": {
            "type": "string",
            "format": "uri"
          },
          "id": {
            "type": "string"
          },
          "interval": {
            "type": "string"
          },
          "name": {
            "type": "string"
          },
          "onshapePlan": {
            "type": "boolean"
          },
          "planType": {
            "type": "integer",
            "format": "int32"
          },
          "trialPeriodDays": {
            "type": "integer",
            "format": "int32"
          },
          "viewRef": {
            "type": "string",
            "format": "uri"
          }
        }
      },
      "BTCardInfo": {
        "type": "object",
        "properties": {
          "billingAddress": {
            "$ref": "#/components/schemas/BTAddressInfo"
          },
          "expMonth": {
            "type": "integer",
            "format": "int32"
          },
          "expYear": {
            "type": "integer",
            "format": "int32"
          },
          "last4": {
            "type": "string"
          },
          "type": {
            "type": "string"
          }
        }
      },
      "BTDiscountInfo": {
        "type": "object",
        "properties": {
          "accountBalance": {
            "type": "integer",
            "format": "int32"
          },
          "amountOff": {
            "type": "integer",
            "format": "int32"
          },
          "couponType": {
            "type": "integer",
            "format": "int32"
          },
          "couponValidMonths": {
            "type": "integer",
            "format": "int32"
          },
          "createdAt": {
            "type": "string",
            "format": "date-time"
          },
          "createdBy": {
            "$ref": "#/components/schemas/BTUserSummaryInfo"
          },
          "expiresAt": {
            "type": "string",
            "format": "date-time"
          },
          "href": {
            "type": "string",
            "format": "uri"
          },
          "id": {
            "type": "string"
          },
          "name": {
            "type": "string"
          },
          "ownerId": {
            "type": "string"
          },
          "percentOff": {
            "type": "integer",
            "format": "int32"
          },
          "planId": {
            "type": "string"
          },
          "trialEndDate": {
            "type": "string"
          },
          "usedAt": {
            "type": "string",
            "format": "date-time"
          },
          "viewRef": {
            "type": "string",
            "format": "uri"
          }
        }
      },
      "BTPlanSubscriberInfo": {
        "type": "object",
        "properties": {
          "email": {
            "type": "string"
          },
          "firstName": {
            "type": "string"
          },
          "href": {
            "type": "string",
            "format": "uri"
          },
          "id": {
            "type": "string"
          },
          "image": {
            "type": "string"
          },
          "lastName": {
            "type": "string"
          },
          "name": {
            "type": "string"
          },
          "state": {
            "type": "integer",
            "format": "int32"
          },
          "viewRef": {
            "type": "string",
            "format": "uri"
          }
        }
      },
      "BTPurchaseInfo": {
        "type": "object",
        "properties": {
          "accountId": {
            "type": "string"
          },
          "actualAmountPaidCents": {
            "type": "integer",
            "format": "int64"
          },
          "amountCents": {
            "type": "integer",
            "format": "int64"
          },
          "application": {
            "$ref": "#/components/schemas/BTAPIApplicationSummaryInfo"
          },
          "canceledAt": {
            "type": "string",
            "format": "date-time"
          },
          "card": {
            "$ref": "#/components/schemas/BTCardInfo"
          },
          "clientId": {
            "type": "string"
          },
          "couponAmountOff": {
            "type": "integer",
            "format": "int64"
          },
          "couponPercentOff": {
            "type": "integer",
            "format": "int32"
          },
          "createdBy": {
            "type": "string"
          },
          "currency": {
            "type": "string"
          },
          "duration": {
            "type": "integer",
            "format": "int32"
          },
          "durationMonths": {
            "type": "integer",
            "format": "int32"
          },
          "group": {
            "type": "string"
          },
          "href": {
            "type": "string",
            "format": "uri"
          },
          "id": {
            "type": "string"
          },
          "lastModified": {
            "type": "string",
            "format": "date-time"
          },
          "lastModifiedBy": {
            "type": "string"
          },
          "lightSeats": {
            "type": "integer",
            "format": "int64"
          },
          "name": {
            "type": "string"
          },
          "nextCharge": {
            "$ref": "#/components/schemas/NextCharge"
          },
          "paymentType": {
            "type": "integer",
            "format": "int32"
          },
          "pendingCancelation": {
            "type": "boolean"
          },
          "plan": {
            "$ref": "#/components/schemas/BTBillingPlanInfo"
          },
          "planId": {
            "type": "string"
          },
          "planName": {
            "type": "string"
          },
          "planType": {
            "type": "integer",
            "format": "int32"
          },
          "proratedCharges": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/ProratedCharges"
            }
          },
          "proratedTotal": {
            "type": "integer",
            "format": "int64"
          },
          "purchaseDate": {
            "type": "string",
            "format": "date-time"
          },
          "resellerName": {
            "type": "string"
          },
          "seats": {
            "type": "integer",
            "format": "int64"
          },
          "state": {
            "type": "integer",
            "format": "int32"
          },
          "subscribers": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/BTPlanSubscriberInfo"
            }
          },
          "subscriptionBeginAt": {
            "type": "string",
            "format": "date-time"
          },
          "subscriptionEndAt": {
            "type": "string",
            "format": "date-time"
          },
          "subscriptionFields": {
            "$ref": "#/components/schemas/Subscription"
          },
          "subscriptionId": {
            "type": "string"
          },
          "subscriptionType": {
            "type": "integer",
            "format": "int32"
          },
          "trialEnd": {
            "type": "string",
            "format": "date-time"
          },
          "trialInitiatedBy": {
            "type": "string"
          },
          "viewRef": {
            "type": "string",
            "format": "uri"
          }
        }
      },
      "Card": {
        "type": "object",
        "properties": {
          "account": {
            "type": "string"
          },
          "addressCity": {
            "type": "string"
          },
          "addressCountry": {
            "type": "string"
          },
          "addressLine1": {
            "type": "string"
          },
          "addressLine1Check": {
            "type": "string"
          },
          "addressLine2": {
            "type": "string"
          },
          "addressState": {
            "type": "string"
          },
          "addressZip": {
            "type": "string"
          },
          "addressZipCheck": {
            "type": "string"
          },
          "availablePayoutMethods": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "brand": {
            "type": "string"
          },
          "country": {
            "type": "string"
          },
          "currency": {
            "type": "string"
          },
          "customer": {
            "type": "string"
          },
          "cvcCheck": {
            "type": "string"
          },
          "defaultForCurrency": {
            "type": "boolean"
          },
          "description": {
            "type": "string"
          },
          "dynamicLast4": {
            "type": "string"
          },
          "expMonth": {
            "type": "integer",
            "format": "int32"
          },
          "expYear": {
            "type": "integer",
            "format": "int32"
          },
          "fingerprint": {
            "type": "string"
          },
          "funding": {
            "type": "string"
          },
          "id": {
            "type": "string"
          },
          "iin": {
            "type": "string"
          },
          "instanceURL": {
            "type": "string"
          },
          "issuer": {
            "type": "string"
          },
          "last4": {
            "type": "string"
          },
          "metadata": {
            "type": "object",
            "additionalProperties": {
              "type": "string"
            }
          },
          "name": {
            "type": "string"
          },
          "object": {
            "type": "string"
          },
          "recipient": {
            "type": "string"
          },
          "status": {
            "type": "string"
          },
          "threeDSecure": {
            "$ref": "#/components/schemas/ThreeDSecure"
          },
          "tokenizationMethod": {
            "type": "string"
          },
          "type": {
            "type": "string"
          }
        }
      },
      "Coupon": {
        "type": "object",
        "properties": {
          "amountOff": {
            "type": "integer",
            "format": "int64"
          },
          "created": {
            "type": "integer",
            "format": "int64"
          },
          "currency": {
            "type": "string"
          },
          "duration": {
            "type": "string"
          },
          "durationInMonths": {
            "type": "integer",
            "format": "int32"
          },
          "id": {
            "type": "string"
          },
          "livemode": {
            "type": "boolean"
          },
          "maxRedemptions": {
            "type": "integer",
            "format": "int64"
          },
          "metadata": {
            "type": "object",
            "additionalProperties": {
              "type": "string"
            }
          },
          "object": {
            "type": "string"
          },
          "percentOff": {
            "type": "integer",
            "format": "int32"
          },
          "redeemBy": {
            "type": "integer",
            "format": "int64"
          },
          "timesRedeemed": {
            "type": "integer",
            "format": "int32"
          },
          "valid": {
            "type": "boolean"
          }
        }
      },
      "Customer": {
        "type": "object",
        "properties": {
          "accountBalance": {
            "type": "integer",
            "format": "int64"
          },
          "businessVatId": {
            "type": "string"
          },
          "cards": {
            "$ref": "#/components/schemas/CustomerCardCollection"
          },
          "created": {
            "type": "integer",
            "format": "int64"
          },
          "currency": {
            "type": "string"
          },
          "defaultCard": {
            "type": "string"
          },
          "defaultSource": {
            "type": "string"
          },
          "defaultSourceObject": {
            "$ref": "#/components/schemas/ExternalAccount"
          },
          "deleted": {
            "type": "boolean"
          },
          "delinquent": {
            "type": "boolean"
          },
          "description": {
            "type": "string"
          },
          "discount": {
            "$ref": "#/components/schemas/Discount"
          },
          "email": {
            "type": "string"
          },
          "id": {
            "type": "string"
          },
          "livemode": {
            "type": "boolean"
          },
          "metadata": {
            "type": "object",
            "additionalProperties": {
              "type": "string"
            }
          },
          "nextRecurringCharge": {
            "$ref": "#/components/schemas/NextRecurringCharge"
          },
          "object": {
            "type": "string"
          },
          "shipping": {
            "$ref": "#/components/schemas/ShippingDetails"
          },
          "sources": {
            "$ref": "#/components/schemas/ExternalAccountCollection"
          },
          "subscription": {
            "$ref": "#/components/schemas/Subscription"
          },
          "subscriptions": {
            "$ref": "#/components/schemas/CustomerSubscriptionCollection"
          },
          "trialEnd": {
            "type": "integer",
            "format": "int64"
          }
        }
      },
      "CustomerCardCollection": {
        "type": "object",
        "properties": {
          "count": {
            "type": "integer",
            "format": "int32"
          },
          "data": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/Card"
            }
          },
          "hasMore": {
            "type": "boolean"
          },
          "requestOptions": {
            "$ref": "#/components/schemas/RequestOptions"
          },
          "requestParams": {
            "type": "object",
            "additionalProperties": {
              "type": "object"
            }
          },
          "totalCount": {
            "type": "integer",
            "format": "int32"
          },
          "url": {
            "type": "string"
          }
        }
      },
      "CustomerSubscriptionCollection": {
        "type": "object",
        "properties": {
          "count": {
            "type": "integer",
            "format": "int32"
          },
          "data": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/Subscription"
            }
          },
          "hasMore": {
            "type": "boolean"
          },
          "requestOptions": {
            "$ref": "#/components/schemas/RequestOptions"
          },
          "requestParams": {
            "type": "object",
            "additionalProperties": {
              "type": "object"
            }
          },
          "totalCount": {
            "type": "integer",
            "format": "int32"
          },
          "url": {
            "type": "string"
          }
        }
      },
      "Discount": {
        "type": "object",
        "properties": {
          "coupon": {
            "$ref": "#/components/schemas/Coupon"
          },
          "customer": {
            "type": "string"
          },
          "end": {
            "type": "integer",
            "format": "int64"
          },
          "id": {
            "type": "string"
          },
          "object": {
            "type": "string"
          },
          "start": {
            "type": "integer",
            "format": "int64"
          },
          "subscription": {
            "type": "string"
          }
        }
      },
      "ExternalAccount": {
        "type": "object",
        "properties": {
          "account": {
            "type": "string"
          },
          "customer": {
            "type": "string"
          },
          "id": {
            "type": "string"
          },
          "instanceURL": {
            "type": "string"
          },
          "metadata": {
            "type": "object",
            "additionalProperties": {
              "type": "string"
            }
          },
          "object": {
            "type": "string"
          }
        }
      },
      "ExternalAccountCollection": {
        "type": "object",
        "properties": {
          "count": {
            "type": "integer",
            "format": "int32"
          },
          "data": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/ExternalAccount"
            }
          },
          "hasMore": {
            "type": "boolean"
          },
          "requestOptions": {
            "$ref": "#/components/schemas/RequestOptions"
          },
          "requestParams": {
            "type": "object",
            "additionalProperties": {
              "type": "object"
            }
          },
          "totalCount": {
            "type": "integer",
            "format": "int32"
          },
          "url": {
            "type": "string"
          }
        }
      },
      "NextCharge": {
        "type": "object",
        "properties": {
          "amount": {
            "type": "integer",
            "format": "int64"
          },
          "currentPeriodEnd": {
            "type": "string",
            "format": "date-time"
          },
          "interval": {
            "type": "string"
          },
          "total": {
            "type": "integer",
            "format": "int64"
          }
        }
      },
      "NextRecurringCharge": {
        "type": "object",
        "properties": {
          "amount": {
            "type": "integer",
            "format": "int64"
          },
          "date": {
            "type": "string"
          }
        }
      },
      "Plan": {
        "type": "object",
        "properties": {
          "amount": {
            "type": "integer",
            "format": "int64"
          },
          "created": {
            "type": "integer",
            "format": "int64"
          },
          "currency": {
            "type": "string"
          },
          "id": {
            "type": "string"
          },
          "interval": {
            "type": "string"
          },
          "intervalCount": {
            "type": "integer",
            "format": "int32"
          },
          "livemode": {
            "type": "boolean"
          },
          "metadata": {
            "type": "object",
            "additionalProperties": {
              "type": "string"
            }
          },
          "name": {
            "type": "string"
          },
          "object": {
            "type": "string"
          },
          "statementDescription": {
            "type": "string"
          },
          "statementDescriptor": {
            "type": "string"
          },
          "trialPeriodDays": {
            "type": "integer",
            "format": "int32"
          }
        }
      },
      "ProratedCharges": {
        "type": "object",
        "properties": {
          "amount": {
            "type": "integer",
            "format": "int64"
          },
          "date": {
            "type": "string",
            "format": "date-time"
          },
          "description": {
            "type": "string"
          }
        }
      },
      "RequestOptions": {
        "type": "object",
        "properties": {
          "apiKey": {
            "type": "string"
          },
          "connectTimeout": {
            "type": "integer",
            "format": "int32"
          },
          "idempotencyKey": {
            "type": "string"
          },
          "readTimeout": {
            "type": "integer",
            "format": "int32"
          },
          "stripeAccount": {
            "type": "string"
          },
          "stripeVersion": {
            "type": "string"
          }
        }
      },
      "ShippingDetails": {
        "type": "object",
        "properties": {
          "address": {
            "$ref": "#/components/schemas/Address"
          },
          "name": {
            "type": "string"
          },
          "phone": {
            "type": "string"
          }
        }
      },
      "Subscription": {
        "type": "object",
        "properties": {
          "applicationFeePercent": {
            "type": "number",
            "format": "double"
          },
          "billing": {
            "type": "string"
          },
          "cancelAtPeriodEnd": {
            "type": "boolean"
          },
          "canceledAt": {
            "type": "integer",
            "format": "int64"
          },
          "created": {
            "type": "integer",
            "format": "int64"
          },
          "currentPeriodEnd": {
            "type": "integer",
            "format": "int64"
          },
          "currentPeriodStart": {
            "type": "integer",
            "format": "int64"
          },
          "customer": {
            "type": "string"
          },
          "customerObject": {
            "$ref": "#/components/schemas/Customer"
          },
          "daysUntilDue": {
            "type": "integer",
            "format": "int32"
          },
          "discount": {
            "$ref": "#/components/schemas/Discount"
          },
          "endedAt": {
            "type": "integer",
            "format": "int64"
          },
          "id": {
            "type": "string"
          },
          "metadata": {
            "type": "object",
            "additionalProperties": {
              "type": "string"
            }
          },
          "object": {
            "type": "string"
          },
          "plan": {
            "$ref": "#/components/schemas/Plan"
          },
          "quantity": {
            "type": "integer",
            "format": "int32"
          },
          "start": {
            "type": "integer",
            "format": "int64"
          },
          "status": {
            "type": "string"
          },
          "subscriptionItems": {
            "$ref": "#/components/schemas/SubscriptionItemCollection"
          },
          "taxPercent": {
            "type": "number",
            "format": "double"
          },
          "trialEnd": {
            "type": "integer",
            "format": "int64"
          },
          "trialStart": {
            "type": "integer",
            "format": "int64"
          }
        }
      },
      "SubscriptionItem": {
        "type": "object",
        "properties": {
          "created": {
            "type": "integer",
            "format": "int64"
          },
          "id": {
            "type": "string"
          },
          "object": {
            "type": "string"
          },
          "plan": {
            "$ref": "#/components/schemas/Plan"
          },
          "quantity": {
            "type": "integer",
            "format": "int32"
          }
        }
      },
      "SubscriptionItemCollection": {
        "type": "object",
        "properties": {
          "count": {
            "type": "integer",
            "format": "int32"
          },
          "data": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/SubscriptionItem"
            }
          },
          "hasMore": {
            "type": "boolean"
          },
          "requestOptions": {
            "$ref": "#/components/schemas/RequestOptions"
          },
          "requestParams": {
            "type": "object",
            "additionalProperties": {
              "type": "object"
            }
          },
          "totalCount": {
            "type": "integer",
            "format": "int32"
          },
          "url": {
            "type": "string"
          }
        }
      },
      "ThreeDSecure": {
        "type": "object",
        "properties": {
          "amount": {
            "type": "integer",
            "format": "int64"
          },
          "authenticated": {
            "type": "boolean"
          },
          "card": {
            "$ref": "#/components/schemas/Card"
          },
          "created": {
            "type": "integer",
            "format": "int64"
          },
          "currency": {
            "type": "string"
          },
          "id": {
            "type": "string"
          },
          "livemode": {
            "type": "boolean"
          },
          "object": {
            "type": "string"
          },
          "redirectURL": {
            "type": "string"
          },
          "status": {
            "type": "string"
          }
        }
      },
      "BTUserBasicSummaryInfo": {
        "type": "object",
        "properties": {
          "href": {
            "type": "string",
            "format": "uri"
          },
          "id": {
            "type": "string"
          },
          "image": {
            "type": "string"
          },
          "jsonType": {
            "type": "string"
          },
          "name": {
            "type": "string"
          },
          "state": {
            "type": "integer",
            "format": "int32"
          },
          "viewRef": {
            "type": "string",
            "format": "uri"
          }
        },
        "discriminator": {
          "propertyName": "jsonType",
          "mapping": {
            "user-summary": "#/components/schemas/BTUserSummaryInfo"
          }
        }
      },
      "BTCompanyInfo": {
        "type": "object",
        "properties": {
          "address": {
            "$ref": "#/components/schemas/BTAddressInfo"
          },
          "admin": {
            "type": "boolean"
          },
          "description": {
            "type": "string"
          },
          "domainPrefix": {
            "type": "string"
          },
          "enterpriseBaseUrl": {
            "type": "string"
          },
          "href": {
            "type": "string",
            "format": "uri"
          },
          "id": {
            "type": "string"
          },
          "image": {
            "type": "string"
          },
          "name": {
            "type": "string"
          },
          "noPublicDocuments": {
            "type": "boolean"
          },
          "ownerId": {
            "type": "string"
          },
          "purchase": {
            "$ref": "#/components/schemas/BTPurchaseInfo"
          },
          "secondaryDomainPrefixes": {
            "uniqueItems": true,
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "state": {
            "type": "integer",
            "format": "int32"
          },
          "type": {
            "type": "integer",
            "format": "int32"
          },
          "viewRef": {
            "type": "string",
            "format": "uri"
          }
        }
      },
      "BTListResponseBTPurchaseInfo": {
        "type": "object",
        "properties": {
          "href": {
            "type": "string",
            "format": "uri"
          },
          "items": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/BTPurchaseInfo"
            }
          },
          "next": {
            "type": "string",
            "format": "uri"
          },
          "previous": {
            "type": "string",
            "format": "uri"
          }
        }
      },
      "BTBaseInfo": {
        "type": "object",
        "properties": {
          "href": {
            "type": "string",
            "format": "uri"
          },
          "id": {
            "type": "string"
          },
          "jsonType": {
            "type": "string"
          },
          "name": {
            "type": "string"
          },
          "viewRef": {
            "type": "string",
            "format": "uri"
          }
        },
        "discriminator": {
          "propertyName": "jsonType",
          "mapping": {
            "version-base": "#/components/schemas/BTVersionInfoBase"
          }
        }
      },
      "BTThumbnailInfo": {
        "type": "object",
        "properties": {
          "href": {
            "type": "string",
            "format": "uri"
          },
          "id": {
            "type": "string"
          },
          "secondarySizes": {
            "type": "array",
            "items": {
              "type": "array",
              "items": {
                "$ref": "#/components/schemas/BTThumbnailSizeInfo"
              }
            }
          },
          "sizes": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/BTThumbnailSizeInfo"
            }
          }
        }
      },
      "BTThumbnailSizeInfo": {
        "type": "object",
        "properties": {
          "href": {
            "type": "string",
            "format": "uri"
          },
          "mediaType": {
            "type": "string"
          },
          "renderMode": {
            "type": "string"
          },
          "sheetName": {
            "type": "string"
          },
          "size": {
            "type": "string"
          },
          "uniqueId": {
            "type": "string"
          },
          "viewOrientation": {
            "type": "string"
          }
        }
      },
      "BTVersionInfo": {
        "type": "object",
        "allOf": [
          {
            "$ref": "#/components/schemas/BTVersionInfoBase"
          },
          {
            "type": "object",
            "properties": {
              "purpose": {
                "type": "integer",
                "format": "int32"
              }
            }
          }
        ]
      },
      "BTVersionInfoBase": {
        "type": "object",
        "properties": {
          "type": {
            "type": "string"
          }
        },
        "discriminator": {
          "propertyName": "type",
          "mapping": {
            "version": "#/components/schemas/BTVersionInfo",
            "workspace": "#/components/schemas/BTWorkspaceInfo"
          }
        },
        "allOf": [
          {
            "$ref": "#/components/schemas/BTBaseInfo"
          },
          {
            "type": "object",
            "properties": {
              "thumbnail": {
                "$ref": "#/components/schemas/BTThumbnailInfo"
              },
              "parents": {
                "type": "array",
                "items": {
                  "$ref": "#/components/schemas/BTVersionInfo"
                }
              },
              "creator": {
                "$ref": "#/components/schemas/BTUserBasicSummaryInfo"
              },
              "lastModifier": {
                "$ref": "#/components/schemas/BTUserBasicSummaryInfo"
              },
              "modifiedAt": {
                "type": "string",
                "format": "date-time"
              },
              "documentId": {
                "type": "string"
              },
              "createdAt": {
                "type": "string",
                "format": "date-time"
              },
              "description": {
                "type": "string"
              },
              "microversion": {
                "type": "string"
              },
              "overrideDate": {
                "type": "string",
                "format": "date-time"
              },
              "type": {
                "type": "string"
              },
              "parent": {
                "type": "string"
              }
            }
          }
        ]
      },
      "BTWorkspaceInfo": {
        "type": "object",
        "allOf": [
          {
            "$ref": "#/components/schemas/BTVersionInfoBase"
          },
          {
            "type": "object",
            "properties": {
              "isReadOnly": {
                "type": "boolean"
              },
              "canDelete": {
                "type": "boolean"
              }
            }
          }
        ]
      },
      "BTPurchaseUserParams": {
        "type": "object",
        "properties": {
          "consumedQuantity": {
            "type": "integer",
            "format": "int32"
          },
          "purchaseId": {
            "type": "string"
          },
          "userId": {
            "type": "string"
          }
        }
      },
      "BTDocumentElementInfo": {
        "type": "object",
        "properties": {
          "angleUnits": {
            "type": "string"
          },
          "dataType": {
            "type": "string"
          },
          "elementType": {
            "type": "string",
            "enum": [
              "PARTSTUDIO",
              "ASSEMBLY",
              "DRAWING",
              "FEATURESTUDIO",
              "BLOB",
              "APPLICATION",
              "TABLE",
              "BILLOFMATERIALS",
              "UNKNOWN"
            ]
          },
          "filename": {
            "type": "string"
          },
          "foreignDataId": {
            "type": "string"
          },
          "id": {
            "type": "string"
          },
          "lengthUnits": {
            "type": "string"
          },
          "massUnits": {
            "type": "string"
          },
          "microversionId": {
            "type": "string"
          },
          "name": {
            "type": "string"
          },
          "specifiedUnit": {
            "type": "string"
          },
          "thumbnailInfo": {
            "$ref": "#/components/schemas/BTThumbnailInfo"
          },
          "thumbnails": {
            "type": "string",
            "format": "uri"
          },
          "type": {
            "type": "string"
          },
          "unupdatable": {
            "type": "boolean"
          }
        }
      },
      "BTAppAssociativeDataInfoArray": {
        "type": "object",
        "properties": {
          "changeId": {
            "type": "string"
          },
          "errorCode": {
            "type": "integer",
            "format": "int32"
          },
          "errorDescription": {
            "type": "string"
          },
          "errorValue": {
            "type": "string",
            "writeOnly": true,
            "enum": [
              "OK",
              "TRANSACTION_CONFLICT",
              "NOT_FOUND",
              "INCONSISTENT_CHANGES"
            ]
          },
          "items": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/BTAssociativeDataInfo"
            }
          },
          "parentChangeId": {
            "type": "string"
          }
        }
      },
      "BTAssociativeDataInfo": {
        "type": "object",
        "properties": {
          "associativeDataId": {
            "type": "string"
          },
          "data": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/BTNameValuePair"
            }
          },
          "documentId": {
            "type": "string"
          },
          "documentMicroversion": {
            "type": "string"
          },
          "elementId": {
            "type": "string"
          },
          "idTag": {
            "type": "string"
          },
          "microversionId": {
            "type": "string"
          },
          "occurrenceId": {
            "type": "string"
          },
          "type": {
            "type": "string",
            "enum": [
              "ONSHAPE_DRAWING_VIEW",
              "MODEL_TOPOLOGY",
              "MODEL_DEFINITION_FEATURE",
              "MODEL_DEFINITION_ENTITY",
              "UNKNOWN"
            ]
          },
          "versionId": {
            "type": "string"
          }
        }
      },
      "BTNameValuePair": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "value": {
            "type": "string"
          }
        }
      },
      "BTAppElementBasicInfo": {
        "type": "object",
        "properties": {
          "changeId": {
            "type": "string"
          },
          "errorCode": {
            "type": "integer",
            "format": "int32"
          },
          "errorDescription": {
            "type": "string"
          },
          "errorValue": {
            "type": "string",
            "writeOnly": true,
            "enum": [
              "OK",
              "TRANSACTION_CONFLICT",
              "NOT_FOUND",
              "INCONSISTENT_CHANGES"
            ]
          },
          "parentChangeId": {
            "type": "string"
          }
        }
      },
      "BTBoundingBox-1052": {
        "type": "object",
        "properties": {
          "maxCorner": {
            "$ref": "#/components/schemas/BTVector3d-389"
          },
          "minCorner": {
            "$ref": "#/components/schemas/BTVector3d-389"
          },
          "valid": {
            "type": "boolean"
          }
        }
      },
      "BTVector3d-389": {
        "type": "object",
        "properties": {
          "x": {
            "type": "number",
            "format": "double"
          },
          "y": {
            "type": "number",
            "format": "double"
          },
          "z": {
            "type": "number",
            "format": "double"
          }
        }
      },
      "BTAppElementReferenceInfo": {
        "type": "object",
        "properties": {
          "changeId": {
            "type": "string"
          },
          "errorCode": {
            "type": "integer",
            "format": "int32"
          },
          "errorDescription": {
            "type": "string"
          },
          "errorValue": {
            "type": "string",
            "writeOnly": true,
            "enum": [
              "OK",
              "TRANSACTION_CONFLICT",
              "NOT_FOUND",
              "INCONSISTENT_CHANGES"
            ]
          },
          "parentChangeId": {
            "type": "string"
          },
          "referenceId": {
            "type": "string"
          },
          "transactionId": {
            "type": "string"
          }
        }
      },
      "BTAppElementReferenceParams": {
        "type": "object",
        "properties": {
          "hasDocumentMicroversions": {
            "type": "boolean"
          },
          "idTag": {
            "type": "string"
          },
          "idTagMicroversionId": {
            "type": "string"
          },
          "isSketchOnly": {
            "type": "boolean"
          },
          "parentChangeId": {
            "type": "string"
          },
          "partNumber": {
            "type": "string"
          },
          "pureSketch": {
            "type": "boolean"
          },
          "referenceType": {
            "type": "integer",
            "format": "int32"
          },
          "returnError": {
            "type": "boolean"
          },
          "revision": {
            "type": "string"
          },
          "sketchIds": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "targetConfiguration": {
            "type": "string"
          },
          "targetDocumentId": {
            "type": "string"
          },
          "targetElementId": {
            "type": "string"
          },
          "targetMicroversionId": {
            "type": "string"
          },
          "targetVersionId": {
            "type": "string"
          },
          "trackNewVersions": {
            "type": "boolean"
          },
          "transactionId": {
            "type": "string"
          },
          "updateSketchInfo": {
            "type": "boolean"
          }
        }
      },
      "BTAppElementModifyInfo": {
        "type": "object",
        "properties": {
          "changeId": {
            "type": "string"
          },
          "elementId": {
            "type": "string"
          },
          "errorCode": {
            "type": "integer",
            "format": "int32"
          },
          "errorDescription": {
            "type": "string"
          },
          "errorValue": {
            "type": "string",
            "writeOnly": true,
            "enum": [
              "OK",
              "TRANSACTION_CONFLICT",
              "NOT_FOUND",
              "INCONSISTENT_CHANGES"
            ]
          },
          "parentChangeId": {
            "type": "string"
          },
          "propertyEditsMerged": {
            "type": "boolean"
          },
          "transactionId": {
            "type": "string"
          }
        }
      },
      "BTAppElementChangeParams": {
        "type": "object",
        "properties": {
          "baseContent": {
            "type": "string"
          },
          "delta": {
            "type": "string"
          },
          "subelementId": {
            "type": "string"
          }
        }
      },
      "BTAppElementParams": {
        "type": "object",
        "properties": {
          "description": {
            "type": "string"
          },
          "formatId": {
            "type": "string"
          },
          "location": {
            "$ref": "#/components/schemas/BTElementLocationParams"
          },
          "name": {
            "type": "string"
          },
          "subelements": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/BTAppElementChangeParams"
            }
          }
        }
      },
      "BTElementLocationParams": {
        "type": "object",
        "properties": {
          "elementId": {
            "type": "string"
          },
          "groupId": {
            "type": "string"
          },
          "position": {
            "type": "integer",
            "format": "int32"
          }
        }
      },
      "BTAppElementUpdateParams": {
        "type": "object",
        "properties": {
          "changes": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/BTAppElementChangeParams"
            }
          },
          "description": {
            "type": "string"
          },
          "parentChangeId": {
            "type": "string"
          },
          "returnError": {
            "type": "boolean"
          },
          "transactionId": {
            "type": "string"
          }
        }
      },
      "BTAppElementStartTransactionParams": {
        "type": "object",
        "properties": {
          "parentChangeId": {
            "type": "string"
          },
          "returnError": {
            "type": "boolean"
          }
        }
      },
      "BTAppElementCommitTransactionParams": {
        "type": "object",
        "properties": {
          "description": {
            "type": "string"
          },
          "returnError": {
            "type": "boolean"
          },
          "transactionId": {
            "type": "string"
          }
        }
      },
      "BTAppElementContentDeltaInfo": {
        "type": "object",
        "properties": {
          "delta": {
            "type": "string"
          }
        }
      },
      "BTAppElementContentEntryInfo": {
        "type": "object",
        "properties": {
          "baseContent": {
            "type": "string"
          },
          "deltas": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/BTAppElementContentDeltaInfo"
            }
          },
          "subelementId": {
            "type": "string"
          }
        }
      },
      "BTAppElementContentInfo": {
        "type": "object",
        "properties": {
          "changeId": {
            "type": "string"
          },
          "data": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/BTAppElementContentEntryInfo"
            }
          },
          "errorCode": {
            "type": "integer",
            "format": "int32"
          },
          "errorDescription": {
            "type": "string"
          },
          "errorValue": {
            "type": "string",
            "writeOnly": true,
            "enum": [
              "OK",
              "TRANSACTION_CONFLICT",
              "NOT_FOUND",
              "INCONSISTENT_CHANGES"
            ]
          }
        }
      },
      "BTAppElementHistoryEntryInfo": {
        "type": "object",
        "properties": {
          "changeId": {
            "type": "string"
          },
          "createdAt": {
            "type": "string",
            "format": "date-time"
          },
          "description": {
            "type": "string"
          }
        }
      },
      "BTAppElementHistoryInfo": {
        "type": "object",
        "properties": {
          "changes": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/BTAppElementHistoryEntryInfo"
            }
          },
          "errorCode": {
            "type": "integer",
            "format": "int32"
          },
          "errorDescription": {
            "type": "string"
          },
          "errorValue": {
            "type": "string",
            "writeOnly": true,
            "enum": [
              "OK",
              "TRANSACTION_CONFLICT",
              "NOT_FOUND",
              "INCONSISTENT_CHANGES"
            ]
          }
        }
      },
      "BTAppElementReferenceResolveInfo": {
        "type": "object",
        "properties": {
          "changeId": {
            "type": "string"
          },
          "errorCode": {
            "type": "integer",
            "format": "int32"
          },
          "errorDescription": {
            "type": "string"
          },
          "errorValue": {
            "type": "string",
            "writeOnly": true,
            "enum": [
              "OK",
              "TRANSACTION_CONFLICT",
              "NOT_FOUND",
              "INCONSISTENT_CHANGES"
            ]
          },
          "idTag": {
            "type": "string"
          },
          "idTagIsValid": {
            "type": "boolean"
          },
          "isConfigurable": {
            "type": "boolean"
          },
          "isFlattenedPart": {
            "type": "boolean"
          },
          "isSketchOnly": {
            "type": "boolean"
          },
          "isSurface": {
            "type": "boolean"
          },
          "partNumber": {
            "type": "string"
          },
          "referenceId": {
            "type": "string"
          },
          "referenceType": {
            "type": "integer",
            "format": "int32"
          },
          "resolvedDocumentMicroversionId": {
            "type": "string"
          },
          "resolvedElementMicroversionId": {
            "type": "string"
          },
          "revision": {
            "type": "string"
          },
          "sketchIds": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "targetConfiguration": {
            "type": "string"
          },
          "targetDocumentId": {
            "type": "string"
          },
          "targetDocumentMicroversionId": {
            "type": "string"
          },
          "targetElementId": {
            "type": "string"
          },
          "targetElementMicroversionId": {
            "type": "string"
          },
          "targetVersionId": {
            "type": "string"
          },
          "trackNewVersions": {
            "type": "boolean"
          }
        }
      },
      "BTAppElementReferencesResolveInfo": {
        "type": "object",
        "properties": {
          "resolvedReferences": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/BTAppElementReferenceResolveInfo"
            }
          },
          "unresolvedReferenceIds": {
            "type": "array",
            "items": {
              "type": "string"
            }
          }
        }
      },
      "BTAssemblyDefinitionInfo": {
        "type": "object",
        "properties": {
          "partStudioFeatures": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/BTAssemblyPSFeatureInfo"
            }
          },
          "parts": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/BTAssemblyPartsInfo"
            }
          },
          "rootAssembly": {
            "$ref": "#/components/schemas/BTRootAssemblyInfo"
          },
          "subAssemblies": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/BTSubAssemblyInfo"
            }
          }
        }
      },
      "BTAssemblyFeatureDataInfo": {
        "type": "object",
        "properties": {
          "mateType": {
            "type": "string"
          },
          "matedEntities": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/BTAssemblyMatedEntity"
            }
          },
          "name": {
            "type": "string"
          }
        }
      },
      "BTAssemblyFeatureInfo": {
        "type": "object",
        "properties": {
          "featureData": {
            "$ref": "#/components/schemas/BTAssemblyFeatureDataInfo"
          },
          "featureType": {
            "type": "string"
          },
          "id": {
            "type": "string"
          },
          "suppressed": {
            "type": "boolean"
          }
        }
      },
      "BTAssemblyInstanceInfo": {
        "type": "object",
        "properties": {
          "configuration": {
            "type": "string"
          },
          "documentId": {
            "type": "string"
          },
          "documentMicroversion": {
            "type": "string"
          },
          "documentVersion": {
            "type": "string"
          },
          "elementId": {
            "type": "string"
          },
          "fullConfiguration": {
            "type": "string"
          },
          "id": {
            "type": "string"
          },
          "name": {
            "type": "string"
          },
          "revision": {
            "type": "string"
          },
          "suppressed": {
            "type": "boolean"
          },
          "type": {
            "type": "string"
          }
        }
      },
      "BTAssemblyMatedEntity": {
        "type": "object",
        "properties": {
          "mateCS": {
            "$ref": "#/components/schemas/BTMateConnectorCSInfo"
          },
          "matedOccurrence": {
            "type": "array",
            "items": {
              "type": "string"
            }
          }
        }
      },
      "BTAssemblyOccurrenceInfo": {
        "type": "object",
        "properties": {
          "fixed": {
            "type": "boolean"
          },
          "hidden": {
            "type": "boolean"
          },
          "path": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "transform": {
            "type": "array",
            "items": {
              "type": "number",
              "format": "double"
            }
          }
        }
      },
      "BTAssemblyPSFeatureInfo": {
        "type": "object",
        "properties": {
          "configuration": {
            "type": "string"
          },
          "documentId": {
            "type": "string"
          },
          "documentMicroversion": {
            "type": "string"
          },
          "documentVersion": {
            "type": "string"
          },
          "elementId": {
            "type": "string"
          },
          "featureId": {
            "type": "string"
          },
          "featureType": {
            "type": "string"
          },
          "fullConfiguration": {
            "type": "string"
          },
          "revision": {
            "type": "string"
          }
        }
      },
      "BTAssemblyPartsInfo": {
        "type": "object",
        "properties": {
          "bodyType": {
            "type": "string",
            "enum": [
              "SOLID",
              "SHEET",
              "WIRE",
              "POINT",
              "MATE_CONNECTOR",
              "COMPOSITE",
              "UNKNOWN"
            ]
          },
          "configuration": {
            "type": "string"
          },
          "documentId": {
            "type": "string"
          },
          "documentMicroversion": {
            "type": "string"
          },
          "documentVersion": {
            "type": "string"
          },
          "elementId": {
            "type": "string"
          },
          "fullConfiguration": {
            "type": "string"
          },
          "partId": {
            "type": "string"
          },
          "revision": {
            "type": "string"
          },
          "standardContent": {
            "type": "boolean"
          }
        }
      },
      "BTMateConnectorCSInfo": {
        "type": "object",
        "properties": {
          "getxAxis": {
            "type": "array",
            "items": {
              "type": "number",
              "format": "double"
            }
          },
          "getyAxis": {
            "type": "array",
            "items": {
              "type": "number",
              "format": "double"
            }
          },
          "getzAxis": {
            "type": "array",
            "items": {
              "type": "number",
              "format": "double"
            }
          },
          "origin": {
            "type": "array",
            "items": {
              "type": "number",
              "format": "double"
            }
          }
        }
      },
      "BTRootAssemblyInfo": {
        "type": "object",
        "properties": {
          "configuration": {
            "type": "string"
          },
          "documentId": {
            "type": "string"
          },
          "documentMicroversion": {
            "type": "string"
          },
          "documentVersion": {
            "type": "string"
          },
          "elementId": {
            "type": "string"
          },
          "features": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/BTAssemblyFeatureInfo"
            }
          },
          "fullConfiguration": {
            "type": "string"
          },
          "instances": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/BTAssemblyInstanceInfo"
            }
          },
          "occurrences": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/BTAssemblyOccurrenceInfo"
            }
          },
          "revision": {
            "type": "string"
          }
        }
      },
      "BTSubAssemblyInfo": {
        "type": "object",
        "properties": {
          "configuration": {
            "type": "string"
          },
          "documentId": {
            "type": "string"
          },
          "documentMicroversion": {
            "type": "string"
          },
          "documentVersion": {
            "type": "string"
          },
          "elementId": {
            "type": "string"
          },
          "features": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/BTAssemblyFeatureInfo"
            }
          },
          "fullConfiguration": {
            "type": "string"
          },
          "instances": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/BTAssemblyInstanceInfo"
            }
          },
          "revision": {
            "type": "string"
          }
        }
      },
      "BTBoundingBoxInfo": {
        "type": "object",
        "properties": {
          "highX": {
            "type": "number",
            "format": "double"
          },
          "highY": {
            "type": "number",
            "format": "double"
          },
          "highZ": {
            "type": "number",
            "format": "double"
          },
          "lowX": {
            "type": "number",
            "format": "double"
          },
          "lowY": {
            "type": "number",
            "format": "double"
          },
          "lowZ": {
            "type": "number",
            "format": "double"
          }
        }
      },
      "BTShadedViewsInfo": {
        "type": "object",
        "properties": {
          "images": {
            "type": "array",
            "items": {
              "type": "array",
              "items": {
                "type": "string",
                "format": "byte"
              }
            }
          }
        }
      },
      "BTModelFormatInfo": {
        "type": "object",
        "properties": {
          "couldBeAssembly": {
            "type": "boolean"
          },
          "name": {
            "type": "string"
          },
          "translatorName": {
            "type": "string"
          }
        }
      },
      "BTTranslationRequestInfo": {
        "type": "object",
        "properties": {
          "documentId": {
            "type": "string"
          },
          "failureReason": {
            "type": "string"
          },
          "href": {
            "type": "string",
            "format": "uri"
          },
          "id": {
            "type": "string"
          },
          "name": {
            "type": "string"
          },
          "requestElementId": {
            "type": "string"
          },
          "requestState": {
            "type": "string",
            "enum": [
              "ACTIVE",
              "DONE",
              "FAILED"
            ]
          },
          "resultDocumentId": {
            "type": "string"
          },
          "resultElementIds": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "resultExternalDataIds": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "resultWorkspaceId": {
            "type": "string"
          },
          "versionId": {
            "type": "string"
          },
          "viewRef": {
            "type": "string",
            "format": "uri"
          },
          "workspaceId": {
            "type": "string"
          }
        }
      },
      "BTTranslateFormatParams": {
        "type": "object",
        "properties": {
          "allowFaultyParts": {
            "type": "boolean"
          },
          "angularTolerance": {
            "type": "number",
            "format": "double"
          },
          "blobElementId": {
            "type": "string"
          },
          "blobMicroversionId": {
            "type": "string"
          },
          "cloudObjectId": {
            "type": "string"
          },
          "cloudStorageAccountId": {
            "type": "string"
          },
          "colorMethod": {
            "type": "string"
          },
          "configuration": {
            "type": "string"
          },
          "connectionId": {
            "type": "string"
          },
          "createComposite": {
            "type": "boolean"
          },
          "currentSheetOnly": {
            "type": "boolean"
          },
          "destinationName": {
            "type": "string"
          },
          "distanceTolerance": {
            "type": "number",
            "format": "double"
          },
          "elementId": {
            "type": "string"
          },
          "emailLink": {
            "type": "boolean"
          },
          "emailMessage": {
            "type": "string"
          },
          "emailSubject": {
            "type": "string"
          },
          "emailTo": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "extractAssemblyHierarchy": {
            "type": "boolean"
          },
          "flatten": {
            "type": "boolean"
          },
          "flattenAssemblies": {
            "type": "boolean"
          },
          "foreignId": {
            "type": "string"
          },
          "formatName": {
            "type": "string"
          },
          "fromUserId": {
            "type": "string"
          },
          "getyAxisIsUp": {
            "type": "boolean"
          },
          "grouping": {
            "type": "boolean"
          },
          "imageHeight": {
            "type": "integer",
            "format": "int32"
          },
          "imageWidth": {
            "type": "integer",
            "format": "int32"
          },
          "importInBackground": {
            "type": "boolean"
          },
          "importWithinDocument": {
            "type": "boolean"
          },
          "includeExportIds": {
            "type": "boolean"
          },
          "joinAdjacentSurfaces": {
            "type": "boolean"
          },
          "linkDocumentId": {
            "type": "string"
          },
          "linkDocumentWorkspaceId": {
            "type": "string"
          },
          "maximumChordLength": {
            "type": "number",
            "format": "double"
          },
          "notifyUser": {
            "type": "boolean"
          },
          "originalForeignId": {
            "type": "string"
          },
          "parentId": {
            "type": "string"
          },
          "partIds": {
            "type": "string"
          },
          "password": {
            "type": "string"
          },
          "passwordRequired": {
            "type": "boolean"
          },
          "processedForeignId": {
            "type": "string"
          },
          "projectId": {
            "type": "string"
          },
          "selectablePdfText": {
            "type": "boolean"
          },
          "sendCopyToMe": {
            "type": "boolean"
          },
          "showOverriddenDimensions": {
            "type": "boolean"
          },
          "sourceName": {
            "type": "string"
          },
          "specifyUnits": {
            "type": "boolean"
          },
          "splinesAsPolylines": {
            "type": "boolean"
          },
          "splitAssembliesIntoMultipleDocuments": {
            "type": "boolean"
          },
          "storeInDocument": {
            "type": "boolean"
          },
          "textAsGeometry": {
            "type": "boolean"
          },
          "triggerAutoDownload": {
            "type": "boolean"
          },
          "unit": {
            "type": "string"
          },
          "uploadId": {
            "type": "string"
          },
          "validForDays": {
            "type": "integer",
            "format": "int32"
          },
          "versionString": {
            "type": "string"
          }
        }
      },
      "BTAssemblyTransformDefinitionParams": {
        "type": "object",
        "properties": {
          "isRelative": {
            "type": "boolean"
          },
          "occurrences": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/BTOccurrence-74"
            }
          },
          "transform": {
            "type": "array",
            "items": {
              "type": "number",
              "format": "double"
            }
          }
        }
      },
      "BTOccurrence-74": {
        "type": "object",
        "properties": {
          "fullPathAsString": {
            "type": "string"
          },
          "headInstanceId": {
            "type": "string"
          },
          "occurrenceWithoutHead": {
            "$ref": "#/components/schemas/BTOccurrence-74"
          },
          "occurrenceWithoutTail": {
            "$ref": "#/components/schemas/BTOccurrence-74"
          },
          "parent": {
            "$ref": "#/components/schemas/BTOccurrence-74"
          },
          "path": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "patternDescendant": {
            "type": "boolean"
          },
          "rootOccurrence": {
            "type": "boolean"
          },
          "tailInstanceId": {
            "type": "string"
          }
        }
      },
      "BTAssemblyInsertTransformedInstancesResponse": {
        "type": "object",
        "properties": {
          "insertResponses": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/BTAssemblyOccurrenceInfo"
            }
          }
        }
      },
      "BTAssemblyInstanceDefinitionParams": {
        "type": "object",
        "properties": {
          "configuration": {
            "type": "string"
          },
          "documentId": {
            "type": "string"
          },
          "elementId": {
            "type": "string"
          },
          "featureId": {
            "type": "string"
          },
          "isAssembly": {
            "type": "boolean"
          },
          "isHidden": {
            "type": "boolean"
          },
          "isSuppressed": {
            "type": "boolean"
          },
          "isWholePartStudio": {
            "type": "boolean"
          },
          "microversionId": {
            "type": "string"
          },
          "partId": {
            "type": "string"
          },
          "partNumber": {
            "type": "string"
          },
          "revision": {
            "type": "string"
          },
          "versionId": {
            "type": "string"
          }
        }
      },
      "BTAssemblyTransformedInstancesDefinitionParams": {
        "type": "object",
        "properties": {
          "transformGroups": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/TransformGroup"
            }
          }
        }
      },
      "TransformGroup": {
        "type": "object",
        "properties": {
          "instances": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/BTAssemblyInstanceDefinitionParams"
            }
          },
          "transform": {
            "type": "array",
            "items": {
              "type": "number",
              "format": "double"
            }
          }
        }
      },
      "BTAssemblyFeatureListResponse-1174": {
        "type": "object",
        "allOf": [
          {
            "$ref": "#/components/schemas/BTFeatureApiBase-1430"
          },
          {
            "type": "object",
            "properties": {
              "features": {
                "type": "array",
                "items": {
                  "$ref": "#/components/schemas/BTMAssemblyFeature-887"
                }
              },
              "isComplete": {
                "type": "boolean"
              },
              "featureStates": {
                "type": "object",
                "additionalProperties": {
                  "$ref": "#/components/schemas/BTFeatureState-1688"
                }
              }
            }
          }
        ]
      },
      "BTCurveGeometry-114": {
        "type": "object",
        "properties": {
          "btType": {
            "type": "string"
          }
        },
        "discriminator": {
          "propertyName": "btType",
          "mapping": {
            "BTCurveGeometryCircle-115": "#/components/schemas/BTCurveGeometryCircle-115",
            "BTCurveGeometryConic-2284": "#/components/schemas/BTCurveGeometryConic-2284",
            "BTCurveGeometryInterpolatedSpline-116": "#/components/schemas/BTCurveGeometryInterpolatedSpline-116",
            "BTCurveGeometryLine-117": "#/components/schemas/BTCurveGeometryLine-117",
            "BTCurveGeometrySpline-118": "#/components/schemas/BTCurveGeometrySpline-118"
          }
        }
      },
      "BTCurveGeometryCircle-115": {
        "type": "object",
        "properties": {
          "btType": {
            "type": "string"
          }
        },
        "discriminator": {
          "propertyName": "btType",
          "mapping": {
            "BTCurveGeometryEllipse-1189": "#/components/schemas/BTCurveGeometryEllipse-1189"
          }
        },
        "allOf": [
          {
            "$ref": "#/components/schemas/BTCurveGeometry-114"
          },
          {
            "type": "object",
            "properties": {
              "radius": {
                "type": "number",
                "format": "double"
              },
              "xcenter": {
                "type": "number",
                "format": "double"
              },
              "ycenter": {
                "type": "number",
                "format": "double"
              },
              "xdir": {
                "type": "number",
                "format": "double"
              },
              "ydir": {
                "type": "number",
                "format": "double"
              },
              "clockwise": {
                "type": "boolean"
              }
            }
          }
        ]
      },
      "BTCurveGeometryConic-2284": {
        "type": "object",
        "allOf": [
          {
            "$ref": "#/components/schemas/BTCurveGeometry-114"
          },
          {
            "type": "object",
            "properties": {
              "points": {
                "type": "array",
                "items": {
                  "type": "number",
                  "format": "double"
                }
              },
              "rho": {
                "type": "number",
                "format": "double"
              }
            }
          }
        ]
      },
      "BTCurveGeometryEllipse-1189": {
        "type": "object",
        "allOf": [
          {
            "$ref": "#/components/schemas/BTCurveGeometryCircle-115"
          },
          {
            "type": "object",
            "properties": {
              "minorRadius": {
                "type": "number",
                "format": "double"
              }
            }
          }
        ]
      },
      "BTCurveGeometryInterpolatedSpline-116": {
        "type": "object",
        "allOf": [
          {
            "$ref": "#/components/schemas/BTCurveGeometry-114"
          },
          {
            "type": "object",
            "properties": {
              "isPeriodic": {
                "type": "boolean"
              },
              "interpolationPoints": {
                "type": "array",
                "items": {
                  "type": "number",
                  "format": "double"
                }
              },
              "startDerivativeX": {
                "type": "number",
                "format": "double"
              },
              "startDerivativeY": {
                "type": "number",
                "format": "double"
              },
              "endDerivativeX": {
                "type": "number",
                "format": "double"
              },
              "endDerivativeY": {
                "type": "number",
                "format": "double"
              },
              "startHandleX": {
                "type": "number",
                "format": "double"
              },
              "startHandleY": {
                "type": "number",
                "format": "double"
              },
              "endHandleX": {
                "type": "number",
                "format": "double"
              },
              "endHandleY": {
                "type": "number",
                "format": "double"
              }
            }
          }
        ]
      },
      "BTCurveGeometryLine-117": {
        "type": "object",
        "allOf": [
          {
            "$ref": "#/components/schemas/BTCurveGeometry-114"
          },
          {
            "type": "object",
            "properties": {
              "pntX": {
                "type": "number",
                "format": "double"
              },
              "pntY": {
                "type": "number",
                "format": "double"
              },
              "dirX": {
                "type": "number",
                "format": "double"
              },
              "dirY": {
                "type": "number",
                "format": "double"
              }
            }
          }
        ]
      },
      "BTCurveGeometrySpline-118": {
        "type": "object",
        "allOf": [
          {
            "$ref": "#/components/schemas/BTCurveGeometry-114"
          },
          {
            "type": "object",
            "properties": {
              "degree": {
                "type": "integer",
                "format": "int32"
              },
              "isRational": {
                "type": "boolean"
              },
              "controlPointCount": {
                "type": "integer",
                "format": "int32"
              },
              "controlPoints": {
                "type": "array",
                "items": {
                  "type": "number",
                  "format": "double"
                }
              },
              "knots": {
                "type": "array",
                "items": {
                  "type": "number",
                  "format": "double"
                }
              },
              "isPeriodic": {
                "type": "boolean"
              }
            }
          }
        ]
      },
      "BTDocumentWithVersionAndElementId": {
        "type": "object",
        "properties": {
          "documentId": {
            "type": "string"
          },
          "documentVersionId": {
            "type": "string"
          },
          "elementId": {
            "type": "string"
          },
          "partNumber": {
            "type": "string"
          },
          "revision": {
            "type": "string"
          },
          "uniqueVersionId": {
            "type": "string"
          },
          "validRevisionReference": {
            "type": "boolean"
          }
        }
      },
      "BTDocumentWithVersionId": {
        "type": "object",
        "properties": {
          "documentId": {
            "type": "string"
          },
          "documentVersionId": {
            "type": "string"
          }
        }
      },
      "BTElementReference-725": {
        "type": "object",
        "properties": {
          "btType": {
            "type": "string"
          },
          "configured": {
            "type": "boolean"
          },
          "elementId": {
            "type": "string"
          },
          "externalDocumentWithVersion": {
            "$ref": "#/components/schemas/BTDocumentWithVersionId"
          },
          "externalDocumentWithVersionAndElementId": {
            "$ref": "#/components/schemas/BTDocumentWithVersionAndElementId"
          },
          "externalReference": {
            "type": "boolean"
          },
          "fullElementId": {
            "$ref": "#/components/schemas/BTFullElementId-756"
          },
          "microversionIdAndConfiguration": {
            "$ref": "#/components/schemas/BTMicroversionIdAndConfiguration-2338"
          },
          "nodeId": {
            "type": "string"
          }
        },
        "discriminator": {
          "propertyName": "btType",
          "mapping": {
            "BTExternalReference-1936": "#/components/schemas/BTExternalReference-1936"
          }
        }
      },
      "BTExplosion-2754": {
        "type": "object",
        "allOf": [
          {
            "$ref": "#/components/schemas/BTMAssemblyFeature-887"
          },
          {
            "type": "object",
            "properties": {
              "explodeSteps": {
                "type": "array",
                "items": {
                  "$ref": "#/components/schemas/BTExplosionStepFeature-3008"
                }
              },
              "startingPositionId": {
                "$ref": "#/components/schemas/BTMicroversionIdAndConfiguration-2338"
              }
            }
          }
        ]
      },
      "BTExplosionStepFeature-3008": {
        "type": "object",
        "allOf": [
          {
            "$ref": "#/components/schemas/BTMAssemblyFeature-887"
          }
        ]
      },
      "BTExternalReference-1936": {
        "type": "object",
        "allOf": [
          {
            "$ref": "#/components/schemas/BTElementReference-725"
          },
          {
            "type": "object",
            "properties": {
              "documentVersionId": {
                "type": "string"
              }
            }
          }
        ]
      },
      "BTFSValue-1888": {
        "type": "object",
        "properties": {
          "btType": {
            "type": "string"
          },
          "configurationValueString": {
            "type": "string"
          },
          "typeTag": {
            "type": "string"
          },
          "valueObject": {
            "type": "object"
          }
        },
        "discriminator": {
          "propertyName": "btType",
          "mapping": {
            "BTFSValueArray-1499": "#/components/schemas/BTFSValueArray-1499",
            "BTFSValueBoolean-1195": "#/components/schemas/BTFSValueBoolean-1195",
            "BTFSValueMap-2062": "#/components/schemas/BTFSValueMap-2062",
            "BTFSValueNumber-772": "#/components/schemas/BTFSValueNumber-772",
            "BTFSValueOther-1124": "#/components/schemas/BTFSValueOther-1124",
            "BTFSValueString-1422": "#/components/schemas/BTFSValueString-1422",
            "BTFSValueTooBig-1247": "#/components/schemas/BTFSValueTooBig-1247",
            "BTFSValueUndefined-2003": "#/components/schemas/BTFSValueUndefined-2003",
            "BTFSValueWithUnits-1817": "#/components/schemas/BTFSValueWithUnits-1817"
          }
        }
      },
      "BTFSValueArray-1499": {
        "type": "object",
        "allOf": [
          {
            "$ref": "#/components/schemas/BTFSValue-1888"
          },
          {
            "type": "object",
            "properties": {
              "valueObject": {
                "type": "array",
                "items": {
                  "type": "object"
                }
              },
              "value": {
                "type": "array",
                "items": {
                  "$ref": "#/components/schemas/BTFSValue-1888"
                }
              }
            }
          }
        ]
      },
      "BTFSValueBoolean-1195": {
        "type": "object",
        "allOf": [
          {
            "$ref": "#/components/schemas/BTFSValue-1888"
          },
          {
            "type": "object",
            "properties": {
              "valueObject": {
                "type": "boolean"
              },
              "value": {
                "type": "boolean"
              }
            }
          }
        ]
      },
      "BTFSValueMap-2062": {
        "type": "object",
        "properties": {
          "configurationValueString": {
            "type": "string"
          },
          "fsvaluesKeyedByStrings": {
            "type": "object",
            "additionalProperties": {
              "$ref": "#/components/schemas/BTFSValue-1888"
            }
          },
          "typeTag": {
            "type": "string"
          },
          "value": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/BTFSValueMapEntry-2077"
            }
          },
          "valueObject": {
            "type": "object",
            "additionalProperties": {
              "type": "object"
            }
          }
        }
      },
      "BTFSValueMapEntry-2077": {
        "type": "object",
        "properties": {
          "key": {
            "$ref": "#/components/schemas/BTFSValue-1888"
          },
          "value": {
            "$ref": "#/components/schemas/BTFSValue-1888"
          }
        }
      },
      "BTFSValueNumber-772": {
        "type": "object",
        "allOf": [
          {
            "$ref": "#/components/schemas/BTFSValue-1888"
          },
          {
            "type": "object",
            "properties": {
              "valueObject": {
                "type": "number",
                "format": "double"
              },
              "value": {
                "type": "number",
                "format": "double"
              }
            }
          }
        ]
      },
      "BTFSValueOther-1124": {
        "type": "object",
        "allOf": [
          {
            "$ref": "#/components/schemas/BTFSValue-1888"
          },
          {
            "type": "object",
            "properties": {
              "type": {
                "type": "string",
                "enum": [
                  "UNDEFINED",
                  "BOOLEAN",
                  "NUMBER",
                  "STRING",
                  "ARRAY",
                  "MAP",
                  "BOX",
                  "BUILTIN",
                  "FUNCTION",
                  "UNKNOWN"
                ]
              }
            }
          }
        ]
      },
      "BTFSValueString-1422": {
        "type": "object",
        "allOf": [
          {
            "$ref": "#/components/schemas/BTFSValue-1888"
          },
          {
            "type": "object",
            "properties": {
              "valueObject": {
                "type": "string"
              },
              "value": {
                "type": "string"
              }
            }
          }
        ]
      },
      "BTFSValueTooBig-1247": {
        "type": "object",
        "allOf": [
          {
            "$ref": "#/components/schemas/BTFSValue-1888"
          }
        ]
      },
      "BTFSValueUndefined-2003": {
        "type": "object",
        "allOf": [
          {
            "$ref": "#/components/schemas/BTFSValue-1888"
          }
        ]
      },
      "BTFSValueWithUnits-1817": {
        "type": "object",
        "allOf": [
          {
            "$ref": "#/components/schemas/BTFSValue-1888"
          },
          {
            "type": "object",
            "properties": {
              "valueObject": {
                "type": "number",
                "format": "double"
              },
              "quantityType": {
                "type": "string",
                "enum": [
                  "UNKNOWN",
                  "INTEGER",
                  "REAL",
                  "LENGTH",
                  "ANGLE",
                  "MASS",
                  "TIME",
                  "TEMPERATURE",
                  "CURRENT",
                  "ANYTHING"
                ]
              },
              "unitToPower": {
                "type": "object",
                "additionalProperties": {
                  "type": "integer",
                  "format": "int32"
                }
              },
              "value": {
                "type": "number",
                "format": "double"
              }
            }
          }
        ]
      },
      "BTFeatureState-1688": {
        "type": "object",
        "properties": {
          "btType": {
            "type": "string"
          },
          "featureStatus": {
            "type": "string",
            "enum": [
              "OK",
              "INFO",
              "WARNING",
              "ERROR",
              "UNKNOWN"
            ]
          }
        }
      },
      "BTForeignDataResponse-1070": {
        "type": "object",
        "properties": {
          "bucketName": {
            "type": "string"
          },
          "bucketPath": {
            "type": "string"
          },
          "cacheChunkList": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "dataId": {
            "type": "string"
          },
          "format": {
            "type": "string",
            "enum": [
              "X_T",
              "XMM",
              "STL",
              "ONSHAPE",
              "ZIP",
              "X_T_XMM_ZIP",
              "UNKNOWN"
            ]
          },
          "name": {
            "type": "string"
          },
          "region": {
            "type": "string"
          },
          "size": {
            "type": "integer",
            "format": "int32"
          },
          "useLocalStorage": {
            "type": "boolean"
          }
        }
      },
      "BTFullElementId-756": {
        "type": "object",
        "properties": {
          "btType": {
            "type": "string"
          },
          "configured": {
            "type": "boolean"
          },
          "elementId": {
            "type": "string"
          },
          "microversionId": {
            "$ref": "#/components/schemas/BTMicroversionId-366"
          },
          "microversionIdAndConfiguration": {
            "$ref": "#/components/schemas/BTMicroversionIdAndConfiguration-2338"
          },
          "target": {
            "$ref": "#/components/schemas/BTMicroversionIdAndConfiguration-2338"
          }
        },
        "discriminator": {
          "propertyName": "btType",
          "mapping": {
            "BTFullElementIdWithDocument-1729": "#/components/schemas/BTFullElementIdWithDocument-1729"
          }
        }
      },
      "BTFullElementIdAndPartId-643": {
        "type": "object",
        "allOf": [
          {
            "$ref": "#/components/schemas/BTFullElementIdWithDocument-1729"
          },
          {
            "type": "object",
            "properties": {
              "partId": {
                "type": "string"
              }
            }
          }
        ]
      },
      "BTFullElementIdWithDocument-1729": {
        "type": "object",
        "properties": {
          "btType": {
            "type": "string"
          }
        },
        "discriminator": {
          "propertyName": "btType",
          "mapping": {
            "BTFullElementIdAndPartId-643": "#/components/schemas/BTFullElementIdAndPartId-643"
          }
        },
        "allOf": [
          {
            "$ref": "#/components/schemas/BTFullElementId-756"
          },
          {
            "type": "object",
            "properties": {
              "documentId": {
                "type": "string"
              }
            }
          }
        ]
      },
      "BTGraphicsAppearance-1152": {
        "type": "object",
        "properties": {
          "color": {
            "type": "array",
            "items": {
              "type": "string",
              "format": "byte"
            }
          },
          "nonTrivial": {
            "type": "boolean"
          },
          "opacity": {
            "type": "integer",
            "format": "int32"
          },
          "reset": {
            "type": "boolean"
          },
          "rgbaColor": {
            "type": "array",
            "items": {
              "type": "string",
              "format": "byte"
            }
          },
          "usableAppearance": {
            "type": "boolean"
          }
        }
      },
      "BTMArrayParameterItem-1843": {
        "type": "object",
        "properties": {
          "importMicroversion": {
            "type": "string",
            "writeOnly": true
          },
          "nodeId": {
            "type": "string"
          }
        }
      },
      "BTMAssemblyFeature-887": {
        "type": "object",
        "properties": {
          "btType": {
            "type": "string"
          }
        },
        "discriminator": {
          "propertyName": "btType",
          "mapping": {
            "BTExplosion-2754": "#/components/schemas/BTExplosion-2754",
            "BTExplosionStepFeature-3008": "#/components/schemas/BTExplosionStepFeature-3008",
            "BTMAssemblyFeature1-2218": "#/components/schemas/BTMAssemblyFeature1-2218",
            "BTMAssemblyFeature2-1022": "#/components/schemas/BTMAssemblyFeature2-1022",
            "BTMAssemblyPatternFeature-2241": "#/components/schemas/BTMAssemblyPatternFeature-2241",
            "BTMGeometryMate-1260": "#/components/schemas/BTMGeometryMate-1260",
            "BTMMate-64": "#/components/schemas/BTMMate-64",
            "BTMMateConnector-66": "#/components/schemas/BTMMateConnector-66",
            "BTMMateGroup-65": "#/components/schemas/BTMMateGroup-65",
            "BTMMateRelation-1412": "#/components/schemas/BTMMateRelation-1412",
            "BTMNonGeometricItem-1864": "#/components/schemas/BTMNonGeometricItem-1864"
          }
        },
        "allOf": [
          {
            "$ref": "#/components/schemas/BTMFeature-134"
          },
          {
            "type": "object",
            "properties": {
              "auxiliaryAssemblyFeature": {
                "type": "boolean"
              },
              "featureListFieldIndex": {
                "type": "integer",
                "format": "int32"
              },
              "occurrenceQueriesFromAllConfigurations": {
                "type": "array",
                "items": {
                  "$ref": "#/components/schemas/BTMIndividualQueryWithOccurrenceBase-904"
                }
              },
              "version": {
                "type": "integer",
                "format": "int32"
              }
            }
          }
        ]
      },
      "BTMAssemblyFeature1-2218": {
        "type": "object",
        "allOf": [
          {
            "$ref": "#/components/schemas/BTMAssemblyFeature-887"
          }
        ]
      },
      "BTMAssemblyFeature2-1022": {
        "type": "object",
        "allOf": [
          {
            "$ref": "#/components/schemas/BTMAssemblyFeature-887"
          }
        ]
      },
      "BTMAssemblyPatternFeature-2241": {
        "type": "object",
        "allOf": [
          {
            "$ref": "#/components/schemas/BTMAssemblyFeature-887"
          },
          {
            "type": "object",
            "properties": {
              "patternType": {
                "type": "string",
                "enum": [
                  "LINEAR",
                  "CIRCULAR",
                  "UNKNOWN"
                ]
              }
            }
          }
        ]
      },
      "BTMConfiguredValue-1341": {
        "type": "object",
        "properties": {
          "btType": {
            "type": "string"
          },
          "configurationValueString": {
            "type": "string"
          },
          "importMicroversion": {
            "type": "string",
            "writeOnly": true
          },
          "nodeId": {
            "type": "string"
          },
          "value": {
            "$ref": "#/components/schemas/BTMParameter-1"
          }
        },
        "discriminator": {
          "propertyName": "btType",
          "mapping": {
            "BTMConfiguredValueByBoolean-1501": "#/components/schemas/BTMConfiguredValueByBoolean-1501",
            "BTMConfiguredValueByEnum-1923": "#/components/schemas/BTMConfiguredValueByEnum-1923"
          }
        }
      },
      "BTMConfiguredValueByBoolean-1501": {
        "type": "object",
        "allOf": [
          {
            "$ref": "#/components/schemas/BTMConfiguredValue-1341"
          },
          {
            "type": "object",
            "properties": {
              "booleanValue": {
                "type": "boolean"
              }
            }
          }
        ]
      },
      "BTMConfiguredValueByEnum-1923": {
        "type": "object",
        "allOf": [
          {
            "$ref": "#/components/schemas/BTMConfiguredValue-1341"
          },
          {
            "type": "object",
            "properties": {
              "namespace": {
                "type": "string"
              },
              "enumValue": {
                "type": "string"
              },
              "enumName": {
                "type": "string"
              }
            }
          }
        ]
      },
      "BTMDatabaseParameter-2229": {
        "type": "object",
        "allOf": [
          {
            "$ref": "#/components/schemas/BTMParameter-1"
          },
          {
            "type": "object",
            "properties": {
              "databaseId": {
                "type": "string"
              }
            }
          }
        ]
      },
      "BTMFeature-134": {
        "type": "object",
        "properties": {
          "btType": {
            "type": "string"
          },
          "featureId": {
            "type": "string"
          },
          "featureType": {
            "type": "string"
          },
          "importMicroversion": {
            "type": "string",
            "writeOnly": true
          },
          "name": {
            "type": "string"
          },
          "namespace": {
            "type": "string"
          },
          "nodeId": {
            "type": "string"
          },
          "returnAfterSubfeatures": {
            "type": "boolean"
          },
          "subFeatures": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/BTMFeature-134"
            }
          },
          "suppressed": {
            "type": "boolean"
          }
        },
        "discriminator": {
          "propertyName": "btType",
          "mapping": {
            "BTMAssemblyFeature-887": "#/components/schemas/BTMAssemblyFeature-887",
            "BTMFeatureInvalid-1031": "#/components/schemas/BTMFeatureInvalid-1031",
            "BTMSketch-151": "#/components/schemas/BTMSketch-151"
          }
        }
      },
      "BTMFeatureInvalid-1031": {
        "type": "object",
        "allOf": [
          {
            "$ref": "#/components/schemas/BTMFeature-134"
          }
        ]
      },
      "BTMFeatureQueryWithOccurrence-157": {
        "type": "object",
        "properties": {
          "btType": {
            "type": "string"
          }
        },
        "discriminator": {
          "propertyName": "btType",
          "mapping": {
            "BTMPartStudioMateConnectorQuery-1324": "#/components/schemas/BTMPartStudioMateConnectorQuery-1324"
          }
        },
        "allOf": [
          {
            "$ref": "#/components/schemas/BTMIndividualQueryWithOccurrenceBase-904"
          },
          {
            "type": "object",
            "properties": {
              "featureIdWithOccurrence": {
                "type": "string"
              },
              "partStudioMateConnectorQuery": {
                "type": "boolean"
              },
              "featureId": {
                "type": "string"
              },
              "queryData": {
                "type": "string"
              }
            }
          }
        ]
      },
      "BTMGeometryMate-1260": {
        "type": "object",
        "allOf": [
          {
            "$ref": "#/components/schemas/BTMAssemblyFeature-887"
          }
        ]
      },
      "BTMImport-136": {
        "type": "object",
        "properties": {
          "elementImport": {
            "type": "boolean"
          },
          "importMicroversion": {
            "type": "string",
            "writeOnly": true
          },
          "importedExternalDocumentId": {
            "type": "string"
          },
          "namespace": {
            "type": "string"
          },
          "nodeId": {
            "type": "string"
          },
          "path": {
            "type": "string"
          },
          "version": {
            "type": "string"
          }
        }
      },
      "BTMInContextQuery-2254": {
        "type": "object",
        "allOf": [
          {
            "$ref": "#/components/schemas/BTMIndividualQueryBase-139"
          },
          {
            "type": "object",
            "properties": {
              "path": {
                "type": "array",
                "items": {
                  "type": "string"
                }
              }
            }
          }
        ]
      },
      "BTMIndividualCoEdgeQuery-1332": {
        "type": "object",
        "allOf": [
          {
            "$ref": "#/components/schemas/BTMIndividualQuery-138"
          },
          {
            "type": "object",
            "properties": {
              "faceQuery": {
                "$ref": "#/components/schemas/BTMIndividualQuery-138"
              },
              "edgeQuery": {
                "$ref": "#/components/schemas/BTMIndividualQuery-138"
              }
            }
          }
        ]
      },
      "BTMIndividualCreatedByQuery-137": {
        "type": "object",
        "allOf": [
          {
            "$ref": "#/components/schemas/BTMIndividualQuery-138"
          },
          {
            "type": "object",
            "properties": {
              "featureId": {
                "type": "string"
              },
              "bodyType": {
                "type": "string",
                "enum": [
                  "SOLID",
                  "SHEET",
                  "WIRE",
                  "POINT",
                  "MATE_CONNECTOR",
                  "COMPOSITE",
                  "UNKNOWN"
                ]
              },
              "entityType": {
                "type": "string",
                "enum": [
                  "VERTEX",
                  "EDGE",
                  "FACE",
                  "BODY",
                  "DEGENERATE_EDGE",
                  "UNKNOWN"
                ]
              },
              "filterConstruction": {
                "type": "boolean"
              }
            }
          }
        ]
      },
      "BTMIndividualOccurrenceQuery-626": {
        "type": "object",
        "allOf": [
          {
            "$ref": "#/components/schemas/BTMIndividualQueryWithOccurrenceBase-904"
          }
        ]
      },
      "BTMIndividualQuery-138": {
        "type": "object",
        "properties": {
          "btType": {
            "type": "string"
          }
        },
        "discriminator": {
          "propertyName": "btType",
          "mapping": {
            "BTMIndividualCoEdgeQuery-1332": "#/components/schemas/BTMIndividualCoEdgeQuery-1332",
            "BTMIndividualCreatedByQuery-137": "#/components/schemas/BTMIndividualCreatedByQuery-137",
            "BTMIndividualSketchRegionQuery-140": "#/components/schemas/BTMIndividualSketchRegionQuery-140",
            "BTMIndividualSketchUniqueVerticesQuery-1472": "#/components/schemas/BTMIndividualSketchUniqueVerticesQuery-1472"
          }
        },
        "allOf": [
          {
            "$ref": "#/components/schemas/BTMIndividualQueryBase-139"
          },
          {
            "type": "object",
            "properties": {
              "persistentQuery": {
                "$ref": "#/components/schemas/BTPStatement-269"
              },
              "variableName": {
                "$ref": "#/components/schemas/BTMIndividualQuery-138"
              },
              "queryStatement": {
                "$ref": "#/components/schemas/BTPStatement-269"
              }
            }
          }
        ]
      },
      "BTMIndividualQueryBase-139": {
        "type": "object",
        "properties": {
          "btType": {
            "type": "string"
          },
          "deterministicIdList": {
            "$ref": "#/components/schemas/BTMIndividualQueryBase-139"
          },
          "deterministicIds": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "importMicroversion": {
            "type": "string",
            "writeOnly": true
          },
          "nodeId": {
            "type": "string"
          },
          "query": {
            "$ref": "#/components/schemas/BTMIndividualQueryBase-139"
          },
          "queryString": {
            "type": "string"
          }
        },
        "discriminator": {
          "propertyName": "btType",
          "mapping": {
            "BTMInContextQuery-2254": "#/components/schemas/BTMInContextQuery-2254",
            "BTMIndividualQuery-138": "#/components/schemas/BTMIndividualQuery-138",
            "BTMIndividualQueryWithOccurrenceBase-904": "#/components/schemas/BTMIndividualQueryWithOccurrenceBase-904"
          }
        }
      },
      "BTMIndividualQueryWithOccurrence-811": {
        "type": "object",
        "properties": {
          "btType": {
            "type": "string"
          }
        },
        "discriminator": {
          "propertyName": "btType",
          "mapping": {
            "BTMInferenceQueryWithOccurrence-1083": "#/components/schemas/BTMInferenceQueryWithOccurrence-1083"
          }
        },
        "allOf": [
          {
            "$ref": "#/components/schemas/BTMIndividualQueryWithOccurrenceBase-904"
          },
          {
            "type": "object",
            "properties": {
              "entityQuery": {
                "type": "string"
              }
            }
          }
        ]
      },
      "BTMIndividualQueryWithOccurrenceBase-904": {
        "type": "object",
        "properties": {
          "btType": {
            "type": "string"
          },
          "deterministicIdList": {
            "$ref": "#/components/schemas/BTMIndividualQueryBase-139"
          },
          "deterministicIds": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "importMicroversion": {
            "type": "string",
            "writeOnly": true
          },
          "nodeId": {
            "type": "string"
          },
          "path": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "query": {
            "$ref": "#/components/schemas/BTMIndividualQueryBase-139"
          },
          "queryString": {
            "type": "string"
          }
        },
        "discriminator": {
          "propertyName": "btType",
          "mapping": {
            "BTMFeatureQueryWithOccurrence-157": "#/components/schemas/BTMFeatureQueryWithOccurrence-157",
            "BTMIndividualOccurrenceQuery-626": "#/components/schemas/BTMIndividualOccurrenceQuery-626",
            "BTMIndividualQueryWithOccurrence-811": "#/components/schemas/BTMIndividualQueryWithOccurrence-811"
          }
        }
      },
      "BTMIndividualSketchRegionQuery-140": {
        "type": "object",
        "allOf": [
          {
            "$ref": "#/components/schemas/BTMIndividualQuery-138"
          },
          {
            "type": "object",
            "properties": {
              "featureId": {
                "type": "string"
              },
              "filterInnerLoops": {
                "type": "boolean"
              }
            }
          }
        ]
      },
      "BTMIndividualSketchUniqueVerticesQuery-1472": {
        "type": "object",
        "allOf": [
          {
            "$ref": "#/components/schemas/BTMIndividualQuery-138"
          },
          {
            "type": "object",
            "properties": {
              "featureId": {
                "type": "string"
              }
            }
          }
        ]
      },
      "BTMInferenceQueryWithOccurrence-1083": {
        "type": "object",
        "allOf": [
          {
            "$ref": "#/components/schemas/BTMIndividualQueryWithOccurrence-811"
          },
          {
            "type": "object",
            "properties": {
              "secondDeterministicId": {
                "type": "string"
              },
              "secondEntityQuery": {
                "type": "string"
              },
              "inferenceType": {
                "type": "string",
                "enum": [
                  "PART_ORIGIN",
                  "POINT",
                  "CENTROID",
                  "CENTER",
                  "MID_POINT",
                  "TOP_AXIS_POINT",
                  "MID_AXIS_POINT",
                  "BOTTOM_AXIS_POINT",
                  "ORIGIN_X",
                  "ORIGIN_Y",
                  "ORIGIN_Z",
                  "LOOP_CENTER",
                  "UNKNOWN"
                ]
              }
            }
          }
        ]
      },
      "BTMMate-64": {
        "type": "object",
        "allOf": [
          {
            "$ref": "#/components/schemas/BTMAssemblyFeature-887"
          },
          {
            "type": "object",
            "properties": {
              "mateConnectorQueryList": {
                "$ref": "#/components/schemas/BTMParameterQueryWithOccurrenceList-67"
              },
              "primaryAxisAlignment": {
                "type": "boolean"
              },
              "secondaryAxisAlignment": {
                "type": "string",
                "enum": [
                  "PLUS_X",
                  "PLUS_Y",
                  "MINUS_X",
                  "MINUS_Y",
                  "UNKNOWN"
                ]
              },
              "mateOffset": {
                "$ref": "#/components/schemas/BTVector3d-389"
              },
              "mateConnectors": {
                "type": "array",
                "items": {
                  "$ref": "#/components/schemas/BTMMateConnector-66"
                }
              }
            }
          }
        ]
      },
      "BTMMateConnector-66": {
        "type": "object",
        "allOf": [
          {
            "$ref": "#/components/schemas/BTMAssemblyFeature-887"
          },
          {
            "type": "object",
            "properties": {
              "savedFeatureType": {
                "type": "string"
              },
              "isHidden": {
                "type": "boolean"
              },
              "implicit": {
                "type": "boolean"
              }
            }
          }
        ]
      },
      "BTMMateGroup-65": {
        "type": "object",
        "allOf": [
          {
            "$ref": "#/components/schemas/BTMAssemblyFeature-887"
          }
        ]
      },
      "BTMMateRelation-1412": {
        "type": "object",
        "allOf": [
          {
            "$ref": "#/components/schemas/BTMAssemblyFeature-887"
          }
        ]
      },
      "BTMNonGeometricItem-1864": {
        "type": "object",
        "allOf": [
          {
            "$ref": "#/components/schemas/BTMAssemblyFeature-887"
          },
          {
            "type": "object",
            "properties": {
              "itemDefinitionId": {
                "type": "string"
              }
            }
          }
        ]
      },
      "BTMParameter-1": {
        "type": "object",
        "properties": {
          "btType": {
            "type": "string"
          },
          "importMicroversion": {
            "type": "string",
            "writeOnly": true
          },
          "nodeId": {
            "type": "string"
          },
          "parameterId": {
            "type": "string"
          }
        },
        "discriminator": {
          "propertyName": "btType",
          "mapping": {
            "BTMDatabaseParameter-2229": "#/components/schemas/BTMDatabaseParameter-2229",
            "BTMParameterAppearance-627": "#/components/schemas/BTMParameterAppearance-627",
            "BTMParameterArray-2025": "#/components/schemas/BTMParameterArray-2025",
            "BTMParameterBlobReference-1679": "#/components/schemas/BTMParameterBlobReference-1679",
            "BTMParameterBoolean-144": "#/components/schemas/BTMParameterBoolean-144",
            "BTMParameterConfigured-2222": "#/components/schemas/BTMParameterConfigured-2222",
            "BTMParameterDerived-864": "#/components/schemas/BTMParameterDerived-864",
            "BTMParameterEnum-145": "#/components/schemas/BTMParameterEnum-145",
            "BTMParameterFeatureList-1749": "#/components/schemas/BTMParameterFeatureList-1749",
            "BTMParameterForeignId-146": "#/components/schemas/BTMParameterForeignId-146",
            "BTMParameterInvalid-1664": "#/components/schemas/BTMParameterInvalid-1664",
            "BTMParameterLookupTablePath-1419": "#/components/schemas/BTMParameterLookupTablePath-1419",
            "BTMParameterMaterial-1388": "#/components/schemas/BTMParameterMaterial-1388",
            "BTMParameterQuantity-147": "#/components/schemas/BTMParameterQuantity-147",
            "BTMParameterQueryList-148": "#/components/schemas/BTMParameterQueryList-148",
            "BTMParameterQueryWithOccurrenceList-67": "#/components/schemas/BTMParameterQueryWithOccurrenceList-67",
            "BTMParameterReference-2434": "#/components/schemas/BTMParameterReference-2434",
            "BTMParameterString-149": "#/components/schemas/BTMParameterString-149"
          }
        }
      },
      "BTMParameterAppearance-627": {
        "type": "object",
        "allOf": [
          {
            "$ref": "#/components/schemas/BTMParameter-1"
          },
          {
            "type": "object",
            "properties": {
              "appearance": {
                "$ref": "#/components/schemas/BTGraphicsAppearance-1152"
              }
            }
          }
        ]
      },
      "BTMParameterArray-2025": {
        "type": "object",
        "allOf": [
          {
            "$ref": "#/components/schemas/BTMParameter-1"
          },
          {
            "type": "object",
            "properties": {
              "items": {
                "type": "array",
                "items": {
                  "$ref": "#/components/schemas/BTMArrayParameterItem-1843"
                }
              }
            }
          }
        ]
      },
      "BTMParameterBlobReference-1679": {
        "type": "object",
        "allOf": [
          {
            "$ref": "#/components/schemas/BTMParameter-1"
          },
          {
            "type": "object",
            "properties": {
              "namespace": {
                "type": "string"
              },
              "blobImport": {
                "$ref": "#/components/schemas/BTMImport-136"
              }
            }
          }
        ]
      },
      "BTMParameterBoolean-144": {
        "type": "object",
        "allOf": [
          {
            "$ref": "#/components/schemas/BTMParameter-1"
          },
          {
            "type": "object",
            "properties": {
              "value": {
                "type": "boolean"
              }
            }
          }
        ]
      },
      "BTMParameterConfigured-2222": {
        "type": "object",
        "allOf": [
          {
            "$ref": "#/components/schemas/BTMParameter-1"
          },
          {
            "type": "object",
            "properties": {
              "valuesFieldIndex": {
                "type": "integer",
                "format": "int32"
              },
              "configurationParameterIdFieldIndex": {
                "type": "integer",
                "format": "int32"
              },
              "configurationParameterId": {
                "type": "string"
              },
              "values": {
                "type": "array",
                "items": {
                  "$ref": "#/components/schemas/BTMConfiguredValue-1341"
                }
              }
            }
          }
        ]
      },
      "BTMParameterDerived-864": {
        "type": "object",
        "allOf": [
          {
            "$ref": "#/components/schemas/BTMParameter-1"
          },
          {
            "type": "object",
            "properties": {
              "moduleId": {
                "$ref": "#/components/schemas/BTPModuleId-235"
              },
              "namespace": {
                "type": "string"
              },
              "imports": {
                "type": "array",
                "items": {
                  "$ref": "#/components/schemas/BTMImport-136"
                }
              }
            }
          }
        ]
      },
      "BTMParameterEnum-145": {
        "type": "object",
        "allOf": [
          {
[...]
