# coding: utf-8

"""
    Onshape REST API

    The Onshape REST API consumed by all clients.  # noqa: E501

    OpenAPI spec version: 1.96
    Contact: api-support@onshape.zendesk.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class BTThumbnailInfo(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'sizes': 'list[BTThumbnailSizeInfo]',
        'secondary_sizes': 'list[list[BTThumbnailSizeInfo]]',
        'id': 'str',
        'href': 'str'
    }

    attribute_map = {
        'sizes': 'sizes',
        'secondary_sizes': 'secondarySizes',
        'id': 'id',
        'href': 'href'
    }

    def __init__(self, sizes=None, secondary_sizes=None, id=None, href=None):  # noqa: E501
        """BTThumbnailInfo - a model defined in OpenAPI"""  # noqa: E501

        self._sizes = None
        self._secondary_sizes = None
        self._id = None
        self._href = None
        self.discriminator = None

        if sizes is not None:
            self.sizes = sizes
        if secondary_sizes is not None:
            self.secondary_sizes = secondary_sizes
        if id is not None:
            self.id = id
        if href is not None:
            self.href = href

    @property
    def sizes(self):
        """Gets the sizes of this BTThumbnailInfo.  # noqa: E501


        :return: The sizes of this BTThumbnailInfo.  # noqa: E501
        :rtype: list[BTThumbnailSizeInfo]
        """
        return self._sizes

    @sizes.setter
    def sizes(self, sizes):
        """Sets the sizes of this BTThumbnailInfo.


        :param sizes: The sizes of this BTThumbnailInfo.  # noqa: E501
        :type: list[BTThumbnailSizeInfo]
        """

        self._sizes = sizes

    @property
    def secondary_sizes(self):
        """Gets the secondary_sizes of this BTThumbnailInfo.  # noqa: E501


        :return: The secondary_sizes of this BTThumbnailInfo.  # noqa: E501
        :rtype: list[list[BTThumbnailSizeInfo]]
        """
        return self._secondary_sizes

    @secondary_sizes.setter
    def secondary_sizes(self, secondary_sizes):
        """Sets the secondary_sizes of this BTThumbnailInfo.


        :param secondary_sizes: The secondary_sizes of this BTThumbnailInfo.  # noqa: E501
        :type: list[list[BTThumbnailSizeInfo]]
        """

        self._secondary_sizes = secondary_sizes

    @property
    def id(self):
        """Gets the id of this BTThumbnailInfo.  # noqa: E501


        :return: The id of this BTThumbnailInfo.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this BTThumbnailInfo.


        :param id: The id of this BTThumbnailInfo.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def href(self):
        """Gets the href of this BTThumbnailInfo.  # noqa: E501


        :return: The href of this BTThumbnailInfo.  # noqa: E501
        :rtype: str
        """
        return self._href

    @href.setter
    def href(self, href):
        """Sets the href of this BTThumbnailInfo.


        :param href: The href of this BTThumbnailInfo.  # noqa: E501
        :type: str
        """

        self._href = href

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, BTThumbnailInfo):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
