# coding: utf-8

"""
    Onshape REST API

    The Onshape REST API consumed by all clients.  # noqa: E501

    The version of the OpenAPI document: 1.106
    Contact: api-support@onshape.zendesk.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class BTMIndividualQueryWithOccurrence(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'entity_query': 'str'
    }

    attribute_map = {
        'entity_query': 'entityQuery'
    }

    discriminator_value_class_map = {
        'BTMInferenceQueryWithOccurrence': 'BTMInferenceQueryWithOccurrence'
    }

    def __init__(self, entity_query=None):  # noqa: E501
        """BTMIndividualQueryWithOccurrence - a model defined in OpenAPI"""  # noqa: E501

        self._entity_query = None
        self.discriminator = 'bt_type'

        if entity_query is not None:
            self.entity_query = entity_query

    @property
    def entity_query(self):
        """Gets the entity_query of this BTMIndividualQueryWithOccurrence.  # noqa: E501


        :return: The entity_query of this BTMIndividualQueryWithOccurrence.  # noqa: E501
        :rtype: str
        """
        return self._entity_query

    @entity_query.setter
    def entity_query(self, entity_query):
        """Sets the entity_query of this BTMIndividualQueryWithOccurrence.


        :param entity_query: The entity_query of this BTMIndividualQueryWithOccurrence.  # noqa: E501
        :type: str
        """

        self._entity_query = entity_query

    def get_real_child_model(self, data):
        """Returns the real base class specified by the discriminator"""
        discriminator_key = self.attribute_map[self.discriminator]
        discriminator_value = data[discriminator_key]
        return self.discriminator_value_class_map.get(discriminator_value)

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, BTMIndividualQueryWithOccurrence):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
