# coding: utf-8

"""
    Onshape REST API

    The Onshape REST API consumed by all clients.  # noqa: E501

    The version of the OpenAPI document: 1.106.24625.56a35b263da3
    Contact: api-support@onshape.zendesk.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import
import re  # noqa: F401
import sys  # noqa: F401

import six  # noqa: F401

from onshape_client.oas.model_utils import (  # noqa: F401
    ModelComposed,
    ModelNormal,
    ModelSimple,
    date,
    datetime,
    file_type,
    int,
    none_type,
    str,
    validate_get_composed_info,
)
try:
    from onshape_client.oas.models import btp_annotation
except ImportError:
    btp_annotation = sys.modules['onshape_client.oas.models.btp_annotation']
try:
    from onshape_client.oas.models import btp_space
except ImportError:
    btp_space = sys.modules['onshape_client.oas.models.btp_space']
try:
    from onshape_client.oas.models import btp_statement_assignment
except ImportError:
    btp_statement_assignment = sys.modules['onshape_client.oas.models.btp_statement_assignment']
try:
    from onshape_client.oas.models import btp_statement_block
except ImportError:
    btp_statement_block = sys.modules['onshape_client.oas.models.btp_statement_block']
try:
    from onshape_client.oas.models import btp_statement_break
except ImportError:
    btp_statement_break = sys.modules['onshape_client.oas.models.btp_statement_break']
try:
    from onshape_client.oas.models import btp_statement_compressed_query
except ImportError:
    btp_statement_compressed_query = sys.modules['onshape_client.oas.models.btp_statement_compressed_query']
try:
    from onshape_client.oas.models import btp_statement_constant_declaration
except ImportError:
    btp_statement_constant_declaration = sys.modules['onshape_client.oas.models.btp_statement_constant_declaration']
try:
    from onshape_client.oas.models import btp_statement_continue
except ImportError:
    btp_statement_continue = sys.modules['onshape_client.oas.models.btp_statement_continue']
try:
    from onshape_client.oas.models import btp_statement_expression
except ImportError:
    btp_statement_expression = sys.modules['onshape_client.oas.models.btp_statement_expression']
try:
    from onshape_client.oas.models import btp_statement_if
except ImportError:
    btp_statement_if = sys.modules['onshape_client.oas.models.btp_statement_if']
try:
    from onshape_client.oas.models import btp_statement_loop
except ImportError:
    btp_statement_loop = sys.modules['onshape_client.oas.models.btp_statement_loop']
try:
    from onshape_client.oas.models import btp_statement_return
except ImportError:
    btp_statement_return = sys.modules['onshape_client.oas.models.btp_statement_return']
try:
    from onshape_client.oas.models import btp_statement_throw
except ImportError:
    btp_statement_throw = sys.modules['onshape_client.oas.models.btp_statement_throw']
try:
    from onshape_client.oas.models import btp_statement_try
except ImportError:
    btp_statement_try = sys.modules['onshape_client.oas.models.btp_statement_try']
try:
    from onshape_client.oas.models import btp_statement_var_declaration
except ImportError:
    btp_statement_var_declaration = sys.modules['onshape_client.oas.models.btp_statement_var_declaration']


class BTPStatement(ModelNormal):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    Attributes:
      allowed_values (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          with a capitalized key describing the allowed value and an allowed
          value. These dicts store the allowed enum values.
      attribute_map (dict): The key is attribute name
          and the value is json key in definition.
      discriminator_value_class_map (dict): A dict to go from the discriminator
          variable value to the discriminator class name.
      openapi_types (dict): The key is attribute name
          and the value is attribute type.
      validations (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          that stores validations for max_length, min_length, max_items,
          min_items, exclusive_maximum, inclusive_maximum, exclusive_minimum,
          inclusive_minimum, and regex.
      additional_properties_type (tuple): A tuple of classes accepted
          as additional properties values.
    """

    allowed_values = {
        ('documentation_type',): {
            'FUNCTION': "FUNCTION",
            'PREDICATE': "PREDICATE",
            'CONSTANT': "CONSTANT",
            'ENUM': "ENUM",
            'USER_TYPE': "USER_TYPE",
            'FEATURE_DEFINITION': "FEATURE_DEFINITION",
            'FILE_HEADER': "FILE_HEADER",
            'UNDOCUMENTABLE': "UNDOCUMENTABLE",
            'UNKNOWN': "UNKNOWN",
        },
    }

    @staticmethod
    @property
    def openapi_types():
        return {
        'annotation': (btp_annotation.BTPAnnotation,),  # noqa: E501
        'short_descriptor': (str,),  # noqa: E501
        'atomic': (bool,),  # noqa: E501
        'start_source_location': (int,),  # noqa: E501
        'end_source_location': (int,),  # noqa: E501
        'documentation_type': (str,),  # noqa: E501
        'space_before': (btp_space.BTPSpace,),  # noqa: E501
        'space_after': (btp_space.BTPSpace,),  # noqa: E501
        'space_default': (bool,),  # noqa: E501
        'node_id': (str,),  # noqa: E501
        'bt_type': (str,),  # noqa: E501
    }

    validations = {
    }

    additional_properties_type = None

    @staticmethod
    def discriminator():
        return {
            'bt_type': {
                'BTPStatementLoop': btp_statement_loop.BTPStatementLoop,
                'BTPStatementReturn': btp_statement_return.BTPStatementReturn,
                'BTPStatementThrow': btp_statement_throw.BTPStatementThrow,
                'BTPStatementCompressedQuery': btp_statement_compressed_query.BTPStatementCompressedQuery,
                'BTPStatementContinue': btp_statement_continue.BTPStatementContinue,
                'BTPStatementBreak': btp_statement_break.BTPStatementBreak,
                'BTPStatementIf': btp_statement_if.BTPStatementIf,
                'BTPStatementAssignment': btp_statement_assignment.BTPStatementAssignment,
                'BTPStatementVarDeclaration': btp_statement_var_declaration.BTPStatementVarDeclaration,
                'BTPStatementBlock': btp_statement_block.BTPStatementBlock,
                'BTPStatementConstantDeclaration': btp_statement_constant_declaration.BTPStatementConstantDeclaration,
                'BTPStatementTry': btp_statement_try.BTPStatementTry,
                'BTPStatementExpression': btp_statement_expression.BTPStatementExpression,
            },
        }


    attribute_map = {
        'annotation': 'annotation',  # noqa: E501
        'short_descriptor': 'shortDescriptor',  # noqa: E501
        'atomic': 'atomic',  # noqa: E501
        'start_source_location': 'startSourceLocation',  # noqa: E501
        'end_source_location': 'endSourceLocation',  # noqa: E501
        'documentation_type': 'documentationType',  # noqa: E501
        'space_before': 'spaceBefore',  # noqa: E501
        'space_after': 'spaceAfter',  # noqa: E501
        'space_default': 'spaceDefault',  # noqa: E501
        'node_id': 'nodeId',  # noqa: E501
        'bt_type': 'btType',  # noqa: E501
    }

    @staticmethod
    def _composed_schemas():
        return None

    required_properties = set([
        '_data_store',
        '_check_type',
        '_from_server',
        '_path_to_item',
        '_configuration',
    ])

    def __init__(self, _check_type=True, _from_server=False, _path_to_item=(), _configuration=None, **kwargs):  # noqa: E501
        """btp_statement.BTPStatement - a model defined in OpenAPI


        Keyword Args:
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _from_server (bool): True if the data is from the server
                                False if the data is from the client (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            annotation (btp_annotation.BTPAnnotation): [optional]  # noqa: E501
            short_descriptor (str): [optional]  # noqa: E501
            atomic (bool): [optional]  # noqa: E501
            start_source_location (int): [optional]  # noqa: E501
            end_source_location (int): [optional]  # noqa: E501
            documentation_type (str): [optional]  # noqa: E501
            space_before (btp_space.BTPSpace): [optional]  # noqa: E501
            space_after (btp_space.BTPSpace): [optional]  # noqa: E501
            space_default (bool): [optional]  # noqa: E501
            node_id (str): [optional]  # noqa: E501
            bt_type (str): [optional]  # noqa: E501
        """

        self._data_store = {}
        self._check_type = _check_type
        self._from_server = _from_server
        self._path_to_item = _path_to_item
        self._configuration = _configuration

        for var_name, var_value in six.iteritems(kwargs):
            setattr(self, var_name, var_value)

    @classmethod
    def get_discriminator_class(cls, from_server, data):
        """Returns the child class specified by the discriminator"""
        discriminator = cls.discriminator()
        discr_propertyname_py = list(discriminator.keys())[0]
        discr_propertyname_js = cls.attribute_map[discr_propertyname_py]
        if from_server:
            class_name = data[discr_propertyname_js]
        else:
            class_name = data[discr_propertyname_py]
        class_name_to_discr_class = discriminator[discr_propertyname_py]
        return class_name_to_discr_class.get(class_name)
