openapi: 3.0.1
info:
  contact:
    email: api-support@onshape.zendesk.com
  description: The Onshape REST API consumed by all clients.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Onshape REST API
  version: "1.111"
  x-logo:
    backgroundColor: '#ffffff'
    altText: Onshape
    href: https://www.onshape.com/
    url: http://localhost.dev.onshape.com:8084/images/onshape_logo_medium.png
servers:
- description: Production
  url: https://cad.onshape.com
tags:
- description: Manage application settings.
  name: Applications
- description: Modify and access account information.
  name: Accounts
- description: Save and manage application state.
  name: App Elements
- description: Access and manipulate assembly elements.
  name: Assemblies
- description: Access billing plans for clients.
  name: Billing
- description: Save and access Blob Elements.
  name: BlobElements
- description: Access company information.
  name: Companies
- description: Manage documents.
  name: Documents
- description: Access drawing translations.
  name: Drawings
- description: Access and manipulate Elements.
  name: Elements
- description: Access and write to Feature Studio Elements.
  name: FeatureStudios
- description: Access Folders.
  name: Folders
- description: Manipulate and access metadata.
  name: Metadata
- description: Endpoints for getting the OpenAPI specification for the Onshape API.
  name: OpenAPI
- description: Get details about specific parts.
  name: Parts
- description: Modify, change, and get PartStudios.
  name: PartStudios
- description: Manage Release Management workflows.
  name: ReleaseManagement
- description: Access revisions.
  name: Revisions
- description: Access team details.
  name: Teams
- description: Create and manage translations.
  name: Translations
- description: Get details about users.
  name: Users
- description: Example of API version management.
  name: Versions
- description: Create and manage webhooks.
  name: Webhooks
- description: Access Release Management workflows.
  name: Workflow
paths:
  /api/accounts/plans/{planId}/purchases:
    get:
      deprecated: false
      operationId: getPlanPurchases
      summary: Get Plan Purchases
      tags:
      - Accounts
      x-BTVisibility: PRODUCTION
  /api/accounts/purchases:
    get:
      deprecated: false
      operationId: getPurchases
      summary: Get User's Appstore Purchases.
      tags:
      - Accounts
      x-BTVisibility: PRODUCTION
  /api/accounts/purchases/{pid}/consume:
    post:
      deprecated: false
      operationId: consumePurchase
      security:
      - OAuth2:
        - OAuth2Purchase
      summary: Mark Purchase Consumed For User
      tags:
      - Accounts
      x-BTVisibility: PRODUCTION
  /api/accounts/{aid}/purchases/{pid}:
    delete:
      deprecated: false
      operationId: cancelPurchaseNew
      security:
      - OAuth2:
        - OAuth2Purchase
      summary: Cancel Recurring Subscription
      tags:
      - Accounts
      x-BTVisibility: PRODUCTION
  /api/appelements/d/{did}/w/{wid}:
    post:
      deprecated: false
      operationId: createElement
      security:
      - OAuth2:
        - OAuth2Write
      summary: Create Element.
      tags:
      - App Elements
      x-BTVisibility: PRODUCTION
  /api/appelements/d/{did}/w/{wid}/e/{eid}/transactions:
    post:
      deprecated: false
      operationId: startTransaction
      security:
      - OAuth2:
        - OAuth2Write
      summary: Start Transaction
      tags:
      - App Elements
      x-BTVisibility: PRODUCTION
  /api/appelements/d/{did}/w/{wid}/e/{eid}/transactions/{tid}:
    post:
      deprecated: false
      operationId: commitTransaction
      security:
      - OAuth2:
        - OAuth2Write
      summary: Commit Transaction
      tags:
      - App Elements
      x-BTVisibility: PRODUCTION
  /api/appelements/d/{did}/{wvm}/{wvmid}/e/{eid}/associativedata:
    delete:
      deprecated: false
      operationId: deleteAssociativeData
      security:
      - OAuth2:
        - OAuth2Write
      x-BTVisibility: PRODUCTION
    get:
      deprecated: false
      operationId: getAssociativeData
      security:
      - OAuth2:
        - OAuth2Read
      x-BTVisibility: PRODUCTION
    post:
      deprecated: false
      operationId: postAssociativeData
      security:
      - OAuth2:
        - OAuth2Read
        - OAuth2Write
      x-BTVisibility: PRODUCTION
  /api/appelements/d/{did}/{wvm}/{wvmid}/e/{eid}/content:
    get:
      deprecated: false
      operationId: getSubElementContent
      security:
      - OAuth2:
        - OAuth2Read
      summary: Get Content
      tags:
      - App Elements
      x-BTVisibility: PRODUCTION
    post:
      deprecated: false
      operationId: updateAppElement
      security:
      - OAuth2:
        - OAuth2Read
        - OAuth2Write
      summary: Update Element
      tags:
      - App Elements
      x-BTVisibility: PRODUCTION
  /api/appelements/d/{did}/{wvm}/{wvmid}/e/{eid}/content/history:
    get:
      deprecated: false
      operationId: getAppElementHistory
      security:
      - OAuth2:
        - OAuth2Read
      summary: Get History
      tags:
      - App Elements
      x-BTVisibility: PRODUCTION
  /api/appelements/d/{did}/{wvm}/{wvmid}/e/{eid}/content/ids:
    get:
      deprecated: false
      operationId: getSubelementIds
      security:
      - OAuth2:
        - OAuth2Read
      summary: Get Sub-element IDs
      tags:
      - App Elements
      x-BTVisibility: PRODUCTION
  /api/appelements/d/{did}/{wvm}/{wvmid}/e/{eid}/content/subelements/{sid}:
    delete:
      deprecated: false
      operationId: deleteAppElementContent
      security:
      - OAuth2:
        - OAuth2Write
      summary: Delete a Sub-element
      tags:
      - App Elements
      x-BTVisibility: PRODUCTION
  /api/appelements/d/{did}/{wvm}/{wvmid}/e/{eid}/references:
    post:
      deprecated: false
      operationId: createReference
      security:
      - OAuth2:
        - OAuth2Write
        - OAuth2Read
      summary: Create Reference
      tags:
      - App Elements
      x-BTVisibility: PRODUCTION
  /api/appelements/d/{did}/{wvm}/{wvmid}/e/{eid}/references/{rid}:
    delete:
      deprecated: false
      operationId: deleteReference
      security:
      - OAuth2:
        - OAuth2Write
      summary: Delete Reference
      tags:
      - App Elements
      x-BTVisibility: PRODUCTION
    get:
      deprecated: false
      operationId: resolveReference
      security:
      - OAuth2:
        - OAuth2Read
      summary: Resolve Reference
      tags:
      - App Elements
      x-BTVisibility: PRODUCTION
    post:
      deprecated: false
      operationId: updateReference
      security:
      - OAuth2:
        - OAuth2Write
        - OAuth2Read
      summary: Update Reference
      tags:
      - App Elements
      x-BTVisibility: PRODUCTION
  /api/appelements/d/{did}/{wvm}/{wvmid}/e/{eid}/resolvereferences:
    get:
      deprecated: false
      operationId: resolveReferences
      security:
      - OAuth2:
        - OAuth2Read
      summary: Resolve references.
      tags:
      - App Elements
      x-BTVisibility: PRODUCTION
  /api/applications/clients/{cid}/settings/users/{uid}:
    delete:
      deprecated: false
      operationId: deleteAppSettings
      summary: Delete Application Settings
      tags:
      - Applications
      x-BTVisibility: PRODUCTION
    get:
      deprecated: false
      operationId: getUserAppSettings
      summary: Get User Application Settings
      tags:
      - Applications
      x-BTVisibility: PRODUCTION
    post:
      deprecated: false
      operationId: updateAppSettings
      summary: Update Application Settings
      tags:
      - Applications
      x-BTVisibility: PRODUCTION
  /api/assemblies/d/{did}/e/{eid}/namedViews:
    get:
      deprecated: false
      operationId: getNamedViews
      security:
      - OAuth2:
        - OAuth2Read
      tags:
      - Assemblies
      x-BTVisibility: PRODUCTION
  /api/assemblies/d/{did}/w/{wid}:
    post:
      deprecated: false
      operationId: createAssembly
      security:
      - OAuth2:
        - OAuth2Write
      summary: Create Assembly
      tags:
      - Assemblies
      x-BTVisibility: PRODUCTION
  /api/assemblies/d/{did}/w/{wid}/e/{eid}/bomelement:
    post:
      deprecated: false
      operationId: getOrCreateBillOfMaterialsElement
      security:
      - OAuth2:
        - OAuth2Read
      summary: Get or Create Bill of Materials Element
      tags:
      - Assemblies
      x-BTVisibility: PRODUCTION
  /api/assemblies/d/{did}/w/{wid}/e/{eid}/features/featureid/{fid}:
    delete:
      deprecated: false
      operationId: deleteFeature
      security:
      - OAuth2:
        - OAuth2Write
      summary: Delete Feature
      tags:
      - Assemblies
      x-BTVisibility: PRODUCTION
    post:
      deprecated: false
      operationId: updateFeature
      security:
      - OAuth2:
        - OAuth2Write
      tags:
      - Assemblies
      x-BTVisibility: PRODUCTION
  /api/assemblies/d/{did}/w/{wid}/e/{eid}/instance/nodeid/{nid}:
    delete:
      deprecated: false
      operationId: deleteInstance
      security:
      - OAuth2:
        - OAuth2Write
      summary: Delete assembly instance.
      tags:
      - Assemblies
      x-BTVisibility: PRODUCTION
  /api/assemblies/d/{did}/w/{wid}/e/{eid}/instances:
    post:
      deprecated: false
      operationId: createInstance
      security:
      - OAuth2:
        - OAuth2Read
        - OAuth2Write
      summary: Create assembly instance
      tags:
      - Assemblies
      x-BTVisibility: PRODUCTION
  /api/assemblies/d/{did}/w/{wid}/e/{eid}/occurrencetransforms:
    post:
      deprecated: false
      operationId: transformOccurrences
      security:
      - OAuth2:
        - OAuth2Read
        - OAuth2Write
      summary: Transform assembly occurrences.
      tags:
      - Assemblies
      x-BTVisibility: PRODUCTION
  /api/assemblies/d/{did}/w/{wid}/e/{eid}/transformedinstances:
    post:
      deprecated: false
      operationId: insertTransformedInstances
      security:
      - OAuth2:
        - OAuth2Read
        - OAuth2Write
      summary: Create and transform assembly instances
      tags:
      - Assemblies
      x-BTVisibility: PRODUCTION
  /api/assemblies/d/{did}/w/{wid}/e/{eid}/translationformats:
    get:
      deprecated: false
      operationId: getTranslatorFormats
      summary: Get Translation Formats
      tags:
      - Assemblies
      x-BTVisibility: PRODUCTION
  /api/assemblies/d/{did}/{wvm}/{wvmid}/e/{eid}:
    get:
      deprecated: false
      operationId: getAssemblyDefinition
      security:
      - OAuth2:
        - OAuth2Read
      summary: Assembly Definition.
      tags:
      - Assemblies
      x-BTVisibility: PRODUCTION
  /api/assemblies/d/{did}/{wvm}/{wvmid}/e/{eid}/bom:
    get:
      deprecated: false
      operationId: getBillOfMaterials
      security:
      - OAuth2:
        - OAuth2Read
      summary: Get Bill of Materials
      tags:
      - Assemblies
      x-BTVisibility: PRODUCTION
  /api/assemblies/d/{did}/{wvm}/{wvmid}/e/{eid}/boundingboxes:
    get:
      deprecated: false
      operationId: getAssemblyBoundingBoxes
      security:
      - OAuth2:
        - OAuth2Read
      summary: Bounding Boxes.
      tags:
      - Assemblies
      x-BTVisibility: PRODUCTION
  /api/assemblies/d/{did}/{wvm}/{wvmid}/e/{eid}/features:
    get:
      deprecated: false
      operationId: getFeatures
      security:
      - OAuth2:
        - OAuth2Read
      summary: Get Feature List
      tags:
      - Assemblies
      x-BTVisibility: PRODUCTION
    post:
      deprecated: false
      operationId: addFeature
      security:
      - OAuth2:
        - OAuth2Write
      tags:
      - Assemblies
      x-BTVisibility: PRODUCTION
  /api/assemblies/d/{did}/{wvm}/{wvmid}/e/{eid}/featurespecs:
    get:
      deprecated: false
      operationId: getFeatureSpecs
      security:
      - OAuth2:
        - OAuth2Read
      tags:
      - Assemblies
      x-BTVisibility: PRODUCTION
  /api/assemblies/d/{did}/{wvm}/{wvmid}/e/{eid}/shadedviews:
    get:
      deprecated: false
      operationId: getAssemblyShadedViews
      security:
      - OAuth2:
        - OAuth2Read
      tags:
      - Assemblies
      x-BTVisibility: PRODUCTION
  /api/assemblies/d/{did}/{wv}/{wvid}/e/{eid}/translations:
    post:
      deprecated: false
      operationId: translateFormat
      security:
      - OAuth2:
        - OAuth2Read
      summary: Create Assembly translation.
      tags:
      - Assemblies
      x-BTVisibility: PRODUCTION
  /api/billing/plans/client/{cid}:
    get:
      deprecated: false
      operationId: getClientPlans
      summary: Get billing plans for client.
      tags:
      - Billing
      x-BTVisibility: PRODUCTION
  /api/blobelements/d/{did}/w/{wid}:
    post:
      deprecated: false
      operationId: uploadFileCreateElement
      security:
      - OAuth2:
        - OAuth2Write
      summary: Upload file to new element.
      tags:
      - BlobElements
      x-BTVisibility: PRODUCTION
  /api/blobelements/d/{did}/w/{wid}/e/{eid}:
    get:
      deprecated: false
      operationId: downloadFileWorkspace
      security:
      - OAuth2:
        - OAuth2Read
      summary: Download File From Blob Element.
      tags:
      - BlobElements
      x-BTVisibility: PRODUCTION
    post:
      deprecated: false
      operationId: uploadFileUpdateElement
      security:
      - OAuth2:
        - OAuth2Write
      summary: Update Blob Element.
      tags:
      - BlobElements
      x-BTVisibility: PRODUCTION
  /api/blobelements/d/{did}/w/{wid}/e/{eid}/units:
    post:
      deprecated: false
      operationId: updateUnits
      security:
      - OAuth2:
        - OAuth2Write
      summary: Update Mesh Units.
      tags:
      - BlobElements
      x-BTVisibility: PRODUCTION
  /api/blobelements/d/{did}/{wv}/{wvid}/e/{eid}/translations:
    post:
      deprecated: false
      operationId: createBlobTranslation
      security:
      - OAuth2:
        - OAuth2Read
      summary: Create Translation.
      tags:
      - BlobElements
      x-BTVisibility: PRODUCTION
  /api/companies:
    get:
      deprecated: false
      operationId: findCompany
      summary: Get User companies.
      tags:
      - Companies
      x-BTVisibility: PRODUCTION
  /api/companies/{cid}:
    get:
      deprecated: false
      operationId: getCompany
      summary: Get company.
      tags:
      - Companies
      x-BTVisibility: PRODUCTION
  /api/documents:
    get:
      deprecated: false
      operationId: getDocuments
      security:
      - OAuth2:
        - OAuth2Read
      summary: Get Documents
      tags:
      - Documents
      x-BTVisibility: PRODUCTION
    post:
      deprecated: false
      operationId: createDocument
      security:
      - OAuth2:
        - OAuth2Write
      summary: Create document.
      tags:
      - Documents
      x-BTVisibility: PRODUCTION
  /api/documents/d/{did}/externaldata/{fid}:
    get:
      deprecated: false
      operationId: downloadExternalData
      security:
      - OAuth2:
        - OAuth2Read
      summary: Download External Data
      tags:
      - Documents
      x-BTVisibility: PRODUCTION
  /api/documents/d/{did}/versions:
    get:
      deprecated: false
      operationId: getDocumentVersions
      security:
      - OAuth2:
        - OAuth2Read
      summary: Get Versions
      tags:
      - Documents
      x-BTVisibility: PRODUCTION
    post:
      deprecated: false
      operationId: createVersion
      security:
      - OAuth2:
        - OAuth2Write
      summary: Create Version.
      tags:
      - Documents
      x-BTVisibility: PRODUCTION
  /api/documents/d/{did}/versions/{vid}:
    get:
      deprecated: false
      operationId: getVersion
      security:
      - OAuth2:
        - OAuth2Read
      summary: Get Version
      tags:
      - Documents
      x-BTVisibility: PRODUCTION
  /api/documents/d/{did}/w/{wid}/e/{eid}/latestdocumentreferences:
    post:
      deprecated: false
      operationId: updateExternalReferencesToLatestDocuments
      security:
      - OAuth2:
        - OAuth2Write
      summary: Update External References to Latest
      tags:
      - Documents
      x-BTVisibility: PRODUCTION
  /api/documents/d/{did}/w/{wid}/moveelement:
    post:
      deprecated: false
      operationId: moveElementsToDocument
      security:
      - OAuth2:
        - OAuth2Write
      summary: Move Elements
      tags:
      - Documents
      x-BTVisibility: PRODUCTION
  /api/documents/d/{did}/w/{wid}/syncApplicationElements:
    post:
      deprecated: false
      operationId: syncApplicationElements
      security:
      - OAuth2:
        - OAuth2Write
      summary: Sync Application Elements
      tags:
      - Documents
      x-BTVisibility: PRODUCTION
  /api/documents/d/{did}/workspaces:
    get:
      deprecated: false
      operationId: getDocumentWorkspaces
      security:
      - OAuth2:
        - OAuth2Read
      summary: Get Workspaces
      tags:
      - Documents
      x-BTVisibility: PRODUCTION
    post:
      deprecated: false
      operationId: createWorkspace
      security:
      - OAuth2:
        - OAuth2Write
      summary: Create Workspace
      tags:
      - Documents
      x-BTVisibility: PRODUCTION
  /api/documents/d/{did}/workspaces/{wid}:
    delete:
      deprecated: false
      operationId: deleteWorkspace
      security:
      - OAuth2:
        - OAuth2Delete
      summary: Delete Workspace
      tags:
      - Documents
      x-BTVisibility: PRODUCTION
  /api/documents/d/{did}/{wvm}/{wvmid}/elements:
    get:
      deprecated: false
      operationId: getElementsInDocument
      security:
      - OAuth2:
        - OAuth2Read
      summary: Get a list of elements in the workspace, version, or microversion of
        the document.
      tags:
      - Documents
      x-BTVisibility: PRODUCTION
  /api/documents/d/{did}/{wvm}/{wvmid}/insertables:
    get:
      deprecated: false
      operationId: getInsertables
      security:
      - OAuth2:
        - OAuth2Read
      summary: Insertable List for Document Version.
      tags:
      - Documents
      x-BTVisibility: PRODUCTION
  /api/documents/d/{did}/{wv}/{wvid}/currentmicroversion:
    get:
      deprecated: false
      operationId: getCurrentMicroversion
      security:
      - OAuth2:
        - OAuth2Read
      summary: Get Current Document Microversion
      tags:
      - Documents
      x-BTVisibility: PRODUCTION
  /api/documents/d/{did}/{wv}/{wvid}/e/{eid}/export:
    post:
      deprecated: false
      operationId: export2Json
      security:
      - OAuth2:
        - OAuth2Read
      tags:
      - Documents
      x-BTVisibility: PRODUCTION
  /api/documents/search:
    post:
      deprecated: false
      operationId: search
      security:
      - OAuth2:
        - OAuth2Read
      tags:
      - Documents
      x-BTVisibility: PRODUCTION
  /api/documents/{did}:
    delete:
      deprecated: false
      operationId: deleteDocument
      security:
      - OAuth2:
        - OAuth2Delete
      summary: Delete Document
      tags:
      - Documents
      x-BTVisibility: PRODUCTION
    get:
      deprecated: false
      operationId: getDocument
      security:
      - OAuth2:
        - OAuth2Read
      summary: Get Document
      tags:
      - Documents
      x-BTVisibility: PRODUCTION
    post:
      deprecated: false
      operationId: updateDocumentAttributes
      security:
      - OAuth2:
        - OAuth2Write
      summary: Update Document Attributes.
      tags:
      - Documents
      x-BTVisibility: PRODUCTION
  /api/documents/{did}/acl:
    get:
      deprecated: false
      operationId: getDocumentAcl
      security:
      - OAuth2:
        - OAuth2Read
      summary: Get Access Control List
      tags:
      - Documents
      x-BTVisibility: PRODUCTION
  /api/documents/{did}/permissionset:
    get:
      deprecated: false
      operationId: getDocumentPermissionSet
      security:
      - OAuth2:
        - OAuth2Read
      summary: Get Document Permissions
      tags:
      - Documents
      x-BTVisibility: PRODUCTION
  /api/documents/{did}/share:
    post:
      deprecated: false
      operationId: shareDocument
      security:
      - OAuth2:
        - OAuth2Read
        - OAuth2Share
      summary: Share Document
      tags:
      - Documents
      x-BTVisibility: PRODUCTION
  /api/documents/{did}/share/{eid}:
    delete:
      deprecated: false
      operationId: unShareDocument
      security:
      - OAuth2:
        - OAuth2Read
        - OAuth2Share
      summary: Unshare Document
      tags:
      - Documents
      x-BTVisibility: PRODUCTION
  /api/documents/{did}/w/{wid}/restore/{vm}/{vmid}:
    post:
      deprecated: false
      operationId: restoreFromHistory
      security:
      - OAuth2:
        - OAuth2Write
      summary: Restore version or microversion to workspace.
      tags:
      - Documents
      x-BTVisibility: PRODUCTION
  /api/documents/{did}/workspaces/{wid}/copy:
    post:
      deprecated: false
      operationId: copyWorkspace
      security:
      - OAuth2:
        - OAuth2Write
      summary: Copy Workspace
      tags:
      - Documents
      x-BTVisibility: PRODUCTION
  /api/documents/{did}/workspaces/{wid}/merge:
    post:
      deprecated: false
      operationId: mergeIntoWorkspace
      security:
      - OAuth2:
        - OAuth2Write
      summary: Merge into workspace
      tags:
      - Documents
      x-BTVisibility: PRODUCTION
  /api/drawings/create:
    post:
      deprecated: false
      operationId: createDrawingAppElement
      security:
      - OAuth2:
        - OAuth2Write
      tags:
      - Drawings
      x-BTVisibility: PRODUCTION
  /api/drawings/d/{did}/w/{wid}/e/{eid}/translationformats:
    get:
      deprecated: false
      operationId: getDrawingTranslatorFormats
      tags:
      - Drawings
      x-BTVisibility: PRODUCTION
  /api/drawings/d/{did}/{wv}/{wvid}/e/{eid}/translations:
    post:
      deprecated: false
      operationId: createDrawingTranslation
      security:
      - OAuth2:
        - OAuth2Read
      summary: Create Drawing translation
      tags:
      - Drawings
      x-BTVisibility: PRODUCTION
  /api/elements/copyelement/{did}/workspace/{wid}:
    post:
      deprecated: false
      operationId: copyElementFromSourceDocument
      security:
      - OAuth2:
        - OAuth2Write
      summary: Copy Element
      tags:
      - Elements
      x-BTVisibility: PRODUCTION
  /api/elements/d/{did}/e/{eid}/configurationencodings:
    post:
      deprecated: false
      operationId: encodeConfigurationMap
      security:
      - OAuth2:
        - OAuth2Read
      summary: Encode Configuration
      tags:
      - Elements
      x-BTVisibility: PRODUCTION
  /api/elements/d/{did}/w/{wid}/e/{eid}:
    delete:
      deprecated: false
      operationId: deleteElement
      security:
      - OAuth2:
        - OAuth2Delete
      summary: Delete Element
      tags:
      - Elements
      x-BTVisibility: PRODUCTION
  /api/elements/d/{did}/w/{wid}/e/{eid}/updatereferences:
    post:
      deprecated: false
      operationId: updateReferences
      security:
      - OAuth2:
        - OAuth2Read
        - OAuth2Write
      summary: Update or replace node references
      tags:
      - Elements
      x-BTVisibility: PRODUCTION
  /api/elements/d/{did}/{wvm}/{wvmid}/e/{eid}/configuration:
    get:
      deprecated: false
      operationId: getConfiguration
      security:
      - OAuth2:
        - OAuth2Read
      summary: Get Configuration
      tags:
      - Elements
      x-BTVisibility: PRODUCTION
    post:
      deprecated: false
      operationId: updateConfiguration
      security:
      - OAuth2:
        - OAuth2Write
      summary: Update Configuration
      tags:
      - Elements
      x-BTVisibility: PRODUCTION
  /api/elements/d/{did}/{wvm}/{wvmid}/e/{eid}/configurationencodings/{cid}:
    get:
      deprecated: false
      operationId: decodeConfiguration
      security:
      - OAuth2:
        - OAuth2Read
      summary: Decode Configuration String
      tags:
      - Elements
      x-BTVisibility: PRODUCTION
  /api/elements/translatorFormats/{did}/{wv}/{wvid}/{eid}:
    get:
      deprecated: false
      operationId: getElementTranslatorFormatsByVersionOrWorkspace
      summary: Get Element Translator Formats
      tags:
      - Elements
      x-BTVisibility: PRODUCTION
  /api/featurestudios/d/{did}/w/{wid}:
    post:
      deprecated: false
      operationId: createFeatureStudio
      security:
      - OAuth2:
        - OAuth2Write
      summary: Create Feature Studio
      tags:
      - FeatureStudios
      x-BTVisibility: PRODUCTION
  /api/featurestudios/d/{did}/{wvm}/{wvmid}/e/{eid}:
    get:
      deprecated: false
      operationId: getFeatureStudioContents
      security:
      - OAuth2:
        - OAuth2Read
      summary: Get Feature Studio Contents.
      tags:
      - FeatureStudios
      x-BTVisibility: PRODUCTION
    post:
      deprecated: false
      operationId: updateFeatureStudioContents
      security:
      - OAuth2:
        - OAuth2Write
      summary: Update Feature Studio contents
      tags:
      - FeatureStudios
      x-BTVisibility: PRODUCTION
  /api/featurestudios/d/{did}/{wvm}/{wvmid}/e/{eid}/featurespecs:
    get:
      deprecated: false
      operationId: getFeatureStudioSpecs
      security:
      - OAuth2:
        - OAuth2Read
      summary: Get Feature Studio Specs
      tags:
      - FeatureStudios
      x-BTVisibility: PRODUCTION
  /api/folders/{fid}/acl:
    get:
      deprecated: false
      operationId: getFolderAcl
      security:
      - OAuth2:
        - OAuth2Read
      summary: Get Access Control List
      tags:
      - Folders
      x-BTVisibility: PRODUCTION
  /api/folders/{fid}/share:
    post:
      deprecated: false
      operationId: share
      security:
      - OAuth2:
        - OAuth2Read
        - OAuth2Share
      summary: Share Folder
      tags:
      - Folders
      x-BTVisibility: PRODUCTION
  /api/folders/{fid}/share/{eid}:
    delete:
      deprecated: false
      operationId: unShare
      security:
      - OAuth2:
        - OAuth2Read
        - OAuth2Share
      summary: Unshare Folder
      tags:
      - Folders
      x-BTVisibility: PRODUCTION
  /api/insertables/d/{did}/latest:
    get:
      deprecated: false
      operationId: getLatestInDocument
      security:
      - OAuth2:
        - OAuth2Read
      summary: insertables for a document
      x-BTVisibility: PRODUCTION
  /api/metadata/d/{did}/{wvm}/{wvmid}/e:
    get:
      deprecated: false
      operationId: getWMVEsMetadata
      security:
      - OAuth2:
        - OAuth2Read
      tags:
      - Metadata
      x-BTVisibility: PRODUCTION
  /api/metadata/d/{did}/{wvm}/{wvmid}/e/{eid}:
    get:
      deprecated: false
      operationId: getWMVEMetadata
      security:
      - OAuth2:
        - OAuth2Read
      tags:
      - Metadata
      x-BTVisibility: PRODUCTION
    post:
      deprecated: false
      operationId: updateWVEMetadata
      security:
      - OAuth2:
        - OAuth2Write
      tags:
      - Metadata
      x-BTVisibility: PRODUCTION
  /api/metadata/d/{did}/{wvm}/{wvmid}/e/{eid}/p:
    get:
      deprecated: false
      operationId: getWMVEPsMetadata
      security:
      - OAuth2:
        - OAuth2Read
      tags:
      - Metadata
      x-BTVisibility: PRODUCTION
  /api/metadata/d/{did}/{wvm}/{wvmid}/e/{eid}/p/{pid}:
    get:
      deprecated: false
      operationId: getWMVEPMetadata
      security:
      - OAuth2:
        - OAuth2Read
      tags:
      - Metadata
      x-BTVisibility: PRODUCTION
    post:
      deprecated: false
      operationId: updateWVEPMetadata
      security:
      - OAuth2:
        - OAuth2Write
      tags:
      - Metadata
      x-BTVisibility: PRODUCTION
  /api/metadata/d/{did}/{wv}/{wvid}:
    get:
      deprecated: false
      operationId: getWVMetadata
      security:
      - OAuth2:
        - OAuth2Read
      tags:
      - Metadata
      x-BTVisibility: PRODUCTION
    post:
      deprecated: false
      operationId: updateWVMetadata
      security:
      - OAuth2:
        - OAuth2Write
      tags:
      - Metadata
      x-BTVisibility: PRODUCTION
  /api/metadata/standardcontent/d/{did}/v/{vid}/e/{eid}/{otype}/{oid}/p/{pid}:
    get:
      deprecated: false
      operationId: getVEOPStandardContentMetadata
      security:
      - OAuth2:
        - OAuth2Read
      tags:
      - Metadata
      x-BTVisibility: PRODUCTION
    post:
      deprecated: false
      operationId: updateVEOPStandardContentPartMetadata
      security:
      - OAuth2:
        - OAuth2Write
      tags:
      - Metadata
      x-BTVisibility: PRODUCTION
  /api/metadataschema:
    get:
      deprecated: false
      operationId: getMetadataSchema
      security:
      - OAuth2:
        - OAuth2Read
      x-BTVisibility: PRODUCTION
  /api/metadataschema/properties:
    get:
      deprecated: false
      operationId: getProperties
      security:
      - OAuth2:
        - OAuth2Read
      x-BTVisibility: PRODUCTION
  /api/metadataschema/propertyinfo/{pid}:
    get:
      deprecated: false
      operationId: getPropertyInfo
      security:
      - OAuth2:
        - OAuth2Read
      x-BTVisibility: PRODUCTION
  /api/metadataschema/{sid}:
    get:
      deprecated: false
      operationId: getSchema
      security:
      - OAuth2:
        - OAuth2Read
      x-BTVisibility: PRODUCTION
  /api/openapi:
    get:
      deprecated: false
      operationId: getOpenApi
      summary: OpenAPI spec documentation for the Onshape REST API.
      tags:
      - OpenAPI
      x-BTVisibility: PRODUCTION
  /api/parts/d/{did}/{wvm}/{wvmid}:
    get:
      deprecated: false
      operationId: getPartsWMV
      security:
      - OAuth2:
        - OAuth2Read
      summary: Get list of parts
      tags:
      - Parts
      x-BTVisibility: PRODUCTION
  /api/parts/d/{did}/{wvm}/{wvmid}/e/{eid}:
    get:
      deprecated: false
      operationId: getPartsWMVE
      security:
      - OAuth2:
        - OAuth2Read
      summary: Get parts from an element.
      tags:
      - Parts
      x-BTVisibility: PRODUCTION
  /api/parts/d/{did}/{wvm}/{wvmid}/e/{eid}/partid/{partid}/bodydetails:
    get:
      deprecated: false
      operationId: getBodyDetails
      security:
      - OAuth2:
        - OAuth2Read
      tags:
      - Parts
      x-BTVisibility: PRODUCTION
  /api/parts/d/{did}/{wvm}/{wvmid}/e/{eid}/partid/{partid}/boundingboxes:
    get:
      deprecated: false
      operationId: getBoundingBoxes
      security:
      - OAuth2:
        - OAuth2Read
      tags:
      - Parts
      x-BTVisibility: PRODUCTION
  /api/parts/d/{did}/{wvm}/{wvmid}/e/{eid}/partid/{partid}/massproperties:
    get:
      deprecated: false
      operationId: getMassProperties
      security:
      - OAuth2:
        - OAuth2Read
      tags:
      - Parts
      x-BTVisibility: PRODUCTION
  /api/parts/d/{did}/{wvm}/{wvmid}/e/{eid}/partid/{partid}/metadata:
    get:
      deprecated: false
      operationId: getPartMetadata
      security:
      - OAuth2:
        - OAuth2Read
      tags:
      - Parts
      x-BTVisibility: PRODUCTION
    post:
      deprecated: false
      operationId: updatePartMetadata
      security:
      - OAuth2:
        - OAuth2Read
        - OAuth2Write
      tags:
      - Parts
      x-BTVisibility: PRODUCTION
  /api/parts/d/{did}/{wvm}/{wvmid}/e/{eid}/partid/{partid}/parasolid:
    get:
      deprecated: false
      operationId: exportPS
      security:
      - OAuth2:
        - OAuth2Read
      summary: Export Part to Parasolid.
      tags:
      - Parts
      x-BTVisibility: PRODUCTION
  /api/parts/d/{did}/{wvm}/{wvmid}/e/{eid}/partid/{partid}/shadedviews:
    get:
      deprecated: false
      operationId: getShadedViews_1
      security:
      - OAuth2:
        - OAuth2Read
      tags:
      - Parts
      x-BTVisibility: PRODUCTION
  /api/parts/d/{did}/{wvm}/{wvmid}/e/{eid}/partid/{partid}/sheetmetal/bendtable:
    get:
      deprecated: false
      operationId: getBendTable
      security:
      - OAuth2:
        - OAuth2Read
      summary: Get Sheet Metal Bend Table.
      tags:
      - Parts
      x-BTVisibility: PRODUCTION
  /api/parts/d/{did}/{wvm}/{wvmid}/e/{eid}/partid/{partid}/tessellatededges:
    get:
      deprecated: false
      operationId: getEdges
      security:
      - OAuth2:
        - OAuth2Read
      summary: Tessellated Edges
      tags:
      - Parts
      x-BTVisibility: PRODUCTION
  /api/parts/d/{did}/{wvm}/{wvmid}/e/{eid}/partid/{partid}/tessellatedfaces:
    get:
      deprecated: false
      operationId: getFaces_1
      security:
      - OAuth2:
        - OAuth2Read
      summary: Get Tessellated Faces
      tags:
      - Parts
      x-BTVisibility: PRODUCTION
  /api/parts/standardcontent/d/{did}/v/{vid}/e/{eid}/{otype}/{oid}/partid/{partid}/metadata:
    get:
      deprecated: false
      operationId: getStandardContentPartMetadata
      security:
      - OAuth2:
        - OAuth2Read
      tags:
      - Parts
      x-BTVisibility: PRODUCTION
    post:
      deprecated: false
      operationId: updateStandardContentPartMetadata
      security:
      - OAuth2:
        - OAuth2Read
        - OAuth2Write
      tags:
      - Parts
      x-BTVisibility: PRODUCTION
  /api/partstudios/d/{did}/e/{eid}/namedViews:
    get:
      deprecated: false
      operationId: getPartStudioNamedViews
      summary: Get Named Views
      tags:
      - PartStudios
      x-BTVisibility: PRODUCTION
  /api/partstudios/d/{did}/w/{wid}:
    post:
      deprecated: false
      operationId: createPartStudio
      security:
      - OAuth2:
        - OAuth2Write
      summary: Create Part Studio
      tags:
      - PartStudios
      x-BTVisibility: PRODUCTION
  /api/partstudios/d/{did}/w/{wid}/e/{eid}/features/featureid/{fid}:
    delete:
      deprecated: false
      operationId: deletePartStudioFeature
      security:
      - OAuth2:
        - OAuth2Write
      summary: Delete Feature
      tags:
      - PartStudios
      x-BTVisibility: PRODUCTION
    post:
      deprecated: false
      operationId: updatePartStudioFeature
      security:
      - OAuth2:
        - OAuth2Write
      summary: Update Feature
      tags:
      - PartStudios
      x-BTVisibility: PRODUCTION
  /api/partstudios/d/{did}/w/{wid}/e/{eid}/features/rollback:
    post:
      deprecated: false
      operationId: updateRollback
      security:
      - OAuth2:
        - OAuth2Write
      summary: Update Feature Rollback
      tags:
      - PartStudios
      x-BTVisibility: PRODUCTION
  /api/partstudios/d/{did}/w/{wid}/e/{eid}/features/updates:
    post:
      deprecated: false
      operationId: updateFeatures
      security:
      - OAuth2:
        - OAuth2Write
      summary: Update Features
      tags:
      - PartStudios
      x-BTVisibility: PRODUCTION
  /api/partstudios/d/{did}/{wvm}/{wvmid}/e/{eid}/bodydetails:
    get:
      deprecated: false
      operationId: getPartStudioBodyDetails
      security:
      - OAuth2:
        - OAuth2Read
      summary: Array of body information
      tags:
      - PartStudios
      x-BTVisibility: PRODUCTION
  /api/partstudios/d/{did}/{wvm}/{wvmid}/e/{eid}/boundingboxes:
    get:
      deprecated: false
      operationId: getPartStudioBoundingBoxes
      security:
      - OAuth2:
        - OAuth2Read
      summary: Mass properties of parts or a PartStudio.
      tags:
      - PartStudios
      x-BTVisibility: PRODUCTION
  /api/partstudios/d/{did}/{wvm}/{wvmid}/e/{eid}/compare:
    get:
      deprecated: false
      operationId: comparePartStudios
      security:
      - OAuth2:
        - OAuth2Read
      summary: Compare Part Studios
      tags:
      - PartStudios
      x-BTVisibility: PRODUCTION
  /api/partstudios/d/{did}/{wvm}/{wvmid}/e/{eid}/configuration:
    get:
      deprecated: false
      operationId: getPartStudioConfiguration
      security:
      - OAuth2:
        - OAuth2Read
      summary: Get Configuration
      tags:
      - PartStudios
      x-BTVisibility: PRODUCTION
    post:
      deprecated: false
      operationId: updatePartStudioConfiguration
      security:
      - OAuth2:
        - OAuth2Write
      summary: Update Configuration
      tags:
      - PartStudios
      x-BTVisibility: PRODUCTION
  /api/partstudios/d/{did}/{wvm}/{wvmid}/e/{eid}/features:
    get:
      deprecated: false
      operationId: getPartStudioFeatures
      security:
      - OAuth2:
        - OAuth2Read
      summary: Get Feature List
      tags:
      - PartStudios
      x-BTVisibility: PRODUCTION
    post:
      deprecated: false
      operationId: addPartStudioFeature
      security:
      - OAuth2:
        - OAuth2Write
      summary: Add Feature
      tags:
      - PartStudios
      x-BTVisibility: PRODUCTION
  /api/partstudios/d/{did}/{wvm}/{wvmid}/e/{eid}/featurescript:
    post:
      deprecated: false
      operationId: evalFeatureScript
      security:
      - OAuth2:
        - OAuth2Read
      summary: Evaluate FeatureScript
      tags:
      - PartStudios
      x-BTVisibility: PRODUCTION
  /api/partstudios/d/{did}/{wvm}/{wvmid}/e/{eid}/featurespecs:
    get:
      deprecated: false
      operationId: getPartStudioFeatureSpecs
      security:
      - OAuth2:
        - OAuth2Read
      summary: Get Feature Specs
      tags:
      - PartStudios
      x-BTVisibility: PRODUCTION
  /api/partstudios/d/{did}/{wvm}/{wvmid}/e/{eid}/idtranslations:
    post:
      deprecated: false
      operationId: translateIds
      security:
      - OAuth2:
        - OAuth2Read
      summary: Id Translations
      tags:
      - PartStudios
      x-BTVisibility: PRODUCTION
  /api/partstudios/d/{did}/{wvm}/{wvmid}/e/{eid}/massproperties:
    get:
      deprecated: false
      operationId: getPartStudioMassProperties
      security:
      - OAuth2:
        - OAuth2Read
      summary: Mass properties of parts or a PartStudio.
      tags:
      - PartStudios
      x-BTVisibility: PRODUCTION
  /api/partstudios/d/{did}/{wvm}/{wvmid}/e/{eid}/parasolid:
    get:
      deprecated: false
      operationId: exportPS_1
      security:
      - OAuth2:
        - OAuth2Read
      summary: Export Part Studio to Parasolid
      tags:
      - PartStudios
      x-BTVisibility: PRODUCTION
  /api/partstudios/d/{did}/{wvm}/{wvmid}/e/{eid}/shadedviews:
    get:
      deprecated: false
      operationId: getPartStudioShadedViews
      security:
      - OAuth2:
        - OAuth2Read
      summary: Get Shaded Views
      tags:
      - PartStudios
      x-BTVisibility: PRODUCTION
  /api/partstudios/d/{did}/{wvm}/{wvmid}/e/{eid}/sketches:
    get:
      deprecated: false
      operationId: getSketchInfo
      security:
      - OAuth2:
        - OAuth2Read
      x-BTVisibility: PRODUCTION
  /api/partstudios/d/{did}/{wvm}/{wvmid}/e/{eid}/sketches/{sid}/boundingboxes:
    get:
      deprecated: false
      operationId: getSketchBoundingBoxes
      security:
      - OAuth2:
        - OAuth2Read
      x-BTVisibility: PRODUCTION
  /api/partstudios/d/{did}/{wvm}/{wvmid}/e/{eid}/sketches/{sid}/tessellatedentities:
    get:
      deprecated: false
      operationId: getTessellatedEntities
      security:
      - OAuth2:
        - OAuth2Read
      x-BTVisibility: PRODUCTION
  /api/partstudios/d/{did}/{wvm}/{wvmid}/e/{eid}/stl:
    get:
      deprecated: false
      operationId: exportStl_1
      security:
      - OAuth2:
        - OAuth2Read
      summary: Export Part Studio to STL
      tags:
      - PartStudios
      x-BTVisibility: PRODUCTION
  /api/partstudios/d/{did}/{wvm}/{wvmid}/e/{eid}/tessellatededges:
    get:
      deprecated: false
      operationId: getPartStudioTessellatedEdges
      security:
      - OAuth2:
        - OAuth2Read
      summary: Tesselated edges from a PartStudio.
      tags:
      - PartStudios
      x-BTVisibility: PRODUCTION
  /api/partstudios/d/{did}/{wvm}/{wvmid}/e/{eid}/tessellatedfaces:
    get:
      deprecated: false
      operationId: getPartStudioTessellatedFaces
      security:
      - OAuth2:
        - OAuth2Read
      summary: Tesselated faces of the parts in the Part Studio.
      tags:
      - PartStudios
      x-BTVisibility: PRODUCTION
  /api/partstudios/d/{did}/{wv}/{wvid}/e/{eid}/translations:
    post:
      deprecated: false
      operationId: createPartStudioTranslation
      security:
      - OAuth2:
        - OAuth2Read
      summary: Create Part Studio translation
      tags:
      - PartStudios
      x-BTVisibility: PRODUCTION
  /api/releasepackages/companyreleaseworkflow:
    get:
      deprecated: false
      operationId: getCompanyReleaseWorkflow
      security:
      - OAuth2:
        - OAuth2Read
      tags:
      - ReleaseManagement
      x-BTVisibility: PRODUCTION
  /api/releasepackages/obsoletion/{wfid}:
    post:
      deprecated: false
      operationId: createObsoletionPackage
      security:
      - OAuth2:
        - OAuth2Write
      tags:
      - ReleaseManagement
      x-BTVisibility: PRODUCTION
  /api/releasepackages/release/{wfid}:
    post:
      deprecated: false
      operationId: createReleasePackage
      security:
      - OAuth2:
        - OAuth2Write
      tags:
      - ReleaseManagement
      x-BTVisibility: PRODUCTION
  /api/releasepackages/{rpid}:
    get:
      deprecated: false
      operationId: getReleasePackage
      security:
      - OAuth2:
        - OAuth2Read
      tags:
      - ReleaseManagement
      x-BTVisibility: PRODUCTION
    post:
      deprecated: false
      operationId: updateReleasePackage
      security:
      - OAuth2:
        - OAuth2Write
      tags:
      - ReleaseManagement
      x-BTVisibility: PRODUCTION
  /api/revisions/companies/{cid}:
    get:
      deprecated: false
      operationId: enumerateRevisions
      security:
      - OAuth2:
        - OAuth2Read
      tags:
      - Revisions
      x-BTVisibility: PRODUCTION
  /api/revisions/companies/{cid}/partnumber/{pnum}:
    get:
      deprecated: false
      operationId: getRevisionHistoryInCompany
      security:
      - OAuth2:
        - OAuth2Read
      tags:
      - Revisions
      x-BTVisibility: PRODUCTION
  /api/revisions/{cd}/{cdid}/p/{pnum}/latest:
    get:
      deprecated: false
      operationId: getLatestInDocumentOrCompany
      security:
      - OAuth2:
        - OAuth2Read
      tags:
      - Revisions
      x-BTVisibility: PRODUCTION
  /api/teams:
    get:
      deprecated: false
      operationId: find
      security:
      - OAuth2:
        - OAuth2Read
      tags:
      - Teams
      x-BTVisibility: PRODUCTION
  /api/teams/{tid}:
    get:
      deprecated: false
      operationId: getTeam
      security:
      - OAuth2:
        - OAuth2Read
      tags:
      - Teams
      x-BTVisibility: PRODUCTION
  /api/thumbnails/d/{did}:
    get:
      deprecated: false
      operationId: getThumbnailForDocument
      security:
      - OAuth2:
        - OAuth2Read
      x-BTVisibility: PRODUCTION
  /api/thumbnails/d/{did}/v/{vid}:
    get:
      deprecated: false
      operationId: getThumbnailForDocumentAndVersion
      security:
      - OAuth2:
        - OAuth2Read
      x-BTVisibility: PRODUCTION
  /api/thumbnails/d/{did}/w/{wid}:
    get:
      deprecated: false
      operationId: getDocumentThumbnail
      security:
      - OAuth2:
        - OAuth2Read
      x-BTVisibility: PRODUCTION
  /api/thumbnails/d/{did}/w/{wid}/e/{eid}/ac/{cid}/s/{sz}:
    get:
      deprecated: false
      operationId: getElementThumbnailWithApiConfiguration
      security:
      - OAuth2:
        - OAuth2Read
      x-BTVisibility: PRODUCTION
  /api/thumbnails/d/{did}/w/{wid}/e/{eid}/c/{cid}/s/{sz}:
    get:
      deprecated: false
      operationId: getConfiguredElementThumbnailWithSize
      security:
      - OAuth2:
        - OAuth2Read
      x-BTVisibility: PRODUCTION
  /api/thumbnails/d/{did}/w/{wid}/e/{eid}/s/{sz}:
    get:
      deprecated: false
      operationId: getElementThumbnailWithSize
      security:
      - OAuth2:
        - OAuth2Read
      x-BTVisibility: PRODUCTION
  /api/thumbnails/d/{did}/w/{wid}/s/{sz}:
    get:
      deprecated: false
      operationId: getDocumentThumbnailWithSize
      security:
      - OAuth2:
        - OAuth2Read
      x-BTVisibility: PRODUCTION
  /api/thumbnails/d/{did}/{wv}/{wvid}/e/{eid}:
    delete:
      deprecated: false
      operationId: deleteApplicationThumbnails
      security:
      - OAuth2:
        - OAuth2Write
      x-BTVisibility: PRODUCTION
    get:
      deprecated: false
      operationId: getElementThumbnail
      security:
      - OAuth2:
        - OAuth2Read
      x-BTVisibility: PRODUCTION
    post:
      deprecated: false
      operationId: setApplicationElementThumbnail
      security:
      - OAuth2:
        - OAuth2Write
      x-BTVisibility: PRODUCTION
  /api/thumbnails/document/{did}:
    get:
      deprecated: false
      operationId: getThumbnailForDocumentOld
      security:
      - OAuth2:
        - OAuth2Read
      x-BTVisibility: PRODUCTION
  /api/thumbnails/document/{did}/version/{vid}:
    get:
      deprecated: false
      operationId: getThumbnailForDocumentAndVersionOld
      security:
      - OAuth2:
        - OAuth2Read
      x-BTVisibility: PRODUCTION
  /api/translations/d/{did}:
    get:
      deprecated: false
      operationId: getDocumentTranslations
      security:
      - OAuth2:
        - OAuth2Read
      tags:
      - Translations
      x-BTVisibility: PRODUCTION
  /api/translations/d/{did}/w/{wid}:
    post:
      deprecated: false
      operationId: createTranslation
      security:
      - OAuth2:
        - OAuth2Read
      tags:
      - Translations
      x-BTVisibility: PRODUCTION
  /api/translations/translationformats:
    get:
      deprecated: false
      operationId: getAllTranslatorFormats
      tags:
      - Translations
      x-BTVisibility: PRODUCTION
  /api/translations/{tid}:
    delete:
      deprecated: false
      operationId: deleteTranslation
      security:
      - OAuth2:
        - OAuth2Write
      tags:
      - Translations
      x-BTVisibility: PRODUCTION
    get:
      deprecated: false
      operationId: getTranslation
      security:
      - OAuth2:
        - OAuth2Read
      tags:
      - Translations
      x-BTVisibility: PRODUCTION
  /api/users/sessioninfo:
    get:
      deprecated: false
      operationId: sessionInfo
      tags:
      - Users
      x-BTVisibility: PRODUCTION
  /api/users/settings:
    get:
      deprecated: false
      operationId: getUserSettingsCurrentLoggedInUser
      tags:
      - Users
      x-BTVisibility: PRODUCTION
  /api/users/{uid}/settings:
    get:
      deprecated: false
      operationId: getUserSettings
      tags:
      - Users
      x-BTVisibility: PRODUCTION
  /api/versions/test:
    get:
      deprecated: false
      operationId: testVersionsGet
      tags:
      - Versions
      x-BTVisibility: PRODUCTION
    post:
      deprecated: false
      operationId: testVersionsPost
      tags:
      - Versions
      x-BTVisibility: PRODUCTION
  /api/webhooks:
    get:
      deprecated: false
      operationId: getWebhooks
      security:
      - OAuth2:
        - OAuth2Read
      tags:
      - Webhooks
      x-BTVisibility: PRODUCTION
    post:
      deprecated: false
      operationId: createWebhook
      security:
      - OAuth2:
        - OAuth2Read
      tags:
      - Webhooks
      x-BTVisibility: PRODUCTION
  /api/webhooks/{webhookid}:
    delete:
      deprecated: false
      operationId: unregisterWebhook
      security:
      - OAuth2:
        - OAuth2Read
      tags:
      - Webhooks
      x-BTVisibility: PRODUCTION
    get:
      deprecated: false
      operationId: getWebhook
      security:
      - OAuth2:
        - OAuth2Read
      tags:
      - Webhooks
      x-BTVisibility: PRODUCTION
    post:
      deprecated: false
      operationId: updateWebhook
      security:
      - OAuth2:
        - OAuth2Read
      tags:
      - Webhooks
      x-BTVisibility: PRODUCTION
  /api/webhooks/{webhookid}/ping:
    post:
      deprecated: false
      operationId: pingWebhook
      security:
      - OAuth2:
        - OAuth2Read
      tags:
      - Webhooks
      x-BTVisibility: PRODUCTION
  /api/workflow/active:
    get:
      deprecated: false
      operationId: getActiveWorkflows
      security:
      - OAuth2:
        - OAuth2Read
      tags:
      - Workflow
      x-BTVisibility: PRODUCTION
  /api/workflowabletestobject/testobject/{wfid}:
    post:
      deprecated: false
      operationId: createWorkflowableTestObject
      security:
      - OAuth2:
        - OAuth2Write
      x-BTVisibility: PRODUCTION
  /api/workflowabletestobject/{oid}:
    get:
      deprecated: false
      operationId: getWorkflowableTestObject
      security:
      - OAuth2:
        - OAuth2Read
      x-BTVisibility: PRODUCTION
    post:
      deprecated: false
      operationId: updateWorkflowableTestObject
      security:
      - OAuth2:
        - OAuth2Write
      x-BTVisibility: PRODUCTION
  /api/workflowabletestobject/{oid}/{transition}:
    post:
      deprecated: false
      operationId: transitionWorkflowableTestObject
      security:
      - OAuth2:
        - OAuth2Write
      x-BTVisibility: PRODUCTION
components:
  schemas:
    Address:
      properties:
        city:
          type: string
        country:
          type: string
        line1:
          type: string
        line2:
          type: string
        postalCode:
          type: string
        state:
          type: string
      type: object
    ApiResponse:
      example:
        extensions:
          key: '{}'
        get$ref: get$ref
        description: description
        links:
          key:
            server:
              extensions:
                key: '{}'
              variables:
                key:
                  default: default
                  extensions:
                    key: '{}'
                  description: description
                  enum:
                  - enum
                  - enum
              description: description
              url: url
            extensions:
              key: '{}'
            get$ref: get$ref
            operationRef: operationRef
            description: description
            operationId: operationId
        content:
          key:
            schema:
              writeOnly: true
              nullable: true
              deprecated: true
              minLength: 2
              pattern: pattern
              description: description
              title: title
              type: type
              required:
              - required
              - required
              exclusiveMaximum: true
              default: '{}'
              xml:
                extensions:
                  key: '{}'
                prefix: prefix
                name: name
                namespace: namespace
                attribute: true
                wrapped: true
              maxProperties: 1
              exclusiveMinimum: true
              multipleOf: 3.616076749251911
              maxItems: 0
              format: format
              readOnly: true
              enum:
              - '{}'
              - '{}'
              discriminator:
                mapping:
                  key: mapping
                propertyName: propertyName
              minProperties: 7
              minItems: 5
              extensions:
                key: '{}'
              get$ref: get$ref
              uniqueItems: true
              maximum: 5.962133916683182
              additionalProperties: '{}'
              minimum: 9.301444243932576
              maxLength: 6
              properties: {}
            extensions:
              key: '{}'
            encoding:
              key:
                extensions:
                  key: '{}'
                allowReserved: true
                explode: true
                style: FORM
                contentType: contentType
      properties:
        content:
          additionalProperties:
            $ref: '#/components/schemas/MediaType'
          properties:
            empty:
              type: boolean
          type: object
        description:
          type: string
        extensions:
          additionalProperties:
            type: object
          type: object
        get$ref:
          type: string
      type: object
    BTAPIApplicationSummaryInfo:
      properties:
        clientId:
          type: string
        description:
          type: string
        href:
          format: uri
          type: string
        id:
          type: string
        name:
          type: string
        state:
          format: int32
          type: integer
        viewRef:
          format: uri
          type: string
      type: object
    BTAclEntryInfo:
      properties:
        acceptOwnerTransfer:
          type: boolean
        companyName:
          type: string
        email:
          type: string
        enterpriseMember:
          type: boolean
        entryId:
          type: string
        entryState:
          enum:
          - DELETED
          - ACTIVE
          - INACTIVE
          - REQUESTED
          - APPROVED
          - REQUEST_EXPIRED
          - ALL
          - MARKED_FOR_DELETION
          type: string
        entryType:
          format: int32
          type: integer
        image:
          type: string
        name:
          type: string
        objectId:
          type: string
        pendingOwnerTransfer:
          type: boolean
        permission:
          format: int64
          type: integer
        permissionSet:
          type: object
        teamName:
          type: string
      type: object
    BTAclInfo:
      properties:
        admin:
          type: boolean
        entries:
          items:
            $ref: '#/components/schemas/BTAclEntryInfo'
          type: array
        href:
          format: uri
          type: string
        id:
          type: string
        inheritedAcls:
          items:
            $ref: '#/components/schemas/BTInheritedAclInfo'
          type: array
        name:
          type: string
        objectId:
          type: string
        objectType:
          format: int64
          type: integer
        owner:
          $ref: '#/components/schemas/BTOwnerInfo'
        public:
          type: boolean
        sharedWithSupport:
          type: boolean
        viewRef:
          format: uri
          type: string
        visibility:
          type: string
      type: object
    BTActiveSheetMetalFilter-2944:
      allOf:
      - $ref: '#/components/schemas/BTQueryFilter-183'
      - $ref: '#/components/schemas/BTActiveSheetMetalFilter_2944_allOf'
      type: object
    BTActiveWorkflowInfo:
      properties:
        canCreateReleases:
          type: boolean
        canCurrentUserCreateReleases:
          type: boolean
        companyId:
          type: string
        documentId:
          type: string
        drawingCanDuplicatePartNumber:
          type: boolean
        enabledActiveMultipleWorkflows:
          type: boolean
        obsoletionWorkflow:
          $ref: '#/components/schemas/BTPublishedWorkflowInfo'
        obsoletionWorkflowId:
          type: string
        pickableWorkflows:
          items:
            $ref: '#/components/schemas/BTPublishedWorkflowInfo'
          type: array
        releaseWorkflow:
          $ref: '#/components/schemas/BTPublishedWorkflowInfo'
        releaseWorkflowId:
          type: string
        usingAutoPartNumbering:
          type: boolean
        usingAutoPartNumberingScheme:
          type: boolean
        usingManagedWorkflow:
          type: boolean
      type: object
    BTAddressInfo:
      properties:
        address:
          type: string
        city:
          type: string
        country:
          type: string
        countryCode:
          type: string
        id:
          type: string
        state:
          type: string
        stateCode:
          type: string
        zip:
          type: string
      type: object
    BTAllowEdgePointFilter-2371:
      allOf:
      - $ref: '#/components/schemas/BTQueryFilter-183'
      - $ref: '#/components/schemas/BTAllowEdgePointFilter_2371_allOf'
      type: object
    BTAllowFlattenedGeometryFilter-2140:
      allOf:
      - $ref: '#/components/schemas/BTQueryFilter-183'
      - $ref: '#/components/schemas/BTAllowFlattenedGeometryFilter_2140_allOf'
      type: object
    BTAllowMeshGeometryFilter-1026:
      allOf:
      - $ref: '#/components/schemas/BTQueryFilter-183'
      - $ref: '#/components/schemas/BTAllowMeshGeometryFilter_1026_allOf'
      type: object
    BTAllowedMateTypeFilter-1511:
      allOf:
      - $ref: '#/components/schemas/BTMateFilter-162'
      - $ref: '#/components/schemas/BTAllowedMateTypeFilter_1511_allOf'
      type: object
    BTAndFilter-110:
      allOf:
      - $ref: '#/components/schemas/BTQueryFilter-183'
      - $ref: '#/components/schemas/BTAndFilter_110_allOf'
      type: object
    BTAppAssociativeDataInfoArray:
      properties:
        changeId:
          type: string
        errorCode:
          format: int32
          type: integer
        errorDescription:
          type: string
        errorValue:
          enum:
          - OK
          - TRANSACTION_CONFLICT
          - NOT_FOUND
          - INCONSISTENT_CHANGES
          type: string
          writeOnly: true
        items:
          items:
            $ref: '#/components/schemas/BTAssociativeDataInfo'
          type: array
        parentChangeId:
          type: string
      type: object
    BTAppElementBasicInfo:
      properties:
        changeId:
          type: string
        errorCode:
          format: int32
          type: integer
        errorDescription:
          type: string
        errorValue:
          enum:
          - OK
          - TRANSACTION_CONFLICT
          - NOT_FOUND
          - INCONSISTENT_CHANGES
          type: string
          writeOnly: true
        parentChangeId:
          type: string
      type: object
    BTAppElementChangeParams:
      properties:
        baseContent:
          type: string
        delta:
          type: string
        subelementId:
          type: string
      type: object
    BTAppElementCommitTransactionParams:
      properties:
        description:
          type: string
        returnError:
          type: boolean
        transactionId:
          type: string
      type: object
    BTAppElementContentDeltaInfo:
      properties:
        delta:
          type: string
      type: object
    BTAppElementContentEntryInfo:
      properties:
        baseContent:
          type: string
        deltas:
          items:
            $ref: '#/components/schemas/BTAppElementContentDeltaInfo'
          type: array
        subelementId:
          type: string
      type: object
    BTAppElementContentInfo:
      properties:
        changeId:
          type: string
        data:
          items:
            $ref: '#/components/schemas/BTAppElementContentEntryInfo'
          type: array
        errorCode:
          format: int32
          type: integer
        errorDescription:
          type: string
        errorValue:
          enum:
          - OK
          - TRANSACTION_CONFLICT
          - NOT_FOUND
          - INCONSISTENT_CHANGES
          type: string
          writeOnly: true
      type: object
    BTAppElementHistoryEntryInfo:
      properties:
        changeId:
          type: string
        createdAt:
          format: date-time
          type: string
        description:
          type: string
      type: object
    BTAppElementHistoryInfo:
      properties:
        changes:
          items:
            $ref: '#/components/schemas/BTAppElementHistoryEntryInfo'
          type: array
        errorCode:
          format: int32
          type: integer
        errorDescription:
          type: string
        errorValue:
          enum:
          - OK
          - TRANSACTION_CONFLICT
          - NOT_FOUND
          - INCONSISTENT_CHANGES
          type: string
          writeOnly: true
      type: object
    BTAppElementModifyInfo:
      properties:
        changeId:
          type: string
        elementId:
          type: string
        errorCode:
          format: int32
          type: integer
        errorDescription:
          type: string
        errorValue:
          enum:
          - OK
          - TRANSACTION_CONFLICT
          - NOT_FOUND
          - INCONSISTENT_CHANGES
          type: string
          writeOnly: true
        parentChangeId:
          type: string
        propertyEditsMerged:
          type: boolean
        transactionId:
          type: string
      type: object
    BTAppElementParams:
      properties:
        description:
          type: string
        formatId:
          type: string
        location:
          $ref: '#/components/schemas/BTElementLocationParams'
        name:
          type: string
        subelements:
          items:
            $ref: '#/components/schemas/BTAppElementChangeParams'
          type: array
      type: object
    BTAppElementReferenceInfo:
      properties:
        changeId:
          type: string
        errorCode:
          format: int32
          type: integer
        errorDescription:
          type: string
        errorValue:
          enum:
          - OK
          - TRANSACTION_CONFLICT
          - NOT_FOUND
          - INCONSISTENT_CHANGES
          type: string
          writeOnly: true
        parentChangeId:
          type: string
        referenceId:
          type: string
        transactionId:
          type: string
      type: object
    BTAppElementReferenceParams:
      properties:
        hasDocumentMicroversions:
          type: boolean
        idTag:
          type: string
        idTagMicroversionId:
          type: string
        isSketchOnly:
          type: boolean
        parentChangeId:
          type: string
        partNumber:
          type: string
        pureSketch:
          type: boolean
        referenceType:
          format: int32
          type: integer
        returnError:
          type: boolean
        revision:
          type: string
        sketchIds:
          items:
            type: string
          type: array
        targetConfiguration:
          type: string
        targetDocumentId:
          type: string
        targetElementId:
          type: string
        targetMicroversionId:
          type: string
        targetVersionId:
          type: string
        trackNewVersions:
          type: boolean
        transactionId:
          type: string
        updateSketchInfo:
          type: boolean
      type: object
    BTAppElementReferenceResolveInfo:
      properties:
        changeId:
          type: string
        errorCode:
          format: int32
          type: integer
        errorDescription:
          type: string
        errorValue:
          enum:
          - OK
          - TRANSACTION_CONFLICT
          - NOT_FOUND
          - INCONSISTENT_CHANGES
          type: string
          writeOnly: true
        idTag:
          type: string
        idTagIsValid:
          type: boolean
        isConfigurable:
          type: boolean
        isFlattenedPart:
          type: boolean
        isSketchOnly:
          type: boolean
        isSurface:
          type: boolean
        partNumber:
          type: string
        referenceId:
          type: string
        referenceType:
          format: int32
          type: integer
        resolvedDocumentMicroversionId:
          type: string
        resolvedElementMicroversionId:
          type: string
        revision:
          type: string
        sketchIds:
          items:
            type: string
          type: array
        targetConfiguration:
          type: string
        targetDocumentId:
          type: string
        targetDocumentMicroversionId:
          type: string
        targetElementId:
          type: string
        targetElementMicroversionId:
          type: string
        targetVersionId:
          type: string
        trackNewVersions:
          type: boolean
      type: object
    BTAppElementReferencesResolveInfo:
      properties:
        resolvedReferences:
          items:
            $ref: '#/components/schemas/BTAppElementReferenceResolveInfo'
          type: array
        unresolvedReferenceIds:
          items:
            type: string
          type: array
      type: object
    BTAppElementStartTransactionParams:
      properties:
        parentChangeId:
          type: string
        returnError:
          type: boolean
      type: object
    BTAppElementUpdateParams:
      properties:
        changes:
          items:
            $ref: '#/components/schemas/BTAppElementChangeParams'
          type: array
        description:
          type: string
        parentChangeId:
          type: string
        returnError:
          type: boolean
        transactionId:
          type: string
      type: object
    BTApplicationElementThumbnailParams:
      properties:
        base64EncodedImage:
          type: string
        description:
          type: string
        imageHeight:
          format: int32
          type: integer
        imageWidth:
          format: int32
          type: integer
        isPrimary:
          type: boolean
        uniqueId:
          type: string
      type: object
    BTApplicationElementThumbnailParamsArray:
      properties:
        thumbnails:
          items:
            $ref: '#/components/schemas/BTApplicationElementThumbnailParams'
          type: array
      type: object
    BTAssemblyDefinitionInfo:
      properties:
        partStudioFeatures:
          items:
            $ref: '#/components/schemas/BTAssemblyPSFeatureInfo'
          type: array
        parts:
          items:
            $ref: '#/components/schemas/BTAssemblyPartsInfo'
          type: array
        rootAssembly:
          $ref: '#/components/schemas/BTRootAssemblyInfo'
        subAssemblies:
          items:
            $ref: '#/components/schemas/BTSubAssemblyInfo'
          type: array
      type: object
    BTAssemblyFeatureDataInfo:
      properties:
        mateType:
          type: string
        matedEntities:
          items:
            $ref: '#/components/schemas/BTAssemblyMatedEntity'
          type: array
        name:
          type: string
      type: object
    BTAssemblyFeatureInfo:
      properties:
        featureData:
          $ref: '#/components/schemas/BTAssemblyFeatureDataInfo'
        featureType:
          type: string
        id:
          type: string
        suppressed:
          type: boolean
      type: object
    BTAssemblyFeatureListResponse-1174:
      allOf:
      - $ref: '#/components/schemas/BTFeatureApiBase-1430'
      - $ref: '#/components/schemas/BTAssemblyFeatureListResponse_1174_allOf'
      type: object
    BTAssemblyInsertTransformedInstancesResponse:
      properties:
        insertResponses:
          items:
            $ref: '#/components/schemas/BTAssemblyOccurrenceInfo'
          type: array
      type: object
    BTAssemblyInstanceDefinitionParams:
      properties:
        configuration:
          type: string
        documentId:
          type: string
        elementId:
          type: string
        featureId:
          type: string
        isAssembly:
          type: boolean
        isHidden:
          type: boolean
        isSuppressed:
          type: boolean
        isWholePartStudio:
          type: boolean
        microversionId:
          type: string
        partId:
          type: string
        partNumber:
          type: string
        revision:
          type: string
        versionId:
          type: string
      type: object
    BTAssemblyInstanceInfo:
      properties:
        configuration:
          type: string
        documentId:
          type: string
        documentMicroversion:
          type: string
        documentVersion:
          type: string
        elementId:
          type: string
        fullConfiguration:
          type: string
        id:
          type: string
        name:
          type: string
        revision:
          type: string
        suppressed:
          type: boolean
        type:
          type: string
      type: object
    BTAssemblyMatedEntity:
      properties:
        mateCS:
          $ref: '#/components/schemas/BTMateConnectorCSInfo'
        matedOccurrence:
          items:
            type: string
          type: array
      type: object
    BTAssemblyOccurrenceInfo:
      properties:
        fixed:
          type: boolean
        hidden:
          type: boolean
        path:
          items:
            type: string
          type: array
        transform:
          items:
            format: double
            type: number
          type: array
      type: object
    BTAssemblyPSFeatureInfo:
      properties:
        configuration:
          type: string
        documentId:
          type: string
        documentMicroversion:
          type: string
        documentVersion:
          type: string
        elementId:
          type: string
        featureId:
          type: string
        featureType:
          type: string
        fullConfiguration:
          type: string
        revision:
          type: string
      type: object
    BTAssemblyPartsInfo:
      properties:
        bodyType:
          enum:
          - SOLID
          - SHEET
          - WIRE
          - POINT
          - MATE_CONNECTOR
          - COMPOSITE
          - UNKNOWN
          type: string
        configuration:
          type: string
        documentId:
          type: string
        documentMicroversion:
          type: string
        documentVersion:
          type: string
        elementId:
          type: string
        fullConfiguration:
          type: string
        partId:
          type: string
        revision:
          type: string
        standardContent:
          type: boolean
      type: object
    BTAssemblyTransformDefinitionParams:
      properties:
        isRelative:
          type: boolean
        occurrences:
          items:
            $ref: '#/components/schemas/BTOccurrence-74'
          type: array
        transform:
          items:
            format: double
            type: number
          type: array
      type: object
    BTAssemblyTransformedInstancesDefinitionParams:
      properties:
        transformGroups:
          items:
            $ref: '#/components/schemas/TransformGroup'
          type: array
      type: object
    BTAssociativeDataInfo:
      properties:
        associativeDataId:
          type: string
        data:
          items:
            $ref: '#/components/schemas/BTNameValuePair'
          type: array
        documentId:
          type: string
        documentMicroversion:
          type: string
        elementId:
          type: string
        idTag:
          type: string
        microversionId:
          type: string
        occurrenceId:
          type: string
        type:
          enum:
          - ONSHAPE_DRAWING_VIEW
          - MODEL_TOPOLOGY
          - MODEL_DEFINITION_FEATURE
          - MODEL_DEFINITION_ENTITY
          - UNKNOWN
          type: string
        versionId:
          type: string
      type: object
    BTBaseInfo:
      discriminator:
        mapping:
          version-base: '#/components/schemas/BTVersionInfoBase'
        propertyName: jsonType
      properties:
        href:
          format: uri
          type: string
        id:
          type: string
        jsonType:
          type: string
        name:
          type: string
        viewRef:
          format: uri
          type: string
      required:
      - jsonType
      type: object
    BTBaseSMJointTableRowMetadata-2232:
      allOf:
      - $ref: '#/components/schemas/BTTableBaseRowMetadata-3181'
      - $ref: '#/components/schemas/BTBaseSMJointTableRowMetadata_2232_allOf'
      discriminator:
        mapping:
          BTSMBendTableRowMetadata-1705: '#/components/schemas/BTSMBendTableRowMetadata-1705'
          BTSMOtherJointTableRowMetadata-2640: '#/components/schemas/BTSMOtherJointTableRowMetadata-2640'
        propertyName: btType
      properties:
        btType:
          type: string
      type: object
    BTBillOfMaterialsTable-1073:
      allOf:
      - $ref: '#/components/schemas/BTTable-1825'
      - $ref: '#/components/schemas/BTBillOfMaterialsTable_1073_allOf'
      type: object
    BTBillOfMaterialsTableRow-1425:
      allOf:
      - $ref: '#/components/schemas/BTTableRow-1054'
      - $ref: '#/components/schemas/BTBillOfMaterialsTableRow_1425_allOf'
      type: object
    BTBillOfMaterialsTableRowMetadata-1300:
      allOf:
      - $ref: '#/components/schemas/BTTableBaseRowMetadata-3181'
      - $ref: '#/components/schemas/BTBillOfMaterialsTableRowMetadata_1300_allOf'
      type: object
    BTBillOfMaterialsUniqueItemId-2029:
      properties:
        ambiguousUniqueId:
          $ref: '#/components/schemas/BTBillOfMaterialsUniqueItemId-2029'
        apiConfiguration:
          type: string
        btType:
          type: string
        documentVersionElementId:
          $ref: '#/components/schemas/BTDocumentVersionElementIds-1897'
        elementId:
          type: string
        fullElementId:
          $ref: '#/components/schemas/BTFullElementId-756'
        isStandardContent:
          type: boolean
        itemDefinitionId:
          type: string
        nonGeometric:
          type: boolean
        partId:
          type: string
        sourceElement:
          $ref: '#/components/schemas/BTElementReference-725'
        standardContentOwner:
          $ref: '#/components/schemas/BTOwner-3114'
        uniqueElementId:
          $ref: '#/components/schemas/BTBillOfMaterialsUniqueItemId-2029'
        versionId:
          type: string
        workspacePartItem:
          type: boolean
        workspaceReference:
          type: boolean
      type: object
    BTBillingPlanInfo:
      properties:
        amountCents:
          format: int32
          type: integer
        applicationId:
          type: string
        clientId:
          type: string
        companyPlan:
          type: boolean
        consumableQuantity:
          format: int32
          type: integer
        deprecated:
          type: boolean
        description:
          type: string
        discountInfo:
          $ref: '#/components/schemas/BTDiscountInfo'
        group:
          type: string
        hidden:
          type: boolean
        href:
          format: uri
          type: string
        id:
          type: string
        interval:
          type: string
        name:
          type: string
        onshapePlan:
          type: boolean
        planType:
          format: int32
          type: integer
        trialPeriodDays:
          format: int32
          type: integer
        viewRef:
          format: uri
          type: string
      type: object
    BTBodyTypeFilter-112:
      allOf:
      - $ref: '#/components/schemas/BTQueryFilter-183'
      - $ref: '#/components/schemas/BTBodyTypeFilter_112_allOf'
      type: object
    BTBoundingBox-1052:
      properties:
        maxCorner:
          $ref: '#/components/schemas/BTVector3d-389'
        minCorner:
          $ref: '#/components/schemas/BTVector3d-389'
        valid:
          type: boolean
      type: object
    BTBoundingBoxInfo:
      properties:
        highX:
          format: double
          type: number
        highY:
          format: double
          type: number
        highZ:
          format: double
          type: number
        lowX:
          format: double
          type: number
        lowY:
          format: double
          type: number
        lowZ:
          format: double
          type: number
      type: object
    BTCacheDataPath-191:
      properties:
        btType:
          type: string
        documentId:
          type: string
        elementId:
          type: string
        expireSecs:
          type: string
        fullFilePath:
          type: string
        isPersisted:
          type: boolean
        key:
          type: string
        urlPath:
          type: string
        useLocalFileCache:
          type: boolean
      type: object
    BTCardInfo:
      properties:
        billingAddress:
          $ref: '#/components/schemas/BTAddressInfo'
        expMonth:
          format: int32
          type: integer
        expYear:
          format: int32
          type: integer
        last4:
          type: string
        type:
          type: string
      type: object
    BTCircleDescription-1145:
      allOf:
      - $ref: '#/components/schemas/BTCurveDescription-1583'
      - $ref: '#/components/schemas/BTCircleDescription_1145_allOf'
      type: object
    BTClosedCurveFilter-1206:
      allOf:
      - $ref: '#/components/schemas/BTQueryFilter-183'
      - $ref: '#/components/schemas/BTClosedCurveFilter_1206_allOf'
      type: object
    BTCloudStorageAccountInfo:
      allOf:
      - $ref: '#/components/schemas/BTGlobalTreeNodeInfo'
      - $ref: '#/components/schemas/BTCloudStorageAccountInfo_allOf'
      type: object
    BTCloudStorageObjectInfo:
      properties:
        canMove:
          type: boolean
        cloudStorageAccountId:
          type: string
        cloudStorageObjectId:
          type: string
        cloudStorageProvider:
          format: int32
          type: integer
        createdAt:
          format: date-time
          type: string
        createdBy:
          $ref: '#/components/schemas/BTUserBasicSummaryInfo'
        createdById:
          type: string
        description:
          type: string
        href:
          format: uri
          type: string
        iconLink:
          type: string
        id:
          type: string
        isContainer:
          type: boolean
        isEnterpriseOwned:
          type: boolean
        isMutable:
          type: boolean
        mimeType:
          type: string
        modifiedAt:
          format: date-time
          type: string
        modifiedBy:
          $ref: '#/components/schemas/BTUserBasicSummaryInfo'
        modifiedById:
          type: string
        name:
          type: string
        owner:
          $ref: '#/components/schemas/BTOwnerInfo'
        parentId:
          type: string
        projectId:
          type: string
        resourceType:
          type: string
        sizeBytes:
          format: int64
          type: integer
        thumbnailInfo:
          $ref: '#/components/schemas/BTThumbnailInfo'
        treeHref:
          type: string
        viewRef:
          format: uri
          type: string
        webViewLink:
          type: string
      type: object
    BTColorInfo:
      properties:
        blue:
          format: int32
          type: integer
        green:
          format: int32
          type: integer
        red:
          format: int32
          type: integer
      type: object
    BTColorParams:
      properties:
        blue:
          format: int32
          type: integer
        green:
          format: int32
          type: integer
        red:
          format: int32
          type: integer
      type: object
    BTCommentAttachmentInfo:
      properties:
        fileName:
          type: string
        href:
          format: uri
          type: string
        id:
          type: string
        mimeType:
          type: string
        name:
          type: string
        thumbnailFor:
          type: string
        viewRef:
          format: uri
          type: string
      type: object
    BTCommentInfo:
      properties:
        assemblyFeatures:
          items:
            type: string
          type: array
        assignedAt:
          format: date-time
          type: string
        assignee:
          $ref: '#/components/schemas/BTUserSummaryInfo'
        attachment:
          $ref: '#/components/schemas/BTCommentAttachmentInfo'
        canDelete:
          type: boolean
        canResolveOrReopen:
          type: boolean
        createdAt:
          format: date-time
          type: string
        documentId:
          type: string
        elementFeature:
          type: string
        elementId:
          type: string
        elementOccurrences:
          items:
            type: string
          type: array
        elementQuery:
          type: string
        href:
          format: uri
          type: string
        id:
          type: string
        message:
          type: string
        name:
          type: string
        parentId:
          type: string
        releasePackageId:
          type: string
        reopenedAt:
          format: date-time
          type: string
        reopenedBy:
          $ref: '#/components/schemas/BTUserSummaryInfo'
        replyCount:
          format: int64
          type: integer
        resolvedAt:
          format: date-time
          type: string
        resolvedBy:
          $ref: '#/components/schemas/BTUserSummaryInfo'
        state:
          format: int32
          type: integer
        thumbnail:
          $ref: '#/components/schemas/BTCommentAttachmentInfo'
        topLevel:
          type: boolean
        user:
          $ref: '#/components/schemas/BTUserSummaryInfo'
        versionId:
          type: string
        viewData:
          $ref: '#/components/schemas/BTViewDataInfo'
        viewRef:
          format: uri
          type: string
        workspaceId:
          type: string
      type: object
    BTCommonUnitInfo:
      properties:
        abbreviation:
          type: string
        unit:
          type: string
        unitName:
          type: string
        unitType:
          type: string
        valueInBaseUnits:
          format: double
          type: number
      type: object
    BTCommonUnitsInfo:
      properties:
        units:
          items:
            $ref: '#/components/schemas/BTCommonUnitInfo'
          type: array
      type: object
    BTCompanyInfo:
      properties:
        address:
          $ref: '#/components/schemas/BTAddressInfo'
        admin:
          type: boolean
        description:
          type: string
        domainPrefix:
          type: string
        enterpriseBaseUrl:
          type: string
        href:
          format: uri
          type: string
        id:
          type: string
        image:
          type: string
        name:
          type: string
        noPublicDocuments:
          type: boolean
        ownerId:
          type: string
        purchase:
          $ref: '#/components/schemas/BTPurchaseInfo'
        secondaryDomainPrefixes:
          items:
            type: string
          type: array
          uniqueItems: true
        state:
          format: int32
          type: integer
        type:
          format: int32
          type: integer
        viewRef:
          format: uri
          type: string
      type: object
    BTCompanySummaryInfo:
      properties:
        admin:
          type: boolean
        description:
          type: string
        domainPrefix:
          type: string
        enterpriseBaseUrl:
          type: string
        href:
          format: uri
          type: string
        id:
          type: string
        image:
          type: string
        name:
          type: string
        noPublicDocuments:
          type: boolean
        ownerId:
          type: string
        secondaryDomainPrefixes:
          items:
            type: string
          type: array
          uniqueItems: true
        state:
          format: int32
          type: integer
        type:
          format: int32
          type: integer
        viewRef:
          format: uri
          type: string
      type: object
    BTComputedConfigurationInputSpec-2525:
      properties:
        btType:
          type: string
        inputId:
          type: string
      type: object
    BTConeDescription-860:
      allOf:
      - $ref: '#/components/schemas/BTSurfaceDescription-1564'
      - $ref: '#/components/schemas/BTConeDescription_860_allOf'
      type: object
    BTConfigurationInfo:
      properties:
        isStandardContent:
          type: boolean
      type: object
    BTConfigurationParams:
      properties:
        standardContentParametersId:
          type: string
      type: object
    BTConfigurationResponse-2019:
      properties:
        configurationParameters:
          items:
            $ref: '#/components/schemas/BTMConfigurationParameter-819'
          type: array
        currentConfiguration:
          items:
            $ref: '#/components/schemas/BTMParameter-1'
          type: array
        libraryVersion:
          format: int32
          type: integer
        microversionSkew:
          type: boolean
        rejectMicroversionSkew:
          type: boolean
        serializationVersion:
          type: string
        sourceMicroversion:
          type: string
      type: object
    BTConfigurationUpdateCall-2933:
      allOf:
      - $ref: '#/components/schemas/BTFeatureApiBase-1430'
      - $ref: '#/components/schemas/BTConfigurationUpdateCall_2933_allOf'
      type: object
    BTConfiguredDimensionColumnInfo-2168:
      allOf:
      - $ref: '#/components/schemas/BTConfiguredValuesColumnInfo-1025'
      - $ref: '#/components/schemas/BTConfiguredDimensionColumnInfo_2168_allOf'
      type: object
    BTConfiguredFeatureColumnInfo-1014:
      allOf:
      - $ref: '#/components/schemas/BTConfiguredValuesColumnInfo-1025'
      - $ref: '#/components/schemas/BTConfiguredFeatureColumnInfo_1014_allOf'
      type: object
    BTConfiguredParameterColumnInfo-2900:
      allOf:
      - $ref: '#/components/schemas/BTConfiguredValuesColumnInfo-1025'
      - $ref: '#/components/schemas/BTConfiguredParameterColumnInfo_2900_allOf'
      type: object
    BTConfiguredPartPropertiesTable-2740:
      allOf:
      - $ref: '#/components/schemas/BTTable-1825'
      - $ref: '#/components/schemas/BTConfiguredPartPropertiesTable_2740_allOf'
      type: object
    BTConfiguredSuppressionColumnInfo-2498:
      allOf:
      - $ref: '#/components/schemas/BTConfiguredValuesColumnInfo-1025'
      - $ref: '#/components/schemas/BTConfiguredFeatureColumnInfo_1014_allOf'
      type: object
    BTConfiguredValuesColumnInfo-1025:
      allOf:
      - $ref: '#/components/schemas/BTTableColumnInfo-1222'
      - $ref: '#/components/schemas/BTConfiguredValuesColumnInfo_1025_allOf'
      discriminator:
        mapping:
          BTConfiguredDimensionColumnInfo-2168: '#/components/schemas/BTConfiguredDimensionColumnInfo-2168'
          BTConfiguredFeatureColumnInfo-1014: '#/components/schemas/BTConfiguredFeatureColumnInfo-1014'
          BTConfiguredParameterColumnInfo-2900: '#/components/schemas/BTConfiguredParameterColumnInfo-2900'
          BTConfiguredSuppressionColumnInfo-2498: '#/components/schemas/BTConfiguredSuppressionColumnInfo-2498'
        propertyName: btType
      properties:
        btType:
          type: string
      type: object
    BTConstructionObjectFilter-113:
      allOf:
      - $ref: '#/components/schemas/BTQueryFilter-183'
      - $ref: '#/components/schemas/BTConstructionObjectFilter_113_allOf'
      type: object
    BTCopyDocumentInfo:
      properties:
        newDocumentId:
          type: string
        newDocumentName:
          type: string
        newOwner:
          $ref: '#/components/schemas/BTOwnerInfo'
        newParentId:
          type: string
        newProjectId:
          type: string
        newWorkspaceId:
          type: string
      type: object
    BTCopyDocumentParams:
      properties:
        betaCapabilityIds:
          items:
            type: string
          type: array
        isPublic:
          type: boolean
        newName:
          type: string
        ownerId:
          type: string
        ownerTypeIndex:
          format: int32
          type: integer
        parentId:
          type: string
        projectId:
          type: string
      type: object
    BTCopyElementParams:
      properties:
        anchorElementId:
          type: string
        documentIdSource:
          type: string
        elementIdSource:
          type: string
        isGroupAnchor:
          type: boolean
        workspaceIdSource:
          type: string
      type: object
    BTCurveDescription-1583:
      discriminator:
        mapping:
          BTCircleDescription-1145: '#/components/schemas/BTCircleDescription-1145'
          BTEllipseDescription-866: '#/components/schemas/BTEllipseDescription-866'
          BTLineDescription-1559: '#/components/schemas/BTLineDescription-1559'
          BTSplineDescription-2118: '#/components/schemas/BTSplineDescription-2118'
        propertyName: btType
      properties:
        btType:
          type: string
        type:
          enum:
          - OTHER
          - LINE
          - CIRCLE
          - ELLIPSE
          - BCURVE
          - ICURVE
          - UNKNOWN
          type: string
      type: object
    BTCurveGeometry-114:
      discriminator:
        mapping:
          BTCurveGeometryCircle-115: '#/components/schemas/BTCurveGeometryCircle-115'
          BTCurveGeometryConic-2284: '#/components/schemas/BTCurveGeometryConic-2284'
          BTCurveGeometryInterpolatedSpline-116: '#/components/schemas/BTCurveGeometryInterpolatedSpline-116'
          BTCurveGeometryLine-117: '#/components/schemas/BTCurveGeometryLine-117'
          BTCurveGeometrySpline-118: '#/components/schemas/BTCurveGeometrySpline-118'
        propertyName: btType
      properties:
        btType:
          type: string
      type: object
    BTCurveGeometryCircle-115:
      allOf:
      - $ref: '#/components/schemas/BTCurveGeometry-114'
      - $ref: '#/components/schemas/BTCurveGeometryCircle_115_allOf'
      discriminator:
        mapping:
          BTCurveGeometryEllipse-1189: '#/components/schemas/BTCurveGeometryEllipse-1189'
        propertyName: btType
      properties:
        btType:
          type: string
      type: object
    BTCurveGeometryConic-2284:
      allOf:
      - $ref: '#/components/schemas/BTCurveGeometry-114'
      - $ref: '#/components/schemas/BTCurveGeometryConic_2284_allOf'
      type: object
    BTCurveGeometryEllipse-1189:
      allOf:
      - $ref: '#/components/schemas/BTCurveGeometryCircle-115'
      - $ref: '#/components/schemas/BTCurveGeometryEllipse_1189_allOf'
      type: object
    BTCurveGeometryInterpolatedSpline-116:
      allOf:
      - $ref: '#/components/schemas/BTCurveGeometry-114'
      - $ref: '#/components/schemas/BTCurveGeometryInterpolatedSpline_116_allOf'
      type: object
    BTCurveGeometryLine-117:
      allOf:
      - $ref: '#/components/schemas/BTCurveGeometry-114'
      - $ref: '#/components/schemas/BTCurveGeometryLine_117_allOf'
      type: object
    BTCurveGeometrySpline-118:
      allOf:
      - $ref: '#/components/schemas/BTCurveGeometry-114'
      - $ref: '#/components/schemas/BTCurveGeometrySpline_118_allOf'
      type: object
    BTCustomPropertyDefinitionInfo:
      properties:
        description:
          type: string
        enumDefinition:
          items:
            type: string
          type: array
        name:
          type: string
        template:
          type: string
        type:
          enum:
          - STRING
          - NUMBER
          - INTEGER
          - BOOLEAN
          - DATE
          - ENUM
          - BLOB
          - OBJECT
          - ARRAY
          - UNKNOWN
          type: string
      type: object
    BTCustomPropertyDefinitionParams:
      properties:
        description:
          type: string
        enumDefinition:
          items:
            type: string
          type: array
        name:
          type: string
        template:
          type: string
        type:
          enum:
          - STRING
          - NUMBER
          - INTEGER
          - BOOLEAN
          - DATE
          - ENUM
          - BLOB
          - OBJECT
          - ARRAY
          - UNKNOWN
          type: string
      type: object
    BTCylinderDescription-686:
      allOf:
      - $ref: '#/components/schemas/BTSurfaceDescription-1564'
      - $ref: '#/components/schemas/BTCylinderDescription_686_allOf'
      type: object
    BTDefaultUnitInfo:
      properties:
        key:
          type: string
        value:
          type: string
      type: object
    BTDefaultUnitsInfo:
      properties:
        nodeId:
          type: string
        units:
          items:
            $ref: '#/components/schemas/BTDefaultUnitInfo'
          type: array
      type: object
    BTDiffInfo:
      properties:
        collectionChanges:
          additionalProperties:
            items:
              $ref: '#/components/schemas/BTDiffInfo'
            type: array
          type: object
        entityType:
          enum:
          - PARTS
          - SKETCHES
          - POINTS
          - MATE_CONNECTORS
          - PLANES
          - CURVES
          - SURFACES
          type: string
        geometryChangeMessages:
          items:
            type: string
          type: array
        sourceId:
          type: string
        sourceValue:
          type: string
        targetId:
          type: string
        targetValue:
          type: string
        type:
          enum:
          - NONE
          - MOVED
          - MODIFIED
          - MOVED_AND_MODIFIED
          - ADDED
          - DELETED
          - UNKNOWN
          type: string
      type: object
    BTDiscountInfo:
      properties:
        accountBalance:
          format: int32
          type: integer
        amountOff:
          format: int32
          type: integer
        couponType:
          format: int32
          type: integer
        couponValidMonths:
          format: int32
          type: integer
        createdAt:
          format: date-time
          type: string
        createdBy:
          $ref: '#/components/schemas/BTUserSummaryInfo'
        expiresAt:
          format: date-time
          type: string
        href:
          format: uri
          type: string
        id:
          type: string
        name:
          type: string
        ownerId:
          type: string
        percentOff:
          format: int32
          type: integer
        planId:
          type: string
        trialEndDate:
          type: string
        usedAt:
          format: date-time
          type: string
        viewRef:
          format: uri
          type: string
      type: object
    BTDocumentElementInfo:
      properties:
        angleUnits:
          type: string
        dataType:
          type: string
        elementType:
          enum:
          - PARTSTUDIO
          - ASSEMBLY
          - DRAWING
          - FEATURESTUDIO
          - BLOB
          - APPLICATION
          - TABLE
          - BILLOFMATERIALS
          - UNKNOWN
          type: string
        filename:
          type: string
        foreignDataId:
          type: string
        id:
          type: string
        lengthUnits:
          type: string
        massUnits:
          type: string
        microversionId:
          type: string
        name:
          type: string
        specifiedUnit:
          type: string
        thumbnailInfo:
          $ref: '#/components/schemas/BTThumbnailInfo'
        thumbnails:
          format: uri
          type: string
        type:
          type: string
        unupdatable:
          type: boolean
      type: object
    BTDocumentElementProcessingInfo:
      properties:
        angleUnits:
          type: string
        dataType:
          type: string
        elementType:
          enum:
          - PARTSTUDIO
          - ASSEMBLY
          - DRAWING
          - FEATURESTUDIO
          - BLOB
          - APPLICATION
          - TABLE
          - BILLOFMATERIALS
          - UNKNOWN
          type: string
        filename:
          type: string
        foreignDataId:
          type: string
        id:
          type: string
        lengthUnits:
          type: string
        massUnits:
          type: string
        microversionId:
          type: string
        name:
          type: string
        specifiedUnit:
          type: string
        thumbnailInfo:
          $ref: '#/components/schemas/BTThumbnailInfo'
        thumbnails:
          format: uri
          type: string
        translationEventKey:
          type: string
        translationId:
          type: string
        type:
          type: string
        unupdatable:
          type: boolean
      type: object
    BTDocumentInfo:
      discriminator:
        mapping:
          document-processing: '#/components/schemas/BTDocumentProcessingInfo'
        propertyName: jsonType
      properties:
        anonymousAccessAllowed:
          type: boolean
        anonymousAllowsExport:
          type: boolean
        betaCapabilityIds:
          items:
            type: string
          type: array
        canMove:
          type: boolean
        canUnshare:
          type: boolean
        createdAt:
          format: date-time
          type: string
        createdBy:
          $ref: '#/components/schemas/BTUserBasicSummaryInfo'
        createdWithEducationPlan:
          type: boolean
        defaultElementId:
          type: string
        defaultWorkspace:
          $ref: '#/components/schemas/BTWorkspaceInfo'
        description:
          type: string
        documentLabels:
          items:
            $ref: '#/components/schemas/BTDocumentLabelInfo'
          type: array
        documentThumbnailElementId:
          type: string
        duplicateNameViolationError:
          type: string
        hasPendingOwner:
          type: boolean
        hasReleaseRevisionableObjects:
          type: boolean
        hasRelevantInsertables:
          type: boolean
        href:
          format: uri
          type: string
        id:
          type: string
        isContainer:
          type: boolean
        isEnterpriseOwned:
          type: boolean
        isMutable:
          type: boolean
        isOrphaned:
          type: boolean
        isUpgradedToLatestVersion:
          type: boolean
        isUsingManagedWorkflow:
          type: boolean
        jsonType:
          type: string
        likedByCurrentUser:
          type: boolean
        likes:
          format: int64
          type: integer
        modifiedAt:
          format: date-time
          type: string
        modifiedBy:
          $ref: '#/components/schemas/BTUserBasicSummaryInfo'
        name:
          type: string
        notRevisionManaged:
          type: boolean
        numberOfTimesCopied:
          format: int64
          type: integer
        numberOfTimesReferenced:
          format: int64
          type: integer
        owner:
          $ref: '#/components/schemas/BTOwnerInfo'
        parentId:
          type: string
        permission:
          enum:
          - NOACCESS
          - ANONYMOUS_ACCESS
          - READ
          - READ_COPY_EXPORT
          - COMMENT
          - WRITE
          - RESHARE
          - FULL
          - OWNER
          type: string
        permissionSet:
          type: object
        projectId:
          type: string
        public:
          type: boolean
        recentVersion:
          $ref: '#/components/schemas/BTBaseInfo'
        resourceType:
          type: string
        supportTeamUserAndShared:
          type: boolean
        tags:
          items:
            type: string
          type: array
        thumbnail:
          $ref: '#/components/schemas/BTThumbnailInfo'
        totalWorkspacesScheduledForUpdate:
          format: int32
          type: integer
        totalWorkspacesUpdating:
          format: int32
          type: integer
        trash:
          type: boolean
        trashedAt:
          format: date-time
          type: string
        treeHref:
          type: string
        userAccountLimitsBreached:
          type: boolean
        viewRef:
          format: uri
          type: string
      type: object
    BTDocumentLabelInfo:
      properties:
        canMove:
          type: boolean
        createdAt:
          format: date-time
          type: string
        createdBy:
          $ref: '#/components/schemas/BTUserBasicSummaryInfo'
        description:
          type: string
        href:
          format: uri
          type: string
        id:
          type: string
        isContainer:
          type: boolean
        isEnterpriseOwned:
          type: boolean
        isMutable:
          type: boolean
        modifiedAt:
          format: date-time
          type: string
        modifiedBy:
          $ref: '#/components/schemas/BTUserBasicSummaryInfo'
        name:
          type: string
        owner:
          $ref: '#/components/schemas/BTOwnerInfo'
        parentLabelId:
          type: string
        path:
          type: string
        projectId:
          type: string
        resourceType:
          type: string
        treeHref:
          type: string
        viewRef:
          format: uri
          type: string
      type: object
    BTDocumentMergeInfo:
      properties:
        libraryVersionMismatch:
          type: boolean
        overwrittenElements:
          items:
            $ref: '#/components/schemas/BTDocumentElementInfo'
          type: array
      type: object
    BTDocumentParams:
      properties:
        betaCapabilityIds:
          items:
            type: string
          type: array
        description:
          type: string
        generateUnknownMessages:
          type: boolean
        isEmptyContent:
          type: boolean
        isPublic:
          type: boolean
        name:
          type: string
        notRevisionManaged:
          type: boolean
        ownerEmail:
          type: string
        ownerId:
          type: string
        ownerType:
          format: int32
          type: integer
        parentId:
          type: string
        projectId:
          type: string
        tags:
          items:
            type: string
          type: array
      type: object
    BTDocumentProcessingInfo:
      allOf:
      - $ref: '#/components/schemas/BTDocumentInfo'
      - $ref: '#/components/schemas/BTDocumentProcessingInfo_allOf'
      type: object
    BTDocumentSearchHitInfo:
      properties:
        documentId:
          type: string
        elementName:
          type: string
        highlightedFields:
          additionalProperties:
            items:
              type: string
            type: array
          type: object
        name:
          type: string
        sourceMap:
          additionalProperties:
            type: object
          type: object
        type:
          type: string
        versionOrWorkspaceName:
          type: string
      type: object
    BTDocumentSearchParams:
      properties:
        documentFilter:
          format: int32
          type: integer
        foundIn:
          enum:
          - ALL
          - WORKSPACES
          - VERSIONS
          type: string
        limit:
          format: int32
          type: integer
        offset:
          format: int32
          type: integer
        ownerId:
          type: string
        parentId:
          type: string
        rawQuery:
          type: string
        sortColumn:
          type: string
        sortOrder:
          type: string
        type:
          type: string
        when:
          enum:
          - ALL
          - LATEST
          - LATEST_PER_HIT
          type: string
      type: object
    BTDocumentSummaryInfo:
      allOf:
      - $ref: '#/components/schemas/BTGlobalTreeNodeInfo'
      - $ref: '#/components/schemas/BTDocumentSummaryInfo_allOf'
      discriminator:
        mapping:
          document: '#/components/schemas/BTDocumentInfo'
          document-summary-search: '#/components/schemas/BTDocumentSummarySearchInfo'
        propertyName: jsonType
      properties:
        jsonType:
          type: string
      type: object
    BTDocumentSummarySearchInfo:
      allOf:
      - $ref: '#/components/schemas/BTDocumentSummaryInfo'
      - $ref: '#/components/schemas/BTDocumentSummarySearchInfo_allOf'
      type: object
    BTDocumentVersionElementIds-1897:
      properties:
        btType:
          type: string
        documentId:
          type: string
        elementId:
          type: string
        versionId:
          type: string
      type: object
    BTDocumentWithVersionAndElementId:
      properties:
        documentId:
          type: string
        documentVersionId:
          type: string
        elementId:
          type: string
        partNumber:
          type: string
        revision:
          type: string
        uniqueVersionId:
          type: string
        validRevisionReference:
          type: boolean
      type: object
    BTDocumentWithVersionId:
      properties:
        documentId:
          type: string
        documentVersionId:
          type: string
      type: object
    BTDrawingParams:
      properties:
        border:
          type: boolean
        computeIntersection:
          type: boolean
        decimalSeparator:
          type: string
        documentId:
          type: string
        documentMicroversionId:
          type: string
        drawingName:
          type: string
        elementConfiguration:
          type: string
        elementId:
          type: string
        elementMicroversionId:
          type: string
        externalDocumentId:
          type: string
        externalDocumentVersionId:
          type: string
        hiddenLines:
          enum:
          - DRAFTING
          - EXCLUDED
          - MARKED
          type: string
        includeSurfaces:
          type: boolean
        isFlattenedPart:
          type: boolean
        isSketchOnly:
          type: boolean
        isSurface:
          type: boolean
        language:
          type: string
        location:
          $ref: '#/components/schemas/BTElementLocationParams'
        modelType:
          type: string
        numberHorizontalZones:
          format: int32
          type: integer
        numberVerticalZones:
          format: int32
          type: integer
        partId:
          type: string
        partNumber:
          type: string
        partQuery:
          type: string
        projection:
          type: string
        pureSketch:
          type: boolean
        qualityOption:
          type: string
        referenceType:
          format: int32
          type: integer
        referenceTypeEnum:
          enum:
          - UNKNOWN
          - PARTSTUDIO
          - ASSEMBLY
          - PART
          - FLATTENED_PART
          - COMPOSITE_PART
          - MESH_PART
          - SURFACE
          - SKETCH
          - CURVE
          type: string
        revision:
          type: string
        showCutGeomOnly:
          type: boolean
        simplificationOption:
          type: string
        simplificationThreshold:
          format: double
          type: number
        size:
          type: string
        sketchIds:
          items:
            type: string
          type: array
        standard:
          type: string
        startZones:
          type: string
        templateArgs:
          items:
            type: string
          type: array
        templateDocumentId:
          type: string
        templateElementId:
          type: string
        templateName:
          type: string
        templateVersionId:
          type: string
        templateWorkspaceId:
          type: string
        titleblock:
          type: boolean
        units:
          type: string
        views:
          type: string
        workspaceId:
          type: string
      type: object
    BTEdgeTopologyFilter-122:
      allOf:
      - $ref: '#/components/schemas/BTQueryFilter-183'
      - $ref: '#/components/schemas/BTEdgeTopologyFilter_122_allOf'
      type: object
    BTEditingLogic-2350:
      properties:
        functionName:
          type: string
        wantsHiddenBodies:
          type: boolean
        wantsIsCreating:
          type: boolean
        wantsSpecifiedParameters:
          type: boolean
      type: object
    BTElementLocationParams:
      properties:
        elementId:
          type: string
        groupId:
          type: string
        position:
          format: int32
          type: integer
      type: object
    BTElementReference-725:
      discriminator:
        mapping:
          BTExternalReference-1936: '#/components/schemas/BTExternalReference-1936'
        propertyName: btType
      properties:
        btType:
          type: string
        configured:
          type: boolean
        elementId:
          type: string
        externalDocumentWithVersion:
          $ref: '#/components/schemas/BTDocumentWithVersionId'
        externalDocumentWithVersionAndElementId:
          $ref: '#/components/schemas/BTDocumentWithVersionAndElementId'
        externalReference:
          type: boolean
        fullElementId:
          $ref: '#/components/schemas/BTFullElementId-756'
        microversionIdAndConfiguration:
          $ref: '#/components/schemas/BTMicroversionIdAndConfiguration-2338'
        nodeId:
          type: string
      type: object
    BTEllipseDescription-866:
      allOf:
      - $ref: '#/components/schemas/BTCurveDescription-1583'
      - $ref: '#/components/schemas/BTEllipseDescription_866_allOf'
      type: object
    BTEncodedConfigurationInfo:
      properties:
        encodedId:
          type: string
        queryParam:
          type: string
        queryParam_:
          type: string
          writeOnly: true
      type: object
    BTEntityTypeFilter-124:
      allOf:
      - $ref: '#/components/schemas/BTQueryFilter-183'
      - $ref: '#/components/schemas/BTEntityTypeFilter_124_allOf'
      type: object
    BTExplosion-2754:
      allOf:
      - $ref: '#/components/schemas/BTMAssemblyFeature-887'
      - $ref: '#/components/schemas/BTExplosion_2754_allOf'
      type: object
    BTExplosionStepFeature-3008:
      allOf:
      - $ref: '#/components/schemas/BTMAssemblyFeature-887'
      - $ref: '#/components/schemas/BTConfiguredFeatureColumnInfo_1014_allOf'
      type: object
    BTExportModelArcEdgeGeometry-1257:
      allOf:
      - $ref: '#/components/schemas/BTExportModelEdgeGeometry-1125'
      - $ref: '#/components/schemas/BTExportModelArcEdgeGeometry_1257_allOf'
      type: object
    BTExportModelBodiesResponse-734:
      properties:
        bodies:
          items:
            $ref: '#/components/schemas/BTExportModelBody-1272'
          type: array
        errorEnum:
          enum:
          - NO_ERROR
          - UNKNOWN_OPERATION
          - TOO_MANY_ENTITIES_SELECTED
          - POINTS_COINCIDENT
          - NO_TRANSLATION_DIRECTION
          - NO_ROTATION_AXIS
          - NO_TANGENT_PLANE
          - NO_TANGENT_LINE
          - INVALID_INPUT
          - CANNOT_RESOLVE_ENTITIES
          - CANNOT_EVALUATE_VERTEX
          - CANNOT_RESOLVE_PLANE
          - CANNOT_COMPUTE_BBOX
          - CANNOT_BE_EMPTY
          - CACHE_WRITE_FAILED
          - CACHE_READ_FAILED
          - HLR_FAILED
          - BAD_GEOMETRY
          - INVALID_RESULT
          - MISSING_EXT_REF
          - READ_FAILED
          - WRITE_FAILED
          - WRONG_TYPE
          - TANGENT_PROPAGATION_FAILED
          - REGEN_ERROR
          - COULD_NOT_COMPUTE_TRANSFORM
          - MATE_INVALID_MATE
          - MATECONNECTOR_INVALID_MATE
          - MATE_TWO_MATECONNECTORS_NEEDED
          - MATECONNECTORS_ON_SAME_OCCURRENCE
          - MATE_OVERDEFINED
          - MATE_INCONSISTENT
          - BOOLEAN_NEED_ONE_SOLID
          - BOOLEAN_INVALID
          - BOOLEAN_INTERSECT_FAIL
          - BOOLEAN_SAME_INPUT
          - BOOLEAN_BAD_INPUT
          - BOOLEAN_UNION_NO_OP
          - BOOLEAN_INTERSECT_NO_OP
          - BOOLEAN_SUBTRACT_NO_OP
          - CPLANE_INPUT_MIDPLANE
          - CPLANE_INPUT_OFFSET_PLANE
          - CPLANE_INPUT_POINT_PLANE
          - CPLANE_INPUT_LINE_ANGLE
          - CPLANE_INPUT_POINT_LINE
          - CPLANE_INPUT_THREE_POINT
          - CPLANE_FAILED
          - DRAFT_NO_NEUTRAL_PLANE
          - DRAFT_NO_DRAFT_FACE
          - DRAFT_FAILED
          - EXTRUDE_INVALID_REF_FACE
          - EXTRUDE_INVALID_REF_SURFACE
          - EXTRUDE_FAILED
          - EXTRUDE_NO_DIRECTION
          - EXTRUDE_INVALID_ENTITIES
          - PATTERN_INPUT_TOO_MANY_INSTANCES
          - PATTERN_INPUT_TOO_FEW_INSTANCES
          - PATTERN_FACE_FAILED
          - PATTERN_NOT_ON_BODY
          - PATTERN_BODY_FAILED
          - TRANSFORM_TRANSLATE_INPUT
          - TRANSFORM_TRANSLATE_BY_DISTANCE_INPUT
          - TRANSFORM_FAILED
          - SHELL_FAILED
          - EDGEBLEND_SMOOTH
          - EDGEBLEND_FAILED
          - DIRECT_EDIT_WRONG_CONCENTRIC
          - DIRECT_EDIT_WRONG_EQ_RADIUS
          - DIRECT_EDIT_NO_FILLET_FACES
          - DIRECT_EDIT_NO_OFFSET
          - DIRECT_EDIT_CONSTRAIN_FACE_FAILED
          - DIRECT_EDIT_REPLACE_FACE_FAILED
          - DIRECT_EDIT_DELETE_FACE_FAILED
          - DIRECT_EDIT_MODIFY_FILLET_FAILED
          - DIRECT_EDIT_MODIFY_FACE_FAILED
          - DIRECT_EDIT_MOVE_FACE_FAILED
          - DIRECT_EDIT_OFFSET_FACE_FAILED
          - IMPORT_PART_FAILED
          - IMPORT_ASSEMBLY_FAILED
          - IMPRINT_FAILED
          - REVOLVE_FAILED
          - REVOLVE_2ND_DIR_FAILED
          - REVOLVE_NOT_PLANAR
          - REVOLVE_PERPENDICULAR
          - REVOLVE_INVALID_ENTITIES
          - SPLIT_FAILED
          - SPLIT_INVALID_INPUT
          - SWEEP_INVALID_PATH
          - SWEEP_FAILED
          - SWEEP_PATH_FAILED
          - SWEEP_PROFILE_FAILED
          - WIRE_CREATION_FAILED
          - SKETCH_NO_PLANE
          - SKETCH_INPUT_INVALID
          - SKETCH_NOT_ACTIVE
          - SKETCH_SOLVER_NOT_INITIALIZED
          - SKETCH_EVALUATION_FAILED
          - SKETCH_MODIFICATION_FAILED
          - SKETCH_UPDATE_FAILED
          - SKETCH_SOLVE_FAILED
          - SKETCH_ADD_CONSTRAINT_FAILED
          - SKETCH_ADD_DIMENSION_FAILED
          - SKETCH_POSITION_DIMENSION_FAILED
          - SKETCH_CONSTRAINT_NEEDS_SKETCH_ENTITY
          - SKETCH_CONSTRAINT_UNKNOWN
          - SKETCH_MISSING_ENTITY
          - SKETCH_FILLET_INVALID_POINT
          - SKETCH_FILLET_PARALLEL
          - SKETCH_FILLET_FAIL
          - SKETCH_USE_FAILED
          - SKETCH_USE_PARTIAL
          - SKETCH_SPLINE_FAILED
          - SKETCH_BAD_SPLINE
          - SKETCH_DRAG_ERROR
          - SKETCH_PROJ_FAILED
          - SKETCH_PROJ_PARTIAL
          - SKETCH_TANGENT_ARC_FAILED
          - SKETCH_TANGENT_NOT_FOUND
          - SKETCH_OFFSET_FAILED
          - SKETCH_OFFSET_DISTANCE
          - SKETCH_TRIM_FAILED
          - SKETCH_INFERENCE_FAILED
          - SKETCH_MODIFY_DIM_FAILED
          - SKETCH_DRAG_NO_SKETCH
          - SKETCH_INFER_DIM_FAILED
          - SKETCH_DELETE_PTS_FAILED
          - SKETCH_DELETE_FAILED
          - SKETCH_ARC_FAILED
          - SKETCH_LINE_FAILED
          - SKETCH_CIRCLE_FAILED
          - SKETCH_RECTANGLE_FAILED
          - SKETCH_TANGENT_ARC_INVALID_START
          - SKETCH_CONSTRUCTION_POINT_FAILED
          - SYS_INTERNAL_DESERIALIZATION
          - SYS_SERVER_EXCEPTION
          - SYS_ERROR_REGEN
          - SYS_ERROR_MESSAGING
          - CANNOT_RESOLVE_ELEMENT
          - NOTHING_SELECTED
          - SKETCH_ANGLE_TWO_LINES
          - SKETCH_DIMENSION_DIFF_ENTITIES
          - SKETCH_CONSTRAINT_DIFF_ENTITIES
          - SKETCH_CONSTRAINT_TWO_ENTITIES
          - SKETCH_DIMENSION_TWO_ENTITIES
          - SKETCH_COINCIDENT_FAILED
          - SKETCH_COINCIDENT_INPUT_ERROR
          - SKETCH_COINCIDENT_DIFF_POINTS
          - SKETCH_CONCENTRIC_INPUT_ERROR
          - SKETCH_CONCENTRIC_FAILED
          - SKETCH_EQUAL_INPUT_ERROR
          - SKETCH_EQUAL_NO_ENDS
          - SKETCH_EQUAL_FAILED
          - SKETCH_FIX_ONE_ENT
          - SKETCH_FIX_FAILED
          - SKETCH_DIR_INTERNAL
          - SKETCH_DIR_INPUT
          - SKETCH_HORIZONTAL_FAILED
          - SKETCH_VERTICAL_FAILED
          - SKETCH_OFFSET_CONSTRAINT_FAILED
          - SKETCH_PARALLEL_CONSTRAINT_FAILED
          - SKETCH_PARALLEL_INPUT_ERROR
          - SKETCH_DIMENSION_INPUT_ERROR
          - SKETCH_DIMENSION_DIST_ERROR
          - SKETCH_DIMENSION_FAILED
          - SKETCH_NORMAL_NEED_LINE
          - SKETCH_NORMAL_INPUT_ERROR
          - SKETCH_NORMAL_INPUT_NEEDED
          - SKETCH_CANNOT_SPLIT_INTO_GROUPS
          - SKETCH_OFFSET_BAD_PAIR
          - SKETCH_OFFSET_INPUT_ERROR
          - SKETCH_MIDPOINT_INPUT_ERROR
          - SKETCH_MIDPOINT_NEED_POINT
          - SKETCH_MIDPOINT_NEED_DIFF_POINT
          - SKETCH_MIDPOINT_MISSING_ENDS
          - SKETCH_MIDPOINT_MISSING_PTS
          - SKETCH_MIDPOINT_NO_INTERNAL_LINE
          - SKETCH_MIDPOINT_NO_COINCIDENT
          - SKETCH_MIDPOINT_FAILED
          - SKETCH_PERPENDICULAR_INPUT_ERROR
          - SKETCH_PERPENDICULAR_FAILED
          - SKETCH_POINT_LINE_ONLY
          - SKETCH_PROJECTION_UNKNOWN
          - SKETCH_PROJECTION_FAILED
          - SKETCH_SIL_PROJECTION_INPUT_ERROR
          - SKETCH_SIL_PROJECTION_MISSING_POINT
          - SKETCH_LENGTH_DIM_INPUT_ERROR
          - SKETCH_LENGTH_DIM_MISSING_ENDS
          - SKETCH_LENGTH_DIM_NOT_FOUND
          - SKETCH_LENGTH_DIM_FAILED
          - SKETCH_RADIUS_INPUT_ERROR
          - SKETCH_RADIUS_DIM_FAILED
          - SKETCH_TANGENT_INPUT_ERROR
          - SKETCH_TANGENT_FAILED
          - PART_QUERY_FAILED
          - PART_QUERY_MULTI
          - MATECONNECTOR_QUERY_FAILED
          - MATECONNECTOR_QUERY_ORIGIN_FAILED
          - MATECONNECTOR_QUERY_AXIS_FAILED
          - MATECONNECTOR_QUERY_CSYS_FAILED
          - ASSEMBLY_INSERT_WILL_CAUSE_CYCLES
          - SKETCH_MIRROR_NEED_VALID_MIRROR_LINE
          - SKETCH_MIRROR_NEED_ENTITIES_TO_MIRROR
          - SKETCH_MIRROR_CONSTRAINT_FAILED
          - SKETCH_MIRROR_FAILED
          - SELF_INTERSECTING_CURVE_SELECTED
          - SWEEP_START_NOT_ON_PROFILE
          - PATTERN_DIRECTIONS_PARALLEL
          - MATE_OCCURRENCE_NOT_VALID
          - MATE_WITHIN_SAME_GROUP
          - EXPORT_ASSEMBLY_UNKNOWN_NODE_TYPE
          - EXPORT_ASSEMBLY_CREATE_INSTANCE_FAILED
          - EXPORT_PARTS_AS_XTS_NOT_A_BODY
          - EXPORT_PARTS_AS_XTS_FAILED_TO_WRITE_XT
          - MATECONNECTOR_OWNER_PART_NOT_RESOLVED
          - WIRE_CREATION_PARTIAL_FAILURE
          - SERVER_IS_IN_INVALID_STATE
          - SKETCH_EXTEND_FAILED
          - FOLLOW_CYCLE_ERROR
          - SKETCH_FILLET_INVALID_RADIUS
          - SKETCH_CONSTRAINT_COINCIDENT_TWO_ENTITIES
          - SKETCH_CONSTRAINT_CONCENTRIC_TWO_ENTITIES
          - SKETCH_CONSTRAINT_EQUAL_TWO_ENTITIES
          - SKETCH_CONSTRAINT_MIDPOINT_TWO_ENTITIES
          - EXTRUDE_NO_SELECTED_REGION
          - EXTRUDE_NO_REGION_IN_SKETCH
          - DELETE_SELECT_PARTS
          - COPY_SELECT_PARTS
          - SPLIT_NO_CHANGE
          - MIRROR_NO_PLANE
          - MIRROR_SELECT_PARTS
          - PATTERN_CIRCULAR_NO_AXIS
          - PATTERN_SELECT_FACES
          - PATTERN_SELECT_PARTS
          - PATTERN_LINEAR_NO_DIR
          - SHELL_SELECT_FACES
          - DRAFT_SELECT_NEUTRAL
          - DRAFT_SELECT_FACES
          - CHAMFER_SELECT_EDGES
          - FILLET_SELECT_EDGES
          - EXTRUDE_SURF_NO_CURVE
          - EXTRUDE_SELECT_TERMINATING_BODY
          - EXTRUDE_SELECT_TERMINATING_SURFACE
          - DIRECT_EDIT_SELECT_ANCHOR
          - REVOLVE_SURF_NO_CURVE
          - REVOLVE_SELECT_FACES
          - REVOLVE_SELECT_AXIS
          - SWEEP_SELECT_PROFILE
          - SWEEP_SELECT_PATH
          - DIRECT_EDIT_DELETE_SELECT_FACES
          - DIRECT_EDIT_MODIFY_FILLET_SELECT
          - DIRECT_EDIT_MODIFY_FACE_SELECT
          - DIRECT_EDIT_REPLACE_FACE_SELECT
          - DIRECT_EDIT_OFFSET_FACE_SELECT
          - DIRECT_EDIT_MOVE_FACE_SELECT
          - SELECT_MATECONNECTOR
          - OVERDEFINED_ASSEMBLY
          - PART_STUDIO_UPGRADE_SUCCESSFUL
          - PART_STUDIO_UPGRADE_FAILED
          - PART_STUDIO_UPGRADE_NONE
          - MATE_GROUP_OCCURRENCES_UNRESOLVED
          - SWEEP_SURF_NO_CURVE_PROFILE
          - MATE_RESET_HAD_NO_EFFECT
          - MATECONNECTOR_MULTIPLE_OCCURRENCES
          - MATECONNECTOR_OCCURRENCE_NOT_RESOLVED
          - ELEMENT_REFERENCE_CYCLE_DETECTED
          - MATE_OVERDEFINES_ASSEMBLY
          - MATE_CANNOT_RESOLVE_CONNECTORS
          - SKETCH_EXCEEDS_BOUNDS
          - SWEEP_SELF_INT
          - SKETCH_UNSOLVABLE_CONSTRAINT
          - RESTRUCTURE_INVALID_SOURCE_OR_TARGET
          - CPLANE_INPUT_CURVE_POINT
          - TRANSFORM_OCCURRENCES_HAD_NO_EFFECT
          - HELIX_FAILED
          - HELIX_INPUT_CONE
          - RENDERER_NOT_AVAILABLE
          - RENDERER_FAILED_TO_RENDER
          - EXPRESSION_FAILED_VALIDATION
          - VERSION_MISMATCH_ERROR
          - EXTRUDE_UPTO_NEXT_NO_DIVISION
          - MATE_BETWEEN_FIXED_OCCURRENCES
          - THICKEN_SELECT_ENTITIES
          - THICKEN_FAILED
          - WORKSPACE_UPGRADE_SUCCESSFUL
          - WORKSPACE_UPGRADE_FAILED
          - WORKSPACE_UPGRADE_NONE
          - SKETCH_CIRCULAR_PATTERN_FAILED
          - DIRECT_EDIT_ALL_FILLET_FACES_SELECTED
          - DIRECT_EDIT_FAILED_TO_IDENTIFY_FILLETS
          - PARASOLID_IMPORT_FAILED
          - FOLLOW_LEADER_HAS_NO_FUNCTIONALITY_ERROR
          - MIRROR_SELECT_FACES
          - RELATION_INVALID_RELATION
          - RELATION_INVALID_MATE
          - GEAR_RELATION_INVALID_MATE_TYPES
          - SCREW_RELATION_INVALID_MATE_TYPES
          - RACK_RELATION_INVALID_MATE_TYPES
          - ROLLING_RELATION_INVALID_MATE_TYPES
          - LINEAR_RELATION_INVALID_MATE_TYPES
          - RELATION_OVERDEFINED
          - RELATION_INCONSISTENT
          - RELATION_SAME_OCCURRENCES
          - SKETCH_SPLIT_FAILED
          - SKETCH_CONSTRAINT_PIERCE_TWO_ENTITIES
          - SKETCH_PIERCE_FAILED
          - MIRROR_FACE_FAILED
          - MIRROR_BODY_FAILED
          - SKETCH_CANNOT_PIERCE_WITH_PLANE
          - WITH_SUPPORT_CODE
          - FILLET_FAIL_SMOOTH
          - FILLET_FAILED
          - CHAMFER_FAIL_SMOOTH
          - CHAMFER_FAILED
          - BOOLEAN_OFFSET_NO_FACES
          - MATE_OCCURRENCE_SUPPRESSED
          - MATECONNECTOR_OCCURRENCE_SUPPRESSED
          - SKETCH_SPLINE_NEW_POINTS_TOO_CLOSE
          - SKETCH_SPLINE_CANNOT_DELETE_ENDPOINTS
          - SKETCH_SPLINE_POINT_TO_DELETE_NOT_FOUND
          - ASSEMBLY_INSERT_FAILED
          - SKETCH_PATTERN_UNKNOWN_FAILURE
          - SKETCH_PATTERN_TOO_LARGE
          - SKETCH_LINEAR_PATTERN_ZERO_LENGTH
          - SKETCH_LINEAR_PATTERN_PARALLEL_DIRECTIONS
          - SKETCH_CIRCULAR_PATTERN_ZERO_ANGLE
          - SKETCH_ELLIPSE_FAILED
          - SKETCH_ELLIPSE_FAILED_TOO_SMALL
          - DELETE_PARTS_FAILED
          - DELETE_PARTS_PARTIAL
          - SKETCH_ELLIPSE_RADIUS_INPUT_ERROR
          - QUADRANT_CONSTRAINT_INPUT
          - SKETCH_QUADRANT_FAILED
          - SKETCH_SPLINE_TOO_FEW_POINTS
          - SKETCH_SPLINE_NOT_INTERPOLATED_SPLINE
          - SKETCH_SPLINE_POINTS_NOT_DELETED
          - SKETCH_TEXT_RECTANGLE_FAILED
          - IMPORT_DERIVED_NO_PARTS
          - LOFT_SELECT_PROFILES
          - LOFT_PROFILE_SINGLE_FACE
          - LOFT_PROFILE_SOLID
          - LOFT_PROFILE_POINT
          - LOFT_PROFILE_FAILED
          - LOFT_SELECT_GUIDES
          - LOFT_GUIDE_FAILED
          - LOFT_PERIODIC_ERROR
          - LOFT_GUIDE_POINT_INTERSECTION
          - LOFT_GUIDE_PROFILE_INTERSECTION
          - LOFT_VERTEX_MATCHING
          - LOFT_DIRECTION_ERROR
          - LOFT_PROFILE_ALIGNMENT
          - LOFT_GUIDE_ALIGNMENT
          - LOFT_VERTEX_ADDITIONS
          - LOFT_FAILED
          - LOFT_INVALID
          - LOFT_ALIGNMENT_INFO
          - LOFT_VERTEX_NOT_ON_PROFILE
          - LOFT_PROFILE_NO_INNER_LOOPS
          - LOFT_TWO_PROFILES
          - CANNOT_OFFSET_ELLIPSE
          - SKETCH_MIRROR_NEEDS_LINE_AND_TWO_OTHERS
          - SKETCH_POLYGON_BAD_SIDE_COUNT
          - SKETCH_DIRECTIONAL_GROUP_INPUT
          - NAMED_VIEWS_DUPLICATE_NAME
          - SILHOUETTE_USE_FAILED
          - PASTE_SKETCH_METRICS_FAILURE
          - PASTE_SKETCH_LIBRARY_MISMATCH
          - PASTE_SKETCH_CLIPBOARD_EMPTY
          - SKETCH_MIRROR_OFFSET_SPLINE
          - SKETCH_MIRROR_CURVE_POINT
          - LOFT_PERIODIC_GUIDE_ERROR
          - SHELL_SELECT_PARTS
          - RELATION_MATE_DOES_NOT_EXIST
          - RELATION_MATE_IS_SUPPRESSED
          - VARIABLE_NAME_INVALID
          - LOFT_GUIDE_INFO
          - HOLE_NO_POINTS
          - HOLE_FAIL_BBOX
          - HOLE_EMPTY_SCOPE
          - HOLE_NO_HITS
          - WITH_EXTRA_DATA
          - HOLE_DISJOINT
          - SKETCH_INSERT_DWG_CONVERSION_FAILURE
          - HOLE_CBORE_TOO_SMALL
          - HOLE_CBORE_TOO_DEEP
          - HOLE_CSINK_TOO_SMALL
          - HOLE_CSINK_TOO_DEEP
          - SWEEP_PATH_NO_CONSTRUCTION
          - SKETCH_IMAGE_RECTANGLE_FAILED
          - ASSEMBLY_REPLICATE_NO_VALID_TARGET
          - ASSEMBLY_REPLICATE_NO_MATCHING_TARGET
          - LOFT_SHAPE_CONTROL_FAILED
          - LOFT_START_CONDITIONS_FAILED
          - LOFT_END_CONDITIONS_FAILED
          - LOFT_NO_FACE_FOR_START_CLAMP
          - LOFT_NO_FACE_FOR_END_CLAMP
          - LOFT_NO_PLANE_FOR_START_CLAMP
          - LOFT_NO_PLANE_FOR_END_CLAMP
          - LOFT_NO_CLAMPS_ON_POINT_PROFILE
          - EXPORT_NOT_IMPLEMENTED
          - SKETCH_POLYGON_ZERO_RADIUS_FAIL
          - DRAWING_FAILED_TO_RESOLVE_VIEW_REFERENCE
          - DRAWING_PARTSTUDIO_EMPTY_AFTER_SECTION_CUT
          - DRAWING_ASSEMBLY_DOES_NOT_CONTAIN_VISIBLE_INSTANCES
          - DRAWING_ASSEMBLY_EMPTY_AFTER_SECTION_CUT
          - DRAWING_VIEW_GENERATION_FAILED
          - SKETCH_SLOT_FAILURE
          - SKETCH_SLOT_PARTIAL_FAILURE
          - NO_UNIT
          - RESTRUCTURE_INVALID_SOURCE
          - RESTRUCTURE_INVALID_TARGET
          - MATE_MIN_MAX_LIMIT_VIOLATION
          - REST_ASSEMBLY_GET_DOCUMENT_FAILED
          - REST_ASSEMBLY_UNKNOWN_INSERTABLE_TYPE
          - REST_ASSEMBLY_SETUP_EXCEPTION
          - REST_ASSEMBLY_BEGIN_OPERATION_FAILED
          - REST_ASSEMBLY_INSERT_INSTANCE_FAILED
          - REST_ASSEMBLY_COMMIT_OPERATION_FAILED
          - REST_ASSEMBLY_CLOSE_CLIENT_FAILED
          - REST_ASSEMBLY_NULL_OCCURRENCES
          - REST_ASSEMBLY_EMPTY_OCCURRENCE
          - REST_ASSEMBLY_TRANSFORM_WRONG_SIZE
          - ASSEMBLY_EMPTY_OCCURRENCE_LIST
          - ASSEMBLY_NULL_TRANSFORM
          - ASSEMBLY_TRANSFORM_NOT_RIGID
          - ASSEMBLY_CANNOT_TRANSFORM_FIXED_OCCURRENCE
          - ASSEMBLY_TRANSFORM_FAILED
          - ASSEMBLY_OCCURRENCE_NOT_FOUND
          - ASSEMBLY_REPLICATE_MULTIPLE_VALID_TARGET
          - ASSEMBLY_REPLICATE_NO_TARGET_SELECTED
          - CPLANE_INPUT_LINE_ANGLE2
          - CPLANE_DEGENERATE_SELECTION
          - CPLANE_SELECT_LINE_ANGLE_REFERENCE
          - ASSEMBLY_REPLICATE_INVALID_SEED_INSTANCE
          - CANNOT_USE_VARIABLES_IN_SKETCH_PATTERNS
          - SKETCH_MIRROR_OFFSET_ELLIPSE
          - EXTERNAL_REFERENCE_FAILED_TO_CREATE
          - SPLIT_FACE_NO_CHANGE
          - SKETCH_INTERSECTION_FAILED
          - SKETCH_INTERSECTION_MULTIPLE_FAILED
          - SKETCH_INTERSECTION_PARTIAL_FAILED
          - FEATURE_ID_IN_PATH_DOES_NOT_MATCH_BODY
          - FEATURE_NOT_FOUND
          - FEATURE_DOES_NOT_MATCH
          - FEATURE_HAS_INVALID_TYPE
          - FEATURE_DOES_NOT_MATCH_ITS_FEATURE_SPEC
          - FEATURE_BAD_SERIALIZATION_VERSION
          - FEATURE_WRONG_SERIALIZATION_VERSION
          - FEATURE_INVALID_ROLLBACK_INDEX
          - FEATURE_ERROR_IN_INPUT
          - FEATURE_CONCURRENCY_ERROR
          - FEATURE_CHANGE_BREAKS_MODEL
          - FEATURE_NODE_IDS_INVALID
          - ROLLBACK_INDEX_INVALID
          - FEATURE_NO_SOLIDS
          - SKETCH_EXTERNAL_GEOMETRY_MISMATCH
          - HOLE_EXCEEDS_MAX_LOCATIONS
          - SKETCH_TEXT_IS_EMPTY
          - SKETCH_INSERT_DWG_MAX_ENTITIES_EXCEEDED
          - HOLE_TAP_DIA_TOO_LARGE
          - ASSEMBLY_EMPTY_BODY
          - SIMPLIFY_BODY_FAILED
          - INVALID_VIEW_NAME
          - PATTERN_SELECT_FEATURES
          - MIRROR_SELECT_FEATURES
          - PATTERN_FEATURE_FAILED
          - SKETCH_TRANSFORM_FAILED
          - TANGENT_MATE_TWO_ENTITIES_NEEDED
          - HOLE_CANNOT_DETERMINE_LAST_BODY
          - RESTRUCTURE_CANNOT_MODIFY_SAVED_VERSION
          - REST_ASSEMBLY_EXTERNAL_REFERENCE_REQUIRES_VERSION
          - REST_ASSEMBLY_EXTERNAL_REFERENCE_DISALLOWS_MICROVERSION
          - REST_ASSEMBLY_VERSION_SUPPORTED_ONLY_FOR_EXTERNAL_REFERENCES
          - SWEEP_BAD_LOCK_FACES
          - SKETCH_TEXT_CANNOT_BE_CONSTRUCTION
          - CUSTOM_ERROR
          - BEND_BAD_CONFIGURATION
          - BEND_WRONG_NUMBER_OF_ENTITIES
          - BEND_BAD_CURVES
          - BEND_GENERAL_ERROR
          - BEND_EDGE_NO_EDGES
          - BEND_EDGE_NO_SEED_ENTITY
          - EXTEND_SHEET_BODY_NO_BODY
          - EXTRACT_SURFACE_NO_FACES
          - FLATTEN_NO_EDGES
          - FLATTEN_NO_FACES
          - FOLD_NO_BODIES
          - BEND_PREP_NO_FACES
          - BEND_PREP_NO_BODIES
          - BEND_PREP_ERROR_FINDING_EDGE_LOCATIONS
          - BEND_PREP_ERROR_IMPRINTING_EDGES
          - ASSEMBLY_ANIMATE_MATE_START_AFTER_END
          - ASSEMBLY_ANIMATE_NO_MATE
          - ASSEMBLY_ANIMATE_MATE_SUPPRESSED
          - TANGENT_MATE_GEOMETRY_NOT_SUPPORTED
          - SKETCH_DIMENSION_INFINITY
          - BOLEAN_INPUTS_NOT_SOLID
          - FACE_IS_NOT_RECTANGLE
          - HOLE_DESTROY_SOLID
          - HELIX_INPUT_CIRCLE
          - IMPORT_SCALING_NON_MESH_DATA
          - EVALUATE_FACE_TANGENT_FOR_MESHES
          - CANNOT_COMPUTE_CENTROID
          - CANNOT_EVALUATE_DIMENSION
          - CANNOT_IMPORT_MESH
          - SKETCH_ELLIPSE_ZERO_AXIS
          - TRANSFORM_SCALE_UNIFORMLY
          - TRANSFORM_MATE_CONNECTORS
          - ASSEMBLY_WRONG_ELEMENT_TYPE
          - ASSEMBLY_ELEMENT_NOT_FOUND
          - SHEET_METAL_TABLE_UNKNOWN_ERROR
          - SHEET_METAL_TABLE_REGEN_ERROR
          - SHEET_METAL_TABLE_READ_ONLY
          - ASSEMBLY_PATTERN_INVALID_TYPE
          - ASSEMBLY_PATTERN_DIRECTION_ERROR
          - ASSEMBLY_PATTERN_NONPOSITIVE_LINEAR_DISTANCE
          - ASSEMBLY_PATTERN_NONPOSITIVE_ANGLE
          - ASSEMBLY_PATTERN_INVALID_SEED
          - ASSEMBLY_PATTERN_INVALID_REFERENCE_MATE_CONNECTOR
          - RESTORE_FEATURE_FAILED
          - FACES_NOT_OWNED_BY_PARTS
          - EDGES_NOT_OWNED_BY_PARTS
          - SHEET_METAL_REBUILD_ERROR
          - SHEET_METAL_INPUT_BODY_SHOULD_NOT_BE_SHEET_METAL
          - SHEET_METAL_CANNOT_RECOGNIZE_PARTS
          - SHEET_METAL_CANNOT_THICKEN
          - SHEET_METAL_CONVERT_PLANE
          - ASSEMBLY_PATTERN_AXIS_ERROR
          - RIB_NO_PROFILES
          - RIB_NO_PARTS
          - RIB_PROFILE_FAILED
          - RIB_BODY_FAILED
          - RIB_NO_INTERSECTIONS
          - RIB_MERGE_FAILED
          - ASSEMBLY_NAMED_POSITIONS_SAVE_FAILED
          - ASSEMBLY_NAMED_POSITIONS_LOAD_FAILED
          - ASSEMBLY_NAMED_POSITIONS_NO_MATES_TO_SAVE
          - ASSEMBLY_NAMED_POSITIONS_POSITION_NOT_FOUND
          - SPHERE_FAILED
          - ASSEMBLY_PATTERN_NOT_SUPPORTED
          - ASSEMBLY_NAMED_POSITIONS_PARTIAL_LOAD_FAILURE
          - ASSEMBLY_NAMED_POSITIONS_LOAD_SUCCEEDED_WITH_EXTRA_MATES
          - ASSEMBLY_NAMED_POSITIONS_SAVED_MATE_NOT_FOUND_ON_LOAD
          - SHEET_METAL_SINGLE_MODEL_NEEDED
          - SHEET_METAL_ACTIVE_JOIN_NEEDED
          - INSTANCE_QUERY_FAILED
          - SHEET_METAL_ACTIVE_EDGE_NEEDED
          - SHEET_METAL_FLANGE_NO_EDGES
          - MESH_NOT_SUPPORTED
          - SHEET_METAL_PARTS_PROHIBITED
          - VARIABLE_CANNOT_EVALUATE
          - DRAWING_ASSEMBLY_INVALID_SECTION_CUT
          - DRAWING_PARTSTUDIO_INVALID_SECTION_CUT
          - SHEET_METAL_COULD_NOT_UNFOLD
          - PARAMETER_OUT_OF_RANGE
          - SHEET_METAL_NO_0_ANGLE_BEND
          - SHEET_METAL_FLAT_RIP_NO_EDIT
          - SHEET_METAL_CANT_CHANGE_TO_FLAT
          - PARAMETER_PRECONDITION_FAILED
          - PARAMETER_SYNTAX_ERROR
          - SHEET_METAL_CAN_ONLY_REMOVE
          - SHEET_METAL_CAN_ONLY_SUBTRACT
          - REST_ASSEMBLY_INVALID_FEATURE
          - REST_ASSEMBLY_INVALID_BODY_TYPE
          - PARTING_OUT_TARGET_READONLY
          - SHEET_METAL_MULTI_SM_DEFAULT_RADIUS
          - SHEET_METAL_FLANGE_FAIL_ALIGNMENT
          - SHEET_METAL_FLANGE_FAIL_UP_TO
          - SHEET_METAL_FLANGE_FAIL_UP_TO_ENTITY
          - SHEET_METAL_FLANGE_FAIL
          - SHEET_METAL_FLANGE_FAIL_LIMIT_OPP_FLANGE
          - CANT_SPLIT_SHEET_METAL_BEND_FACE
          - IN_CONTEXT_INSTANCE_INVALID_TARGET
          - SHEET_METAL_SELF_INTERSECTING_MODEL
          - SHEET_METAL_SELF_INTERSECTING_FLAT
          - SHEET_METAL_NON_90_BUTT
          - SHEET_METAL_RIP_STYLE_ERROR
          - CANNOT_USE_MATECONNECTORS_IN_PATTERN
          - CANNOT_COPY_MATECONNECTORS
          - SHEET_METAL_CAN_ONLY_OFFSET
          - MODIFIABLE_ENTITY_ONLY
          - IN_CONTEXT_UPDATE_DELETED_ASSEMBLY
          - IN_CONTEXT_UPDATE_EMPTY_INSTANCE
          - IN_CONTEXT_UPDATE_INVALID_SOURCE
          - IN_CONTEXT_UPDATE_INVALID_TARGET
          - SHEET_METAL_NO_FEATURE_PATTERN
          - CUSTOM_FEATURE_DEFINITION_NOT_FOUND
          - SHEET_METAL_START_SELECT_BENDS
          - SHEET_METAL_END_DONE
          - PATH_EDGES_NOT_CONTINUOUS
          - SHEET_METAL_RIP_FAIL_INTERNAL_EDGE
          - SHEET_METAL_RIP_FAIL
          - SHEET_METAL_RIP_MULTI_BODY
          - SHEET_METAL_RIP_FAIL_NON_PLANAR
          - PATTERN_CURVE_NO_EDGES
          - SHEET_METAL_RIP_NO_CORNER
          - SHEET_METAL_RIP_EVEN
          - SHEET_METAL_RIP_WALL_NOT_FOUND
          - SHEET_METAL_RIP_SAME_VERTEX
          - SHEET_METAL_RIP_NEED_MORE_VERTICES
          - SHEET_METAL_MAKE_JOINT_FAIL
          - CURVE_PATTERN_START_OFF_PATH
          - PART_LOAD_FAILED
          - SHEET_METAL_MOVE_NOT_PLANAR
          - SHEET_METAL_JOINT_FAIL_ADJACENT_FACES
          - WRONG_PARASOLID_VERSION
          - SHEET_METAL_SINGLE_MODEL_NEEDED_EDGES
          - REST_ASSEMBLY_MISSING_INSTANCE_DOCUMENT_ID
          - REST_ASSEMBLY_MISSING_INSTANCE_ELEMENT_ID
          - FACE_CLASH
          - CURVE_PATTERN_START_OFF_CLOSED_PATH
          - SHEET_METAL_CUT_JOINT
          - EXPORT_STL_NO_PARTS
          - INPUT_NAME_TOO_LONG
          - IMPORT_BODY_FAILED_CHECK
          - DERIVED_BODIES_HAVE_FAULTS
          - SHEET_METAL_BLOCKED_PATTERN
          - SHEET_METAL_FLANGE_INTERNAL
          - SHEET_METAL_TOO_THICK
          - SHEET_METAL_BEND_END_NOT_A_CORNER
          - SHEET_METAL_NOT_A_CLOSED_CORNER
          - SHEET_METAL_CORNER_NOT_A_BEND_END
          - RIB_ONLY_OPEN_PROFILES
          - TAB_NO_LONGER_EXISTS
          - CLINE_FAILED
          - ILLEGAL_MODIFICATION
          - ASSEMBLY_MATE_VALUE_SET_FAILED
          - EXTRUDE_OFFSET_TOO_DEEP
          - SHEET_METAL_CANNOT_MOVE_BEND_EDGE
          - UP_TO_FACE_NOT_PARALLEL
          - TRANSLATION_FACE_NOT_PLANAR
          - MOVE_FACE_NO_INTERSECTION
          - SWEEP_PATH_PROFILE_NO_INTERSECTION
          - DIRECT_EDIT_MOVE_FACE_CREATE_SELECT
          - SHEET_METAL_THICKEN_IN_CONTEXT_INFO
          - CANNOT_DELETE_RHO_DIMENSION
          - INVALID_RHO
          - SKETCH_RHO_DIM_NOT_FOUND
          - SKETCH_CONIC_FAILED
          - TAB_NAME_TOO_LONG
          - DIRECT_EDIT_DELETE_FACE_ALL_FACES
          - SHEET_METAL_CORNER_BREAK_FAILED
          - BOOLEAN_NO_TARGET_SURFACE
          - BAD_BSPLINECURVE_DEFINITION
          - REQUIRE_3D_BSPLINECURVE_DATA
          - PERIODIC_BSPLINECURVE_NOT_CLOSED
          - PERIODIC_BSPLINECURVE_NOT_SMOOTH
          - RATIONAL_BSPLINECURVE_WEIGHT_NEGATIVE
          - BSPLINECURVE_NOT_G1
          - BRIDGING_CURVE_VERTEX_BOTH_SIDES
          - BRIDGING_CURVE_ONE_EDGE_EACH_SIDE
          - BRIDGING_CURVE_VERTEX_AT_END_OF_EDGE
          - PROJECT_CURVES_PARALLEL_PLANES
          - PROJECT_CURVES_DIFFERENT_SKETCHES
          - SHEET_METAL_SELECT_PART
          - VARIABLE_NOT_FOUND
          - CANNOT_EDIT_FIXED_CONIC
          - EXTRACT_WIRES_OVERLAPPING_EDGES
          - EXTRACT_WIRES_NON_MANIFOLD
          - EXTRACT_WIRES_NEEDS_EDGES
          - SPLINE_TWO_POINTS
          - CLOSED_SPLINE_THREE_POINTS
          - TANGENCY_ONE_EDGE
          - FIT_SPLINE_CANNOT_EVALUATE_END_CONDITION
          - FIT_SPLINE_REPEATED_POINT
          - FEATURE_ID_REQUIRED
          - PARAMETER_NOT_FOUND
          - PARAMETER_DOES_NOT_MATCH_ITS_FEATURE_SPEC
          - SHEET_METAL_CORNER_BREAK_DISABLED
          - SHEET_METAL_FILLET_NO_CONIC
          - SHEET_METAL_CHAMFER_NO_TWO_OFFSETS
          - SHEET_METAL_CHAMFER_NO_OFFSET_ANGLE
          - SHEET_METAL_CHAMFER_MUST_BE_EQUAL_OFFSETS
          - SHEET_METAL_ACTIVE_ENTITY_NEEDED
          - SHEET_METAL_CORNER_BREAK_NOT_A_CORNER
          - SHEET_METAL_CORNER_BREAK_NO_WALL
          - SHEET_METAL_CORNER_BREAK_VERTEX_NOT_FREE
          - SHEET_METAL_CORNER_BREAK_ATTRIBUTE_EXISTS
          - FIT_SPLINE_ZERO_START_MAGNITUDE
          - FIT_SPLINE_ZERO_END_MAGNITUDE
          - SHEET_METAL_CORNER_BREAK_SELECT_ENTITIES
          - EXTRUDE_SELECT_TERMINATING_VERTEX
          - FILL_SURFACE_NO_EDGES
          - FILL_SURFACE_DOUBLE_SELECTION
          - FILL_SURFACE_MULTI_LOOP
          - FILL_SURFACE_OPEN_LOOP
          - FILL_SURFACE_FAIL
          - FILL_SURFACE_ATTACH_FAIL
          - FILL_SURFACE_G2_FAIL
          - FILL_SURFACE_VERTEX_INTERPOLATION_FAIL
          - LOFT_SPINE_DISJOINT_PATH
          - LOFT_SPINE_SELF_INTERSECTING_PATH
          - LOFT_SPINE_PATH_PROFILE_NO_INTERSECTION
          - LOFT_SPINE_FAILED_XSECTIONS
          - LOFT_SPINE_GUIDE_WITH_POINT_PROFILE
          - LOFT_SPINE_PROFILES_NOT_IN_ORDER
          - LOFT_SELECT_SPINE
          - DOCUMENT_NOT_FOUND
          - ELEMENT_NOT_FOUND
          - ENCLOSE_NO_REGION
          - ENCLOSE_CANNOT_MERGE_REGIONS
          - ENCLOSE_CANNOT_CREATE_SOLID
          - ENCLOSE_NOTHING_SELECTED
          - ENCLOSE_UNKNOWN_ERROR
          - ACCESS_NOT_ALLOWED
          - LOFT_SPINE_TOO_MANY_GUIDES
          - FEATURE_INVALID_NAMESPACE
          - FEATURE_NULL_NOT_ALLOWED
          - SKETCH_DIMENSION_LIMIT_ERROR
          - FILL_SURFACE_WIRE_CONTINUITY_MISMATCH
          - FILL_SURFACE_INTERNAL_CONTINUITY_MISMATCH
          - LOFT_START_OR_END_CONDITIONS_FAILED
          - LOFT_START_OR_END_CONDITIONS_MAGNITUDE_NO_EFFECT
          - FOLLOW_LEADER_IS_IN_UNFOLLOWABLE_TAB
          - LOFT_START_OR_END_CONDITIONS_WITH_GUIDES_FAILED
          - REST_ASSEMBLY_MISSING_TRANSFORM_GROUPS
          - REST_ASSEMBLY_NULL_TRANSFORM_GROUP
          - REST_ASSEMBLY_NULL_TRANSFORM_GROUP_INSTANCES
          - REST_ASSEMBLY_NULL_TRANSFORM_GROUP_INSTANCE
          - LOFT_NO_FACE_FOR_GUIDE_CLAMP
          - LOFT_NO_CONTINUITY_CONDITION_AT_INTERNAL_GUIDE
          - SKETCH_CONSTRAINT_NOT_FOUND
          - SKETCH_CONSTRAINT_PARAMETER_NOT_FOUND
          - SKETCH_ENTITY_NOT_FOUND
          - SKETCH_ENTITY_PARAMETER_NOT_FOUND
          - FEATURE_PARAMETER_TYPE_MISMATCH
          - FEATURE_CONFIGURED_PARAMETER_NO_VALUES
          - FEATURE_CONFIGURED_PARAMETER_INCONSISTENT_TYPES
          - SHEET_METAL_FLANGE_FAIL_AUTO_MITER
          - SHEET_METAL_FLANGE_FAIL_PARALLEL_EDGE
          - SHEET_METAL_FLANGE_FAIL_PARALLEL_PLANE
          - SHEET_METAL_FLANGE_FAIL_PARALLEL_DIRECTION
          - SHEET_METAL_FLANGE_FAIL_NO_BEND
          - SHEET_METAL_FLANGE_NO_PARALLEL_ENTITY
          - SHEET_METAL_FLANGE_NO_DIRECTION_ENTITY
          - SHEET_METAL_TAB_NO_BEND
          - BOOLEAN_NO_SURFACE_IN_MERGE_SCOPE
          - BOOLEAN_NO_SHARED_EDGE_WITH_SURFACE_IN_MERGE_SCOPE
          - SHEET_METAL_BEND_RELIEF_NO_CORNER
          - SHEET_METAL_CORNER_SELECT_ENTITIES
          - SHEET_METAL_BEND_RELIEF_SELECT_ENTITIES
          - VRFILLET_RADIUS_REQUIRED_AT_VERTEX
          - VRFILLET_RHO_REQUIRED_AT_VERTEX
          - VRFILLET_MAG_REQUIRED_AT_VERTEX
          - VRFILLET_SELECT_VERTICES
          - VRFILLET_VERTEX_NOT_ON_CHAIN
          - VRFILLET_INVALID_CHAIN
          - SHEET_METAL_TAB_NO_MERGE
          - SHEET_METAL_TAB_NONPLANAR
          - SHEET_METAL_TAB_NO_WALL
          - SHEET_METAL_TAB_NO_TAB
          - VRFILLET_NO_EFFECT
          - VRFILLET_MULTI_SELECTION
          - SHEET_METAL_TAB_NO_PARALLEL_WALL
          - SHEET_METAL_CORNER_UNDER_SIZED
          - FILLET_PARTIAL_FAIL
          - VRFILLET_INTERNAL_ZERO
          - SHEET_METAL_TAB_NO_EFFECT
          - SHEET_METAL_TAB_LOW_CLEARANCE
          - SHEET_METAL_TAB_FAILS_MERGE
          - SHEET_METAL_TAB_COLLISION
          - REPLACE_FACE_FACE_COUNT_CHANGED
          - FACE_OVERLAP
          - FACE_REMOVED
          - INTERSECTING_EDGES
          - CANNOT_SPLIT_FACE
          - FILL_SURFACE_BAD_SUPPORT
          - FILL_SURFACE_SUPPORT_NOT_ON_BOUNDARY
          - FILL_SURFACE_SUPPORT_NOT_SMOOTH
          - FILL_CURVE_OR_POINT_CONSTRAINTS
          - SHEET_METAL_ADD_WRONG_MODEL
          - SHEET_METAL_PATTERN_DISABLED_BOOLEANS
          - DRAWING_ALL_INSTANCES_HIDDEN
          - FILL_SUPPORT_NOT_SMOOTH_INTERNAL
          - SKETCH_CONSTRAINT_WRONG_SHEET_METAL_BODY
          - SKETCH_CONSTRAINT_FLAT_IN_3D
          - SKETCH_CONSTRAINT_3D_IN_FLAT
          - FIT_SPLINE_CURVATURE_FACE
          - FIT_SPLINE_CANNOT_EVALUATE_CURVATURE_END_CONDITION
          - FIT_SPLINE_NEED_DIRECTION_FOR_CURVATURE
          - CONFIGURATION_HAS_BAD_PARAMETERS
          - CONFIGURATION_HAS_BAD_CURRENT_CONFIGURATION
          - FEATURE_CONFIGURED_PARAMETER_VALUES_HAVE_IDS
          - WORKSPACE_NO_LONGER_EXISTS
          - CONTENT_STACKING_INVALID_MODE
          - CONTENT_STACKING_INVALID_COMPONENTS
          - CONTENT_STACKING_INVALID_TOP_STACK
          - SHEET_METAL_FACE_PATTERN_NO_JOINT
          - SHEET_METAL_FACE_PATTERN_FLOATING_CUT
          - SHEET_METAL_FACE_PATTERN_FLOATING_WALL
          - SM_FLAT_OP_NO_INTERSECT
          - SM_FLAT_OP_PARTIAL_INTERSECT
          - SM_FLAT_OP_ADD_CROSSES_EDGE
          - SM_FLAT_OP_NON_PLANAR_TOOL
          - SM_FLAT_OP_NON_PLANAR_TARGET
          - SM_FLAT_OPERATION_FAILED
          - SM_FLAT_OP_LEGACY_MODEL
          - SHEET_METAL_FLANGE_NON_LINEAR_EDGES
          - SHEET_METAL_CYLINDER_BEND
          - SHEET_METAL_INVALID_FACE
          - SHEET_METAL_ROLLED_CORNER_RELIF
          - SHEET_METAL_RELIEF_FAILURES
          - EDGE_CHANGE_FAILED
          - BOOLEAN_INPUTS_NOT_SOLID
          - TRANSFORM_SCALE_SELECTION
          - SHEET_METAL_SUBTRACT_DESTROYS_SHEET
          - SPLIT_KEEP_TOOLS_WITH_FACE
          - SPLIT_TRIM_WITH_SINGLE_FACE
          - SHEET_METAL_SKETCH_DETACHED_FACE
          - HOLE_CUT_FAIL
          - SHEET_METAL_FLAT_OP_ROLL_FAIL
          - PATTERN_EDGE_FAILED
          - SHEET_METAL_FACE_PATTERN_NO_VERTEX
          - SHEET_METAL_FACE_PATTERN_PARTIAL_FLOATING_WALL
          - EXTRUDE_3D_AND_FLAT
          - PATTERN_SWITCH_TO_PER_INSTANCE
          - PATTERN_NO_GEOM_FROM_FEATURES
          - RM_NO_LINK_PERMISSION_TO_REVISION
          - DRAFT_SELECT_PARTING_EDGES
          - DRAFT_CONFLICTING_OPPOSITION
          - SPLIT_SELECT_TARGETS
          - SPLIT_SELECT_TOOL
          - SPLIT_SELECT_FACE_TARGETS
          - SPLIT_SELECT_FACE_TOOLS
          - ASSEMBLY_PATTERN_EXCEED_MAX_INSTANCE_COUNT
          - ASSEMBLY_PATTERN_RECURSIVE_SEED
          - NO_LINK_PERMISSION_TO_THIS_DOCUMENT
          - SM_FLAT_OP_FACES_NOT_COPLANAR
          - FLATTENED_SHEET_METAL_SKETCH_PROHIBTED
          - DRAFT_SELECT_PULL_DIRECTION_ENTITY
          - DRAFT_PARALLEL_PARTING_EDGE
          - FLATTENED_SHEET_METAL_SKETCH_ONE_FACE
          - SKETCH_OFFSET_CHAIN_FAIL
          - SKETCH_OFFSET_BASE_CURVE_CONSUMED
          - SKETCH_OFFSET_SPLINE_SPLIT
          - SKETCH_OFFSET_ELLIPSE_SPLIT
          - CANNOT_FIND_FLATTENED_BODY
          - SHEET_METAL_ACTIVE_MODEL_REQUIRED
          - SKETCH_REFERENCE_WRONG_FLAT_PART
          - SKETCH_CANNOT_REFERENCE_3D
          - SM_FLAT_OP_CANNOT_JOIN_DIFFERENT_TRANSFORMS
          - DEFINED_IN_3D_CANT_REFERENCE_SM_FLAT
          - DEFINED_IN_SM_FLAT_CANT_REFERENCE_3D
          - CANNOT_CHANGE_REFERENCE_TO_DELETED_DOCUMENT
          - COPIED_SKETCH_NOT_FOUND
          - VARIABLE_NAME_TOO_LONG
          - NO_INSTANCE_TO_REPLACE
          - ASSEMBLY_REPLACE_NO_REPLACER
          - CANNOT_REPLACE_IN_SUBASSEMBLIES
          - FILL_SURFACE_G1_FAIL
          - ALL_CONFIGURATION_PARAMETERS_NOT_SPECIFIED
          - ASSEMBLY_REPLACE_INVALID_SEED_INSTANCE
          - ASSEMBLY_REPLACE_INVALID_SEED_TYPE
          - ASSEMBLY_REPLACE_SUPPRESSED_FORBIDDEN
          - DISPLAY_STATES_INVALID_NAME
          - DISPLAY_STATES_DUPLICATE_NAME
          - WORKSPACE_UPGRADE_NONE_ENABLE_CAPABILITY
          - DISPLAY_STATES_UPDATE_HAD_NO_EFFECT
          - DISPLAY_STATES_APPLY_HAD_NO_EFFECT
          - DISPLAY_STATES_DOES_NOT_EXIST
          - LOFT_SPINE_NONTANGENT_PATH
          - LOFT_SPINE_APPROXIMATED
          - REST_ASSEMBLY_REVISION_PART_NUMBER_BLANK
          - REST_ASSEMBLY_REVISION_NOT_FOUND
          - ROLL_FAILED
          - ROLL_CANNOT_ADJUST
          - ROLL_MISMATCHED_SOURCE
          - INVALID_ROLL_SURFACE
          - ROLL_NOT_TO_OR_FROM_PLANE
          - FAILED_TO_FIND_ELEMENT_FOR_TO_STATE
          - FAILED_TO_FIND_VERSION_FOR_TO_STATE
          - MISSING_REVISION_ID_FOR_TO_STATE
          - MISSING_VERSION_ID_FOR_TO_STATE
          - INVALID_DOCUMENT_ID_FOR_TO_STATE
          - ASSEMBLY_CONTAINS_MISSING_PART_DATA
          - SHEET_METAL_HEM_NO_EDGES
          - SHEET_METAL_HEM_NON_LINEAR_EDGES
          - SHEET_METAL_HEM_FAIL_ALIGNMENT
          - SHEET_METAL_HEM_TOO_SHORT
          - SHEET_METAL_HEM_TEAR_DROP_GAP_TOO_LARGE
          - SHEET_METAL_HEM_INTERNAL
          - SHEET_METAL_HEM_FAILED
          - INVALID_CONFIGURATION_SPECIFIED
          - EDGEBLEND_PARTIAL
          - CHAMFER_PARTIAL_FAIL
          - LOFT_INCONSISTENT_EXTENT
          - LOFT_CANT_TRIM_PROFILES_INFO
          - LOFT_CANT_TRIM_GUIDES_INFO
          - NON_GEOMETRIC_ITEM_INSERTION_FAILED
          - SHEET_METAL_FLANGE_NEXT_TO_CYLINDER_BEND
          - SHEET_METAL_HEM_NEXT_TO_CYLINDER_BEND
          - SHEET_METAL_MOVE_FACE_NEXT_TO_CYLINDER_BEND
          - ASSEMBLY_UNKNOWN_SOLVE_ERROR
          - ASSEMBLY_FEATURE_FAILED_TO_RESOLVE_ALL_INSTANCES
          - SHEET_METAL_ORPHANED_BEND
          - ASSEMBLY_CONTEXT_INVALID_REFERENCE
          - ASSEMBLY_FEATURE_QUERY_DATA_MISSING
          - NON_GEOMETRIC_ITEMS_DOCUMENT_NOT_OWNED_BY_COMPANY
          - NON_GEOMETRIC_ITEM_NO_ITEM_FOUND_FOR_DOCUMENT_OWNER
          - EXTEND_SHEET_BODY_NO_TARGET
          - EXTEND_TARGET_MISSED
          - EXTEND_SELF_INTERSECTION
          - EXTEND_FAILED
          - EXTEND_TO_FACE_FAILED
          - TRIM_TO_MULTI_FAILED
          - EXTEND_NON_LAMINAR
          - EXTEND_TO_VERTEX_FAILED
          - TRIM_FAILED
          - SKETCH_EQUAL_CURVATURE_FAILED
          - SKETCH_EQUAL_CURVATURE_INPUT_ERROR
          - ASSEMBLY_EXPLODE_STEP_DIRECTION_QUERY_FAILED
          - WRAP_DESTINATION_NO_FACE
          - WRAP_TRIM_FAILED
          - WRAP_TRIM_NO_INTERSECTION
          - WRAP_IMPRINT_FAILED
          - WRAP_NEEDS_ANCHOR
          - WRAP_SELECT_TOOLS
          - WRAP_SELECT_TARGET
          - CREATE_COMPOSITE_PART_FAILED
          - NESTED_COMPOSITE_PARTS
          - ASSEMBLY_EXPLOSION_DOES_NOT_EXIST
          - FILL_SURFACE_NO_GUIDES
          - HOLE_INCONSISTENT_TAP_INFO
          - WRAP_SOURCE_DIFFERING_PLANES
          - WRAP_IMPRINT_SHEET_METAL
          - WRAP_SELECT_ANCHORS
          - OPERATION_CANCELLED
          - COMPOSITE_CLOSED_OVERLAP
          - COMPOSITE_OPEN_OVERLAP
          - COMPOSITE_SKETCH
          - COMPOSITE_MATE_CONNECTOR
          - COMPOSITE_PLANE
          - COMPOSITE_NON_MODIFIABLE
          - ASSEMBLY_REPLACE_WILL_CAUSE_CYCLES
          - CREATE_OUTLINE_TWO_OFFSET_FACES_PER_BODY
          - SHEET_METAL_TOOL_DOES_NOT_CUT_THROUGH
          - PERIODIC_BSPLINESURFACE_NOT_CLOSED
          - PERIODIC_BSPLINESURFACE_NOT_SMOOTH
          - CANNOT_MAKE_BSPLINESURFACE
          - BSPLINESURFACE_NOT_G1
          - BAD_2D_BOUNDARY_BSPLINECURVE_DEFINITION
          - PERIODIC_2D_BOUNDARY_BSPLINECURVE_NOT_CLOSED
          - PERIODIC_2D_BOUNDARY_BSPLINECURVE_NOT_SMOOTH
          - BSPLINESURFACE_BOUNDARY_NOT_SINGLE_CLOSED_LOOP
          - BSPLINESURFACE_FAILED_TO_MAKE_SOLID
          - BOOLEAN_NO_SHARED_EDGE_WITH_OTHER_SURFACE
          - BOOLEAN_NO_SURFACE_TO_MERGE_WITH
          - BOOLEAN_INVALID_PARAMETER_COMBINATION
          - MODIFY_COMPOSITE_PART_FAILED
          - INSTANCE_CONSUMED_BY_CLOSED_COMPOSITE
          - EXPLODE_STEP_INSTANCE_IS_SUPPRESSED
          - NO_COMPOSITE_FOR_SINGLE_SOLID
          - COMPOSITE_PART_ADD_AND_REMOVE_BODY
          - BOOLEAN_TOOL_INPUTS_NOT_SOLID
          - BOOLEAN_CANNOT_MIX_SOLIDS_AND_SURFACES
          - BSPLINESURFACE_CONTROL_POINTS_GRID_TOO_LONG
          - BSPLINE_TOO_MANY_CONTROL_POINTS
          - BSPLINE_DEGREE_TOO_HIGH
          - COMPOSITE_PART_SELECT_ENTITIES
          - DELETE_COMPOSITE_PART_FAILED
          - SURFACES_NOT_SUPPORTED_BY_PATTERN_REMOVE_AND_INTERSECT
          - SHEET_METAL_TAB_MERGE_AND_SUBTRACT_SAME_FLANGE
          - EXPLODED_VIEW_INVALID_STARTING_POSITION
          - UNKNOWN
          type: string
        microversionId:
          $ref: '#/components/schemas/BTMicroversionId-366'
      type: object
    BTExportModelBody-1272:
      properties:
        edges:
          items:
            $ref: '#/components/schemas/BTExportModelEdge-1782'
          type: array
        faces:
          items:
            $ref: '#/components/schemas/BTExportModelFace-1363'
          type: array
        id:
          type: string
        type:
          enum:
          - SOLID
          - SHEET
          - WIRE
          - POINT
          - MATE_CONNECTOR
          - COMPOSITE
          - UNKNOWN
          type: string
        vertices:
          items:
            $ref: '#/components/schemas/BTExportModelVertex-858'
          type: array
      type: object
    BTExportModelCoedge-1342:
      properties:
        edgeId:
          type: string
        orientation:
          type: boolean
      type: object
    BTExportModelEdge-1782:
      properties:
        curve:
          $ref: '#/components/schemas/BTCurveDescription-1583'
        geometry:
          $ref: '#/components/schemas/BTExportModelEdgeGeometry-1125'
        id:
          type: string
        vertices:
          items:
            type: string
          type: array
      type: object
    BTExportModelEdgeGeometry-1125:
      discriminator:
        mapping:
          BTExportModelArcEdgeGeometry-1257: '#/components/schemas/BTExportModelArcEdgeGeometry-1257'
        propertyName: btType
      properties:
        btType:
          type: string
        endPoint:
          $ref: '#/components/schemas/BTVector3d-389'
        endVector:
          $ref: '#/components/schemas/BTVector3d-389'
        length:
          format: double
          type: number
        midPoint:
          $ref: '#/components/schemas/BTVector3d-389'
        quarterPoint:
          $ref: '#/components/schemas/BTVector3d-389'
        startPoint:
          $ref: '#/components/schemas/BTVector3d-389'
        startVector:
          $ref: '#/components/schemas/BTVector3d-389'
      type: object
    BTExportModelFace-1363:
      properties:
        area:
          format: double
          type: number
        box:
          $ref: '#/components/schemas/BTBoundingBox-1052'
        id:
          type: string
        loops:
          items:
            $ref: '#/components/schemas/BTExportModelLoop-1182'
          type: array
        orientation:
          type: boolean
        surface:
          $ref: '#/components/schemas/BTSurfaceDescription-1564'
      type: object
    BTExportModelLoop-1182:
      properties:
        coedges:
          items:
            $ref: '#/components/schemas/BTExportModelCoedge-1342'
          type: array
        isInner:
          type: boolean
        isOuter:
          type: boolean
      type: object
    BTExportModelParams:
      properties:
        angleTolerance:
          format: double
          type: number
        batchFlatPatterns:
          type: boolean
        chordTolerance:
          format: double
          type: number
        cloudObjectId:
          type: string
        cloudStorageAccountId:
          type: string
        configuration:
          type: string
        deepSearchForForeignData:
          type: boolean
        destinationName:
          type: string
        documentId:
          type: string
        documentVersionId:
          type: string
        elementId:
          type: string
        elementIds:
          type: string
        emailLink:
          type: boolean
        emailMessage:
          type: string
        emailSubject:
          type: string
        emailTo:
          type: string
        extractToS3:
          type: boolean
        featureIds:
          type: string
        flatten:
          type: boolean
        format:
          type: string
        fromUserId:
          type: string
        grouping:
          type: string
        includeBendCenterlines:
          type: boolean
        includeBendLines:
          type: boolean
        includeCustomProperties:
          type: boolean
          writeOnly: true
        includeCustomPropertiesData:
          type: boolean
        includeExportIds:
          type: boolean
        includeForeignData:
          type: boolean
        includeItemsData:
          type: boolean
        includeLinkedDocuments:
          type: boolean
        includeReleaseManagementData:
          type: boolean
        includeSketches:
          type: boolean
        includeStd:
          type: boolean
        isPartingOut:
          type: boolean
        linkDocumentId:
          type: string
        linkDocumentWorkspaceId:
          type: string
        maxFacetWidth:
          format: double
          type: number
        microversion:
          type: string
        minFacetWidth:
          format: double
          type: number
        mode:
          type: string
        partIds:
          type: string
        partQuery:
          type: string
        password:
          type: string
        passwordRequired:
          type: boolean
        resolution:
          type: string
        scale:
          format: double
          type: number
        sendCopyToMe:
          type: boolean
        sheetMetalFlat:
          type: boolean
        splinesAsPolylines:
          type: boolean
        storeInDocument:
          type: boolean
        triggerAutoDownload:
          type: boolean
        units:
          type: string
        userId:
          type: string
        validForDays:
          format: int32
          type: integer
        version:
          type: string
        view:
          type: string
        workspaceId:
          type: string
        zipSingleFileOutput:
          type: boolean
      type: object
    BTExportModelVertex-858:
      properties:
        id:
          type: string
        point:
          $ref: '#/components/schemas/BTVector3d-389'
      type: object
    BTExportTessellatedBody-3398:
      discriminator:
        mapping:
          BTExportTessellatedEdgesBody-890: '#/components/schemas/BTExportTessellatedEdgesBody-890'
          BTExportTessellatedFacesBody-1321: '#/components/schemas/BTExportTessellatedFacesBody-1321'
        propertyName: btType
      properties:
        btType:
          type: string
        constituents:
          items:
            type: string
          type: array
        id:
          type: string
      type: object
    BTExportTessellatedEdgesBody-890:
      allOf:
      - $ref: '#/components/schemas/BTExportTessellatedBody-3398'
      - $ref: '#/components/schemas/BTExportTessellatedEdgesBody_890_allOf'
      type: object
    BTExportTessellatedEdgesEdge-1364:
      properties:
        btType:
          type: string
        id:
          type: string
        vertices:
          items:
            $ref: '#/components/schemas/BTVector3d-389'
          type: array
      type: object
    BTExportTessellatedEdgesResponse-327:
      properties:
        bodies:
          items:
            $ref: '#/components/schemas/BTExportTessellatedBody-3398'
          type: array
        errorEnum:
          enum:
          - NO_ERROR
          - UNKNOWN_OPERATION
          - TOO_MANY_ENTITIES_SELECTED
          - POINTS_COINCIDENT
          - NO_TRANSLATION_DIRECTION
          - NO_ROTATION_AXIS
          - NO_TANGENT_PLANE
          - NO_TANGENT_LINE
          - INVALID_INPUT
          - CANNOT_RESOLVE_ENTITIES
          - CANNOT_EVALUATE_VERTEX
          - CANNOT_RESOLVE_PLANE
          - CANNOT_COMPUTE_BBOX
          - CANNOT_BE_EMPTY
          - CACHE_WRITE_FAILED
          - CACHE_READ_FAILED
          - HLR_FAILED
          - BAD_GEOMETRY
          - INVALID_RESULT
          - MISSING_EXT_REF
          - READ_FAILED
          - WRITE_FAILED
          - WRONG_TYPE
          - TANGENT_PROPAGATION_FAILED
          - REGEN_ERROR
          - COULD_NOT_COMPUTE_TRANSFORM
          - MATE_INVALID_MATE
          - MATECONNECTOR_INVALID_MATE
          - MATE_TWO_MATECONNECTORS_NEEDED
          - MATECONNECTORS_ON_SAME_OCCURRENCE
          - MATE_OVERDEFINED
          - MATE_INCONSISTENT
          - BOOLEAN_NEED_ONE_SOLID
          - BOOLEAN_INVALID
          - BOOLEAN_INTERSECT_FAIL
          - BOOLEAN_SAME_INPUT
          - BOOLEAN_BAD_INPUT
          - BOOLEAN_UNION_NO_OP
          - BOOLEAN_INTERSECT_NO_OP
          - BOOLEAN_SUBTRACT_NO_OP
          - CPLANE_INPUT_MIDPLANE
          - CPLANE_INPUT_OFFSET_PLANE
          - CPLANE_INPUT_POINT_PLANE
          - CPLANE_INPUT_LINE_ANGLE
          - CPLANE_INPUT_POINT_LINE
          - CPLANE_INPUT_THREE_POINT
          - CPLANE_FAILED
          - DRAFT_NO_NEUTRAL_PLANE
          - DRAFT_NO_DRAFT_FACE
          - DRAFT_FAILED
          - EXTRUDE_INVALID_REF_FACE
          - EXTRUDE_INVALID_REF_SURFACE
          - EXTRUDE_FAILED
          - EXTRUDE_NO_DIRECTION
          - EXTRUDE_INVALID_ENTITIES
          - PATTERN_INPUT_TOO_MANY_INSTANCES
          - PATTERN_INPUT_TOO_FEW_INSTANCES
          - PATTERN_FACE_FAILED
          - PATTERN_NOT_ON_BODY
          - PATTERN_BODY_FAILED
          - TRANSFORM_TRANSLATE_INPUT
          - TRANSFORM_TRANSLATE_BY_DISTANCE_INPUT
          - TRANSFORM_FAILED
          - SHELL_FAILED
          - EDGEBLEND_SMOOTH
          - EDGEBLEND_FAILED
          - DIRECT_EDIT_WRONG_CONCENTRIC
          - DIRECT_EDIT_WRONG_EQ_RADIUS
          - DIRECT_EDIT_NO_FILLET_FACES
          - DIRECT_EDIT_NO_OFFSET
          - DIRECT_EDIT_CONSTRAIN_FACE_FAILED
          - DIRECT_EDIT_REPLACE_FACE_FAILED
          - DIRECT_EDIT_DELETE_FACE_FAILED
          - DIRECT_EDIT_MODIFY_FILLET_FAILED
          - DIRECT_EDIT_MODIFY_FACE_FAILED
          - DIRECT_EDIT_MOVE_FACE_FAILED
          - DIRECT_EDIT_OFFSET_FACE_FAILED
          - IMPORT_PART_FAILED
          - IMPORT_ASSEMBLY_FAILED
          - IMPRINT_FAILED
          - REVOLVE_FAILED
          - REVOLVE_2ND_DIR_FAILED
          - REVOLVE_NOT_PLANAR
          - REVOLVE_PERPENDICULAR
          - REVOLVE_INVALID_ENTITIES
          - SPLIT_FAILED
          - SPLIT_INVALID_INPUT
          - SWEEP_INVALID_PATH
          - SWEEP_FAILED
          - SWEEP_PATH_FAILED
          - SWEEP_PROFILE_FAILED
          - WIRE_CREATION_FAILED
          - SKETCH_NO_PLANE
          - SKETCH_INPUT_INVALID
          - SKETCH_NOT_ACTIVE
          - SKETCH_SOLVER_NOT_INITIALIZED
          - SKETCH_EVALUATION_FAILED
          - SKETCH_MODIFICATION_FAILED
          - SKETCH_UPDATE_FAILED
          - SKETCH_SOLVE_FAILED
          - SKETCH_ADD_CONSTRAINT_FAILED
          - SKETCH_ADD_DIMENSION_FAILED
          - SKETCH_POSITION_DIMENSION_FAILED
          - SKETCH_CONSTRAINT_NEEDS_SKETCH_ENTITY
          - SKETCH_CONSTRAINT_UNKNOWN
          - SKETCH_MISSING_ENTITY
          - SKETCH_FILLET_INVALID_POINT
          - SKETCH_FILLET_PARALLEL
          - SKETCH_FILLET_FAIL
          - SKETCH_USE_FAILED
          - SKETCH_USE_PARTIAL
          - SKETCH_SPLINE_FAILED
          - SKETCH_BAD_SPLINE
          - SKETCH_DRAG_ERROR
          - SKETCH_PROJ_FAILED
          - SKETCH_PROJ_PARTIAL
          - SKETCH_TANGENT_ARC_FAILED
          - SKETCH_TANGENT_NOT_FOUND
          - SKETCH_OFFSET_FAILED
          - SKETCH_OFFSET_DISTANCE
          - SKETCH_TRIM_FAILED
          - SKETCH_INFERENCE_FAILED
          - SKETCH_MODIFY_DIM_FAILED
          - SKETCH_DRAG_NO_SKETCH
          - SKETCH_INFER_DIM_FAILED
          - SKETCH_DELETE_PTS_FAILED
          - SKETCH_DELETE_FAILED
          - SKETCH_ARC_FAILED
          - SKETCH_LINE_FAILED
          - SKETCH_CIRCLE_FAILED
          - SKETCH_RECTANGLE_FAILED
          - SKETCH_TANGENT_ARC_INVALID_START
          - SKETCH_CONSTRUCTION_POINT_FAILED
          - SYS_INTERNAL_DESERIALIZATION
          - SYS_SERVER_EXCEPTION
          - SYS_ERROR_REGEN
          - SYS_ERROR_MESSAGING
          - CANNOT_RESOLVE_ELEMENT
          - NOTHING_SELECTED
          - SKETCH_ANGLE_TWO_LINES
          - SKETCH_DIMENSION_DIFF_ENTITIES
          - SKETCH_CONSTRAINT_DIFF_ENTITIES
          - SKETCH_CONSTRAINT_TWO_ENTITIES
          - SKETCH_DIMENSION_TWO_ENTITIES
          - SKETCH_COINCIDENT_FAILED
          - SKETCH_COINCIDENT_INPUT_ERROR
          - SKETCH_COINCIDENT_DIFF_POINTS
          - SKETCH_CONCENTRIC_INPUT_ERROR
          - SKETCH_CONCENTRIC_FAILED
          - SKETCH_EQUAL_INPUT_ERROR
          - SKETCH_EQUAL_NO_ENDS
          - SKETCH_EQUAL_FAILED
          - SKETCH_FIX_ONE_ENT
          - SKETCH_FIX_FAILED
          - SKETCH_DIR_INTERNAL
          - SKETCH_DIR_INPUT
          - SKETCH_HORIZONTAL_FAILED
          - SKETCH_VERTICAL_FAILED
          - SKETCH_OFFSET_CONSTRAINT_FAILED
          - SKETCH_PARALLEL_CONSTRAINT_FAILED
          - SKETCH_PARALLEL_INPUT_ERROR
          - SKETCH_DIMENSION_INPUT_ERROR
          - SKETCH_DIMENSION_DIST_ERROR
          - SKETCH_DIMENSION_FAILED
          - SKETCH_NORMAL_NEED_LINE
          - SKETCH_NORMAL_INPUT_ERROR
          - SKETCH_NORMAL_INPUT_NEEDED
          - SKETCH_CANNOT_SPLIT_INTO_GROUPS
          - SKETCH_OFFSET_BAD_PAIR
          - SKETCH_OFFSET_INPUT_ERROR
          - SKETCH_MIDPOINT_INPUT_ERROR
          - SKETCH_MIDPOINT_NEED_POINT
          - SKETCH_MIDPOINT_NEED_DIFF_POINT
          - SKETCH_MIDPOINT_MISSING_ENDS
          - SKETCH_MIDPOINT_MISSING_PTS
          - SKETCH_MIDPOINT_NO_INTERNAL_LINE
          - SKETCH_MIDPOINT_NO_COINCIDENT
          - SKETCH_MIDPOINT_FAILED
          - SKETCH_PERPENDICULAR_INPUT_ERROR
          - SKETCH_PERPENDICULAR_FAILED
          - SKETCH_POINT_LINE_ONLY
          - SKETCH_PROJECTION_UNKNOWN
          - SKETCH_PROJECTION_FAILED
          - SKETCH_SIL_PROJECTION_INPUT_ERROR
          - SKETCH_SIL_PROJECTION_MISSING_POINT
          - SKETCH_LENGTH_DIM_INPUT_ERROR
          - SKETCH_LENGTH_DIM_MISSING_ENDS
          - SKETCH_LENGTH_DIM_NOT_FOUND
          - SKETCH_LENGTH_DIM_FAILED
          - SKETCH_RADIUS_INPUT_ERROR
          - SKETCH_RADIUS_DIM_FAILED
          - SKETCH_TANGENT_INPUT_ERROR
          - SKETCH_TANGENT_FAILED
          - PART_QUERY_FAILED
          - PART_QUERY_MULTI
          - MATECONNECTOR_QUERY_FAILED
          - MATECONNECTOR_QUERY_ORIGIN_FAILED
          - MATECONNECTOR_QUERY_AXIS_FAILED
          - MATECONNECTOR_QUERY_CSYS_FAILED
          - ASSEMBLY_INSERT_WILL_CAUSE_CYCLES
          - SKETCH_MIRROR_NEED_VALID_MIRROR_LINE
          - SKETCH_MIRROR_NEED_ENTITIES_TO_MIRROR
          - SKETCH_MIRROR_CONSTRAINT_FAILED
          - SKETCH_MIRROR_FAILED
          - SELF_INTERSECTING_CURVE_SELECTED
          - SWEEP_START_NOT_ON_PROFILE
          - PATTERN_DIRECTIONS_PARALLEL
          - MATE_OCCURRENCE_NOT_VALID
          - MATE_WITHIN_SAME_GROUP
          - EXPORT_ASSEMBLY_UNKNOWN_NODE_TYPE
          - EXPORT_ASSEMBLY_CREATE_INSTANCE_FAILED
          - EXPORT_PARTS_AS_XTS_NOT_A_BODY
          - EXPORT_PARTS_AS_XTS_FAILED_TO_WRITE_XT
          - MATECONNECTOR_OWNER_PART_NOT_RESOLVED
          - WIRE_CREATION_PARTIAL_FAILURE
          - SERVER_IS_IN_INVALID_STATE
          - SKETCH_EXTEND_FAILED
          - FOLLOW_CYCLE_ERROR
          - SKETCH_FILLET_INVALID_RADIUS
          - SKETCH_CONSTRAINT_COINCIDENT_TWO_ENTITIES
          - SKETCH_CONSTRAINT_CONCENTRIC_TWO_ENTITIES
          - SKETCH_CONSTRAINT_EQUAL_TWO_ENTITIES
          - SKETCH_CONSTRAINT_MIDPOINT_TWO_ENTITIES
          - EXTRUDE_NO_SELECTED_REGION
          - EXTRUDE_NO_REGION_IN_SKETCH
          - DELETE_SELECT_PARTS
          - COPY_SELECT_PARTS
          - SPLIT_NO_CHANGE
          - MIRROR_NO_PLANE
          - MIRROR_SELECT_PARTS
          - PATTERN_CIRCULAR_NO_AXIS
          - PATTERN_SELECT_FACES
          - PATTERN_SELECT_PARTS
          - PATTERN_LINEAR_NO_DIR
          - SHELL_SELECT_FACES
          - DRAFT_SELECT_NEUTRAL
          - DRAFT_SELECT_FACES
          - CHAMFER_SELECT_EDGES
          - FILLET_SELECT_EDGES
          - EXTRUDE_SURF_NO_CURVE
          - EXTRUDE_SELECT_TERMINATING_BODY
          - EXTRUDE_SELECT_TERMINATING_SURFACE
          - DIRECT_EDIT_SELECT_ANCHOR
          - REVOLVE_SURF_NO_CURVE
          - REVOLVE_SELECT_FACES
          - REVOLVE_SELECT_AXIS
          - SWEEP_SELECT_PROFILE
          - SWEEP_SELECT_PATH
          - DIRECT_EDIT_DELETE_SELECT_FACES
          - DIRECT_EDIT_MODIFY_FILLET_SELECT
          - DIRECT_EDIT_MODIFY_FACE_SELECT
          - DIRECT_EDIT_REPLACE_FACE_SELECT
          - DIRECT_EDIT_OFFSET_FACE_SELECT
          - DIRECT_EDIT_MOVE_FACE_SELECT
          - SELECT_MATECONNECTOR
          - OVERDEFINED_ASSEMBLY
          - PART_STUDIO_UPGRADE_SUCCESSFUL
          - PART_STUDIO_UPGRADE_FAILED
          - PART_STUDIO_UPGRADE_NONE
          - MATE_GROUP_OCCURRENCES_UNRESOLVED
          - SWEEP_SURF_NO_CURVE_PROFILE
          - MATE_RESET_HAD_NO_EFFECT
          - MATECONNECTOR_MULTIPLE_OCCURRENCES
          - MATECONNECTOR_OCCURRENCE_NOT_RESOLVED
          - ELEMENT_REFERENCE_CYCLE_DETECTED
          - MATE_OVERDEFINES_ASSEMBLY
          - MATE_CANNOT_RESOLVE_CONNECTORS
          - SKETCH_EXCEEDS_BOUNDS
          - SWEEP_SELF_INT
          - SKETCH_UNSOLVABLE_CONSTRAINT
          - RESTRUCTURE_INVALID_SOURCE_OR_TARGET
          - CPLANE_INPUT_CURVE_POINT
          - TRANSFORM_OCCURRENCES_HAD_NO_EFFECT
          - HELIX_FAILED
          - HELIX_INPUT_CONE
          - RENDERER_NOT_AVAILABLE
          - RENDERER_FAILED_TO_RENDER
          - EXPRESSION_FAILED_VALIDATION
          - VERSION_MISMATCH_ERROR
          - EXTRUDE_UPTO_NEXT_NO_DIVISION
          - MATE_BETWEEN_FIXED_OCCURRENCES
          - THICKEN_SELECT_ENTITIES
          - THICKEN_FAILED
          - WORKSPACE_UPGRADE_SUCCESSFUL
          - WORKSPACE_UPGRADE_FAILED
          - WORKSPACE_UPGRADE_NONE
          - SKETCH_CIRCULAR_PATTERN_FAILED
          - DIRECT_EDIT_ALL_FILLET_FACES_SELECTED
          - DIRECT_EDIT_FAILED_TO_IDENTIFY_FILLETS
          - PARASOLID_IMPORT_FAILED
          - FOLLOW_LEADER_HAS_NO_FUNCTIONALITY_ERROR
          - MIRROR_SELECT_FACES
          - RELATION_INVALID_RELATION
          - RELATION_INVALID_MATE
          - GEAR_RELATION_INVALID_MATE_TYPES
          - SCREW_RELATION_INVALID_MATE_TYPES
          - RACK_RELATION_INVALID_MATE_TYPES
          - ROLLING_RELATION_INVALID_MATE_TYPES
          - LINEAR_RELATION_INVALID_MATE_TYPES
          - RELATION_OVERDEFINED
          - RELATION_INCONSISTENT
          - RELATION_SAME_OCCURRENCES
          - SKETCH_SPLIT_FAILED
          - SKETCH_CONSTRAINT_PIERCE_TWO_ENTITIES
          - SKETCH_PIERCE_FAILED
          - MIRROR_FACE_FAILED
          - MIRROR_BODY_FAILED
          - SKETCH_CANNOT_PIERCE_WITH_PLANE
          - WITH_SUPPORT_CODE
          - FILLET_FAIL_SMOOTH
          - FILLET_FAILED
          - CHAMFER_FAIL_SMOOTH
          - CHAMFER_FAILED
          - BOOLEAN_OFFSET_NO_FACES
          - MATE_OCCURRENCE_SUPPRESSED
          - MATECONNECTOR_OCCURRENCE_SUPPRESSED
          - SKETCH_SPLINE_NEW_POINTS_TOO_CLOSE
          - SKETCH_SPLINE_CANNOT_DELETE_ENDPOINTS
          - SKETCH_SPLINE_POINT_TO_DELETE_NOT_FOUND
          - ASSEMBLY_INSERT_FAILED
          - SKETCH_PATTERN_UNKNOWN_FAILURE
          - SKETCH_PATTERN_TOO_LARGE
          - SKETCH_LINEAR_PATTERN_ZERO_LENGTH
          - SKETCH_LINEAR_PATTERN_PARALLEL_DIRECTIONS
          - SKETCH_CIRCULAR_PATTERN_ZERO_ANGLE
          - SKETCH_ELLIPSE_FAILED
          - SKETCH_ELLIPSE_FAILED_TOO_SMALL
          - DELETE_PARTS_FAILED
          - DELETE_PARTS_PARTIAL
          - SKETCH_ELLIPSE_RADIUS_INPUT_ERROR
          - QUADRANT_CONSTRAINT_INPUT
          - SKETCH_QUADRANT_FAILED
          - SKETCH_SPLINE_TOO_FEW_POINTS
          - SKETCH_SPLINE_NOT_INTERPOLATED_SPLINE
          - SKETCH_SPLINE_POINTS_NOT_DELETED
          - SKETCH_TEXT_RECTANGLE_FAILED
          - IMPORT_DERIVED_NO_PARTS
          - LOFT_SELECT_PROFILES
          - LOFT_PROFILE_SINGLE_FACE
          - LOFT_PROFILE_SOLID
          - LOFT_PROFILE_POINT
          - LOFT_PROFILE_FAILED
          - LOFT_SELECT_GUIDES
          - LOFT_GUIDE_FAILED
          - LOFT_PERIODIC_ERROR
          - LOFT_GUIDE_POINT_INTERSECTION
          - LOFT_GUIDE_PROFILE_INTERSECTION
          - LOFT_VERTEX_MATCHING
          - LOFT_DIRECTION_ERROR
          - LOFT_PROFILE_ALIGNMENT
          - LOFT_GUIDE_ALIGNMENT
          - LOFT_VERTEX_ADDITIONS
          - LOFT_FAILED
          - LOFT_INVALID
          - LOFT_ALIGNMENT_INFO
          - LOFT_VERTEX_NOT_ON_PROFILE
          - LOFT_PROFILE_NO_INNER_LOOPS
          - LOFT_TWO_PROFILES
          - CANNOT_OFFSET_ELLIPSE
          - SKETCH_MIRROR_NEEDS_LINE_AND_TWO_OTHERS
          - SKETCH_POLYGON_BAD_SIDE_COUNT
          - SKETCH_DIRECTIONAL_GROUP_INPUT
          - NAMED_VIEWS_DUPLICATE_NAME
          - SILHOUETTE_USE_FAILED
          - PASTE_SKETCH_METRICS_FAILURE
          - PASTE_SKETCH_LIBRARY_MISMATCH
          - PASTE_SKETCH_CLIPBOARD_EMPTY
          - SKETCH_MIRROR_OFFSET_SPLINE
          - SKETCH_MIRROR_CURVE_POINT
          - LOFT_PERIODIC_GUIDE_ERROR
          - SHELL_SELECT_PARTS
          - RELATION_MATE_DOES_NOT_EXIST
          - RELATION_MATE_IS_SUPPRESSED
          - VARIABLE_NAME_INVALID
          - LOFT_GUIDE_INFO
          - HOLE_NO_POINTS
          - HOLE_FAIL_BBOX
          - HOLE_EMPTY_SCOPE
          - HOLE_NO_HITS
          - WITH_EXTRA_DATA
          - HOLE_DISJOINT
          - SKETCH_INSERT_DWG_CONVERSION_FAILURE
          - HOLE_CBORE_TOO_SMALL
          - HOLE_CBORE_TOO_DEEP
          - HOLE_CSINK_TOO_SMALL
          - HOLE_CSINK_TOO_DEEP
          - SWEEP_PATH_NO_CONSTRUCTION
          - SKETCH_IMAGE_RECTANGLE_FAILED
          - ASSEMBLY_REPLICATE_NO_VALID_TARGET
          - ASSEMBLY_REPLICATE_NO_MATCHING_TARGET
          - LOFT_SHAPE_CONTROL_FAILED
          - LOFT_START_CONDITIONS_FAILED
          - LOFT_END_CONDITIONS_FAILED
          - LOFT_NO_FACE_FOR_START_CLAMP
          - LOFT_NO_FACE_FOR_END_CLAMP
          - LOFT_NO_PLANE_FOR_START_CLAMP
          - LOFT_NO_PLANE_FOR_END_CLAMP
          - LOFT_NO_CLAMPS_ON_POINT_PROFILE
          - EXPORT_NOT_IMPLEMENTED
          - SKETCH_POLYGON_ZERO_RADIUS_FAIL
          - DRAWING_FAILED_TO_RESOLVE_VIEW_REFERENCE
          - DRAWING_PARTSTUDIO_EMPTY_AFTER_SECTION_CUT
          - DRAWING_ASSEMBLY_DOES_NOT_CONTAIN_VISIBLE_INSTANCES
          - DRAWING_ASSEMBLY_EMPTY_AFTER_SECTION_CUT
          - DRAWING_VIEW_GENERATION_FAILED
          - SKETCH_SLOT_FAILURE
          - SKETCH_SLOT_PARTIAL_FAILURE
          - NO_UNIT
          - RESTRUCTURE_INVALID_SOURCE
          - RESTRUCTURE_INVALID_TARGET
          - MATE_MIN_MAX_LIMIT_VIOLATION
          - REST_ASSEMBLY_GET_DOCUMENT_FAILED
          - REST_ASSEMBLY_UNKNOWN_INSERTABLE_TYPE
          - REST_ASSEMBLY_SETUP_EXCEPTION
          - REST_ASSEMBLY_BEGIN_OPERATION_FAILED
          - REST_ASSEMBLY_INSERT_INSTANCE_FAILED
          - REST_ASSEMBLY_COMMIT_OPERATION_FAILED
          - REST_ASSEMBLY_CLOSE_CLIENT_FAILED
          - REST_ASSEMBLY_NULL_OCCURRENCES
          - REST_ASSEMBLY_EMPTY_OCCURRENCE
          - REST_ASSEMBLY_TRANSFORM_WRONG_SIZE
          - ASSEMBLY_EMPTY_OCCURRENCE_LIST
          - ASSEMBLY_NULL_TRANSFORM
          - ASSEMBLY_TRANSFORM_NOT_RIGID
          - ASSEMBLY_CANNOT_TRANSFORM_FIXED_OCCURRENCE
          - ASSEMBLY_TRANSFORM_FAILED
          - ASSEMBLY_OCCURRENCE_NOT_FOUND
          - ASSEMBLY_REPLICATE_MULTIPLE_VALID_TARGET
          - ASSEMBLY_REPLICATE_NO_TARGET_SELECTED
          - CPLANE_INPUT_LINE_ANGLE2
          - CPLANE_DEGENERATE_SELECTION
          - CPLANE_SELECT_LINE_ANGLE_REFERENCE
          - ASSEMBLY_REPLICATE_INVALID_SEED_INSTANCE
          - CANNOT_USE_VARIABLES_IN_SKETCH_PATTERNS
          - SKETCH_MIRROR_OFFSET_ELLIPSE
          - EXTERNAL_REFERENCE_FAILED_TO_CREATE
          - SPLIT_FACE_NO_CHANGE
          - SKETCH_INTERSECTION_FAILED
          - SKETCH_INTERSECTION_MULTIPLE_FAILED
          - SKETCH_INTERSECTION_PARTIAL_FAILED
          - FEATURE_ID_IN_PATH_DOES_NOT_MATCH_BODY
          - FEATURE_NOT_FOUND
          - FEATURE_DOES_NOT_MATCH
          - FEATURE_HAS_INVALID_TYPE
          - FEATURE_DOES_NOT_MATCH_ITS_FEATURE_SPEC
          - FEATURE_BAD_SERIALIZATION_VERSION
          - FEATURE_WRONG_SERIALIZATION_VERSION
          - FEATURE_INVALID_ROLLBACK_INDEX
          - FEATURE_ERROR_IN_INPUT
          - FEATURE_CONCURRENCY_ERROR
          - FEATURE_CHANGE_BREAKS_MODEL
          - FEATURE_NODE_IDS_INVALID
          - ROLLBACK_INDEX_INVALID
          - FEATURE_NO_SOLIDS
          - SKETCH_EXTERNAL_GEOMETRY_MISMATCH
          - HOLE_EXCEEDS_MAX_LOCATIONS
          - SKETCH_TEXT_IS_EMPTY
          - SKETCH_INSERT_DWG_MAX_ENTITIES_EXCEEDED
          - HOLE_TAP_DIA_TOO_LARGE
          - ASSEMBLY_EMPTY_BODY
          - SIMPLIFY_BODY_FAILED
          - INVALID_VIEW_NAME
          - PATTERN_SELECT_FEATURES
          - MIRROR_SELECT_FEATURES
          - PATTERN_FEATURE_FAILED
          - SKETCH_TRANSFORM_FAILED
          - TANGENT_MATE_TWO_ENTITIES_NEEDED
          - HOLE_CANNOT_DETERMINE_LAST_BODY
          - RESTRUCTURE_CANNOT_MODIFY_SAVED_VERSION
          - REST_ASSEMBLY_EXTERNAL_REFERENCE_REQUIRES_VERSION
          - REST_ASSEMBLY_EXTERNAL_REFERENCE_DISALLOWS_MICROVERSION
          - REST_ASSEMBLY_VERSION_SUPPORTED_ONLY_FOR_EXTERNAL_REFERENCES
          - SWEEP_BAD_LOCK_FACES
          - SKETCH_TEXT_CANNOT_BE_CONSTRUCTION
          - CUSTOM_ERROR
          - BEND_BAD_CONFIGURATION
          - BEND_WRONG_NUMBER_OF_ENTITIES
          - BEND_BAD_CURVES
          - BEND_GENERAL_ERROR
          - BEND_EDGE_NO_EDGES
          - BEND_EDGE_NO_SEED_ENTITY
          - EXTEND_SHEET_BODY_NO_BODY
          - EXTRACT_SURFACE_NO_FACES
          - FLATTEN_NO_EDGES
          - FLATTEN_NO_FACES
          - FOLD_NO_BODIES
          - BEND_PREP_NO_FACES
          - BEND_PREP_NO_BODIES
          - BEND_PREP_ERROR_FINDING_EDGE_LOCATIONS
          - BEND_PREP_ERROR_IMPRINTING_EDGES
          - ASSEMBLY_ANIMATE_MATE_START_AFTER_END
          - ASSEMBLY_ANIMATE_NO_MATE
          - ASSEMBLY_ANIMATE_MATE_SUPPRESSED
          - TANGENT_MATE_GEOMETRY_NOT_SUPPORTED
          - SKETCH_DIMENSION_INFINITY
          - BOLEAN_INPUTS_NOT_SOLID
          - FACE_IS_NOT_RECTANGLE
          - HOLE_DESTROY_SOLID
          - HELIX_INPUT_CIRCLE
          - IMPORT_SCALING_NON_MESH_DATA
          - EVALUATE_FACE_TANGENT_FOR_MESHES
          - CANNOT_COMPUTE_CENTROID
          - CANNOT_EVALUATE_DIMENSION
          - CANNOT_IMPORT_MESH
          - SKETCH_ELLIPSE_ZERO_AXIS
          - TRANSFORM_SCALE_UNIFORMLY
          - TRANSFORM_MATE_CONNECTORS
          - ASSEMBLY_WRONG_ELEMENT_TYPE
          - ASSEMBLY_ELEMENT_NOT_FOUND
          - SHEET_METAL_TABLE_UNKNOWN_ERROR
          - SHEET_METAL_TABLE_REGEN_ERROR
          - SHEET_METAL_TABLE_READ_ONLY
          - ASSEMBLY_PATTERN_INVALID_TYPE
          - ASSEMBLY_PATTERN_DIRECTION_ERROR
          - ASSEMBLY_PATTERN_NONPOSITIVE_LINEAR_DISTANCE
          - ASSEMBLY_PATTERN_NONPOSITIVE_ANGLE
          - ASSEMBLY_PATTERN_INVALID_SEED
          - ASSEMBLY_PATTERN_INVALID_REFERENCE_MATE_CONNECTOR
          - RESTORE_FEATURE_FAILED
          - FACES_NOT_OWNED_BY_PARTS
          - EDGES_NOT_OWNED_BY_PARTS
          - SHEET_METAL_REBUILD_ERROR
          - SHEET_METAL_INPUT_BODY_SHOULD_NOT_BE_SHEET_METAL
          - SHEET_METAL_CANNOT_RECOGNIZE_PARTS
          - SHEET_METAL_CANNOT_THICKEN
          - SHEET_METAL_CONVERT_PLANE
          - ASSEMBLY_PATTERN_AXIS_ERROR
          - RIB_NO_PROFILES
          - RIB_NO_PARTS
          - RIB_PROFILE_FAILED
          - RIB_BODY_FAILED
          - RIB_NO_INTERSECTIONS
          - RIB_MERGE_FAILED
          - ASSEMBLY_NAMED_POSITIONS_SAVE_FAILED
          - ASSEMBLY_NAMED_POSITIONS_LOAD_FAILED
          - ASSEMBLY_NAMED_POSITIONS_NO_MATES_TO_SAVE
          - ASSEMBLY_NAMED_POSITIONS_POSITION_NOT_FOUND
          - SPHERE_FAILED
          - ASSEMBLY_PATTERN_NOT_SUPPORTED
          - ASSEMBLY_NAMED_POSITIONS_PARTIAL_LOAD_FAILURE
          - ASSEMBLY_NAMED_POSITIONS_LOAD_SUCCEEDED_WITH_EXTRA_MATES
          - ASSEMBLY_NAMED_POSITIONS_SAVED_MATE_NOT_FOUND_ON_LOAD
          - SHEET_METAL_SINGLE_MODEL_NEEDED
          - SHEET_METAL_ACTIVE_JOIN_NEEDED
          - INSTANCE_QUERY_FAILED
          - SHEET_METAL_ACTIVE_EDGE_NEEDED
          - SHEET_METAL_FLANGE_NO_EDGES
          - MESH_NOT_SUPPORTED
          - SHEET_METAL_PARTS_PROHIBITED
          - VARIABLE_CANNOT_EVALUATE
          - DRAWING_ASSEMBLY_INVALID_SECTION_CUT
          - DRAWING_PARTSTUDIO_INVALID_SECTION_CUT
          - SHEET_METAL_COULD_NOT_UNFOLD
          - PARAMETER_OUT_OF_RANGE
          - SHEET_METAL_NO_0_ANGLE_BEND
          - SHEET_METAL_FLAT_RIP_NO_EDIT
          - SHEET_METAL_CANT_CHANGE_TO_FLAT
          - PARAMETER_PRECONDITION_FAILED
          - PARAMETER_SYNTAX_ERROR
          - SHEET_METAL_CAN_ONLY_REMOVE
          - SHEET_METAL_CAN_ONLY_SUBTRACT
          - REST_ASSEMBLY_INVALID_FEATURE
          - REST_ASSEMBLY_INVALID_BODY_TYPE
          - PARTING_OUT_TARGET_READONLY
          - SHEET_METAL_MULTI_SM_DEFAULT_RADIUS
          - SHEET_METAL_FLANGE_FAIL_ALIGNMENT
          - SHEET_METAL_FLANGE_FAIL_UP_TO
          - SHEET_METAL_FLANGE_FAIL_UP_TO_ENTITY
          - SHEET_METAL_FLANGE_FAIL
          - SHEET_METAL_FLANGE_FAIL_LIMIT_OPP_FLANGE
          - CANT_SPLIT_SHEET_METAL_BEND_FACE
          - IN_CONTEXT_INSTANCE_INVALID_TARGET
          - SHEET_METAL_SELF_INTERSECTING_MODEL
          - SHEET_METAL_SELF_INTERSECTING_FLAT
          - SHEET_METAL_NON_90_BUTT
          - SHEET_METAL_RIP_STYLE_ERROR
          - CANNOT_USE_MATECONNECTORS_IN_PATTERN
          - CANNOT_COPY_MATECONNECTORS
          - SHEET_METAL_CAN_ONLY_OFFSET
          - MODIFIABLE_ENTITY_ONLY
          - IN_CONTEXT_UPDATE_DELETED_ASSEMBLY
          - IN_CONTEXT_UPDATE_EMPTY_INSTANCE
          - IN_CONTEXT_UPDATE_INVALID_SOURCE
          - IN_CONTEXT_UPDATE_INVALID_TARGET
          - SHEET_METAL_NO_FEATURE_PATTERN
          - CUSTOM_FEATURE_DEFINITION_NOT_FOUND
          - SHEET_METAL_START_SELECT_BENDS
          - SHEET_METAL_END_DONE
          - PATH_EDGES_NOT_CONTINUOUS
          - SHEET_METAL_RIP_FAIL_INTERNAL_EDGE
          - SHEET_METAL_RIP_FAIL
          - SHEET_METAL_RIP_MULTI_BODY
          - SHEET_METAL_RIP_FAIL_NON_PLANAR
          - PATTERN_CURVE_NO_EDGES
          - SHEET_METAL_RIP_NO_CORNER
          - SHEET_METAL_RIP_EVEN
          - SHEET_METAL_RIP_WALL_NOT_FOUND
          - SHEET_METAL_RIP_SAME_VERTEX
          - SHEET_METAL_RIP_NEED_MORE_VERTICES
          - SHEET_METAL_MAKE_JOINT_FAIL
          - CURVE_PATTERN_START_OFF_PATH
          - PART_LOAD_FAILED
          - SHEET_METAL_MOVE_NOT_PLANAR
          - SHEET_METAL_JOINT_FAIL_ADJACENT_FACES
          - WRONG_PARASOLID_VERSION
          - SHEET_METAL_SINGLE_MODEL_NEEDED_EDGES
          - REST_ASSEMBLY_MISSING_INSTANCE_DOCUMENT_ID
          - REST_ASSEMBLY_MISSING_INSTANCE_ELEMENT_ID
          - FACE_CLASH
          - CURVE_PATTERN_START_OFF_CLOSED_PATH
          - SHEET_METAL_CUT_JOINT
          - EXPORT_STL_NO_PARTS
          - INPUT_NAME_TOO_LONG
          - IMPORT_BODY_FAILED_CHECK
          - DERIVED_BODIES_HAVE_FAULTS
          - SHEET_METAL_BLOCKED_PATTERN
          - SHEET_METAL_FLANGE_INTERNAL
          - SHEET_METAL_TOO_THICK
          - SHEET_METAL_BEND_END_NOT_A_CORNER
          - SHEET_METAL_NOT_A_CLOSED_CORNER
          - SHEET_METAL_CORNER_NOT_A_BEND_END
          - RIB_ONLY_OPEN_PROFILES
          - TAB_NO_LONGER_EXISTS
          - CLINE_FAILED
          - ILLEGAL_MODIFICATION
          - ASSEMBLY_MATE_VALUE_SET_FAILED
          - EXTRUDE_OFFSET_TOO_DEEP
          - SHEET_METAL_CANNOT_MOVE_BEND_EDGE
          - UP_TO_FACE_NOT_PARALLEL
          - TRANSLATION_FACE_NOT_PLANAR
          - MOVE_FACE_NO_INTERSECTION
          - SWEEP_PATH_PROFILE_NO_INTERSECTION
          - DIRECT_EDIT_MOVE_FACE_CREATE_SELECT
          - SHEET_METAL_THICKEN_IN_CONTEXT_INFO
          - CANNOT_DELETE_RHO_DIMENSION
          - INVALID_RHO
          - SKETCH_RHO_DIM_NOT_FOUND
          - SKETCH_CONIC_FAILED
          - TAB_NAME_TOO_LONG
          - DIRECT_EDIT_DELETE_FACE_ALL_FACES
          - SHEET_METAL_CORNER_BREAK_FAILED
          - BOOLEAN_NO_TARGET_SURFACE
          - BAD_BSPLINECURVE_DEFINITION
          - REQUIRE_3D_BSPLINECURVE_DATA
          - PERIODIC_BSPLINECURVE_NOT_CLOSED
          - PERIODIC_BSPLINECURVE_NOT_SMOOTH
          - RATIONAL_BSPLINECURVE_WEIGHT_NEGATIVE
          - BSPLINECURVE_NOT_G1
          - BRIDGING_CURVE_VERTEX_BOTH_SIDES
          - BRIDGING_CURVE_ONE_EDGE_EACH_SIDE
          - BRIDGING_CURVE_VERTEX_AT_END_OF_EDGE
          - PROJECT_CURVES_PARALLEL_PLANES
          - PROJECT_CURVES_DIFFERENT_SKETCHES
          - SHEET_METAL_SELECT_PART
          - VARIABLE_NOT_FOUND
          - CANNOT_EDIT_FIXED_CONIC
          - EXTRACT_WIRES_OVERLAPPING_EDGES
          - EXTRACT_WIRES_NON_MANIFOLD
          - EXTRACT_WIRES_NEEDS_EDGES
          - SPLINE_TWO_POINTS
          - CLOSED_SPLINE_THREE_POINTS
          - TANGENCY_ONE_EDGE
          - FIT_SPLINE_CANNOT_EVALUATE_END_CONDITION
          - FIT_SPLINE_REPEATED_POINT
          - FEATURE_ID_REQUIRED
          - PARAMETER_NOT_FOUND
          - PARAMETER_DOES_NOT_MATCH_ITS_FEATURE_SPEC
          - SHEET_METAL_CORNER_BREAK_DISABLED
          - SHEET_METAL_FILLET_NO_CONIC
          - SHEET_METAL_CHAMFER_NO_TWO_OFFSETS
          - SHEET_METAL_CHAMFER_NO_OFFSET_ANGLE
          - SHEET_METAL_CHAMFER_MUST_BE_EQUAL_OFFSETS
          - SHEET_METAL_ACTIVE_ENTITY_NEEDED
          - SHEET_METAL_CORNER_BREAK_NOT_A_CORNER
          - SHEET_METAL_CORNER_BREAK_NO_WALL
          - SHEET_METAL_CORNER_BREAK_VERTEX_NOT_FREE
          - SHEET_METAL_CORNER_BREAK_ATTRIBUTE_EXISTS
          - FIT_SPLINE_ZERO_START_MAGNITUDE
          - FIT_SPLINE_ZERO_END_MAGNITUDE
          - SHEET_METAL_CORNER_BREAK_SELECT_ENTITIES
          - EXTRUDE_SELECT_TERMINATING_VERTEX
          - FILL_SURFACE_NO_EDGES
          - FILL_SURFACE_DOUBLE_SELECTION
          - FILL_SURFACE_MULTI_LOOP
          - FILL_SURFACE_OPEN_LOOP
          - FILL_SURFACE_FAIL
          - FILL_SURFACE_ATTACH_FAIL
          - FILL_SURFACE_G2_FAIL
          - FILL_SURFACE_VERTEX_INTERPOLATION_FAIL
          - LOFT_SPINE_DISJOINT_PATH
          - LOFT_SPINE_SELF_INTERSECTING_PATH
          - LOFT_SPINE_PATH_PROFILE_NO_INTERSECTION
          - LOFT_SPINE_FAILED_XSECTIONS
          - LOFT_SPINE_GUIDE_WITH_POINT_PROFILE
          - LOFT_SPINE_PROFILES_NOT_IN_ORDER
          - LOFT_SELECT_SPINE
          - DOCUMENT_NOT_FOUND
          - ELEMENT_NOT_FOUND
          - ENCLOSE_NO_REGION
          - ENCLOSE_CANNOT_MERGE_REGIONS
          - ENCLOSE_CANNOT_CREATE_SOLID
          - ENCLOSE_NOTHING_SELECTED
          - ENCLOSE_UNKNOWN_ERROR
          - ACCESS_NOT_ALLOWED
          - LOFT_SPINE_TOO_MANY_GUIDES
          - FEATURE_INVALID_NAMESPACE
          - FEATURE_NULL_NOT_ALLOWED
          - SKETCH_DIMENSION_LIMIT_ERROR
          - FILL_SURFACE_WIRE_CONTINUITY_MISMATCH
          - FILL_SURFACE_INTERNAL_CONTINUITY_MISMATCH
          - LOFT_START_OR_END_CONDITIONS_FAILED
          - LOFT_START_OR_END_CONDITIONS_MAGNITUDE_NO_EFFECT
          - FOLLOW_LEADER_IS_IN_UNFOLLOWABLE_TAB
          - LOFT_START_OR_END_CONDITIONS_WITH_GUIDES_FAILED
          - REST_ASSEMBLY_MISSING_TRANSFORM_GROUPS
          - REST_ASSEMBLY_NULL_TRANSFORM_GROUP
          - REST_ASSEMBLY_NULL_TRANSFORM_GROUP_INSTANCES
          - REST_ASSEMBLY_NULL_TRANSFORM_GROUP_INSTANCE
          - LOFT_NO_FACE_FOR_GUIDE_CLAMP
          - LOFT_NO_CONTINUITY_CONDITION_AT_INTERNAL_GUIDE
          - SKETCH_CONSTRAINT_NOT_FOUND
          - SKETCH_CONSTRAINT_PARAMETER_NOT_FOUND
          - SKETCH_ENTITY_NOT_FOUND
          - SKETCH_ENTITY_PARAMETER_NOT_FOUND
          - FEATURE_PARAMETER_TYPE_MISMATCH
          - FEATURE_CONFIGURED_PARAMETER_NO_VALUES
          - FEATURE_CONFIGURED_PARAMETER_INCONSISTENT_TYPES
          - SHEET_METAL_FLANGE_FAIL_AUTO_MITER
          - SHEET_METAL_FLANGE_FAIL_PARALLEL_EDGE
          - SHEET_METAL_FLANGE_FAIL_PARALLEL_PLANE
          - SHEET_METAL_FLANGE_FAIL_PARALLEL_DIRECTION
          - SHEET_METAL_FLANGE_FAIL_NO_BEND
          - SHEET_METAL_FLANGE_NO_PARALLEL_ENTITY
          - SHEET_METAL_FLANGE_NO_DIRECTION_ENTITY
          - SHEET_METAL_TAB_NO_BEND
          - BOOLEAN_NO_SURFACE_IN_MERGE_SCOPE
          - BOOLEAN_NO_SHARED_EDGE_WITH_SURFACE_IN_MERGE_SCOPE
          - SHEET_METAL_BEND_RELIEF_NO_CORNER
          - SHEET_METAL_CORNER_SELECT_ENTITIES
          - SHEET_METAL_BEND_RELIEF_SELECT_ENTITIES
          - VRFILLET_RADIUS_REQUIRED_AT_VERTEX
          - VRFILLET_RHO_REQUIRED_AT_VERTEX
          - VRFILLET_MAG_REQUIRED_AT_VERTEX
          - VRFILLET_SELECT_VERTICES
          - VRFILLET_VERTEX_NOT_ON_CHAIN
          - VRFILLET_INVALID_CHAIN
          - SHEET_METAL_TAB_NO_MERGE
          - SHEET_METAL_TAB_NONPLANAR
          - SHEET_METAL_TAB_NO_WALL
          - SHEET_METAL_TAB_NO_TAB
          - VRFILLET_NO_EFFECT
          - VRFILLET_MULTI_SELECTION
          - SHEET_METAL_TAB_NO_PARALLEL_WALL
          - SHEET_METAL_CORNER_UNDER_SIZED
          - FILLET_PARTIAL_FAIL
          - VRFILLET_INTERNAL_ZERO
          - SHEET_METAL_TAB_NO_EFFECT
          - SHEET_METAL_TAB_LOW_CLEARANCE
          - SHEET_METAL_TAB_FAILS_MERGE
          - SHEET_METAL_TAB_COLLISION
          - REPLACE_FACE_FACE_COUNT_CHANGED
          - FACE_OVERLAP
          - FACE_REMOVED
          - INTERSECTING_EDGES
          - CANNOT_SPLIT_FACE
          - FILL_SURFACE_BAD_SUPPORT
          - FILL_SURFACE_SUPPORT_NOT_ON_BOUNDARY
          - FILL_SURFACE_SUPPORT_NOT_SMOOTH
          - FILL_CURVE_OR_POINT_CONSTRAINTS
          - SHEET_METAL_ADD_WRONG_MODEL
          - SHEET_METAL_PATTERN_DISABLED_BOOLEANS
          - DRAWING_ALL_INSTANCES_HIDDEN
          - FILL_SUPPORT_NOT_SMOOTH_INTERNAL
          - SKETCH_CONSTRAINT_WRONG_SHEET_METAL_BODY
          - SKETCH_CONSTRAINT_FLAT_IN_3D
          - SKETCH_CONSTRAINT_3D_IN_FLAT
          - FIT_SPLINE_CURVATURE_FACE
          - FIT_SPLINE_CANNOT_EVALUATE_CURVATURE_END_CONDITION
          - FIT_SPLINE_NEED_DIRECTION_FOR_CURVATURE
          - CONFIGURATION_HAS_BAD_PARAMETERS
          - CONFIGURATION_HAS_BAD_CURRENT_CONFIGURATION
          - FEATURE_CONFIGURED_PARAMETER_VALUES_HAVE_IDS
          - WORKSPACE_NO_LONGER_EXISTS
          - CONTENT_STACKING_INVALID_MODE
          - CONTENT_STACKING_INVALID_COMPONENTS
          - CONTENT_STACKING_INVALID_TOP_STACK
          - SHEET_METAL_FACE_PATTERN_NO_JOINT
          - SHEET_METAL_FACE_PATTERN_FLOATING_CUT
          - SHEET_METAL_FACE_PATTERN_FLOATING_WALL
          - SM_FLAT_OP_NO_INTERSECT
          - SM_FLAT_OP_PARTIAL_INTERSECT
          - SM_FLAT_OP_ADD_CROSSES_EDGE
          - SM_FLAT_OP_NON_PLANAR_TOOL
          - SM_FLAT_OP_NON_PLANAR_TARGET
          - SM_FLAT_OPERATION_FAILED
          - SM_FLAT_OP_LEGACY_MODEL
          - SHEET_METAL_FLANGE_NON_LINEAR_EDGES
          - SHEET_METAL_CYLINDER_BEND
          - SHEET_METAL_INVALID_FACE
          - SHEET_METAL_ROLLED_CORNER_RELIF
          - SHEET_METAL_RELIEF_FAILURES
          - EDGE_CHANGE_FAILED
          - BOOLEAN_INPUTS_NOT_SOLID
          - TRANSFORM_SCALE_SELECTION
          - SHEET_METAL_SUBTRACT_DESTROYS_SHEET
          - SPLIT_KEEP_TOOLS_WITH_FACE
          - SPLIT_TRIM_WITH_SINGLE_FACE
          - SHEET_METAL_SKETCH_DETACHED_FACE
          - HOLE_CUT_FAIL
          - SHEET_METAL_FLAT_OP_ROLL_FAIL
          - PATTERN_EDGE_FAILED
          - SHEET_METAL_FACE_PATTERN_NO_VERTEX
          - SHEET_METAL_FACE_PATTERN_PARTIAL_FLOATING_WALL
          - EXTRUDE_3D_AND_FLAT
          - PATTERN_SWITCH_TO_PER_INSTANCE
          - PATTERN_NO_GEOM_FROM_FEATURES
          - RM_NO_LINK_PERMISSION_TO_REVISION
          - DRAFT_SELECT_PARTING_EDGES
          - DRAFT_CONFLICTING_OPPOSITION
          - SPLIT_SELECT_TARGETS
          - SPLIT_SELECT_TOOL
          - SPLIT_SELECT_FACE_TARGETS
          - SPLIT_SELECT_FACE_TOOLS
          - ASSEMBLY_PATTERN_EXCEED_MAX_INSTANCE_COUNT
          - ASSEMBLY_PATTERN_RECURSIVE_SEED
          - NO_LINK_PERMISSION_TO_THIS_DOCUMENT
          - SM_FLAT_OP_FACES_NOT_COPLANAR
          - FLATTENED_SHEET_METAL_SKETCH_PROHIBTED
          - DRAFT_SELECT_PULL_DIRECTION_ENTITY
          - DRAFT_PARALLEL_PARTING_EDGE
          - FLATTENED_SHEET_METAL_SKETCH_ONE_FACE
          - SKETCH_OFFSET_CHAIN_FAIL
          - SKETCH_OFFSET_BASE_CURVE_CONSUMED
          - SKETCH_OFFSET_SPLINE_SPLIT
          - SKETCH_OFFSET_ELLIPSE_SPLIT
          - CANNOT_FIND_FLATTENED_BODY
          - SHEET_METAL_ACTIVE_MODEL_REQUIRED
          - SKETCH_REFERENCE_WRONG_FLAT_PART
          - SKETCH_CANNOT_REFERENCE_3D
          - SM_FLAT_OP_CANNOT_JOIN_DIFFERENT_TRANSFORMS
          - DEFINED_IN_3D_CANT_REFERENCE_SM_FLAT
          - DEFINED_IN_SM_FLAT_CANT_REFERENCE_3D
          - CANNOT_CHANGE_REFERENCE_TO_DELETED_DOCUMENT
          - COPIED_SKETCH_NOT_FOUND
          - VARIABLE_NAME_TOO_LONG
          - NO_INSTANCE_TO_REPLACE
          - ASSEMBLY_REPLACE_NO_REPLACER
          - CANNOT_REPLACE_IN_SUBASSEMBLIES
          - FILL_SURFACE_G1_FAIL
          - ALL_CONFIGURATION_PARAMETERS_NOT_SPECIFIED
          - ASSEMBLY_REPLACE_INVALID_SEED_INSTANCE
          - ASSEMBLY_REPLACE_INVALID_SEED_TYPE
          - ASSEMBLY_REPLACE_SUPPRESSED_FORBIDDEN
          - DISPLAY_STATES_INVALID_NAME
          - DISPLAY_STATES_DUPLICATE_NAME
          - WORKSPACE_UPGRADE_NONE_ENABLE_CAPABILITY
          - DISPLAY_STATES_UPDATE_HAD_NO_EFFECT
          - DISPLAY_STATES_APPLY_HAD_NO_EFFECT
          - DISPLAY_STATES_DOES_NOT_EXIST
          - LOFT_SPINE_NONTANGENT_PATH
          - LOFT_SPINE_APPROXIMATED
          - REST_ASSEMBLY_REVISION_PART_NUMBER_BLANK
          - REST_ASSEMBLY_REVISION_NOT_FOUND
          - ROLL_FAILED
          - ROLL_CANNOT_ADJUST
          - ROLL_MISMATCHED_SOURCE
          - INVALID_ROLL_SURFACE
          - ROLL_NOT_TO_OR_FROM_PLANE
          - FAILED_TO_FIND_ELEMENT_FOR_TO_STATE
          - FAILED_TO_FIND_VERSION_FOR_TO_STATE
          - MISSING_REVISION_ID_FOR_TO_STATE
          - MISSING_VERSION_ID_FOR_TO_STATE
          - INVALID_DOCUMENT_ID_FOR_TO_STATE
          - ASSEMBLY_CONTAINS_MISSING_PART_DATA
          - SHEET_METAL_HEM_NO_EDGES
          - SHEET_METAL_HEM_NON_LINEAR_EDGES
          - SHEET_METAL_HEM_FAIL_ALIGNMENT
          - SHEET_METAL_HEM_TOO_SHORT
          - SHEET_METAL_HEM_TEAR_DROP_GAP_TOO_LARGE
          - SHEET_METAL_HEM_INTERNAL
          - SHEET_METAL_HEM_FAILED
          - INVALID_CONFIGURATION_SPECIFIED
          - EDGEBLEND_PARTIAL
          - CHAMFER_PARTIAL_FAIL
          - LOFT_INCONSISTENT_EXTENT
          - LOFT_CANT_TRIM_PROFILES_INFO
          - LOFT_CANT_TRIM_GUIDES_INFO
          - NON_GEOMETRIC_ITEM_INSERTION_FAILED
          - SHEET_METAL_FLANGE_NEXT_TO_CYLINDER_BEND
          - SHEET_METAL_HEM_NEXT_TO_CYLINDER_BEND
          - SHEET_METAL_MOVE_FACE_NEXT_TO_CYLINDER_BEND
          - ASSEMBLY_UNKNOWN_SOLVE_ERROR
          - ASSEMBLY_FEATURE_FAILED_TO_RESOLVE_ALL_INSTANCES
          - SHEET_METAL_ORPHANED_BEND
          - ASSEMBLY_CONTEXT_INVALID_REFERENCE
          - ASSEMBLY_FEATURE_QUERY_DATA_MISSING
          - NON_GEOMETRIC_ITEMS_DOCUMENT_NOT_OWNED_BY_COMPANY
          - NON_GEOMETRIC_ITEM_NO_ITEM_FOUND_FOR_DOCUMENT_OWNER
          - EXTEND_SHEET_BODY_NO_TARGET
          - EXTEND_TARGET_MISSED
          - EXTEND_SELF_INTERSECTION
          - EXTEND_FAILED
          - EXTEND_TO_FACE_FAILED
          - TRIM_TO_MULTI_FAILED
          - EXTEND_NON_LAMINAR
          - EXTEND_TO_VERTEX_FAILED
          - TRIM_FAILED
          - SKETCH_EQUAL_CURVATURE_FAILED
          - SKETCH_EQUAL_CURVATURE_INPUT_ERROR
          - ASSEMBLY_EXPLODE_STEP_DIRECTION_QUERY_FAILED
          - WRAP_DESTINATION_NO_FACE
          - WRAP_TRIM_FAILED
          - WRAP_TRIM_NO_INTERSECTION
          - WRAP_IMPRINT_FAILED
          - WRAP_NEEDS_ANCHOR
          - WRAP_SELECT_TOOLS
          - WRAP_SELECT_TARGET
          - CREATE_COMPOSITE_PART_FAILED
          - NESTED_COMPOSITE_PARTS
          - ASSEMBLY_EXPLOSION_DOES_NOT_EXIST
          - FILL_SURFACE_NO_GUIDES
          - HOLE_INCONSISTENT_TAP_INFO
          - WRAP_SOURCE_DIFFERING_PLANES
          - WRAP_IMPRINT_SHEET_METAL
          - WRAP_SELECT_ANCHORS
          - OPERATION_CANCELLED
          - COMPOSITE_CLOSED_OVERLAP
          - COMPOSITE_OPEN_OVERLAP
          - COMPOSITE_SKETCH
          - COMPOSITE_MATE_CONNECTOR
          - COMPOSITE_PLANE
          - COMPOSITE_NON_MODIFIABLE
          - ASSEMBLY_REPLACE_WILL_CAUSE_CYCLES
          - CREATE_OUTLINE_TWO_OFFSET_FACES_PER_BODY
          - SHEET_METAL_TOOL_DOES_NOT_CUT_THROUGH
          - PERIODIC_BSPLINESURFACE_NOT_CLOSED
          - PERIODIC_BSPLINESURFACE_NOT_SMOOTH
          - CANNOT_MAKE_BSPLINESURFACE
          - BSPLINESURFACE_NOT_G1
          - BAD_2D_BOUNDARY_BSPLINECURVE_DEFINITION
          - PERIODIC_2D_BOUNDARY_BSPLINECURVE_NOT_CLOSED
          - PERIODIC_2D_BOUNDARY_BSPLINECURVE_NOT_SMOOTH
          - BSPLINESURFACE_BOUNDARY_NOT_SINGLE_CLOSED_LOOP
          - BSPLINESURFACE_FAILED_TO_MAKE_SOLID
          - BOOLEAN_NO_SHARED_EDGE_WITH_OTHER_SURFACE
          - BOOLEAN_NO_SURFACE_TO_MERGE_WITH
          - BOOLEAN_INVALID_PARAMETER_COMBINATION
          - MODIFY_COMPOSITE_PART_FAILED
          - INSTANCE_CONSUMED_BY_CLOSED_COMPOSITE
          - EXPLODE_STEP_INSTANCE_IS_SUPPRESSED
          - NO_COMPOSITE_FOR_SINGLE_SOLID
          - COMPOSITE_PART_ADD_AND_REMOVE_BODY
          - BOOLEAN_TOOL_INPUTS_NOT_SOLID
          - BOOLEAN_CANNOT_MIX_SOLIDS_AND_SURFACES
          - BSPLINESURFACE_CONTROL_POINTS_GRID_TOO_LONG
          - BSPLINE_TOO_MANY_CONTROL_POINTS
          - BSPLINE_DEGREE_TOO_HIGH
          - COMPOSITE_PART_SELECT_ENTITIES
          - DELETE_COMPOSITE_PART_FAILED
          - SURFACES_NOT_SUPPORTED_BY_PATTERN_REMOVE_AND_INTERSECT
          - SHEET_METAL_TAB_MERGE_AND_SUBTRACT_SAME_FLANGE
          - EXPLODED_VIEW_INVALID_STARTING_POSITION
          - UNKNOWN
          type: string
      type: object
    BTExportTessellatedFacesBody-1321:
      allOf:
      - $ref: '#/components/schemas/BTExportTessellatedBody-3398'
      - $ref: '#/components/schemas/BTExportTessellatedFacesBody_1321_allOf'
      type: object
    BTExportTessellatedFacesFace-1192:
      properties:
        appearance:
          $ref: '#/components/schemas/BTGraphicsAppearance-1152'
        btType:
          type: string
        errorMessage:
          type: string
        facets:
          items:
            $ref: '#/components/schemas/BTExportTessellatedFacesFacet-1417'
          type: array
        id:
          type: string
      type: object
    BTExportTessellatedFacesFacet-1417:
      properties:
        btType:
          type: string
        indices:
          items:
            format: int32
            type: integer
          type: array
        normal:
          $ref: '#/components/schemas/BTVector3d-389'
        normals:
          items:
            $ref: '#/components/schemas/BTVector3d-389'
          type: array
        textureCoordinates:
          items:
            $ref: '#/components/schemas/BTVector2d-1812'
          type: array
        vertices:
          items:
            $ref: '#/components/schemas/BTVector3d-389'
          type: array
      type: object
    BTExportTessellatedFacesResponse-898:
      properties:
        bodies:
          items:
            $ref: '#/components/schemas/BTExportTessellatedBody-3398'
          type: array
        errorEnum:
          enum:
          - NO_ERROR
          - UNKNOWN_OPERATION
          - TOO_MANY_ENTITIES_SELECTED
          - POINTS_COINCIDENT
          - NO_TRANSLATION_DIRECTION
          - NO_ROTATION_AXIS
          - NO_TANGENT_PLANE
          - NO_TANGENT_LINE
          - INVALID_INPUT
          - CANNOT_RESOLVE_ENTITIES
          - CANNOT_EVALUATE_VERTEX
          - CANNOT_RESOLVE_PLANE
          - CANNOT_COMPUTE_BBOX
          - CANNOT_BE_EMPTY
          - CACHE_WRITE_FAILED
          - CACHE_READ_FAILED
          - HLR_FAILED
          - BAD_GEOMETRY
          - INVALID_RESULT
          - MISSING_EXT_REF
          - READ_FAILED
          - WRITE_FAILED
          - WRONG_TYPE
          - TANGENT_PROPAGATION_FAILED
          - REGEN_ERROR
          - COULD_NOT_COMPUTE_TRANSFORM
          - MATE_INVALID_MATE
          - MATECONNECTOR_INVALID_MATE
          - MATE_TWO_MATECONNECTORS_NEEDED
          - MATECONNECTORS_ON_SAME_OCCURRENCE
          - MATE_OVERDEFINED
          - MATE_INCONSISTENT
          - BOOLEAN_NEED_ONE_SOLID
          - BOOLEAN_INVALID
          - BOOLEAN_INTERSECT_FAIL
          - BOOLEAN_SAME_INPUT
          - BOOLEAN_BAD_INPUT
          - BOOLEAN_UNION_NO_OP
          - BOOLEAN_INTERSECT_NO_OP
          - BOOLEAN_SUBTRACT_NO_OP
          - CPLANE_INPUT_MIDPLANE
          - CPLANE_INPUT_OFFSET_PLANE
          - CPLANE_INPUT_POINT_PLANE
          - CPLANE_INPUT_LINE_ANGLE
          - CPLANE_INPUT_POINT_LINE
          - CPLANE_INPUT_THREE_POINT
          - CPLANE_FAILED
          - DRAFT_NO_NEUTRAL_PLANE
          - DRAFT_NO_DRAFT_FACE
          - DRAFT_FAILED
          - EXTRUDE_INVALID_REF_FACE
          - EXTRUDE_INVALID_REF_SURFACE
          - EXTRUDE_FAILED
          - EXTRUDE_NO_DIRECTION
          - EXTRUDE_INVALID_ENTITIES
          - PATTERN_INPUT_TOO_MANY_INSTANCES
          - PATTERN_INPUT_TOO_FEW_INSTANCES
          - PATTERN_FACE_FAILED
          - PATTERN_NOT_ON_BODY
          - PATTERN_BODY_FAILED
          - TRANSFORM_TRANSLATE_INPUT
          - TRANSFORM_TRANSLATE_BY_DISTANCE_INPUT
          - TRANSFORM_FAILED
          - SHELL_FAILED
          - EDGEBLEND_SMOOTH
          - EDGEBLEND_FAILED
          - DIRECT_EDIT_WRONG_CONCENTRIC
          - DIRECT_EDIT_WRONG_EQ_RADIUS
          - DIRECT_EDIT_NO_FILLET_FACES
          - DIRECT_EDIT_NO_OFFSET
          - DIRECT_EDIT_CONSTRAIN_FACE_FAILED
          - DIRECT_EDIT_REPLACE_FACE_FAILED
          - DIRECT_EDIT_DELETE_FACE_FAILED
          - DIRECT_EDIT_MODIFY_FILLET_FAILED
          - DIRECT_EDIT_MODIFY_FACE_FAILED
          - DIRECT_EDIT_MOVE_FACE_FAILED
          - DIRECT_EDIT_OFFSET_FACE_FAILED
          - IMPORT_PART_FAILED
          - IMPORT_ASSEMBLY_FAILED
          - IMPRINT_FAILED
          - REVOLVE_FAILED
          - REVOLVE_2ND_DIR_FAILED
          - REVOLVE_NOT_PLANAR
          - REVOLVE_PERPENDICULAR
          - REVOLVE_INVALID_ENTITIES
          - SPLIT_FAILED
          - SPLIT_INVALID_INPUT
          - SWEEP_INVALID_PATH
          - SWEEP_FAILED
          - SWEEP_PATH_FAILED
          - SWEEP_PROFILE_FAILED
          - WIRE_CREATION_FAILED
          - SKETCH_NO_PLANE
          - SKETCH_INPUT_INVALID
          - SKETCH_NOT_ACTIVE
          - SKETCH_SOLVER_NOT_INITIALIZED
          - SKETCH_EVALUATION_FAILED
          - SKETCH_MODIFICATION_FAILED
          - SKETCH_UPDATE_FAILED
          - SKETCH_SOLVE_FAILED
          - SKETCH_ADD_CONSTRAINT_FAILED
          - SKETCH_ADD_DIMENSION_FAILED
          - SKETCH_POSITION_DIMENSION_FAILED
          - SKETCH_CONSTRAINT_NEEDS_SKETCH_ENTITY
          - SKETCH_CONSTRAINT_UNKNOWN
          - SKETCH_MISSING_ENTITY
          - SKETCH_FILLET_INVALID_POINT
[...]
