/**
 * Onshape REST API
 * The Onshape REST API consumed by all clients.
 *
 * OpenAPI spec version: 1.93
 * Contact: api-support@onshape.zendesk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { BTAssociativeDataParams } from './bTAssociativeDataParams';

export class BTAppAssociativeDataParamsArray {
    'description'?: string;
    'items'?: Array<BTAssociativeDataParams>;
    'transactionId'?: string;
    'parentChangeId'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "items",
            "baseName": "items",
            "type": "Array<BTAssociativeDataParams>"
        },
        {
            "name": "transactionId",
            "baseName": "transactionId",
            "type": "string"
        },
        {
            "name": "parentChangeId",
            "baseName": "parentChangeId",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return BTAppAssociativeDataParamsArray.attributeTypeMap;
    }
}

