/*
 * Onshape REST API
 *
 * The Onshape REST API consumed by all clients.
 *
 * API version: 1.111
 * Contact: api-support@onshape.zendesk.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// BtTableAssemblyCrossHighlightData2675 struct for BtTableAssemblyCrossHighlightData2675
type BtTableAssemblyCrossHighlightData2675 struct {
	AssemblyCrossHighlightItems []BtTableAssemblyCrossHighlightDataItem2659 `json:"assemblyCrossHighlightItems,omitempty"`
	BtType string `json:"btType,omitempty"`
}
