/*
 * Onshape REST API
 *
 * The Onshape REST API consumed by all clients.
 *
 * API version: 1.111
 * Contact: api-support@onshape.zendesk.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// BtpName261AllOf struct for BtpName261AllOf
type BtpName261AllOf struct {
	ImportMicroversion string `json:"importMicroversion,omitempty"`
	ForExport bool `json:"forExport,omitempty"`
	GlobalNamespace bool `json:"globalNamespace,omitempty"`
	Namespace []BtpIdentifier8 `json:"namespace,omitempty"`
	Identifier BtpIdentifier8 `json:"identifier,omitempty"`
	BtType string `json:"btType,omitempty"`
}
