/*
 * Onshape REST API
 *
 * The Onshape REST API consumed by all clients.
 *
 * API version: 1.111
 * Contact: api-support@onshape.zendesk.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// BtpStatementIf276 struct for BtpStatementIf276
type BtpStatementIf276 struct {
	Atomic bool `json:"atomic,omitempty"`
	BtType string `json:"btType,omitempty"`
	DocumentationType string `json:"documentationType,omitempty"`
	EndSourceLocation int32 `json:"endSourceLocation,omitempty"`
	NodeId string `json:"nodeId,omitempty"`
	ShortDescriptor string `json:"shortDescriptor,omitempty"`
	SpaceAfter BtpSpace10 `json:"spaceAfter,omitempty"`
	SpaceBefore BtpSpace10 `json:"spaceBefore,omitempty"`
	SpaceDefault bool `json:"spaceDefault,omitempty"`
	StartSourceLocation int32 `json:"startSourceLocation,omitempty"`
	Annotation BtpAnnotation231 `json:"annotation,omitempty"`
	Condition BtpExpression9 `json:"condition,omitempty"`
	SpaceAfterIf BtpSpace10 `json:"spaceAfterIf,omitempty"`
	ThenBody BtpStatement269 `json:"thenBody,omitempty"`
	ElseBody BtpStatement269 `json:"elseBody,omitempty"`
}
