/*
 * Onshape REST API
 *
 * The Onshape REST API consumed by all clients.
 *
 * API version: 1.111
 * Contact: api-support@onshape.zendesk.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// ConfigurationEntry struct for ConfigurationEntry
type ConfigurationEntry struct {
	ParameterId string `json:"parameterId,omitempty"`
	ParameterValue string `json:"parameterValue,omitempty"`
}
