/*
 * Onshape REST API
 *
 * The Onshape REST API consumed by all clients.
 *
 * API version: 1.111
 * Contact: api-support@onshape.zendesk.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// BtFeatureListResponse2457 struct for BtFeatureListResponse2457
type BtFeatureListResponse2457 struct {
	BtType string `json:"btType,omitempty"`
	LibraryVersion int32 `json:"libraryVersion,omitempty"`
	MicroversionSkew bool `json:"microversionSkew,omitempty"`
	RejectMicroversionSkew bool `json:"rejectMicroversionSkew,omitempty"`
	SerializationVersion string `json:"serializationVersion,omitempty"`
	SourceMicroversion string `json:"sourceMicroversion,omitempty"`
	Features []BtmFeature134 `json:"features,omitempty"`
	IsComplete bool `json:"isComplete,omitempty"`
	FeatureStates map[string]BtFeatureState1688 `json:"featureStates,omitempty"`
	Imports []BtmImport136 `json:"imports,omitempty"`
	RollbackIndex int32 `json:"rollbackIndex,omitempty"`
	DefaultFeatures []BtmFeature134 `json:"defaultFeatures,omitempty"`
}
