/*
 * Onshape REST API
 *
 * The Onshape REST API consumed by all clients.
 *
 * API version: 1.111
 * Contact: api-support@onshape.zendesk.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// BtParameterSpecNullableQuantity715AllOf struct for BtParameterSpecNullableQuantity715AllOf
type BtParameterSpecNullableQuantity715AllOf struct {
	QuantityType string `json:"quantityType,omitempty"`
	Ranges []BtNullableQuantityRange1340 `json:"ranges,omitempty"`
	BtType string `json:"btType,omitempty"`
}
