/*
 * Onshape REST API
 *
 * The Onshape REST API consumed by all clients.
 *
 * API version: 1.111
 * Contact: api-support@onshape.zendesk.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// BtFullElementIdAndPartId643AllOf struct for BtFullElementIdAndPartId643AllOf
type BtFullElementIdAndPartId643AllOf struct {
	PartId string `json:"partId,omitempty"`
	BtType string `json:"btType,omitempty"`
}
