# coding: utf-8

"""
    Onshape REST API

    The Onshape REST API consumed by all clients.  # noqa: E501

    The version of the OpenAPI document: 1.103
    Contact: api-support@onshape.zendesk.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import onshape_client
from onshape_client.models.bt_admin_task_params import BTAdminTaskParams  # noqa: E501
from onshape_client.rest import ApiException


class TestBTAdminTaskParams(unittest.TestCase):
    """BTAdminTaskParams unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBTAdminTaskParams(self):
        """Test BTAdminTaskParams"""
        # FIXME: construct object with mandatory attributes with example values
        # model = onshape_client.models.bt_admin_task_params.BTAdminTaskParams()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
